
<div id="jqDialogConfirmacion1" style="display:none;vertical-align: middle;">
    <table style="width: 100%;vertical-align: middle;">
        <tr>
            <td style="width: 26px;text-align: center;"><span class="ui-icon ui-icon-info" style="float:left; margin:0 7px 7px 0;"></span></td>
            <td><span id="jqConfirmacion1" style="text-align: justify;"></span></td>
        </tr>
    </table>
</div>
<div id="jqDialogConfirmacion2" style="display:none;vertical-align: middle;">
    <table style="width: 100%;vertical-align: middle;">
        <tr>
            <td style="width: 26px;text-align: center;"><span class="ui-icon ui-icon-info" style="float:left; margin:0 7px 7px 0;"></span></td>
            <td><span id="jqConfirmacion2" style="text-align: justify;"></span></td>
        </tr>
    </table>
</div>
<?php 
    echo $this->dialog()->scriptConfig(
        "jqDialogConfirmacion1" /* @param type $id */
        , $this->util()->getTitle() /* @param type $title */
        , "{'Aceptar':function(){okConfirmacion1();}, 'Cancelar':function(){cancelConfirmacion1();} }" /* @param type $buttons */
        , "172" /* @param type $height */
        , "370" /* @param type $width */
        , "" /* @param type $dialogClass */
        , "false" /* @param type $resizable */
        , "false" /* @param type $autoOpen */
        , "true" /* @param type $closeOnEscape */
        , "true" /* @param type $modal */
        , "#" /* @param type $href */
    );

    echo $this->dialog()->scriptConfig(
        "jqDialogConfirmacion2" /* @param type $id */
        , $this->util()->getTitle() /* @param type $title */
        , "{'Aceptar':function(){okConfirmacion2();}, 'Cancelar':function(){cancelConfirmacion1();} }" /* @param type $buttons */
        , "172" /* @param type $height */
        , "370" /* @param type $width */
        , "" /* @param type $dialogClass */
        , "false" /* @param type $resizable */
        , "false" /* @param type $autoOpen */
        , "true" /* @param type $closeOnEscape */
        , "true" /* @param type $modal */
        , "#" /* @param type $href */
    );    
?>

<!--

<sj:dialog 
id="jqDialogPregunta" title="Mensaje de Confirmación" autoOpen="false" modal="true" resizable="false" closeOnEscape="true"	
height="150" width="300"		
buttons="{'Aceptar':function() { okEjecutar(); },
'Cancelar':function() { cancelEjecutar(); } 
}"
>
</sj:dialog>
<sj:dialog 
id="jqDialogInfo" title="Información" autoOpen="false" modal="true" resizable="false"
height="170" 
buttons="{'Cerrar':function() { closeDialogInfo(); }}"
>
</sj:dialog>

<sj:dialog 
id="jqDialogWarning" title="Advertencia" autoOpen="false" modal="true" resizable="false"
height="170" 
buttons="{'Aceptar':function() { closeDialogWarning(); }}"
>
</sj:dialog>

<sj:dialog 
id="jqDialogError" title="Error" autoOpen="false" modal="true" resizable="false"
height="170" 
buttons="{'Aceptar':function() { closeDialogError(); }}"
>
</sj:dialog>-->