<div class="ui-widget-header" style="width: 100%; border: 0px;">
<table>
    <tr>
        <td>
            <a href="#" id="itemMenu1" class="fg-button fg-button-icon-right ui-widget ui-state-default ui-corner-all">Encuestas</a>
            <div class="hidden">
                <ul>
                    <li><a href="<?php echo $this->util()->getLink("index/test") ?>">Crear</a></li>
                    <li><a href="#">Resultados</a>
                        <ul>
                            <li><a href="<?php echo $this->util()->getLink("index/test") ?>">por Profesor</a></li>
                            <li><a href="<?php echo $this->util()->getLink("index/test") ?>">por Sal&oacute;n</a></li>
                            <li><a href="<?php echo $this->util()->getLink("index/test") ?>">por Especialidad</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Test Dialog</a>
                        <ul>
                            <li><a href="javascript:void(0);" onclick="openDialogConfirm1('Prueba openConfirm1 Prueba openConfirm1 Prueba openConfirm1 Prueba openConfirm1 Prueba openConfirm1 Prueba openConfirm1 Prueba openConfirm1 Prueba openConfirm1');">openConfirm1</a></li>
                            <li><a href="javascript:void(0);" onclick="openDialogInfo('Prueba Info');">openInfo</a></li>
                            <li><a href="javascript:void(0);" onclick="openDialogWarning('Prueba Warning');">openWarning</a></li>
                            <li><a href="javascript:void(0);" onclick="openDialogError('Prueba Error');">openError</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </td>
    </tr>
</table>
</div>

