<div align="center" id="showing">
	        		<table width="690" border="0" cellspacing="0" cellpadding="0">
	                  <tr>
	                    <td width="90">&nbsp;</td>
	                    <td width="151">&nbsp;</td>
	                    <td width="359">&nbsp;</td>
	                    <td width="90">&nbsp;</td>
	                  </tr>
	                  <tr>
	                    <td height="49">&nbsp;</td>
	                    <td colspan="2" align="center"><h2>Anular Recibo</h2></td>
	                    <td>&nbsp;</td>
	                  </tr>
	                  <tr>
	                    <td>&nbsp;</td>
	                    <td>&nbsp;</td>
	                    <td>&nbsp;</td>
	                    <td>&nbsp;</td>
	                  </tr>
	                  <tr>
	                    <td colspan="4"><div id="div_rptaerroranular" align="center"></div></td>
	                  </tr> 
	                  <tr>
	                    <td>&nbsp;</td>
	                    <td>&nbsp;</td>
	                    <td>&nbsp;</td>
	                    <td>&nbsp;</td>
	                  </tr>
	                  <tr>
	                    <td>&nbsp;</td>
	                    <td align="right"><b>Nro. Recibo:&nbsp;&nbsp;</b></td>
	                    <td><input name="txtnrorecibo" type="text" id="txtnrorecibo" value="" size="30" maxlength="12" class="ui-text" /> </td>
	                    <td>&nbsp;</td>
	                  </tr>
	                  <tr>
	                    <td>&nbsp;</td>
	                    <td align="right"><b>Observaci&oacute;n:&nbsp;&nbsp;</b></td>
	                    <td rowspan="2" colspan="2"><textarea name="txtobs" cols="23" rows="5" id="txtobs" ></textarea></td>
	                    
	                  </tr>
	                  <tr>
	                    <td>&nbsp;</td>
	                    <td>&nbsp;</td>
	                    
	                    
	                  </tr>
	                  <tr>
	                    <td>&nbsp;</td>
	                    <td>&nbsp;</td>
	                    <td>&nbsp;</td>
	                    <td>&nbsp;</td>
	                  </tr>
	                  <tr>
	                    <td colspan="4"><div id="div_rptaanular" align="center"></div></td>
	                  </tr>
	                  <tr>
	                    <td>&nbsp;</td>
	                    <td colspan="2" align="center"><input type="button" id="btnaceptar" name="btnaceptar" value="Anular recibo"/></td>
	                    <td>&nbsp;</td>
	                  </tr>
	                  <tr>
	                    <td>&nbsp;</td>
	                    <td>&nbsp;</td>
	                    <td>&nbsp;</td>
	                    <td>&nbsp;</td>
	                  </tr>
	                </table>
		        </div>