<table width="500" border="0" cellspacing="0" cellpadding="0"
		class="reportes">
		<tr>
			<th width="60"></th>
			<th width="240"></th>
			<th width="30"></th>
			<th width="70"></th>
			<th width="70"></th>
			<th width="30"></th>
		</tr>
		<tr>
			<td colspan=6 align="center" id="detail"></td>
		</tr>
		<tr>
			<td colspan="4" align="right"><b>Total</b></td>
			<td align="center" id="ctotal"></td>
			<td >&nbsp;</td>
		</tr>

</table>