<div align="center">
<table width="582" border="0" cellpadding="0" cellspacing="0">
	<tr>
		<td width="317">&nbsp;</td>
		<td width="23">&nbsp;</td>
	</tr>
	<tr>
		<td>
		<table width="300" border="1" style="border: double" cellspacing="0"
			cellpadding="0">
			<tr bgcolor="#A9C82D">
				<th width="40">C&oacute;d.</th>
				<th width="260">Descripci&oacute;n</th>
			</tr>
			<div id="div_detalle_pago_diverso" align="center">
			<tr>
				<td colspan="2"><select id="cbconceptos" name="cbconceptos" size="7"">

				</select></td>
			</tr>
			</div>
			<tr>
				<td width="40"><input type="text" id="busqxcodconcepto"
					name="busqxcodconcepto" value="" size="3" /></td>
				<td width="260"><input type="text" id="busqxnomconcepto"
					name="busqxnomconcepto" value="" size="42" /></td>
			</tr>
		</table>
		</td>
		<td valign="middle">
		<table width="280" border="1" style="border: double" cellspacing="0"
			cellpadding="0">
			<tr>
				<td width="85">C&oacute;digo:</td>
				<td width="195">
				<div id="codconcepto"></div>
				</td>
			</tr>
			<tr>
				<td>Descripci&oacute;n:</td>
				<td>
				<div id="descripconceptomin"></div>
				<input type="hidden" id="descripconcepto" name="descripconcepto"
					value="" /></td>
			</tr>
			<tr>
				<td>Monto:</td>
				<td><input type="text" id="montoconcepto" name="montoconcepto"
					value="0.00" size="10" /></td>
			</tr>
			<tr>
				<td>Cantidad:</td>
				<td><input type="text" id="cantidadconcepto" name="cantidadconcepto"
					value="1" size="10" /></td>
			</tr>
			<tr>
				<td>Glosa:</td>
				<td><textarea name="glosaconcepto" cols="20" rows="3"
					id="glosaconcepto"></textarea></td>
			</tr>
			<tr>
				<td></td>
				<td><input type="button" id="btnagregarconcepto"
					name="btnagregarconcepto"
					value="&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Agregar&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" />
				<input type="hidden" id="cidconcepto" name="cidconcepto" value="" /></td>
			</tr>
			<tr>
				<td colspan="2">
				<div id="div_erroragregarconcepto"></div>
				</td>
			</tr>
		</table>
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
</table>
</div>