<table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0"><tr valign="middle"><td align="center">
<div align="center" id="show"> 
    <table width="501" border="0" cellspacing="0" cellpadding="0">
         <tr>
          <td colspan="5">&nbsp;</td>
         </tr>
         <tr>
           <td colspan="5">
           	<input type="button" name="nuevorecibo" id="nuevorecibo" value="&nbsp;&nbsp;&nbsp;&nbsp;Nuevo Recibo&nbsp;&nbsp;&nbsp;&nbsp;" />
			</td>
         </tr>
         <tr>
          <td colspan="5">&nbsp;</td>
         </tr>
          <tr> 
         <td colspan="5" align="center">
         	<div id="div_title" align="center"></div>
         </td>
         </tr>
         <tr>
            <td colspan="5" align="center">
            <table width="450" border="1" style="border:double" cellspacing="0" cellpadding="0"><tr><td>
                	<table width="450" border="0" cellspacing="0" cellpadding="0">
						<tr>
                            <td width="150" bgcolor="#A9C82D">C&oacute;digo de Persona:</td>
             				<td width="300"><div id="cidpers"></div></td>
                      	</tr>
                        <tr>
                            <td bgcolor="#A9C82D">Apellido y Nombres:</td>
                            <td><div id="nompers"></div></td>
                        </tr>
                     </table>   
                 </td></tr></table>         
             </td>
          </tr>
          <tr>
            <td width="49">&nbsp;</td>
            <td colspan="2">&nbsp;</td>
            <td width="50">&nbsp;</td>
            <td width="50">&nbsp;</td>
          </tr>
	          <!--
	          <tr>
	            <td><input type="hidden" id="hidden_buscarconcepto" name="hidden_buscarconcepto" value="0"> </td>
	            <td colspan="3"><input type="button" id="buscarconcepto" name="buscarconcepto" value="&nbsp;&nbsp;&nbsp;&nbsp;Buscar Concepto&nbsp;&nbsp;&nbsp;&nbsp;" onClick="MostrarBuscarConceptosPagosDiversos(\''.str_replace("\"", "\\'", $jsondatoscpd).'\')"></td>
	            <td>&nbsp;</td>
	          </tr>
	          -->
          <tr>
            <td colspan="2">&nbsp;</td>
            <td width="50">&nbsp;</td>
            <td width="300" align="center">
            
            <div id="div_buscarconcepto" align="center">
          
			          
		
						<div align="center">
						<table width="582" border="0" cellpadding="0" cellspacing="0">
						  <tr>
						    <td width="317">&nbsp;</td>
						    <td width="23">&nbsp;</td>
						  </tr>
						  <tr>
						    <td>
						    		<table width="300" border="1" style="border:double" cellspacing="0" cellpadding="0">
						              <tr bgcolor="#A9C82D">
						                <th width="40">C&oacute;d. </th>
						                <th width="260">Descripci&oacute;n</th>
						              </tr>
						              <div id="div_detalle_pago_diverso" align="center"> 
						                <tr>
						                <td colspan="2">
						                	<select id="cbconceptos" name="cbconceptos" size="7">                                        
																			
						                	</select></td>
						                </tr>
						              </div>
						            	 <tr>
						                	<td width="40"> <input type="text" id="busqxcodconcepto" name="busqxcodconcepto" value="" size="4" /></td>
						                	<td width="260"><input type="text" id="busqxnomconcepto" name="busqxnomconcepto" value="" size="42" /></td>
						             	 </tr>
						            </table>
						      </td>
						    <td valign="middle">
	                           <table width="280" border="1" style="border:double" cellspacing="0" cellpadding="0">
	                          <tr>
	                            <td width="85">C&oacute;digo:</td>
	                            <td width="195"><div id="codconcepto"></div></td>
	                          </tr>
	                          <tr>
	                            <td>Descripci&oacute;n:</td>
	                            <td><div id="descripconceptomin"></div>
	                                <input type="hidden" id="descripconcepto" name="descripconcepto" value="" /></td>
	                          </tr>
	                          <tr>
	                            <td>Monto:</td>
	                            <td><input type="text" id="montoconcepto" name="montoconcepto" value="0.00" size="10" /></td>
	                          </tr>
	                          <tr>
	                            <td>Cantidad:</td>
	                            <td><input type="text" id="cantidadconcepto" name="cantidadconcepto" value="1" size="10"/></td>
	                          </tr>
	                          <tr>
	                            <td>Glosa:</td>
	                            <td><textarea name="glosaconcepto" cols="20" rows="3" id="glosaconcepto"></textarea></td>
	                          </tr>
	                          <tr>
	                            <td></td>
	                            <td><input type="button" id="btnagregarconcepto" name="btnagregarconcepto" value="&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Agregar&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" />
	                                <input type="hidden" id="cidconcepto" name="cidconcepto" value="" /></td>
	                          </tr>
	                          <tr>
	                            <td colspan="2"><div id="div_erroragregarconcepto"></div></td>
	                          </tr>
	                        </table></td>
						  </tr>
						  <tr>
						    <td>&nbsp;</td>
						    <td>&nbsp;</td>
						  </tr>
						</table>										
						</div>
            
            </div>
            
            </td>
            <td colspan="2">&nbsp;</td>
            <td>&nbsp;</td>
          </tr>
          <tr>
            <td>&nbsp;</td>
            <td colspan="3" align="center" valign="middle"> 
            <table width="500" border="1" style="border:double" cellspacing="0" cellpadding="0">
                  <tr bgcolor="#A9C82D">
                    <th width="60">C&oacute;d. </th>
                    <th width="240">Descripci&oacute;n</th>
                    <th width="30">Cant.</th>
                    <th width="70">Val. Unt.</th>
                    <th width="70">Val. Tot.</th>
                    <th width="30">&nbsp;</th>
                  </tr>
                  <tr>
                    <td colspan="6">
                  <div id="divdetallepagodiverso">
                  	<table width="500" border="0" cellspacing="0" cellpadding="0"> 
                  	  <tr>
	                    <td colspan="4" align="right"><b>Total</b></td>	                    
	                    <td align="center" >0</td>
	                    <td>&nbsp;</td>
	                  </tr>				                  	
	                 </table>
                  </div>
                  </td>
                  </tr>
                </table>            
             </td>
            <td>&nbsp;</td>
          </tr>
          <tr>
            <td>&nbsp;</td>
            <td colspan="2">&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
          </tr>
          <tr>
            <td>&nbsp;</td>
            <td colspan="3" align="right"><input type="button" id="cobrar" name="cobrar" value="&nbsp;&nbsp;&nbsp;&nbsp;Cobrar&nbsp;&nbsp;&nbsp;&nbsp;"></td>
            <td>&nbsp;</td>
          </tr>
          <tr>
            <td>&nbsp;</td>
            <td colspan="2">&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
          </tr>
          <tr>
            <td colspan="5"><div id="div_resultpagosdiversos" align="center" ></div></td>
          </tr>
        </table>
    </div>
	</td></tr></table>		