<div class="ui-widget ui-widget-content ui-corner-all" style="width: 95%;margin: 3px;">
	<div align="center" class="ui-widget ui-state-default ui-corner-top ui-title">
    	<label>Contribuyente</label>
	</div>
	<div id="panelSesionPersona">
		<table class="ui-table-panelLayout" style="width: 90%; height: 100%; font-size: 90%;">
			<tr>
				<td colspan="2" style="font-weight: bold;font-size: 12px;"><?php echo $this->mperson['crazsoc'] ?></td>
			</tr>
			<tr>
				<td>C&oacute;digo:&nbsp;<b><?php echo $this->mperson['cidpers'] ?></b>
					<input id="mhresum" name="mhresum" type="hidden" value="<?php echo $this->mperson['mhresum'] ?>" />
					<input id="vnrodoc" name="vnrodoc" type="hidden" value="<?php echo $this->mperson['vnrodoc'] ?>" />
				</td>
				<td rowspan="7" align="center" valign="top">
					<img style="width: 95px; height: 115px; border: 1px solid #000;" src="<?php echo $this->util()->getPhoto($this->mperson['cidpers']); ?>" />
				</td>
			</tr>
			<tr>
				<td>Declaraci&oacute;n Jurada:&nbsp;
					<table>
						<tr>
							<td><b><?php echo $this->mperson['vnrodoc'] ?></b></td>
							<td><button title="Ver declaraci&oacute;n" style="line-height: 25px;height: 25px;" id="btnVerDeclaracion"></button></td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td>Presentada el:&nbsp;<b><?php echo $this->mperson['dfecdoc'] ?></b></td>
			</tr>
			<tr>
				<td>Motivo:&nbsp;<b><?php echo $this->mperson['vmotivo'] ?></b></td>
			</tr>
			<tr>
				<td>Predios registrados:&nbsp;<b><?php echo $this->mperson['ntotpre'] ?></b></td>
			</tr>
			<tr>
				<td>Comercios registrados:&nbsp;<b><?php echo $this->mperson['ntotcom'] ?></b></td>
			</tr>
			<tr>
				<td>Base Imponible:&nbsp;<b><?php echo $this->mperson['nbaseim'] ?></b></td>
			</tr>
			<tr>
				<td colspan="2">Impuesto Predial:&nbsp;<b><?php echo $this->mperson['nimpanu'] ?></b></td>
			</tr>
			<tr>
				<td colspan="2">En proceso de fiscalidaci&oacute;n:&nbsp;<b><?php echo $this->mperson['vprofis'] ?></b></td>
			</tr>
			<tr>
				<td colspan="2">En proceso coactivo:&nbsp;<b><?php echo $this->mperson['vprofis'] ?></b></td>
			</tr>
			<tr>
				<td colspan="2">Convenio de fraccionamiento:&nbsp;<b><?php echo $this->mperson['vprofis'] ?></b></td>
			</tr>
			<tr>
				<td colspan="2">Tramites en proceso:&nbsp;<b><?php echo $this->mperson['vprotra'] ?></b></td>
			</tr>
		</table>
	</div>
</div>
<div class="ui-widget ui-widget-content ui-corner-all" style="width: 95%;margin: 3px;">
	<div align="center" class="ui-widget ui-state-default ui-corner-top ui-title">
    	<label>Morosidad</label>
	</div>
	<div>
		<table class="ui-table-panelLayout" style="width: 90%; height: 100%; font-size: 90%;">
			<tr>
				<td rowspan="7" align="center" valign="top">
					<img style="" src="<?php echo $this->util()->getImage($this->msaldos['vindica']); ?>">
				</td>
				<td>Ultimo pago:&nbsp;<b><?php echo $this->mperson['dfecpag'] ?></b></td>
			</tr>
			<tr>
				<td>Emitido:&nbsp;<b>S/. <?php echo $this->msaldos['ntotals']?></b></td>
			</tr>
			<tr>
				<td>Cobrado:&nbsp;<b>S/. <?php echo $this->msaldos['ntotals']?></b></td>
			</tr>
			<tr>
				<td>Saldo:&nbsp;<b>S/. <?php echo $this->msaldos['npendie']?></b></td>
			</tr>
			<tr>
				<td>Saldo con beneficio:&nbsp;<b>S/. <?php echo $this->msaldos['npendie']?></b></td>
			</tr>
			<tr>
				<td>Porcentaje:&nbsp;<b><?php echo $this->msaldos['ncancel']?>%</b></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
			</tr>
		</table>
	</div>
</div>
<script type="text/javascript">
$(function(){
	$("#btnVerDeclaracion").button({
	    text: false,
	    icons: {primary:'ui-icon-search'}
	}).bind("click", function(){
	    openDialogData1("registro/listardeclaracion", {cidpers: "<?php echo $this->mperson['cidpers'] ?>"}, "750", "496", "Declaraciones Juradas");
	});
});
</script>