
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>Municipalidad Distrital de Puente Piedra</title>
<style type="text/css">
<!--
@media print {
	BODY {
		font-size: 14pt;
		font-family: Arial;
	}
}

@media screen {
	BODY {
		font-size: 12pt;
		font-family: Arial;
	}
}

@media screen , print {
	BODY {
		color: #000000;
	}
}

body {
	margin-left: 0px;
	margin-right: 0px;
}

.Estilo2 {
	font-size: 2px;
	font-weight: bold;
}

.Estilo4 {
	font-size: 14px;
	font-weight: bold;
}

.Estilo6 {
	font-size: 12px
}

.Estilo7 {
	font-size: 10px;
	font-weight: bold;
}

.Estilo8 {
	font-size: 10px
}

.MasGrande {
	font-size: 14px
}

body,td,th {
	font-family: Arial;
}
-->
</style>

		 <script language="javascript">
	//	window.print();
	//	window.close();
		</script> 
</head>
<body>
<!--
		<div style="position:absolute;left:0;top:0;height:25;">
		<input type="button" name="imprimir" id="btnprint" style="visibility:visible;" value="Imprimir" onClick="ocultar();">
		</div>
		-->
<table width="100%" style="border: 0px solid"  id="muni">
	<tr>
		<td height="24" colspan="6" class="Estilo6"><b> Municipalidad
		Distrital de Puente Piedra<br>
		Sub Gerencia de Tesoreria<br>
		RUC: 20131366702</b>
		<hr align="left" width="100%">
		</td>
	</tr>
	<tr>
		<td height="10" colspan="6" class="Estilo7">&nbsp;</td>
	</tr>
	<tr>
		<td colspan="6" class="Estilo6" align="center"><b><font size=+1 id="duplicado"></font></b></td>
	</tr>
	<tr>
		<td width="50" height="21" class="Estilo8">Recibo</td>
		<td width="173" height="21" colspan="5" class="Estilo8" id="datosrec1"></td>
	</tr>
	<tr>
		<td height="21" class="Estilo8">Codigo</td>
		<td height="21" colspan="5" class="Estilo8" id="datosrec6"></td>
	</tr>
	<tr>
		<td height="21" class="Estilo8">Nombre</td>
		<td height="21" colspan="5" class="Estilo8" id="datosper1"></td>
	</tr>
	<tr>
		<td height="24" class="Estilo8">Cod. Pred.</td>
		<td height="21" colspan="5" class="Estilo8" id="datosrec18"></td>
	</tr>
	<tr>
		<td height="24" class="Estilo8">Direcc.</td>
		<td height="21" colspan="5" class="Estilo8" id="datosrec17"></td>
	</tr>
	<tr>
		<td height="25" colspan="6" class="Estilo6" align="center" id="datosrec15"></td>
	</tr>

	<tr>
		<td colspan="6" align="center">
		<table width="100%" border="0" cellpadding="0" cellspacing="0" >
			<tr>
				<td width="56" height="20" class="Estilo8">Descrip.</td>
				<td width="40" align="right" class="Estilo8">Inso+Rea</td>
				<td width="40" align="right" class="Estilo8">Mora</td>
				<td width="40" align="right" class="Estilo8">G.Adm</td>
				<td width="40" align="right" class="Estilo8">Total</td>
			</tr>
			<tr>
				<td colspan="5" id="detalle"></td>
			</tr>
			<tr>
				<td height="20" class="Estilo8" colspan="4" align="right">TOTAL</td>
				<td align="right" class="Estilo4" id="sumtotal"></td>
			</tr>

		</table>
		</td>
	</tr>

	<tr>
		<td colspan="6" class="Estilo8" id="datosrec"></td>
	</tr>
	<tr>
		<td colspan="6" class="Estilo8" align="left" id="codcajero"></td>
	</tr>
	<tr>
		<td colspan="6" class="Estilo8" align="left" id="fechaserver"></td>
	</tr>
	<tr>
		<td colspan="6" height="30">.</td>
	</tr>
</table>
</body>
</html>