<table border="1" cellspacing="0" cellpadding="0" style="font-size:12px">
	<tr style="background-color:#A9C82D">
		<th width="50" >Trib.</th>
		<th width="48">A&ntilde;o</th>
		<th width="49">Perid.</th>
		<th width="63">Imp. Ins.</th>
		<th width="65">Imp. Rea.</th>
		<th width="55">Mora</th>
		<th width="61">Cst Emis.</th>
		<th width="61" >Total</th>
	</tr>
	<tr>
		<td colspan="8" bordercolor="#000000">
			<div style="overflow:auto; height:235px;width:100%;border:1px solid #c3daf9;" id="detail">			
			</div> 
		</td>
	</tr>
	<tr>
		<td colspan="7" align="right">Total:&nbsp;&nbsp;</td>
		<td align="center" id="stotal"></td>
	</tr>
</table>