<table width="100%" height="100%" border="0" cellspacing="0" cellpadding="0"><tr valign="middle"><td align="center">
    <div id="div_p">
    	    <table width="250" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td width="30">&nbsp;</td>
                    <td width="113">
                    	<input type="hidden" id="hddata" name="hddata" value="" />
                    	<input type="hidden" id="fechrecibo" name="fechrecibo" value="" />
                    </td>
                    <td width="77">&nbsp;</td>
                    <td width="30">&nbsp;</td>
              </tr>
                  <tr>
                    <td>&nbsp;</td>
                    <td>Monto Selecionado:</td>
                    <td><input type="text" id="txttotalcobrar" name="txttotalcobrar" value="" size="10" maxlength="10" readonly="readonly" /></td>
                    <td>&nbsp;</td>
                  </tr>                  
                  <tr>
                    <td colspan="4" height="10"></td>
                  </tr>
                  <tr>
                    <td>&nbsp;</td>
                    <td>Importe a Pagar:</td>
                    <td><input type="text" id="txttotalpagar" name="txttotalpagar" value="" size="10"  /></td>
                    <td>&nbsp;</td>
                  </tr>
                  <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td><input type="button" id="btndetalle" name="btndetalle" value="Detalle" /></td>
                    <td><input type="hidden" id="hddetalle" name="hddetalle" value="" /></td>
                  </tr>
                  <tr>
                    <td colspan="4" height="10"></td>
                  </tr>
                  <tr>
                    <td>&nbsp;</td>
                    <td>Efectivo:</td>
                    <td><input type="text" id="txtefectivo" name="txtefectivo" value="" size="10"  /></td>
                    <td>&nbsp;</td>
                  </tr>
                  <tr>
                    <td colspan="4" height="10"></td>
                  </tr>
                  <tr>
                    <td>&nbsp;</td>
                    <td>Vuelto:</td>
                    <td><input type="text" id="txtvuelto" name="txtvuelto" value="" size="10"  /></td>
                    <td>&nbsp;</td>
                  </tr>
                  <tr>
                    <td colspan="4" height="10"></td>
                  </tr>
                  <tr>
                    <td>&nbsp;</td>
                    <td colspan="2" align="center"><input type="button" id="btnaceptarcobro" name="btnaceptarcobro"   value="Aceptar" />
						
						<input type="button" id="btncancelarcobro" name="btncancelarcobro"   value="Regresar"  /></td>
                    <td>&nbsp;</td>
                  </tr>
                  <tr>
                    <td colspan="4"><div id="div_rptacobroarbitrospredios"></div></td>
                  </tr>
                  <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                  </tr>
                </table>
    </div>
</td></tr></table>