<table width="100%" height="100%" border="0" cellspacing="0" cellpadding="0"><tr valign="middle"><td align="center">
    <div id="div_p">
<table width="350" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="4" height="10"></td>
  </tr>
  <tr>
  	<td>&nbsp;</td>
    <td colspan="3"><div id="div_mensajex" class="mensajeerror"></div></td>
  </tr>
  <tr>
    <td colspan="4" height="10"></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><strong>Monto a cancelar:</strong></td>
    <td id="montototal">&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td colspan="4" height="10"></td>
    </tr>
  <tr>
    <td width="20">&nbsp;</td>
    <td width="125"><strong>Tipo Pago :</strong></td>
    <td width="185"><select id="cbtipopago" style="width:140px"></select></td>
    <td width="20">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="4" height="10"></td>
    </tr>
  <tr>
    <td>&nbsp;</td>
    <td><strong>Monto</strong></td>
    <td>
    	<input type="text" id="txtmontopago" name="txtmontopago" value="" size="7" />
    	&nbsp;&nbsp;/&nbsp;&nbsp;
    	<input type="text" id="hdsubtotal" name="hdsubtotal" value="" size="6">
    </td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td colspan="4" height="10"></td>
    </tr>
  <tr>
    <td>&nbsp;</td>
    <td><strong>Nro. de Documento:</strong></td>
    <td><input type="text" id="txtnrodoc" name="txtnrodoc" value="" size="20" maxlength="15" /></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td colspan="4" height="10"></td>
    </tr>
  <tr>
    <td>&nbsp;</td>
    <td><strong>Nro. Operaci&oacute;n :</strong></td>
    <td><input type="text" id="txtnroope" name="txtnroope" value="" size="20" maxlength="10" /></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td colspan="4" height="10"></td>
  </tr>
  <tr>
    <td colspan="4" height="10" align="center"><input type="button" id="btnagregar" name="btnagregar" value="A&ntilde;adir" /></td>
  </tr>
  <tr>
    <td colspan="4" height="10"></td>
    </tr>
  <tr>
    <td>&nbsp;</td>
    <td colspan="2">
    	<table width="310" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <th width="55" >Tipo</th>
            <th width="100">Nro. Doc.</th>
            <th width="65" >Nro. Oper.</th>
            <th width="50" >Monto</th>
            <th width="20">&nbsp;</th>
            <th width="20">&nbsp;</th>
          </tr>
          <tr>
            <td colspan="6">
                <div id="div_detallepago" style="overflow-y:scroll">
                    <table width="290" border="0" cellspacing="0" cellpadding="0">
                      <tr>
                        <td width="55" >&nbsp;</td>
                        <td width="100">&nbsp;</td>
                        <td width="65" >&nbsp;</td>
                        <td width="50" >&nbsp;</td>
                        <td width="20">&nbsp;</td>
                      </tr>
                    </table>
                </div>
              </td>
            </tr>
        </table>    </td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td colspan="4" height="10"></td>
    </tr>
  <tr>
    <td>&nbsp;</td>
    <td colspan="2" align="center">
    	<input type="button" id="btnaceptardetalle" name="btnaceptardetalle" value="Aceptar" />
    	<!--<input type="button" id="btnregresar" name="btnregresar" value="&nbsp;&nbsp;&nbsp;Regresar&nbsp;&nbsp;&nbsp;" />-->    
    </td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td colspan="4">&nbsp;</td>
    </tr>
</table>

    </div>
</td></tr></table>