<div align="center" id='divp'>
<table width="800" border="0" cellspacing="0" cellpadding="0" id=tabla>
	<tr>
		<td width="10">&nbsp;</td>
		<!--contenedor con todos los recibos -->
		<td width="470">
			<div align="center" style="overflow: scroll; height: 450px; width: 470px; border: 1px solid #c3daf9;">
			<table width="442" cellspacing="0" cellpadding="0" class="reportes">
				<thead class="ui-widget ui-widget-header ui-title2">
				<tr>
					<th width="87" class="reportes">Nro. Recibo</th>
					<th width="30" class="reportes">Caja</th>
					<th width="78" class="reportes">Usuario</th>
					<th width="77" class="reportes">Fecha</th>
					<th width="50" class="reportes">Total</th>
					<th width="70" class="reportes">Estado</th>
					<th width="52" class="reportes">Detalle</th>
				</tr>
				</thead>
				<tr>
					<td colspan=7 id="detalletodorecibos"></td>
				</tr>
	
			</table>
		</div>
		<!--contenedor con todos los recibos -->
		</td>
		<td width="17">&nbsp;</td>
		<td width="293"><div id="div_detallerecibo">&nbsp;</div></td>
		<td width="10">&nbsp;</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
</table>
</div>
<input type="button" id="btncancelarcobro" name="btncancelarcobro" value="Regresar" />
