<div align="center" id="show" class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
	<div class="ui-widget ui-state-default ui-corner-top ui-title">
		<label>Pagos Diversos</label>
	</div>
	<div align="center" style="margin: 5px; height: 480px; overflow: auto;">
		<div style="width: 99%; padding: 1px;" class="ui-widget-content ui-widget ui-corner-all">
			<table style="width: 100%; padding-left: 5px; padding-right: 5px;" cellspacing="0" cellpadding="0">
				<tr>
					<td style="width: 120px;">C&oacute;digo de Persona:</td>
					<td><div id="cidpers" class="ui-titleBar2"></div></td>
					<td style="width: 90px; vertical-align: middle; text-align: right;" rowspan="2">
						<input type="button" name="nuevorecibo" id="nuevorecibo" value="Nuevo Recibo" />
					</td>
				</tr>
				<tr>
					<td>Apellido y Nombres:</td>
					<td><div id="nompers" class="ui-titleBar2"></div></td>
				</tr>
			</table>
		</div>
		<div style="height: 3px;"></div>
		<div style="width: 99%; padding: 1px;" class="ui-widget-content ui-widget ui-corner-all">
		<table style="width: 100%; padding: 2px;" border="0" cellspacing="0" cellpadding="0" >
			<tr>
				<td >
					<table border="0" style="width: 100%; padding: 2px;" cellspacing="0" cellpadding="0">
						<thead class="ui-widget ui-widget-header ui-title2">
							<tr>
								<th >Area</th>
							</tr>
						</thead>
						<tbody> 
							<tr>
								<td >
									<select id="cbareas" name="cbareas" class="notcombobox" size="10" style="width: 350px; border: 0px; padding-left: 3px;">
									</select>
								</td>
							</tr>
						</tbody>
					</table>
				</td>
				<td>
					<table border="0" style="width: 100%; padding: 2px;" cellspacing="0" cellpadding="0">
						<thead class="ui-widget ui-widget-header ui-title2">
							<tr>
								<th style="width: 80px;">C&oacute;digo</th>
								<th>Descripci&oacute;n</th>
							</tr>
						</thead>
						<tbody> 
							<tr>
								<td colspan="2">
									<select id="cbconceptos" name="cbconceptos" class="notcombobox" size="9" style="width: 600px; border: 0px; padding-left: 3px;"></select>
								</td>
							</tr>
							<tr>
								<td><input type="text" id="busqxcodconcepto" name="busqxcodconcepto" value="" size="4" style="width: 75px;" class="ui-text"/></td>
								<td><input type="text" id="busqxnomconcepto" name="busqxnomconcepto" value="" size="42" style="width: 380px;" class="ui-text"/></td>
							</tr>
						</tbody>
					</table>
				</td>
			</tr>
		</table>
	
			
		</div>
		<div style="height: 3px;"></div>
		<div style="width: 99%; padding: 1px;" class="ui-widget-content ui-widget ui-corner-all">
			<table style="width: 100%; padding: 2px;" cellspacing="0" cellpadding="0">
				<tr>
					<td style="width: 50px;">&nbsp;C&oacute;digo:</td>
					<td style="width: 70px;"><div id="codconcepto" class="ui-titleBar2">&nbsp;</div></td>
					<td style="width: 80px;">Descripci&oacute;n:</td>
					<td><div id="descripconceptomin" class="ui-titleBar2">&nbsp;</div>
						<input type="hidden" id="descripconcepto" name="descripconcepto" value="" />
					</td>
				</tr>
			</table>
			<table style="width: 100%; padding: 2px;" cellspacing="0" cellpadding="0">
				<tr>
					<td style="width: 50px;">&nbsp;Monto:</td>
					<td style="width: 90px;"><input type="text" id="montoconcepto" name="montoconcepto" value="0.00" size="10" class="ui-text" /></td>
					<td style="width: 60px;">Cantidad:</td>
					<td style="width: 90px;"><input type="text" id="cantidadconcepto" name="cantidadconcepto" value="1" size="10" class="ui-text"/></td>
					<td style="width: 50px;">Glosa:</td>
					<td><textarea name="glosaconcepto" cols="30" rows="2" id="glosaconcepto" style="width: 300px;" class="ui-text"></textarea></td>
					<td style="width: 80px;text-align: right;">
						<input type="button" id="cobrar" name="cobrar" value="Cobrar">
					</td>
					<td style="width: 80px;text-align: right;">
						<input type="button" id="btnagregarconcepto" name="btnagregarconcepto" value="Agregar" />
						<input type="hidden" id="cidconcepto" name="cidconcepto" value="" />
					</td>
				</tr>
			</table>
			<div id="div_erroragregarconcepto"></div>
		</div>
		<div style="height: 3px;"></div>
		<div style="width: 99%;height:150px; padding: 1px;" class="ui-widget-content ui-widget ui-corner-all">
		<table border='0'>
		<tr>
			<td style="height: 100px" 	valign=top > 
				<table id="tblDetalle" style="width: 100%; padding: 2px;" cellspacing="0" cellpadding="0" border="0">
				<thead class="ui-widget ui-widget-header ui-title2">
					<tr>
	                    <th style="width: 85px;">C&oacute;digo</th>
	                    <th>Descripci&oacute;n</th>
	                    <th style="width: 50px;">Cant.</th>
	                    <th style="width: 70px;">Val. Unt.</th>
	                    <th style="width: 70px;">Val. Tot.</th>
	                    <th style="width: 30px;">&nbsp;</th>
					</tr>
				</thead>
				<tbody>
				</tbody>
				<!-- <tfoot>
					<tr>
						<td colspan="4" style="text-align: right;"><b>Total</b></td>	                    
						<td style="text-align: right; padding-right: 5px;"><div id="rowTotal">0.00</div></td>
						<td>&nbsp;</td>
					</tr>
				</tfoot>-->
				</table>			
			</td>	
		</tr>
			<tr>	
				<td>
					<table style="width: 100%; padding: 2px;" cellspacing="0" cellpadding="0" border="0">
						<tr>
							<td  style="text-align: right;width: 885px;" ><b>Total</b></td>	                    
							<td style="text-align: right; padding-right: 5px;width: 62px;"><div id="rowTotal">0.00</div></td>
							<td>&nbsp;</td>
						</tr>
					</table>
				</td>	
			</tr>	
		</table>
			<div id="div_resultpagosdiversos" align="center"></div>
		</div>
		<div id="divdetallepagodiverso" style="display: none;"></div>
	</div>
</div>