CREATE TABLE IILC.TIILC_TOTAL (
		COD_TOTAL NUMBER NOT NULL,
		COD_TERRITORIO VARCHAR2(4),
		IND_REGISTRO VARCHAR2(1),
		COD_OFICINA VARCHAR2(4),
		COD_GESTOR VARCHAR2(6),
		CLIXGEST NUMBER,
		SEG_10100 NUMBER,
		SEG_10200 NUMBER,
		SEG_20100 NUMBER,
		SEG_20200 NUMBER,
		SEG_20300 NUMBER,
		SEG_20400 NUMBER,
		SEG_20500 NUMBER,
		SEG_20600 NUMBER,
		SEG_30100 NUMBER,
		SEG_30200 NUMBER,
		SEG_30300 NUMBER,
		SEG_30400 NUMBER,
		SEG_40100 NUMBER,
		SEG_40200 NUMBER,
		SEG_40300 NUMBER,
		SEG_40400 NUMBER,
		SEG_50100 NUMBER,
		SEG_50200 NUMBER,
		SEG_50300 NUMBER,
		SEG_50400 NUMBER,
		SEG_60100 NUMBER,
		SEG_60200 NUMBER,
		SEG_60300 NUMBER,
		SEG_60400 NUMBER,
		SEG_80100 NUMBER,
		SEG_80200 NUMBER,
		SEG_80300 NUMBER,
		SEG_80400 NUMBER,
		SEG_80500 NUMBER,
		SEG_80600 NUMBER,
		SEG_80700 NUMBER,
		SEG_90200 NUMBER,
		SEG_99900 NUMBER,
		DESVIN NUMBER,
		POCOVIN NUMBER,
		VIN NUMBER,
		MUYVIN NUMBER,
		NATDESVIN NUMBER,
		NATVIN NUMBER,
		JURVIN NUMBER,
		AHOR_T NUMBER,
		AHSD_T NUMBER,
		AVAL_T NUMBER,
		B24_T NUMBER,
		CCTE_T NUMBER,
		CEXT_T NUMBER,
		CLOC_T NUMBER,
		COLB_T NUMBER,
		CPTE_T NUMBER,
		CTS_T NUMBER,
		CTSD_T NUMBER,
		VIP_T NUMBER,
		DSCT_T NUMBER,
		FCEX_T NUMBER,
		FMUT_T NUMBER,
		LCTA_T NUMBER,
		LEAS_T NUMBER,
		MCLA_T NUMBER,
		MORO_T NUMBER,
		MP_T NUMBER,
		PAUT_T NUMBER,
		PCOM_T NUMBER,
		PER_T NUMBER,
		PH_T NUMBER,
		PHIP_T NUMBER,
		PLZO_T NUMBER,
		PMAS_T NUMBER,
		PMIV_T NUMBER,
		PPER_T NUMBER,
		PPPER_T NUMBER,
		PREF_T NUMBER,
		PROM_T NUMBER,
		PSER_T NUMBER,
		PSERV_T NUMBER,
		DEP_T NUMBER,
		SDEP_T NUMBER,
		SEXT_T NUMBER,
		SONC_T NUMBER,
		SPRO_T NUMBER,
		VID_T NUMBER,
		SVID_T NUMBER,
		TDE_T NUMBER,
		SVIP_T NUMBER,
		TVIP_T NUMBER,
		VARC_T NUMBER,
		VCLA_T NUMBER,
		VCTR_T NUMBER,
		VEMP_T NUMBER,
		VNAC_T NUMBER,
		VORO_T NUMBER,
		VPLA_T NUMBER,
		VPOLA_T NUMBER,
		VREP_T NUMBER,
		TDEB_T NUMBER,
		CNET_T NUMBER,
		LINCO_T NUMBER,
		POS_T NUMBER,
		EMPH_T NUMBER,
		RIESGO_D_T NUMBER,
		RIESGO_I_T NUMBER,
		RIESGO_T NUMBER,
		PASIVO_T NUMBER,
		VOLUMEN_T NUMBER,
		SUM_T_ACT NUMBER,
		SUM_T_ACT1 NUMBER,
		SUM_T_ACT2 NUMBER,
		SUM_T_ACT3 NUMBER,
		SUM_T_ACT4 NUMBER,
		SUM_T_ACT5 NUMBER,
		SUM_T_ACT6 NUMBER,
		SUM_ACT_CTO NUMBER,
		SUM_ACT_CT1 NUMBER,
		SUM_ACT_CT2 NUMBER,
		SUM_ACT_CT3 NUMBER,
		SUM_ACT_CT4 NUMBER,
		SUM_ACT_CT5 NUMBER,
		SUM_ACT_CT6 NUMBER,
		CEMP_T NUMBER,
		CVIP_T NUMBER,
		ICALICTE00 NUMBER,
		ICALICTE10 NUMBER,
		ICALICTE20 NUMBER,
		ICALICTE30 NUMBER,
		ICALICTE40 NUMBER,
		MOFACTV_T NUMBER(12 , 0),
		CS000LINEAMAXTC_T NUMBER(12 , 0),
		CS000MTOPRESTAMO_T NUMBER(12 , 0),
		MONTOVEHICULAR_T NUMBER(12 , 0),
		MONTOHIPOTECARIO_T NUMBER(12 , 0),
		MONTOSUBROGADOS_T NUMBER(12 , 0)
	)
	LOGGING;

CREATE TABLE IILC.TIILC_CLIENTE (
		COD_CLIENTE NUMBER NOT NULL,
		CODIGO VARCHAR2(8),
		COD_OFICINA VARCHAR2(4) NOT NULL,
		COD_GESTOR VARCHAR2(6) NOT NULL,
		NOMBRE VARCHAR2(50),
		COD_TERRITORIO VARCHAR2(4) NOT NULL,
		SEGMENT1 VARCHAR2(6),
		EDAD NUMBER,
		ESTCIVIL VARCHAR2(1),
		CALLE VARCHAR2(30),
		NRO VARCHAR2(10),
		PERFIL VARCHAR2(8),
		DIREC1 VARCHAR2(60),
		DISTRITO VARCHAR2(30),
		PROVINCIA VARCHAR2(30),
		DEPARTAMENTO VARCHAR2(30),
		TIPO_PERSONA VARCHAR2(5),
		CLASIFICACION VARCHAR2(10),
		TELEFONO VARCHAR2(12),
		VINCULACION VARCHAR2(5),
		PPER NUMBER,
		PCOM NUMBER,
		VNAC NUMBER,
		CCTE NUMBER,
		COLB NUMBER,
		CNET NUMBER,
		PAUT NUMBER,
		DSCT NUMBER,
		VARC NUMBER,
		CEMP NUMBER,
		SDEP NUMBER,
		CEXT NUMBER,
		PHIP NUMBER,
		LEAS NUMBER,
		VCLA NUMBER,
		CVIP NUMBER,
		SVID NUMBER,
		LINCO NUMBER,
		PMIV NUMBER,
		CLOC NUMBER,
		VREP NUMBER,
		AHSD NUMBER,
		SONC NUMBER,
		TCO NUMBER,
		B24 NUMBER,
		CPTE NUMBER,
		PREF NUMBER,
		VORO NUMBER,
		AHOR NUMBER,
		SPRO NUMBER,
		POS NUMBER,
		T_ACT2 NUMBER,
		PMAS NUMBER,
		T_ACT3 NUMBER,
		LCTA NUMBER,
		T_ACT4 NUMBER,
		VPLA NUMBER,
		T_ACT5 NUMBER,
		PLZO NUMBER,
		T_ACT6 NUMBER,
		PSERV NUMBER,
		TPR NUMBER,
		PROM NUMBER,
		T_ACT_CT2 NUMBER,
		VEMP NUMBER,
		T_ACT_CT3 NUMBER,
		PH NUMBER,
		T_ACT_CT4 NUMBER,
		FCEX NUMBER,
		T_ACT_CT5 NUMBER,
		VCTR NUMBER,
		T_ACT_CT6 NUMBER,
		FMUT NUMBER,
		MARGENO NUMBER,
		NRO_DOCUMENTO VARCHAR2(12),
		BCORIE NUMBER,
		EMPH NUMBER,
		BCORID NUMBER,
		AVAL NUMBER,
		BCORII NUMBER,
		MCLA NUMBER,
		BCOPAS NUMBER,
		CTS NUMBER,
		BCOVOL NUMBER,
		TDEB NUMBER,
		PORCRIE NUMBER,
		MORO NUMBER,
		PORCRID NUMBER,
		CTSD NUMBER,
		PORCRII NUMBER,
		TVIP NUMBER,
		SBSRIE NUMBER,
		SBSRID NUMBER,
		SBSRII NUMBER,
		SBSJUD NUMBER,
		COD_EMPRESA VARCHAR2(8),
		DES_EMPRESA VARCHAR2(40),
		INTERVPAS VARCHAR2(20),
		MOFACTV NUMBER(7 , 0) DEFAULT 0  NOT NULL,
		CS000LINEAMAXTC NUMBER(7 , 0) DEFAULT 0  NOT NULL,
		MOFPASV VARCHAR2(20),
		MOFSERV VARCHAR2(20),
		MOFCANAL VARCHAR2(20),
		MPHPASV VARCHAR2(16),
		CS000MTOPRESTAMO NUMBER(7 , 0) DEFAULT 0  NOT NULL,
		MONTOVEHICULAR NUMBER(7 , 0) DEFAULT 0  NOT NULL,
		CTACTEOFERTA VARCHAR2(20),
		CTAAHOFERTA VARCHAR2(20),
		CTAPOFERTA VARCHAR2(20),
		FMUTUOOFERT VARCHAR2(20),
		CTACTSOFERT VARCHAR2(20),
		TCONSACTV NUMBER(4 , 2) DEFAULT 0  NOT NULL,
		MONTOSUBROGADOS NUMBER(7 , 0) DEFAULT 0  NOT NULL,
		TSUBACTV NUMBER(4 , 2) DEFAULT 0  NOT NULL,
		THIPOTACTV NUMBER(4 , 2) DEFAULT 0  NOT NULL,
		TVEHICACTV NUMBER(4 , 2) DEFAULT 0  NOT NULL,
		TCUOT36ACT NUMBER(4 , 2) DEFAULT 0  NOT NULL,
		TCUOT48ACT NUMBER(4 , 2) DEFAULT 0  NOT NULL,
		CS000MONTOCTA60 NUMBER(6 , 2) DEFAULT 0  NOT NULL,
		TCUOT60ACT NUMBER(4 , 2) DEFAULT 0  NOT NULL,
		CSS000PRESMENA5000 NUMBER(9 , 2) DEFAULT 0  NOT NULL,
		CS000COMISDESEMEN5000 NUMBER(6 , 2) DEFAULT 0  NOT NULL,
		CS000PRES5000A15000 NUMBER(9 , 2) DEFAULT 0  NOT NULL,
		C5000COMDES15000ACT NUMBER(6 , 2) DEFAULT 0  NOT NULL,
		CS000PRESMAYA15000 NUMBER(9 , 2) DEFAULT 0  NOT NULL,
		COMDES15000AC NUMBER(6 , 2) DEFAULT 0  NOT NULL,
		CS000LINMINADQTC NUMBER(7 , 0) DEFAULT 0  NOT NULL,
		CS000TIPODECREDITO VARCHAR2(30),
		CS000MIXMONPREST NUMBER(7 , 0) DEFAULT 0  NOT NULL,
		CS000MIXLINASISTC NUMBER(7 , 0) DEFAULT 0  NOT NULL,
		CS000MIXTIPOTC VARCHAR2(30),
		CS000PRESTCMENA5000 NUMBER(9 , 2) DEFAULT 0  NOT NULL,
		CS000PRESTC500015000 NUMBER(9 , 2) DEFAULT 0  NOT NULL,
		CS000PRESTCMAYA15000 NUMBER(9 , 2) DEFAULT 0  NOT NULL,
		ATRIBCTACTEPASV VARCHAR2(20),
		ATRIBCTAAHPASV VARCHAR2(20),
		ATRIBCTAPLAZPASV VARCHAR2(20),
		ATRIBCTSPASV VARCHAR2(20),
		ATRIBFMUTUOPASV VARCHAR2(20),
		COBOFSERV VARCHAR2(20),
		SVIDOFSERV VARCHAR2(20),
		SONCOFSERV VARCHAR2(20),
		SVINCOFSERV VARCHAR2(20),
		PHOFSERV VARCHAR2(20),
		DEBOFSERV VARCHAR2(20),
		VIPOFSERV VARCHAR2(20),
		OFCNETCAN VARCHAR2(20),
		OFCEMPCAN VARCHAR2(20),
		OFLINCOCAN VARCHAR2(20),
		OFB24CAN VARCHAR2(20),
		OFPOSCAN VARCHAR2(20),
		PREFIJO VARCHAR2(3),
		MONTOHIPOTECARIO NUMBER(7 , 0),
		CS000MONTOCTA36 VARCHAR2(7),
		CS000MONTOCTA48 NUMBER(7 , 0)
	)
	LOGGING;

CREATE TABLE IILC.TIILC_TERRITORIO (
		COD_TERRITORIO VARCHAR2(4) NOT NULL,
		COD_AREA VARCHAR2(4) NOT NULL,
		DES_TERRITORIO VARCHAR2(100)
	)
	LOGGING;

CREATE TABLE IILC.TIILC_PERMISO_PERFIL (
		COD_PERFIL VARCHAR2(4) NOT NULL,
		TIPO_ACCESO NUMBER NOT NULL,
		VALOR_RCP VARCHAR2(50) NOT NULL
	)
	LOGGING;

CREATE TABLE IILC.TIILC_PERFIL (
		COD_PERFIL VARCHAR2(4) NOT NULL,
		DES_PERFIL VARCHAR2(30),
		COMPONENTE VARCHAR2(50)
	)
	LOGGING;

CREATE TABLE IILC.TIILC_OFICINA (
		COD_OFICINA VARCHAR2(4) NOT NULL,
		COD_TERRITORIO VARCHAR2(4) NOT NULL,
		COD_AREA VARCHAR2(4) NOT NULL,
		DES_OFICINA VARCHAR2(100)
	)
	LOGGING;

CREATE TABLE IILC.TIILC_MULTITABLA (
		COD_MULT VARCHAR2(3) NOT NULL,
		COD_ELE VARCHAR2(10) NOT NULL,
		VALOR1 VARCHAR2(80),
		VALOR2 VARCHAR2(80),
		VALOR3 VARCHAR2(80),
		VALOR4 VARCHAR2(80)
	)
	LOGGING;

CREATE TABLE IILC.TIILC_LINEA_COMERCIAL (
		COD_GRUPO VARCHAR2(6) NOT NULL,
		COD_LINCOM VARCHAR2(6) NOT NULL,
		DES_LINCOM VARCHAR2(50) NOT NULL
	)
	LOGGING;

CREATE TABLE IILC.TIILC_GESTOR (
		COD_AREA VARCHAR2(4) NOT NULL,
		COD_TERRITORIO VARCHAR2(4) NOT NULL,
		COD_OFICINA VARCHAR2(4) NOT NULL,
		COD_GESTOR VARCHAR2(7) NOT NULL,
		NOM_GESTOR VARCHAR2(100),
		REG_GESTOR VARCHAR2(8),
		PERFIL_GESTOR VARCHAR2(5)
	)
	LOGGING;

CREATE TABLE IILC.TIILC_EMPRESA (
		COD_EMPRESA VARCHAR2(8) NOT NULL,
		DES_EMPRESA VARCHAR2(40)
	)
	LOGGING;

CREATE TABLE IILC.TIILC_AREA (
		COD_AREA VARCHAR2(4) NOT NULL,
		DES_AREA VARCHAR2(100)
	)
	LOGGING;

CREATE UNIQUE INDEX IILC.TIILC_TOTAL_PK ON IILC.TIILC_TOTAL (COD_TOTAL ASC)
	LOGGING;

CREATE UNIQUE INDEX IILC.TIILC_CLIENTE_PK ON IILC.TIILC_CLIENTE (COD_CLIENTE ASC)
	LOGGING;

CREATE INDEX IILC.XPKTIILC_CLIENTE_01 ON IILC.TIILC_CLIENTE (COD_OFICINA ASC)
	LOGGING;

CREATE INDEX IILC.XPKTIILC_CLIENTE_02 ON IILC.TIILC_CLIENTE (COD_TERRITORIO ASC)
	LOGGING;

CREATE INDEX IILC.XPKTIILC_CLIENTE_03 ON IILC.TIILC_CLIENTE (COD_GESTOR ASC)
	LOGGING;

CREATE INDEX IILC.XPKTIILC_CLIENTE_04 ON IILC.TIILC_CLIENTE (VINCULACION ASC)
	LOGGING;

CREATE INDEX IILC.XPKTIILC_CLIENTE_05 ON IILC.TIILC_CLIENTE (CLASIFICACION ASC)
	LOGGING;

CREATE INDEX IILC.XPKTIILC_CLIENTE_06 ON IILC.TIILC_CLIENTE (MARGENO ASC)
	LOGGING;

CREATE INDEX IILC.XPKTIILC_CLIENTE_07 ON IILC.TIILC_CLIENTE (SEGMENT1 ASC)
	LOGGING;

CREATE INDEX IILC.XPKTIILC_CLIENTE_08 ON IILC.TIILC_CLIENTE (EDAD ASC)
	LOGGING;

CREATE INDEX IILC.XPKTIILC_CLIENTE_09 ON IILC.TIILC_CLIENTE (PORCRIE ASC)
	LOGGING;

CREATE INDEX IILC.XPKTIILC_CLIENTE_10 ON IILC.TIILC_CLIENTE (COD_EMPRESA ASC)
	LOGGING;

CREATE UNIQUE INDEX IILC.TIILC_TERRITORIO_PK ON IILC.TIILC_TERRITORIO (COD_AREA ASC, COD_TERRITORIO ASC)
	LOGGING;

CREATE UNIQUE INDEX IILC.TIILC_PERMISO_PERFIL_PK ON IILC.TIILC_PERMISO_PERFIL (COD_PERFIL ASC, TIPO_ACCESO ASC, VALOR_RCP ASC)
	LOGGING;

CREATE UNIQUE INDEX IILC.TIILC_PERFIL_PK ON IILC.TIILC_PERFIL (COD_PERFIL ASC)
	LOGGING;

CREATE UNIQUE INDEX IILC.TIILC_OFICINA_PK ON IILC.TIILC_OFICINA (COD_AREA ASC, COD_TERRITORIO ASC, COD_OFICINA ASC)
	LOGGING;

CREATE UNIQUE INDEX IILC.TIILC_MULTITABLA_PK ON IILC.TIILC_MULTITABLA (COD_MULT ASC, COD_ELE ASC)
	LOGGING;

CREATE UNIQUE INDEX IILC.TIILC_LINEA_COMERCIAL_PK ON IILC.TIILC_LINEA_COMERCIAL (COD_GRUPO ASC, COD_LINCOM ASC)
	LOGGING;

CREATE UNIQUE INDEX IILC.TIILC_GESTOR_PK ON IILC.TIILC_GESTOR (COD_AREA ASC, COD_TERRITORIO ASC, COD_OFICINA ASC, COD_GESTOR ASC)
	LOGGING;

CREATE UNIQUE INDEX IILC.TIILC_EMPRESA_PK ON IILC.TIILC_EMPRESA (COD_EMPRESA ASC)
	LOGGING;

CREATE UNIQUE INDEX IILC.TIILC_AREA_PK ON IILC.TIILC_AREA (COD_AREA ASC)
	LOGGING;

ALTER TABLE IILC.TIILC_TOTAL ADD CONSTRAINT TIILC_TOTAL_PK PRIMARY KEY (COD_TOTAL);

ALTER TABLE IILC.TIILC_CLIENTE ADD CONSTRAINT TIILC_CLIENTE_PK PRIMARY KEY (COD_CLIENTE);

ALTER TABLE IILC.TIILC_TERRITORIO ADD CONSTRAINT TIILC_TERRITORIO_PK PRIMARY KEY (COD_AREA, COD_TERRITORIO);

ALTER TABLE IILC.TIILC_PERMISO_PERFIL ADD CONSTRAINT TIILC_PERMISO_PERFIL_PK PRIMARY KEY (COD_PERFIL, TIPO_ACCESO, VALOR_RCP);

ALTER TABLE IILC.TIILC_PERFIL ADD CONSTRAINT TIILC_PERFIL_PK PRIMARY KEY (COD_PERFIL);

ALTER TABLE IILC.TIILC_OFICINA ADD CONSTRAINT TIILC_OFICINA_PK PRIMARY KEY (COD_AREA, COD_TERRITORIO, COD_OFICINA);

ALTER TABLE IILC.TIILC_MULTITABLA ADD CONSTRAINT TIILC_MULTITABLA_PK PRIMARY KEY (COD_MULT, COD_ELE);

ALTER TABLE IILC.TIILC_LINEA_COMERCIAL ADD CONSTRAINT TIILC_LINEA_COMERCIAL_PK PRIMARY KEY (COD_GRUPO, COD_LINCOM);

ALTER TABLE IILC.TIILC_GESTOR ADD CONSTRAINT TIILC_GESTOR_PK PRIMARY KEY (COD_AREA, COD_TERRITORIO, COD_OFICINA, COD_GESTOR);

ALTER TABLE IILC.TIILC_EMPRESA ADD CONSTRAINT TIILC_EMPRESA_PK PRIMARY KEY (COD_EMPRESA);

ALTER TABLE IILC.TIILC_AREA ADD CONSTRAINT TIILC_AREA_PK PRIMARY KEY (COD_AREA);

CREATE TRIGGER IILC.INSERT_TOTAL 
	BEFORE INSERT ON IILC.TIILC_TOTAL
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
DECLARE last_cod INTEGER := 0;
count_row INTEGER := 0;
BEGIN
SELECT COUNT(*)
  INTO count_row
  FROM tiilc_total;

  IF count_row = 0 THEN
    :NEW.cod_total := 1;
  ELSE
    SELECT MAX(cod_total)
    INTO last_cod
    FROM tiilc_total;

    :NEW.cod_total := last_cod + 1;
  END IF;
  END;

