<div align="center" class="ui-widget ui-widget-content ui-corner-all" style="width: 460px;margin: 3px;">
	<div class="ui-widget ui-state-default ui-corner-top ui-title">
		<label>Inicio de Sesi&oacute;n</label>
	</div> 
	<table style="width: 100%;" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td width="30">&nbsp;</td>
			<td width="26">&nbsp;</td>
			<td width="64">&nbsp;</td>
			<td width="50">&nbsp;</td>
			<td width="30">&nbsp;</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td colspan="3" align="center"><img id="logo" src="<?php echo $this->util()->getImage('logo.gif'); ?>" name="logo" id="logo"></td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td colspan="3" align="center"><b>Titania<br><span style="font-size: 100%;">Sistema Municipal de Administraci&oacute;n Tributaria</span></b></td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td colspan="5">
			<div id="div_resp_logeo" align="center"></div>
			</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td colspan="3">Local:</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td colspan="2">
				<select style="width: 190px;" id="cboLocal">
					<?php echo $this->util()->getComboContenedor('1000000346', '1000000347'); ?>
				</select>
				<!-- autocomplete="off" -->
			</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td colspan="3">Usuario:</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td colspan="2">
				<input class="ui-text" type="text" id="txtuser" name="txtuser" value="P009221" size="19">
				<!-- autocomplete="off" -->
			</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td colspan="3">Contrase&ntilde;a:</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td colspan="2">
				<input class="ui-text" type="password" id="txtpass" name="txtpass" value="1" size="19">
				<!-- autocomplete="off" -->
			</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
		<!--
		<tr>
			<td>&nbsp;</td>
			<td colspan="3">Nivel:</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td colspan="2">
			<select id="cbnivel" name="cbnivel">
				<option value="0">Trabajador</option>
			</select>
			</td>
			<td>&nbsp;</td>
		</tr>
		-->
		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td colspan="3" align="center">
				<input type="button" id="btningreso" name="btningreso" value="Ingresar">
			</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
	</table>
</div>