spool 3_createView.log
CREATE OR REPLACE VIEW IIDO.VIIDO_GESTORES AS
SELECT A.NOM_GESTOR, B.COD_PERFIL, A.ANHO, A.MES, A.COD_OFIC, A.COD_TERR, A.COD_GESTOR
FROM (
  SELECT MIN(UPPER(NOM_GESTOR)) NOM_GESTOR, ANHO
    , MES, COD_OFIC, COD_TERR, COD_GESTOR
    , MAX(COD_META_GESTOR) COD_META_GESTOR
  FROM IIDO.TIIDO_METAS_GESTOR
  GROUP BY ANHO, MES, COD_OFIC, COD_TERR, COD_GESTOR) A
INNER JOIN IIDO.TIIDO_METAS_GESTOR B ON A.COD_META_GESTOR=B.COD_META_GESTOR;
/
CREATE OR REPLACE VIEW IIDO.VIIDO_SEGUIMIENTO AS
SELECT 
  A.CODEPIGRAFE , A.NOMEPIGRAFE , A.COD_OFIC , A.COD_TERR ,
  A.MES_ACCI , A.ANHO , A.PRIORIDAD , A.MET_GER_OFI ,
  UPPER(A.NOM_ACCI) NOM_ACCI , A.COD_GEST , A.NRO_CLIE , A.COMP_GEST ,
  A.NRO_GEST_SEGU_1 , A.NRO_CONC_SEGU_1 , A.MON_SEGU_1 ,
  A.NRO_GEST_SEGU_2 , A.NRO_CONC_SEGU_2 , A.MON_SEGU_2 ,
  A.COD_ACCI , A.INDAFECTA , A.PORC_ASIG , NVL(C.COD_PERFIL, A.COD_PERFIL) COD_PERFIL,
  '-1' ORDEN , NVL(B.TOTAL, 0) TOTAL ,
  NVL(A.PORCENTAJE_MIN, 0) PORCENTAJE_MIN,
  NVL(A.PORCENTAJE_MAX, 0) PORCENTAJE_MAX,
  'SEG' TIPO, NVL(C.COD_PERFIL, '') || ' - ' || NVL(C.NOM_GESTOR, '') NOM_GEST ,
  NVL(C.NOM_GESTOR, ' ') NOM_GESTOR
FROM IIDO.VIIDO_ACCION A LEFT JOIN IIDO.VIIDO_MIS B ON A.CODEPIGRAFE = B.COD_EPI 
    AND A.COD_TERR = B.COD_TERR 
    AND A.COD_OFIC = B.COD_OFICINA 
    AND A.COD_GEST = B.COD_GESTOR 
    AND A.MES_ACCI = B.MES 
    AND A.ANHO     = B.ANHO
  LEFT JOIN IIDO.VIIDO_GESTORES C ON C.COD_GESTOR=A.COD_GEST
    AND C.COD_TERR =A.COD_TERR
    AND C.COD_OFIC =A.COD_OFIC
    AND C.ANHO     =A.ANHO
    AND C.MES      =A.MES_ACCI
UNION ALL
SELECT 
  CAST(A.CODEPIGRAFE AS VARCHAR2(10)) , A.NOMEPIGRAFE , A.CODOFICINA , A.COD_TERR ,
  A.MES , A.ANHO , '' PRIORIDAD , A.MET_GER_OFI ,
  UPPER(A.NOMBRECAMPANIADETALLE) , A.CODGESTOR , A.NROCLIENTE , A.COMPGESTOR ,
  A.NROGESTSEG1 , A.NROCONCSEG1 , A.NOMTSEG1 ,
  A.NROGESTSEG2 , A.NROCONCSEG2 , A.NOMTSEG2 ,
  A.CODCAMPDETA , '-' INDAFECTA , A.PORC_ASIG , NVL(C.COD_PERFIL, A.COD_PERFIL) COD_PERFIL ,
  A.ORDEN , B.TOTAL ,
  NVL(A.PORCENTAJE_MIN, 0) PORCENTAJE_MIN,
  NVL(A.PORCENTAJE_MAX, 0) PORCENTAJE_MAX,
  'ESF' TIPO , NVL(C.COD_PERFIL, '') || ' - ' || NVL(C.NOM_GESTOR, '') NOM_GEST ,
  NVL(C.NOM_GESTOR, ' ') NOM_GESTOR
FROM IIDO.VIIDO_ESFUERZO A LEFT JOIN IIDO.VIIDO_MIS B ON A.CODEPIGRAFE = B.COD_EPI
    AND A.COD_TERR   = B.COD_TERR
    AND A.CODOFICINA = B.COD_OFICINA
    AND A.CODGESTOR  = B.COD_GESTOR
    AND A.MES        = B.MES
    AND A.ANHO       = B.ANHO
  LEFT JOIN IIDO.VIIDO_GESTORES C ON C.COD_GESTOR=A.CODGESTOR
    AND C.COD_TERR =A.COD_TERR
    AND C.COD_OFIC =A.CODOFICINA
    AND C.ANHO     =A.ANHO
    AND C.MES      =A.MES;
/
spool off