<div class="ui-widget ui-widget-content ui-corner-all" style="width: 50%;margin: 3px;">
    <div class="ui-widget ui-state-default ui-corner-top ui-title">
        <label>Aperturar Caja</label>
    </div>
    <br/>
    <table class="ui-tablecontent">
        <tr>
            <td>Cajero</td>
            <td><input style="width: 85px;" type="text" id="txtnrocaja" name="txtnrocaja" ></input></td>
        </tr>
        <tr>
            <td>Nombre Cajero</td>		
            <td><input style="width: 85px;" type="text" id="txtnomcajero" name="txtnomcajero" ></input></td>
        </tr>
        <tr>
            <td>Monto Inicial</td>		
            <td><input style="width: 85px;" type="text" id="txtmtinicial" name="txtmtinicial" ></input></td>
        </tr>
        <tr>
            <td>Local</td>		
            <td><select id="cbolocal"></select></td>
        </tr>
        <tr>
            <td>Observacion</td>		
            <td><textarea id="txtobserv"></textarea></td>
        </tr>
        <tr>
            <td align="center" colspan="2">
                <button id="btnaperturar" name="btnaperturar">Aperturar Caja</button>
            </td>
        </tr>
    </table>
</div>