<div class="ui-widget ui-widget-content ui-corner-all" style="width: 90%;margin: 3px;">
    <div class="ui-widget ui-state-default ui-corner-top ui-title">
        <label>Aperturar Caja</label>
    </div>
    <br/>
    <div id="divmsj">
	    <table class="ui-tablecontent">
	    	<tr>
	            <td>Id</td>		
	            <td><input style="width: 85px;text-align: right;" type="text" id="txtcodapert" name="txtcodapert" class="ui-text" readonly></input></td>
		        <td >Observacion</td>		
	        </tr>
	    	<tr>
	            <td>Fecha</td>		
	            <td><input style="width: 85px;" type="text" id="txtfecha" name="txtfecha" class="ui-text" readonly></input></td>
	            <td rowspan="5" ><textarea id="txtobserv" class="ui-text"></textarea></td>
	        </tr>
	        <tr>
	            <td>Cajero</td>
	            <td>
	            	<input style="width: 85px;" type="text" id="txtnrocaja" name="txtnrocaja" class="ui-text" readonly></input>
	            	<input type="hidden" id="hddnrocaja" name="hddnrocaja" ></input>
	            	<input type="hidden" id="hddidapercaja" name="hddidapercaja" ></input>
	            </td>
	        </tr>
	        <tr>
	            <td>Nombre Cajero</td>		
	            <td><input style="width: 250px;" type="text" id="txtnomcajero" name="txtnomcajero" class="ui-text" readonly></input></td>
	        </tr>
	        <tr>
	            <td>Monto Inicial</td>		
	            <td><input style="width: 85px;" type="text" id="txtmtinicial" name="txtmtinicial" class="ui-text" readonly></input></td>
	        </tr>
	        <tr>
	            <td valign="top">Local</td>		
	            <td valign="top"><select id="cbolocal" style="width: 200px;"></select></td>
	        </tr>
	        <tr>
	            <td align="center" colspan="4">
	                <button id="btnaperturar" name="btnaperturar">Aperturar Caja</button>
	            </td>
	        </tr>
    </table>
    </div>
</div>