
<div id="panelbusqueda" align="center" class="ui-widget ui-widget-content ui-corner-all "  style="width: 1000px;margin: 3px;">
    <div class="ui-widget ui-state-default ui-corner-top ui-title">
        <label>Aperturar Cajas </label>
    </div>
    <table border="0" class="ui-table-panelLayout">
		<tr>
           	<td align="left" width="130px">
           		<div class="ui-widget">
           			<input type="text" class="ui-text" id="txtdia" name="txtdia" style="width: 90px;"/>
           			<input type="hidden" id="fechaorg" name="fechaorg" />
           			</div>
           	</td>
			<td align="left">
				<button id="btnbuscar">Buscar</button><button id="btnhabilitar" name="btnhabilitar">Habilitar</button>
			</td>
        </tr>
    </table>
</div>
<div id="panelResultapertcaj">
	<table id="tblResultapertcaj"></table>
	<div id="ptblResultapertcaj"></div>
</div>