
<div id="panelbusqueda" align="center" class="ui-widget ui-widget-content ui-corner-all "  style="width: 1000px;margin: 3px;">
    <div class="ui-widget ui-state-default ui-corner-top ui-title">
        <label>Cajas </label>
    </div>
    <table border="0" class="ui-table-panelLayout">
		<tr>
           	<td align="left" width="130px">
           		<div class="ui-widget">
           			<input type="text" class="ui-text" id="txtdia" name="txtdia" style="width: 90px;"/>
           			<input type="hidden" id="fechaorg" name="fechaorg" />
           			</div>
           	</td>
			<td align="left">
				<button id="btnbuscar">Buscar</button><!-- <button id="btnhabilitar" name="btnhabilitar">Habilitar</button> -->
			</td>
			<td align="center" width="800px">
				<span id="totalrecaudado"></span>
			</td>
        </tr>
    </table>
</div>
<div id="panelResultapertcaj">
	<table id="tblResultapertcaj"></table>
	<div id="ptblResultapertcaj"></div>
</div>

<div id="panelResultapertcajtotales">
	<table id="tblResultapertcajtotales"></table>
	<div id="ptblResultapertcajtotales"></div>
</div>

<br />
<div id="chartdivbarras" align="center"></div>
<br /><hr /><br />
<div id="chartdivpie" align="center"></div>
<div id="scriptgraf" align="center"></div>
<br/>
