<div class="ui-widget ui-widget-content ui-corner-all" style="width: 50%;margin: 3px;">
    <div class="ui-widget ui-state-default ui-corner-top ui-title">
        <label>Cerrar Caja</label>
    </div>
    <br/>
    <div id="divmsj">
	    <table class="ui-tablecontent">
	    	<tr>
	            <td>Fecha</td>		
	            <td><input style="width: 85px;" type="text" id="txtfecha" name="txtfecha" class="ui-text" ></input></td>
	        </tr>
	        <tr>
	            <td>Cajero</td>
	            <td>
	            	<input style="width: 85px;" type="text" id="txtnrocaja" name="txtnrocaja" class="ui-text"></input>
	            	<input type="hidden" id="hddnrocaja" name="hddnrocaja" ></input>
	            	<input type="hidden" id="hddidapercaja" name="hddidapercaja" ></input>
	            	<input type="hidden" id="hddnomcaj" name="hddnomcaj" ></input>
	            </td>
	        </tr>
	        <tr>
	            <td>Nombre Cajero</td>		
	            <td><input style="width: 250px;" type="text" id="txtnomcajero" name="txtnomcajero" class="ui-text"></input></td>
	        </tr>
	        <tr>
	            <td>Monto Inicial</td>		
	            <td><input style="width: 85px;" type="text" id="txtmtinicial" name="txtmtinicial" class="ui-text"></input></td>
	        </tr>
	        <tr>
	            <td>Monto Cobrado</td>		
	            <td><input style="width: 85px;" type="text" id="txtmtcobrado" name="txtmtcobrado" class="ui-text"></input></td>
	        </tr>
	        <!-- 
	        <tr>
	            <td>Observacion</td>		
	            <td><textarea id="txtobserv" class="ui-text"></textarea></td>
	        </tr>
	         -->
	        <tr>
	            <td align="center" colspan="2">
	                <button id="btncerrarcaja" name="btncerrarcaja">Cerrar Caja</button>
	            </td>
	        </tr>
    </table>
    </div>
</div>