<div class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
	<div class="ui-widget ui-state-default ui-corner-top ui-title">
		<label>Cerrar Caja</label>
	</div>
	<br/>
	<div id="result2" align="center" style="color: red;"></div>
	<table class="ui-tablecontent">
		<tr>
			<td>Nro. Caja</td>
			<td>
				<input type="text" id="txtnrocaja" name="txtnrocaja" readonly="readonly"></input>
				<!-- button id="btnbuscar" name="btnbuscar" >ver</button -->
			</td>
		</tr>
		<tr>
			<td>Fecha Apertura</td>
			<td><input type="text" id="txtfecha" name="txtfecha" readonly="readonly"></input></td>
		</tr>
		<tr>
			<td>Nro. Inicial</td>
			<td><input type="text" id="txtnroini" name="txtnroini" readonly="readonly"></input></td>
		</tr>
		<tr>
			<td>Nro. Final</td>		
			<td><input type="text" id="txtnrofin" name="txtnrofin" readonly="readonly"></input></td>
		</tr>
		<tr>
			<td>Monto Cancelado</td>		
			<td><input type="text" id="txtmontcan" name="txtmontcan" readonly="readonly"></input></td>
		</tr>
		<tr>
			<td>Observaci&oacute;n</td>		
			<td><textarea rows="3" cols="20" id="txtobs"></textarea> </td>
		</tr>
		<tr>
			<td colspan="2" align="center"><button id="cerrarcaja" name="cerrarcaja">Cerrar Caja</button></td>
		</tr>
	</table>
	<div id="action" style="display: none;"></div>
</div>
