<div class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
	<div class="ui-widget ui-state-default ui-corner-top ui-title">
		<label>Aperturar Caja</label>
	</div>
	<br/>
	<table class="ui-tablecontent">
		<tr>
			<td>Nro. Caja :</td>
			<td><input style="width: 85px;" type="text" id="txtnrocaja" name="txtnrocaja" ></input></td>
		</tr>
		<tr>
			<td>Fecha :</td>		
			<td><input style="width: 85px;" type="text" id="txtfecha" name="txtfecha" ></input></td>
		</tr>
		<tr>
			<td align="center" colspan="2">
				<button id="btnaperturar" name="btnaperturar">Aperturar Caja</button>
			</td>
		</tr>
	</table>
	<br/>
	<div id="result" align="center"></div>
	<br/>
</div>