<div align="center"><h1 style="margin: 10;font-size: 14px;">Reaperturar Caja</h1>
<div id="result" align="center" style="color: red;"></div>
<table cellspacing="10" >
	<tr>
		<td>Observacion</td>
		<td><textarea rows="3" cols="20" id="txtobs" name="txtobs"></textarea> </td>
	</tr>
	<tr>
		<td><button id="btnaperturar" name="btnaperturar">Reaperturar</button></td>
		<td><button id="btncerrar" name="btncerrar">Cerrar</button></td>
	</tr>
</table>
</div>
