<div id="busqpersona" align="center">
<table width="500" border="0" cellspacing="0" cellpadding="0">
	<tr>
		<td colspan="5" id="noregis"><strong>No esta registrado(a):</strong></td>
	</tr>
	<tr>
		<td colspan="2" width="60" id="cidpers"></td>
		<td colspan="3" align="left">
		<div id="div_pers_no_reg" align="left"></div>
		</td>
	</tr>	
		<tr id="botones">
			<td>&nbsp;</td>
			<td><input type="button" id="genrecibo" name="genrecibo"
				value="Continuar Operaci&oacute;n"/></td>
			<td>&nbsp;</td>
			<td><input type="button" id="limpiar" name="limpiar"
				value="Nueva Busqueda"/></td>
			<td>&nbsp;</td>
		</tr>

</table>
</div>