<table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0"><tr valign="middle"><td align="center">
<div id="showbp">
<input type="hidden" name="urlredirect" id="urlredirect" />
<input type="hidden" name="fech" id="fech" />
<div align="center"><br>
<br>
<div align="center" id="div_titulo"></div>
<br>
<br>
<table width="690" height="334" border="0" cellpadding="0"
	cellspacing="0">
	<tr>
		<td width="136" height="37">Nivel de b&uacute;squeda:</td>
		<td width="195"><select id="cbnivelbusqpers" name="cbnivelbusqpers">
			<option value="0" selected>Por C&oacute;digo</option>
			<option value="1">Por Nombre y Apellido</option>
			<option value="2">Por Nro. DNI</option>
		</select></td>
		<td width="359" align="center" valign="middle">
		<div id="div_nivelbusqpers" align="left">
			<input type="text" id="txtcidper" name="txtcidper" value="" maxlength="10" size="30"> 
			<input type="button" id="Buscar" name="Buscar" value="&nbsp;&nbsp;&nbsp;&nbsp;Buscar&nbsp;&nbsp;&nbsp;&nbsp;">
		</div>
		</td>
	</tr>
	<tr>
		<td colspan="3" align="center" valign="middle">
		<div id="div_rsbusqpers" align="center"></div>
		</td>
	</tr>
</table>
</div>
</div>
</td></tr></table>