
<div id="jqDialogCargando" style="display:none;text-align:center;">
    <table style="background-color: #fff; padding: 5px;">
        <tr>
            <td align="right" valign="middle"><img src="<?php echo $this->util()->getImage("loading8.gif"); ?>"></td>
            <td align="left" valign="middle" style="font-weight: bold;">Procesando ...</td>
        </tr>
    </table>
</div>
<?php 
    echo $this->dialog()->scriptConfig("jqDialogCargando", "", "{}", "100", "250", "hide-title-bar", "false", "false", "false", "true", "#");
?>