
<table id="barTitle" style="padding: 0px; margin: 0px;" cellspacing="0">
    <tr>
        <td>&nbsp;</td>
        <td class="left">&nbsp;</td>
        <td class="center" style="width: 400px; text-align: center;">
            Usuario: #usuario# | Fecha: #date# | <a title="Cerrar Sesi&oacute;n" href="cerrarSesion.do" onclick="window.close();">Cerrar Sesi&oacute;n</a>
        </td>
    </tr>
</table>
