
<div align="center"> 
<table width="701" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td height="30">&nbsp;</td>
  </tr>
  <tr>
    <td>    </td>
  </tr>
  <tr>
    <td>
    <div style="border:1px solid">
    <table width="700" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td colspan="5" height="10"></td>
        </tr>
      <tr>
        <td width="40">&nbsp;</td>
        <td width="109"><fieldset><legend>C&oacute;digo de Contrib.:</legend><input id="c_codigocontrib" maxlength="6" style="width:100%" value=""></fieldset></td>
        <td width="15">&nbsp;</td>
        <td width="492"><fieldset><legend>Nombre Contribuyente:</legend><input id="c_nombrecontrib" style="width:100%" value=""></fieldset></td>
        <td width="44">&nbsp;</td>
      </tr>
      <tr>
        <td colspan="5" height="8px"></td>
        </tr>
      <tr>
        <td>&nbsp;</td>
        <td><fieldset><legend>C&oacute;digo Predial:</legend><input id="c_predial" style="width:100%" value=""></fieldset></td>
        <td></td>
        <td><fieldset><legend>Direcci&oacute;n:</legend><input id="c_direccontri" style="width:100%" value=""></fieldset></td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td colspan="5"  height="10"></td>
        </tr>
    </table>
    </div>    
    
    </td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>
    	<div style="border:1px solid">
        	<table width="700" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="3" height="8px"></td>
    </tr>
  <tr>
    <td width="40">&nbsp;</td>
    <td width="620">PREDIOS:</td>
    <td width="40">&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>
    	<div id="div_predios" style="overflow-y:scroll;height:200px;border:1px solid">
        	<!-- 
            <div style="border:1px solid">
            <table width="600" border="0" cellspacing="0" cellpadding="0">
				  <tr>
				    <td colspan="8" height="8px"></td>
				    </tr>
				  <tr>
				    <td width="20">&nbsp;</td>
				    <td width="62">C&oacute;digo:</td>
				    <td width="165">&nbsp;</td>
				    <td colspan="4" align="right">
				    	<button id="btndetpredio000001" name="btndetpredio000001" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only ui-state-hover" role="button"><span class="ui-button-text">Detalle Predio</span></button>
				    </td>
				    <td width="20">&nbsp;</td>
				  </tr>
				  <tr>
				    <td colspan="8" height="8px"></td>
				    </tr>
				  <tr>
				    <td>&nbsp;</td>
				    <td>Tipo:</td>
				    <td>&nbsp;</td>
				    <td width="57">Uso:</td>
				    <td width="166">&nbsp;</td>
				    <td width="60">Porcentaje:</td>
				    <td width="50">&nbsp;</td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td colspan="8" height="8px"></td>
				    </tr>
				  <tr>
				    <td>&nbsp;</td>
				    <td>Fech Adq.:</td>
				    <td>&nbsp;</td>
				    <td>Fech Baja:</td>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td colspan="8" height="8px"></td>
				  </tr>
				  <tr>
				    <td>&nbsp;</td>
				    <td colspan="6" align="center">
				    	<table width="550" border="1" cellspacing="0" cellpadding="0">
				              <tr>
				                <th width="137" scope="col">Valor del Preio</th>
				                <th width="135" scope="col">Valor Afecto</th>
				                <th width="140" scope="col">Impuesto Anual</th>
				                <th width="138" scope="col">Calculo de Valuo</th>
				              </tr>
				              <tr>
				                <td>&nbsp;</td>
				                <td>&nbsp;</td>
				                <td>&nbsp;</td>
				                <td>&nbsp;</td>
				              </tr>
				            </table>    </td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td colspan="8" height="8px"></td>
				    </tr>
				</table>     
            </div>
            -->                   
        </div>    
        
        </td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td align="right">
    <button id="btnnuevopredio" name="btnnuevopredio" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only ui-state-hover" role="button"><span class="ui-button-text">Nuevo Predio</span></button>
    </td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td colspan="3" height="8px"></td>
    </tr>
</table>
        </div>    </td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td align="center">
    	<button id="btndetpredio" name="btndatoscontri" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only ui-state-hover" role="button"><span class="ui-button-text">Datos Contribuyente</span></button>
    	<button id="btndetpredio" name="btnestcta" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only ui-state-hover" role="button"><span class="ui-button-text">Estado de Cuenta</span></button>

   </td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
</table>

</div>

<!-- ---------------------------------------------------------------------------------------------------------------------------------  -->
<!-- form buscar persona -->
<div id="ventanabuscarpersonanombre">
	<table width="700" border="0" cellspacing="0" cellpadding="0">
	  <tr>
	    <td width="20">&nbsp;</td>
	    <td>&nbsp;</td>
	    <td width="20">&nbsp;</td>
	  </tr>
	  <tr>
	    <td>&nbsp;</td>
	    <td>
	    <table width="660" border="1" cellspacing="0" cellpadding="0">
	    <thead class="ui-widget ui-widget-header ui-title1">
	      <tr>
	        <th width="80">Cod. Contrib.</th>
	        <th width="240">Nombre</th>
	        <th width="323">Direcci&oacute;n Fiscal</th>
	        <th width="17">-</th>
	        </tr>
	    </thead>
	    </table>
	    
	    </td>
	    <td>&nbsp;</td>
	  </tr>
	  <tr>
	    <td>&nbsp;</td>
	    <td>
	    	<div id="div_rptabuscarpersonanombre" style="overflow-y: scroll; height: 150px; border: 1px solid;">
	        	<table id="tbl_buscarpersonanombre" width="640" border="1" cellspacing="0" cellpadding="0"><tbody class="ui-table-body">
	                  <tr>
	                    <td width="79">Cod. Contrib.</td>
	                    <td width="239">Nombre</td>
	                    <td width="320">Direcci&oacute;n Fiscal</td>                    
	                    </tr>
	                    <tr>
	                    <td width="79">Cod. Contrib.</td>
	                    <td width="239">Nombre</td>
	                    <td width="320">Direcci&oacute;n Fiscal</td>                    
	                    </tr>
	                </tbody></table>
	        </div>
	    </td>
	    <td>&nbsp;</td>
	  </tr>
	  <tr>
	    <td>&nbsp;</td>
	    <td>&nbsp;</td>
	    <td>&nbsp;</td>
	  </tr>
	</table>
</div>
<!-- ---------------------------------------------------------------------------------------------------------------------------------  -->
<!-- form buscar por direccion -->
<div id="ventanabuscarpersonadireccion">
	<table width="850" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="12">&nbsp;</td>
    <td width="822">&nbsp;</td>
    <td width="16">&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>
    <table width="822" border="1" cellspacing="0" cellpadding="0">
    <thead class="ui-widget ui-widget-header ui-title1">
      <tr>
        <th width="54" >Cod.Pred.</th>
        <th width="237" >Nombre Via</th>
        <th width="24" >Nro.</th>
        <th width="41" >Depart.</th>
        <th width="24" >Int.</th>
        <th width="29" >Letra</th>
        <th width="34" >Estac.</th>
        <th width="39" >Depos.</th>
        <th width="24" >Mz.</th>
        <th width="25" >Lote</th>
        <th width="248" >Contribuyente</th>
        <th width="17" >-</th>
      </tr>
      </thead>
    </table>

    </td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>
    	<div id="div_rptabuscarpersonadir" style="overflow-y: scroll; height: 150px; border: 1px solid;">
        	<table width="805" border="1" cellspacing="0" cellpadding="0">
                <tbody class="ui-table-body">
                 	<tr>
                    	<td width="54" >Cod.Pred.</td>
                        <td width="237" >Nombre Via</td>
                        <td width="24" >Nro.</td>
                        <td width="41" >Depart.</td>
                        <td width="24" >Int.</td>
                        <td width="29" >Letra</td>
                        <td width="34" >Estac.</td>
                        <td width="39" >Depos.</td>
                        <td width="24" >Mz.</td>
                        <td width="25" >Lote</td>
                        <td width="248" >Contribuyente</td>
                    </tr>
                </tbody>
                </table>
        </div>
    </td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
</table>
</div>

<!-- ---------------------------------------------------------------------------------------------------------------------------------  -->
<!-- form predio rustico -->
<div id="ventanadatosprediorustico">
<table width="660" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="30">&nbsp;</td>
    <td width="600">&nbsp;</td>
    <td width="30">&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td  style="border:1px solid">
   	  <fieldset>
        	<legend><h2>Predios Colindantes</h2></legend>
            <table width="600" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="6" align="right" height="8px"></td>
  </tr>
  <thead class="ui-widget ui-widget-header ui-title1">          
  <tr>
    <th width="40">&nbsp;</th>
    <th width="10">&nbsp;</th>
    <th width="300" align="center">Ubicaci&oacute;n</th>
    <th width="10">&nbsp;</th>
    <th width="220" align="center">Propietario</th>
    <th width="20" align="center">(*)</th>
  </tr>
  </thead>
  <tr>
    <td align="right"><b>Norte:</b></td>
    <td>&nbsp;</td>
    <td><input type="text" style="width:100%" id="txtrust_predcolinnorte" value="" /></td>
    <td>&nbsp;</td>
    <td><input type="text" style="width:100%" id="txtrust_propietarionorte" value="" /></td>
    <td align="center"><input type="checkbox" id="txtrust_checknorte" /></td>
  </tr>
  <tr>
    <td colspan="6" align="right" height="5px"></td>
    </tr>
  <tr>
    <td align="right"><b>Sur:</b></td>
    <td>&nbsp;</td>
    <td><input type="text" style="width:100%" id="txtrust_predcolinsur" value="" /></td>
    <td>&nbsp;</td>
    <td><input type="text" style="width:100%" id="txtrust_propietariosur" value="" /></td>
    <td align="center"><input type="checkbox" id="txtrust_checksur" /></td>
  </tr>
  <tr>
    <td colspan="6" align="right" height="5px"></td>
  </tr>
  <tr>
    <td align="right"><b>Este:</b></td>
    <td>&nbsp;</td>
    <td><input type="text" style="width:100%" id="txtrust_predcolineste" value="" /></td>
    <td>&nbsp;</td>
    <td><input type="text" style="width:100%" id="txtrust_propietarioeste" value="" /></td>
    <td align="center"><input type="checkbox" id="txtrust_checkeste" /></td>
  </tr>
  <tr>
    <td colspan="6" align="right" height="5px"></td>
  </tr>
  <tr>
    <td align="right"><b>Oeste:</b></td>
    <td>&nbsp;</td>
    <td><input type="text" style="width:100%" id="txtrust_predcolinoeste" value="" /></td>
    <td>&nbsp;</td>
    <td><input type="text" style="width:100%" id="txtrust_propietariooeste" value="" /></td>
    <td align="center"><input type="checkbox" id="txtrust_checkoeste" /></td>
  </tr>
  <tr>
    <td colspan="6" align="right" height="8px"></td>
  </tr>
</table>

        </fieldset>
    </td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td  style="border:1px solid">
    	<fieldset>
        	<legend><h2>Datos Relativos al Terreno</h2></legend><br>
            <table width="600" border="0" cellspacing="0" cellpadding="0">
            
    <tr>
    <td width="105"><b>Plan de Cultivo:</b></td>
    <td width="15">&nbsp;</td>
    <td width="130"><input type="text" style="width:130px" id="txtrust_plancultivo" value="" /></td>
    <td width="15">&nbsp;</td>
    <td width="115"><b>Canon de Agua:</b></td>
    <td width="10">&nbsp;</td>
    <td width="210"><input type="text" style="width:130px" id="txtrust_canonagua" value="" /></td>
  </tr>
  <tr>
    <td colspan="7" align="right" height="8px"></td>
  </tr>
</table>

    	</fieldset>
    </td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td style="border:1px solid">
    <fieldset>
        	<legend><h2>Determinaci&oacute;n del valuo del Predio</h2></legend>
            <table width="600" border="0" cellspacing="0" cellpadding="0">
 <thead class="ui-widget ui-widget-header ui-title1">
  <tr>  	
    <th width="265">Clasificaci&oacute;n:</th>
    <th width="10">&nbsp;</th>
    <th width="55">Categoria:</th>
    <th width="10">&nbsp;</th>
    <th width="80">Arancel:</th>
    <th width="10">&nbsp;</th>
    <th width="80">Hectarias:</th>
    <th width="10">&nbsp;</th>
    <th width="80">Valor Total:</th>
    
  </tr>
  </thead>
  <tr>
    <td colspan="9" height="5px"></td>
    </tr>
  <tr>
    <td><select id="cbrustico_clasif_0" style="width:100%"></select></td>
    <td>&nbsp;</td>
    <td><select id="cbrustico_categ_0" style="width:100%">
    </select></td>
    <td>&nbsp;</td>
    <td><input type="text" id="cbrustico_arancel_0" style="width:80px" value="" /></td>
    <td>&nbsp;</td>
    <td><input type="text" id="cbrustico_hectaria_0" style="width:80px" value="" /></td>
    <td>&nbsp;</td>
    <td><input type="text" id="cbrustico_valor_0" style="width:80px" value="" /></td>
  </tr>
  <tr>
    <td colspan="9" height="5px"></td>
  </tr>
  <tr>
    <td><select id="cbrustico_clasif_1" style="width:100%"></select></td>
    <td>&nbsp;</td>
    <td><select id="cbrustico_categ_1" style="width:100%">
    </select></td>
    <td>&nbsp;</td>
    <td><input type="text" id="cbrustico_arancel_1" style="width:80px" value="" /></td>
    <td>&nbsp;</td>
    <td><input type="text" id="cbrustico_hectaria_1" style="width:80px" value="" /></td>
    <td>&nbsp;</td>
    <td><input type="text" id="cbrustico_valor_1" style="width:80px" value="" /></td>
  </tr>
  <tr>
    <td colspan="9" height="5px"></td>
  </tr>
  <tr>
     <td><select id="cbrustico_clasif_2" style="width:100%"></select></td>
    <td>&nbsp;</td>
    <td><select id="cbrustico_categ_2" style="width:100%">
    </select></td>
    <td>&nbsp;</td>
    <td><input type="text" id="cbrustico_arancel_2" style="width:80px" value="" /></td>
    <td>&nbsp;</td>
    <td><input type="text" id="cbrustico_hectaria_2" style="width:80px" value="" /></td>
    <td>&nbsp;</td>
    <td><input type="text" id="cbrustico_valor_2" style="width:80px" value="" /></td>
  </tr>
  <tr>
   <td colspan="9" height="5px"></td>
  </tr>
  <tr>
     <td><select id="cbrustico_clasif_3" style="width:100%"></select></td>
    <td>&nbsp;</td>
    <td><select id="cbrustico_categ_3" style="width:100%">
    </select></td>
    <td>&nbsp;</td>
    <td><input type="text" id="cbrustico_arancel_3" style="width:80px" value="" /></td>
    <td>&nbsp;</td>
    <td><input type="text" id="cbrustico_hectaria_3" style="width:80px" value="" /></td>
    <td>&nbsp;</td>
    <td><input type="text" id="cbrustico_valor_3" style="width:80px" value="" /></td>
  </tr>
  <tr>
   <td colspan="9" height="5px"></td>
  </tr>
    <tr>
     <td><select id="cbrustico_clasif_4" style="width:100%"></select></td>
    <td>&nbsp;</td>
    <td><select id="cbrustico_categ_4" style="width:100%">
    </select></td>
    <td>&nbsp;</td>
    <td><input type="text" id="cbrustico_arancel_4" style="width:80px" value="" /></td>
    <td>&nbsp;</td>
    <td><input type="text" id="cbrustico_hectaria_4" style="width:80px" value="" /></td>
    <td>&nbsp;</td>
    <td><input type="text" id="cbrustico_valor_4" style="width:80px" value="" /></td>
  </tr>
  <tr>
    <td colspan="9" height="5px"></td>
  </tr>
    <tr>
      <td><select id="cbrustico_clasif_5" style="width:100%">
      </select></td>
      <td>&nbsp;</td>
      <td><select id="cbrustico_categ_5" style="width:100%">
      </select></td>
      <td>&nbsp;</td>
      <td><input type="text" id="cbrustico_arancel_5" style="width:80px" value="" /></td>
      <td>&nbsp;</td>
      <td><input type="text" id="cbrustico_hectaria_5" style="width:80px" value="" /></td>
      <td>&nbsp;</td>
      <td><input type="text" id="cbrustico_valor_5" style="width:80px" value="" /></td>
    </tr>
   <tr>
    <td colspan="9" height="5px"></td>
  </tr>
    <tr>
     <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td><b>Valor Total</b></td>
    <td>&nbsp;</td>
    <td><input type="text" id="cbrustico_valortotal" style="width:80px" value="" /></td>
  </tr>
<tr>
    <td colspan="9" height="8px"></td>
  </tr>
</table>

    </fieldset>
    </td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><b>(*) El mismo Propietario</b></td>
    <td>&nbsp;</td>
  </tr>
</table>
</div>

<!-- ---------------------------------------------------------------------------------------------------------------------------------  -->
<div id="ventanadetallepredio">

<div align="center">
    <table  border="1" cellspacing="0" cellpadding="0"><tr valign="middle"><td align="center">
    <table width="662" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="7" height="8px"></td>
    </tr>
  <tr>
    <td width="40">&nbsp;</td>
    <td width="50">C&oacute;digo:</td>
    <td width="79" id="c_codigocontrib_x">&nbsp;</td>
    <td width="22">&nbsp;</td>
    <td width="56">Nombre:</td>
    <td width="399" id="c_nombrecontrib_x">&nbsp;</td>
    <td width="16">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="7" height="8px"></td>
    </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Direcci&oacute;n:</td>
    <td colspan="4" id="c_dirfiscal_x">&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td colspan="7" height="8px"></td>
    </tr>
</table>
</td></tr></table>
</div> 
<br>
	<div id="tabs_detallepredio">
		<ul>
			<li><a href="#predio_descripcion">Descripci&oacute;n</a></li>
			<li><a href="#predio_pisos">Pisos</a></li>
			<li><a href="#predio_instalacion">Instalaci&oacute;n</a></li>
		</ul>
		<div id="predio_descripcion">
			
			<div align="center" style="overflow-y:scroll;height:350px;border:1px solid"> 
				<table width="799" border="0" cellspacing="0" cellpadding="0">
				  <tr>
				    <td width="28">&nbsp;</td>
				    <td width="70">&nbsp;</td>
				    <td width="113">&nbsp;</td>
				    <td width="15">&nbsp;</td>
				    <td width="100">&nbsp;</td>
				    <td width="401">&nbsp;</td>
				    <td width="39">&nbsp;</td>
				    <td width="33">&nbsp;</td>
				  </tr>
				  <tr>
				    <td>&nbsp;</td>
				    <td>Cod. Predio:</td>
				    <td id="c_codpred">&nbsp;</td>
				    <td>&nbsp;</td>
				    <td>Direcci&oacute;n Predial:</td>
				    <td id="c_dirpred">&nbsp;</td>
				    <td>
				    	<button id="btndireccion" name="btndireccion" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only ui-state-hover" role="button"><span class="ui-button-text">...</span></button>    </td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td>&nbsp;</td>
				    <td colspan="6"><table width="736" border="0" cellspacing="0" cellpadding="0">
				      <tr>
				        <td><fieldset><legend>Fecha de Adquisici&oacute;n</legend><input id="txt_fechaadquisicion" style="width:100%" value="" /></fieldset></td>
				        <td>&nbsp;</td>
				        <td><fieldset><legend>Fecha de Baja</legend><input id="txt_fechabaja" style="width:100%" value="" /></fieldset></td>
				        <td>&nbsp;</td>
				        <td><fieldset><legend>Ultimo Recalculo</legend><input id="txt_ultimorecalculo" style="width:100%" value="" /></fieldset></td>
				      </tr>
				      <tr>
				        <td>&nbsp;</td>
				        <td>&nbsp;</td>
				        <td>&nbsp;</td>
				        <td>&nbsp;</td>
				        <td>&nbsp;</td>
				      </tr>
				      <tr>
				        <td width="238">
				        	<fieldset><legend>Condici&oacute;n de Propiedad</legend><select id="cb_condicionpropiedad" style="width:100%;padding:2px"></select></fieldset>        </td>
				        <td width="10">&nbsp;</td>
				        <td width="238"><fieldset><legend>Estado de Predio</legend><select id="cb_estadopredio" style="width:100%;padding:2px"></select></fieldset></td>
				        <td width="10">&nbsp;</td>
				        <td width="240"><fieldset><legend>Tipo Predio</legend><select id="cb_tipopredio" style="width:100%;padding:2px"></select></fieldset></td>
				      </tr>
				      <tr>
				        <td colspan="5" height="8px"></td>
				        </tr>
				      <tr>
				        <td><fieldset><legend>Clasificaci&oacute;n del Predio</legend><select id="cb_clasificacionpredio" style="width:100%;padding:2px"></select></fieldset></td>
				        <td>&nbsp;</td>
				        <td><fieldset><legend>Uso General de Predio</legend><select id="cb_usogeneralpredio" style="width:100%;padding:2px"></select></fieldset></td>
				        <td>&nbsp;</td>
				        <td><fieldset><legend>Uso Espec&iacute;fico del Predio</legend><select id="cb_usoespecificopredio" style="width:100%;padding:2px"></select></fieldset></td>
				      </tr>
				      <tr>
				        <td colspan="5" height="8px"></td>
				        </tr>
				        <tr>
				        <td colspan="5" align="left"><button id="btnprediorustico">Datos de Predio R&uacute;stico</button></td>
				        </tr>
				    </table></td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td>&nbsp;</td>
				    <td colspan="6">&nbsp;</td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td>&nbsp;</td>
				    <td colspan="6">
				    	<fieldset  style="padding:5px"><legend>Datos del Terreno</legend>        
				        	<table width="737" border="0" cellspacing="0" cellpadding="0">
				              <tr>
				                <td width="114"><fieldset><legend>&Aacute;rea Terreno:</legend><input id="txt_areaterreno" style="width:100%" value="" /></fieldset></td>
				                <td width="10">&nbsp;</td>
				                <td width="114"><fieldset><legend>Porcentaje Terreno:</legend><input id="txt_procentajeterreno" style="width:100%" value="" /></fieldset></td>
				                <td width="10">&nbsp;</td>
				                <td width="114"><fieldset><legend>Total &Aacute;rea:</legend><input id="txt_totalarea" style="width:100%" value="" /></fieldset></td>
				                <td width="10">&nbsp;</td>
				                <td width="114"><fieldset><legend>&Aacute;rea Com&uacute;n:</legend><input id="txt_areacomun" style="width:100%" value="" /></fieldset></td>
				                <td width="10">&nbsp;</td>
				                <td width="114"><fieldset><legend>Porcentaje Com&uacute;n:</legend><input id="txt_porcentajecomun" style="width:100%" value="" />
				                </fieldset></td>
				                <td width="10">&nbsp;</td>
				                <td width="114"><fieldset><legend>Total Com&uacute;n:</legend><input id="txt_totalcomun" style="width:100%" value="" /></fieldset></td>
				              </tr>
				              <tr>
				                <td colspan="11" height="8px"></td>
				                </tr>
				              <tr>
				                <td><fieldset><legend>Frente:</legend><input id="txt_frente" style="width:100%" value="" /></fieldset></td>
				                <td>&nbsp;</td>
				                <td><fieldset><legend>Arancel:</legend><input id="txt_arancel" style="width:100%" value="" /></fieldset></td>
				                <td>&nbsp;</td>
				                <td><fieldset><legend>Porcentaje Cond:</legend><input id="txt_porcentajecond" style="width:100%" value="" /></fieldset></td>
				                <td>&nbsp;</td>
				                <td colspan="5"><fieldset><legend>Ubicaci&oacute;n del Parque:</legend><select id="cb_ubicacionparque" style="width:100%;padding:2px"></select></fieldset></td>
				              </tr>
				            </table>
				        </fieldset>        </td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td>&nbsp;</td>
				    <td colspan="6">&nbsp;</td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td>&nbsp;</td>
				    <td colspan="6">
				    	<fieldset style="padding:5px"><legend>Inafecto</legend>        
				        	<table width="737" border="0" cellspacing="0" cellpadding="0">
				              <tr>
				                <td colspan="5"><fieldset><legend>Tipo de Inafectaci&oacute;n:</legend><select id="cb_tipoinafecto" style="width:100%;padding:2px"></select></fieldset></td>
				                <td>&nbsp;</td>
				                <td><fieldset><legend>Expediente:</legend><input id="txt_expedienteinafecto" style="width:100%" value="" /></fieldset></td>
				                <td>&nbsp;</td>
				                <td><fieldset><legend>Resoluci&oacute;n:</legend><input id="txt_resolucioninafecto" style="width:100%" value="" /></fieldset></td>
				                <td>&nbsp;</td>
				                <td><fieldset><legend>Fecha Resoluci&oacute;n:</legend><input id="txt_fecharesolucioninafecto" style="width:100%" value="" /></fieldset></td>
				              </tr>
				              <tr>
				                <td colspan="11">&nbsp;</td>
				              </tr>
				              <tr>
				                <td colspan="3"><fieldset><legend>Base Legal:</legend><input id="txt_baselegalinafecto" style="width:100%" value="" /></fieldset></td>
				                <td>&nbsp;</td>
				                <td colspan="3"><fieldset><legend>Observaci&oacute;n:</legend><input id="txt_observacioninafecto" style="width:100%" value="" /></fieldset></td>
				                <td>&nbsp;</td>
				                <td><fieldset><legend>Fecha Inicio:</legend><input id="txt_inicioinafecto" style="width:100%" value="" /></fieldset></td>
				                <td>&nbsp;</td>
				                <td><fieldset><legend>Fecha Fin:</legend><input id="txt_fininafecto" style="width:100%" value="" /></fieldset></td>
				              </tr>
				              <tr>
				                <td colspan="11">&nbsp;</td>
				              </tr>
				              <tr>
				                <td width="114"><fieldset><legend>% IP:</legend><input id="txt_inafectoip" style="width:100%" value="" /></fieldset></td>
				                <td width="10">&nbsp;</td>
				                <td width="114"><fieldset><legend>% LC:</legend><input id="txt_inafectolc" style="width:100%" value="" /></fieldset></td>
				                <td width="10">&nbsp;</td>
				                <td width="114"><fieldset><legend>% RB:</legend><input id="txt_inafectorb" style="width:100%" value="" /></fieldset></td>
				                <td width="10">&nbsp;</td>
				                <td width="114"><fieldset><legend>% LP:</legend><input id="txt_inafectolp" style="width:100%" value="" /></fieldset></td>
				                <td width="10">&nbsp;</td>
				                <td width="114"><fieldset><legend>% PJ:</legend><input id="txt_inafectopj" style="width:100%" value="" /></fieldset></td>
				                <td width="10">&nbsp;</td>
				                <td width="114"><fieldset><legend>% SG:</legend><input id="txt_inafectosg" style="width:100%" value="" /></fieldset></td>
				              </tr>
				              <tr>
				                <td colspan="11" height="8px"></td>
				                </tr>
				            </table>
				        </fieldset>    </td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				  </tr>
				</table>
				
				</div>
			
		</div>
		<div id="predio_pisos">
			
			<div align="center" style="overflow-y:scroll;height:350px;border:1px solid">
					<table width="800" border="0" cellspacing="0" cellpadding="0">
				  <tr>
				    <td colspan="8" height="8px"></td>
				    </tr>
				  <tr>
				    <td width="20">&nbsp;</td>
				    <td colspan="6">
				    
				    	<div style="border:1px solid;overflow-x:scroll;width:760px">
				                <table width="1150" border="1" cellspacing="0" cellpadding="0">
				                <thead class="ui-widget ui-widget-header ui-title1">
				                      <tr>
				                        <th width="30" >Nivel</th>
				                        <th width="41" >Antig.</th>
				                        <th width="80" >Material</th>
				                        <th width="60" >Estado</th>
				                        <th width="20" >Mu</th>
				                        <th width="20" >Te</th>
				                        <th width="20" >Pi</th>
				                        <th width="20" >Pv</th>
				                        <th width="20" >Rv</th>
				                        <th width="20" >Ba</th>
				                        <th width="20" >In</th>
				                        <th width="70" >Area. Contr.</th>
				                        <th width="85" >Val. Unit. m2</th>
				                        <th width="50" >Inc. 5%</th>
				                        <th width="50" >% depr</th>
				                        <th width="50" >depr.</th>
				                        <th width="100" >Val. Unit. Deprec.</th>
				                        <th width="90" >Val. Area Const.</th>
				                        <th width="90" >% Area Com&uacute;n</th>
				                        <th width="95" >Val. Area Comun</th>
				                        <th width="80" >valor final</th>
				                  	  </tr>
				                 </thead> 	  
				                      <tr>
				                        <td colspan="21" height="100px" valign="top" id="c_tablapisos">
				                            
				                                <table border="1" cellspacing="0" cellpadding="0">
				                                    <tr>
				                                      <td width="27" align="center">x</td>
				                                      <td width="40" align="center">x</td>
				                                      <td width="78">x</td>
				                                      <td width="59">x</td>
				                                      <td width="20" align="center">x</td>
				                                      <td width="20" align="center">x</td>
				                                      <td width="20" align="center">x</td>
				                                      <td width="20" align="center">x</td>
				                                      <td width="20" align="center">x</td>
				                                      <td width="20" align="center">x</td>
				                                      <td width="20" align="center">x</td>
				                                      <td width="70" align="right">x</td>
				                                      <td width="85" align="right">x</td>
				                                      <td width="50" align="right">x</td>
				                                      <td width="50" align="right">x</td>
				                                      <td width="50" align="right">x</td>
				                                      <td width="100" align="right">x</td>
				                                      <td width="90" align="right">x</td>
				                                      <td width="90" align="right">x</td>
				                                      <td width="95" align="right">x</td>
				                                      <td width="78" align="right">x</td>
				                                  </tr>
				                                  <tr>
				                                      <td width="27" align="center">x</td>
				                                      <td width="40" align="center">x</td>
				                                      <td width="78">x</td>
				                                      <td width="59">x</td>
				                                      <td width="20" align="center">x</td>
				                                      <td width="20" align="center">x</td>
				                                      <td width="20" align="center">x</td>
				                                      <td width="20" align="center">x</td>
				                                      <td width="20" align="center">x</td>
				                                      <td width="20" align="center">x</td>
				                                      <td width="20" align="center">x</td>
				                                      <td width="70" align="right">x</td>
				                                      <td width="85" align="right">x</td>
				                                      <td width="50" align="right">x</td>
				                                      <td width="50" align="right">x</td>
				                                      <td width="50" align="right">x</td>
				                                      <td width="100" align="right">x</td>
				                                      <td width="90" align="right">x</td>
				                                      <td width="90" align="right">x</td>
				                                      <td width="95" align="right">x</td>
				                                      <td width="78" align="right">x</td>
				                                  </tr>
				                                </table>
				                        </td>
				                      </tr>
				                      <tr>
				                        <td colspan="11">&nbsp;</td>
				                        <td align="right" id="c_total_area_cons">total</td>
				                        <td colspan="5">&nbsp;</td>
				                        <td align="right" id="c_valor_area_cons">total</td>
				                        <td colspan="3">&nbsp;</td>
				                      </tr>
				                    </table>
				    
				    </div>
				       
				    </td>
				    <td width="20">&nbsp;</td>
				  </tr>
				  <tr>
				    <td colspan="8" height="8px"></td>
				    </tr>
				  <tr>
				    <td>&nbsp;</td>
				    <td colspan="6">
				    	<fieldset  style="padding:5px"><legend>Datos del Piso</legend>
				        	<table width="748" border="0" cellspacing="0" cellpadding="0">
				              <tr>
				                <td width="59"><fieldset><legend>Nro Piso</legend><input id="txt_nropiso" style="width:100%" value="" /></fieldset></td>
				                <td width="14">&nbsp;</td>
				                <td width="90"><fieldset><legend>Area Const.</legend><input id="txt_pisoareaconst" style="width:100%" value="" /></fieldset></td>
				                <td width="15">&nbsp;</td>
				                <td width="70"><fieldset><legend>A&ntilde;o Const.</legend><input id="txt_pisoanioconst" style="width:100%" value="" /></fieldset></td>
				                <td width="15">&nbsp;</td>
				                <td width="70"><fieldset><legend>Antig&uuml;edad</legend><input id="txt_pisoantig" style="width:100%" value="" /></fieldset></td>
				                <td width="15">&nbsp;</td>
				                <td width="95"><fieldset><legend>% Area Com&uacute;n</legend><input id="txt_pisoporcareacomun" style="width:100%" value="" /></fieldset></td>
				                <td width="15">&nbsp;</td>
				                <td width="141"><fieldset><legend>Material</legend><select id="cb_pisomaterial" style="width:100%;padding:2px"></select></fieldset></td>
				                <td width="15">&nbsp;</td>
				                <td width="134"><fieldset><legend>Estado</legend><select id="cb_pisoestado" style="width:100%;padding:2px"></select></fieldset></td>
				              </tr>
				            </table>
				        </fieldset>    </td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td colspan="8" height="8px"></td>
				    </tr>
				  <tr>
				    <td>&nbsp;</td>
				    <td colspan="6">
				    	<fieldset  style="padding:5px"><legend>Carecter&iacute;sticas del Piso</legend>
				        	<table width="740" border="0" cellspacing="0" cellpadding="0">
				              <tr>
				                <td width="197">
				               	  <fieldset  style="padding:5px"><legend>Estructura</legend>
				                    	<table width="180" border="0" cellspacing="0" cellpadding="0">
				                          <tr>
				                            <td width="100"><fieldset><legend>Muro y Columas</legend><select id="cb_pisomuro" style="width:100%;padding:2px"></select></fieldset></td>
				                            <td width="10">&nbsp;</td>
				                            <td width="70"><fieldset><legend>Techo</legend><select id="cb_pisotecho" style="width:100%;padding:2px"></select></fieldset></td>
				                          </tr>
				                        </table>
				                  </fieldset>                </td>
				              <td width="400">
				               	<fieldset  style="padding:5px"><legend>Acabado</legend>
				                	<table width="380" border="0" cellspacing="0" cellpadding="0">
				                      <tr>
				                        <td width="70"><fieldset><legend>Pisos</legend><select id="cb_pisopisos" style="width:100%;padding:2px"></select></fieldset></td>
				                        <td width="10">&nbsp;</td>
				                        <td width="125"><fieldset><legend>Puertas y Ventanas</legend><select id="cb_pisopuertavetana" style="width:100%;padding:2px"></select></fieldset></td>
				                        <td width="10">&nbsp;</td>
				                        <td width="85"><fieldset><legend>Revestimiento</legend><select id="cb_pisorevestimiento" style="width:100%;padding:2px"></select></fieldset></td>
				                        <td width="10">&nbsp;</td>
				                        <td width="70"><fieldset><legend>Ba&ntilde;os</legend><select id="cb_pisobanio" style="width:100%;padding:2px"></select></fieldset></td>
				                      </tr>
				                    </table>
				                </fieldset>                </td>
				              <td width="158">
				               	<fieldset  style="padding:5px"><legend>Instalaciones</legend>
				                    <fieldset><legend>Electricas y Sanitarias</legend><select id="cb_pisoinstalaciones" style="width:100%;padding:2px"></select></fieldset>
				               	</fieldset>                </td>
				              </tr>
				            </table>
				        </fieldset>    </td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td colspan="8" height="8px"></td>
				    </tr>
				   <tr>
				    <td>&nbsp;</td>
				    <td colspan="6">
				    	<fieldset  style="padding:5px"><legend>Calculo</legend>
				        	<table width="748" border="0" cellspacing="0" cellpadding="0">
				              <tr>
				                <td width="200"><fieldset><legend>Valor de Construcci&oacute;n</legend><input id="txt_pisovalorconstruccion" style="width:100%" value="" /></fieldset></td>
				                <td width="548">&nbsp;</td>			                
				              </tr>
				            </table>
				        </fieldset>    </td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td colspan="8" height="8px"></td>
				    </tr>  
				  <tr>
				    <td>&nbsp;</td>
				    <td colspan="6">
				    	<fieldset  style="padding:5px"><legend>Datos de Igreso</legend>
				        <table width="740" border="0" cellspacing="0" cellpadding="0">
				  <tr>
				    <td width="100"><fieldset><legend>Ultimo Recalculo</legend><input id="txt_pisoultimorecalculo" style="width:100%" value="" /></fieldset></td>
				    <td width="15">&nbsp;</td>
				    <td width="140"><fieldset><legend>Tipo Documento</legend><select id="cb_pisotipodoc" style="width:100%;padding:2px"></select></fieldset></td>
				    <td width="10">&nbsp;</td>
				    <td width="180"><fieldset><legend>Nro Documento</legend><input id="txt_pisonrodoc" style="width:100%" value="" /></fieldset></td>
				    <td width="10">&nbsp;</td>
				    <td width="175"><fieldset><legend>Motivo</legend><select id="cb_pisomotivo" style="width:100%;padding:2px"></select></fieldset></td>
				    <td width="10">&nbsp;</td>
				    <td width="100"><fieldset><legend>Fecha de Doc.</legend><input id="txt_pisofechadoc" style="width:100%" value="" /></fieldset></td>
				  </tr>
				</table>
				        </fieldset>    </td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td>&nbsp;</td>
				    <td width="160">&nbsp;</td>
				    <td width="120">&nbsp;</td>
				    <td width="100">&nbsp;</td>
				    <td width="100">&nbsp;</td>
				    <td width="100">&nbsp;</td>
				    <td width="180">&nbsp;</td>
				    <td>&nbsp;</td>
				  </tr>
				</table>
				
				</div>			
		</div>
		<div id="predio_instalacion">
			
			<div align="center" style="overflow-y:scroll;height:350px;border:1px solid">
					<table width="800" border="0" cellspacing="0" cellpadding="0">
				  <tr>
				    <td colspan="8" height="8px"></td>
				    </tr>
				  <tr>
				    <td width="20">&nbsp;</td>
				    <td colspan="6">
				    
				    	<div style="border:1px solid;overflow-x:scroll;width:760px">
				                <table width="1310" border="1" cellspacing="0" cellpadding="0">
				                <thead class="ui-widget ui-widget-header ui-title1">
				                      <tr>				                        
				                        <th width="41" >Antig.</th>
				                        <th width="80" >Material</th>
				                        <th width="60" >Estado</th>
				                        <th width="150" >Descripcion</th>
				                        <th width="50" >Altura</th>
				                        <th width="50" >Ancho</th>
				                        <th width="50" >Largo</th>
				                        <th width="80" >Unid. Medida.</th>
				                        <th width="70" >Area. Contr.</th>
				                        <th width="85" >Val. Unit. m2</th>
				                        <th width="50" >% depr</th>
				                        <th width="50" >depr.</th>
				                        <th width="100" >Val. Unit. Deprec.</th>
				                        <th width="90" >Val. Area Const.</th>
				                        <th width="90" >% Area Com&uacute;n</th>
				                        <th width="95" >Val. Area Comun</th>
				                        <th width="80" >valor final</th>
				                  </tr>
				                  </thead>
				                      <tr>
				                        <td colspan="17" height="100px" valign="top" id="c_tablainstalacion">
				                            
				                                <table border="1" cellspacing="0" cellpadding="0">
				                                    <tr>
				                                      <td width="40" align="center">x</td>
				                                      <td width="79">x</td>
				                                      <td width="60">x</td>
				                                      <td width="150">x</td>
				                                      <td width="50" align="center">x</td>
				                                      <td width="50" align="center">x</td>
				                                      <td width="50" align="center">x</td>
				                                      <td width="80" align="center">x</td>
				                                      <td width="70" align="right">x</td>
				                                      <td width="85" align="right">x</td>
				                                      <td width="50" align="right">x</td>
				                                      <td width="50" align="right">x</td>
				                                      <td width="100" align="right">x</td>
				                                      <td width="90" align="right">x</td>
				                                      <td width="90" align="right">x</td>
				                                      <td width="95" align="right">x</td>
				                                      <td width="78" align="right">x</td>
				                                  </tr>
				                                  <tr>
				                                      <td width="40" align="center">x</td>
				                                      <td width="79">x</td>
				                                      <td width="60">x</td>
				                                      <td width="150">x</td>
				                                      <td width="50" align="center">x</td>
				                                      <td width="50" align="center">x</td>
				                                      <td width="50" align="center">x</td>
				                                      <td width="80" align="center">x</td>
				                                      <td width="70" align="right">x</td>
				                                      <td width="85" align="right">x</td>
				                                      <td width="50" align="right">x</td>
				                                      <td width="50" align="right">x</td>
				                                      <td width="100" align="right">x</td>
				                                      <td width="90" align="right">x</td>
				                                      <td width="90" align="right">x</td>
				                                      <td width="95" align="right">x</td>
				                                      <td width="78" align="right">x</td>
				                                  </tr>
				                                </table>
				                        </td>
				                      </tr>
				                      <tr>
				                        <td colspan="8">&nbsp;</td>
				                        <td align="right" id="c_total_area_cons_inst">total</td>
				                        <td colspan="4">&nbsp;</td>
				                        <td align="right" id="c_valor_area_cons_inst">total</td>
				                        <td colspan="3">&nbsp;</td>
				                      </tr>
				                    </table>
				    
				    </div>
				       
				    </td>
				    <td width="20">&nbsp;</td>
				  </tr>
				  <tr>
				    <td colspan="8" height="8px"></td>
				    </tr>
				  <tr>
				    <td>&nbsp;</td>
				    <td colspan="6">
				    	<fieldset  style="padding:5px"><legend>Datos de Instalaci&oacute;n</legend>
				        	<table width="748" border="0" cellspacing="0" cellpadding="0">
				              <tr>
				                <td width="59"><fieldset><legend>Valor</legend><input id="txt_nrovalorinstalacion" style="width:100%" value="" /></fieldset></td>
				                <td width="14">&nbsp;</td>
				                <td width="90"><fieldset><legend>Area Const.</legend><input id="txt_instalacionareaconst" style="width:100%" value="" /></fieldset></td>
				                <td width="15">&nbsp;</td>
				                <td width="70"><fieldset><legend>A&ntilde;o Const.</legend><input id="txt_instalacionanioconst" style="width:100%" value="" /></fieldset></td>
				                <td width="15">&nbsp;</td>
				                <td width="70"><fieldset><legend>Antig&uuml;edad</legend><input id="txt_instalacionantig" style="width:100%" value="" /></fieldset></td>
				                <td width="15">&nbsp;</td>
				                <td width="95"><fieldset><legend>% Area Com&uacute;n</legend><input id="txt_instalacionporcareacomun" style="width:100%" value="" /></fieldset></td>
				                <td width="15">&nbsp;</td>
				                <td width="141"><fieldset><legend>Material</legend><select id="cb_instalacionmaterial" style="width:100%;padding:2px"></select></fieldset></td>
				                <td width="15">&nbsp;</td>
				                <td width="134"><fieldset><legend>Estado</legend><select id="cb_instalacionestado" style="width:100%;padding:2px"></select></fieldset></td>
				              </tr>
				            </table>
				        </fieldset>    </td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td colspan="8" height="8px"></td>
				    </tr>
				    
				    <tr>
					    <td>&nbsp;</td>
					    <td colspan="6">
					    	<fieldset  style="padding:5px"><legend>Datos Dimensionales</legend>
					        <table width="740" border="0" cellspacing="0" cellpadding="0">
								  <tr>
								    <td width="100"><fieldset><legend>Alto</legend><input id="txt_instalacionalto" style="width:100%" value="" /></fieldset></td>
								    <td width="10">&nbsp;</td>
								    <td width="100"><fieldset><legend>Ancho</legend><input id="txt_instalacionancho" style="width:100%" value="" /></fieldset></td>
								    <td width="10">&nbsp;</td>
								    <td width="100"><fieldset><legend>Largo</legend><input id="txt_instalacionlargo" style="width:100%" value="" /></fieldset></td>
								    <td width="10">&nbsp;</td>
								    <td width="150"><fieldset><legend>Unid. Medida</legend><select id="cb_instalacionunidmedida" style="width:100%;padding:2px"></select></fieldset></td>
								    <td width="10">&nbsp;</td>
								    <td width="250"></td>
								  </tr>
								</table>
					        </fieldset>    </td>
					    <td>&nbsp;</td>
					  </tr>
				    
				     <tr>
				    <td colspan="8" height="8px"></td>
				    </tr>
				   <tr>
				    <td>&nbsp;</td>
				    <td colspan="6">
				    	<fieldset  style="padding:5px"><legend>Calculo</legend>
				        	<table width="748" border="0" cellspacing="0" cellpadding="0">
				              <tr>
				                <td width="200"><fieldset><legend>Valor de Instalaci&oacute;n</legend><input id="txt_instalacionvalor" style="width:100%" value="" /></fieldset></td>
				                <td width="548">&nbsp;</td>			                
				              </tr>
				            </table>
				        </fieldset>    </td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td colspan="8" height="8px"></td>
				    </tr>  
				  <tr>
				    <td>&nbsp;</td>
				    <td colspan="6">
				    	<fieldset  style="padding:5px"><legend>Datos de Igreso</legend>
				        <table width="740" border="0" cellspacing="0" cellpadding="0">
							  <tr>
							    <td width="100"><fieldset><legend>Ultimo Recalculo</legend><input id="txt_instalacionultimorecalculo" style="width:100%" value="" /></fieldset></td>
							    <td width="15">&nbsp;</td>
							    <td width="140"><fieldset><legend>Tipo Documento</legend><select id="cb_instalaciontipodoc" style="width:100%;padding:2px"></select></fieldset></td>
							    <td width="10">&nbsp;</td>
							    <td width="180"><fieldset><legend>Nro Documento</legend><input id="txt_instalacionnrodoc" style="width:100%" value="" /></fieldset></td>
							    <td width="10">&nbsp;</td>
							    <td width="175"><fieldset><legend>Motivo</legend><select id="cb_instalacionmotivo" style="width:100%;padding:2px"></select></fieldset></td>
							    <td width="10">&nbsp;</td>
							    <td width="100"><fieldset><legend>Fecha de Doc.</legend><input id="txt_instalacionfechadoc" style="width:100%" value="" /></fieldset></td>
							  </tr>
							</table>
				        </fieldset>    </td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td>&nbsp;</td>
				    <td width="160">&nbsp;</td>
				    <td width="120">&nbsp;</td>
				    <td width="100">&nbsp;</td>
				    <td width="100">&nbsp;</td>
				    <td width="100">&nbsp;</td>
				    <td width="180">&nbsp;</td>
				    <td>&nbsp;</td>
				  </tr>
				</table>
				
				</div>
		</div>
				
		</div>
	</div>
</div>

<!-- ---------------------------------------------------------------------------------------------------------------------------------  -->
