<br>
<div align="center" id="showing">
<table width="200" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="80"><b>Nro rec :</b></td>
    <td width="120" id="c_nrorec">&nbsp;</td>
  </tr>
  <tr>
    <td><b>Estado :</b></td>
    <td id="c_estado">&nbsp;</td>
  </tr>
  <tr>
    <td><b>Fecha Pag:</b></td>
    <td id="c_fecharec">&nbsp;</td>
  </tr>
  <tr>
    <td><b>Cajero:</b></td>
    <td id="c_cajero">&nbsp;</td>
  </tr>
  <tr>
    <td><b>Monto:</b></td>
    <td id="c_monto">&nbsp;</td>
  </tr>
  <tr>
   <td colspan="2" align="center">&nbsp;</td>
  </tr>
  <tr>
   <td colspan="2" align="center"><input type="button" id="btnimprimir" value="&nbsp;&nbsp;&nbsp;Imprimir&nbsp;&nbsp;&nbsp;"></td>
  </tr>
</table>
</div>