<div align="center" id="showing">
	<table width="668" border="0" cellspacing="0" cellpadding="0">
		  <tr>
		    <td colspan="4">&nbsp;</td>
		    </tr>
		  <tr>
		    <td width="70" height="51">&nbsp;</td>
		    <td colspan="2" align="center"><H2>Emisi&oacute;n de duplicados de recibos</H2></td>
		    <td width="70">&nbsp;</td>
		  </tr>
		  <tr>
		    <td colspan="4">&nbsp;</td>
		  </tr>
		  <tr>
		    <td colspan="4"><div id="div_errorduplicado"></div></td>
		  </tr>
		  <tr>
		    <td colspan="4">&nbsp;</td>
		  </tr>
		  <!-- 
		  <tr>
		    <td>&nbsp;</td>
		    <td width="126" align="right"><strong>Tipo de recibo:&nbsp;&nbsp;&nbsp;</strong></td>
		    <td width="402">
		    	<select id="cbtiporecibo" style="width:300px">
		        	<option value="1">Seleccionar...</option>
		        	<option value="1">Recibo por Pagos Diversos</option>
		            <option value="2">Recibo por Tributo</option>
		        </select>    </td>
		    <td>&nbsp;</td>
		  </tr>		  
		  <tr>
		    <td colspan="4">&nbsp;</td>
		    </tr>
		  -->  
		  <tr>
		    <td>&nbsp;</td>
		    <td align="right"><strong>Nro. de recibo:&nbsp;&nbsp;&nbsp;</strong></td>
		    <td><input id="txtrecibo" name="txtrecibo" size="44" maxlength="12" value=""/></td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td colspan="4">&nbsp;</td>
		    </tr>
		  <tr>
		    <td>&nbsp;</td>
		    <td colspan="2" align="center"><input type="button" name="btngenerar" id="btngenerar" value="&nbsp;&nbsp;&nbsp;&nbsp;Buscar Recibo&nbsp;&nbsp;&nbsp;&nbsp;" /></td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td colspan="4">&nbsp;</td>
		    </tr>
		    <tr>
		    <td colspan="4"><div id="div_datosrecibo"></div></td>
		    </tr>
		    <tr>
		    <td colspan="4">&nbsp;</td>
		    </tr>
		</table>
</div>