<html>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>Municipalidad Distrital de Comas</title>
<head>
<style type="text/css">
<!--
@media print {
	BODY {
		font-size: 14pt;
		font-family: Arial;
	}
}

@media screen {
	BODY {
		font-size: 12pt;
		font-family: Arial;
	}
}

@media screen , print {
	BODY {
		color: #000000;
	}
}

body {
	margin-left: 0px;
	margin-right: 0px;
}

.Estilo2 {
	font-size: 2px;
	font-weight: bold;
}

.Estilo4 {
	font-size: 14px;
	font-weight: bold;
}

.Estilo6 {
	font-size: 12px
}

.Estilo7 {
	font-size: 10px;
	font-weº ight: bold;
}

.Estilo8 {
	font-size: 10px
}

.MasGrande {
	font-size: 14px
}

body,td,th {
	font-family: Arial;
}
-->
</style>
<!-- 
<script language="javascript">
	window.print();
	window.close();
	</script>
 --> 

</head>
<body>
<table width="95%" border="0" cellspacing="0" cellpadding="0">
	<tr>
		<td height="24" colspan="6" class="Estilo6"><b> Municipalidad
		Distrital de Comas<br>
		Sub Gerencia de Tesoreria<br>
		RUC: 20168737565</b>
		<hr align="left" width="100%">
		</td>
	</tr>
	<tr>
		<td colspan="3" height="10"></td>
	</tr>
	<tr>
		<td colspan="3" class="Estilo6" align="center" id="duplicado"></td>
	</tr>
	<tr>
		<td colspan="3" height="10"></td>
	</tr>


	<tr>

		<td class="Estilo8" height="15">Recibo:</td>
		<td colspan="2" class="Estilo8" id="tdrecibo"></td>
	</tr>
	<tr>
		<td class="Estilo8" height="15">Codigo:</td>
		<td colspan="2" class="Estilo8" id="tdcodigo"></td>
	</tr>
	<tr>
		<td width="45" class="Estilo8" height="15">Nombre:</td>
		<td colspan="2" class="Estilo8" id="tdnombre"></td>
	</tr>
	<tr>
		<td colspan="2">&nbsp;</td>
	</tr>

	<tr>
		<td height="23" width="170" colspan="3" class="Estilo8" id="detalle"></td>
	</tr>

	<tr>
		<td class="Estilo6">&nbsp;</td>
		<td class="Estilo6" align="right">TOTAL</td>
		<td class="Estilo4" align="right" id="tdtotal"></td>
	</tr>
	<tr>
		<td></td>
		<td width="136"></td>
		<td align="right" height="10"></td>
	</tr>
	<tr>
		<td colspan="3" class="Estilo8" id="tdfecha"></td>
	</tr>
	<tr>
		<td colspan="3" class="Estilo8" align="left" id="tdcajer"></td>
	</tr>
	<tr>
		<td colspan="3" height="30">.</td>
	</tr>
</table>
</body>
</html>