<div id="busqpersona" align="center">
<br/>
<table style="width: 500px; height: 90px;" border="0" cellspacing="0" cellpadding="0">
	<tr>
		<td colspan="4" id="noregis"><b>No esta registrado(a):</b></td>
	</tr>
	<tr>
		<td style="width: 90px;text-align: center;" id="cidpers"></td>
		<td colspan="3" align="left">
			<div id="div_pers_no_reg" align="left"></div>
		</td>
	</tr>	
	<tr id="botones">
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td style="text-align: right;">
			<input type="button" id="genrecibo" name="genrecibo" value="Continuar Operaci&oacute;n"/>
			&nbsp;
			<input type="button" id="limpiar" name="limpiar" value="Nueva Busqueda"/>
		</td>
	</tr>
</table>
</div>
<div id="Pagination"></div><br>
<div id="Searchresult" style="width: 99%;" class="ui-widget-content ui-widget ui-corner-all"></div>
<form name="paginationoptions">
	<input type="hidden" value="12" name="items_per_page" id="items_per_page"/>
	<input type="hidden" value="5" name="num_display_entries" id="num_display_entries" class="numeric"/>
	<input type="hidden" value="1" name="num_edge_entries" id="num_edge_entries" class="numeric"/>
	<input type="hidden" value="Prev" name="prev_text" id="prev_text"/>
	<input type="hidden" value="Next" name="next_text" id="next_text"/>
</form>