<div id="showbp" class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
	<input type="hidden" name="urlredirect" id="urlredirect" />
	<input type="hidden" name="fech" id="fech" />
	<div class="ui-widget ui-state-default ui-corner-top ui-title">
		<label>Buscador de Contribuyentes</label>
	</div> 
	<div align="center" style="margin: 5px; height: 410px; overflow: auto;">
		<table border='0' width="99%" height="400px" border="0" cellpadding="0" cellspacing="0">
			<tr>
				<td width="130" height="37">Nivel de b&uacute;squeda:</td>
				<td width="180">
					<select id="cbonivelbusqpers" name="cbonivelbusqpers">
						<option value="0" selected>Por C&oacute;digo</option>
						<option value="1">Por Nombre y Apellido</option>
						<option value="2">Por Nro. DNI</option>
					</select>
				</td>
				<td width="340" align="center" valign="middle">
					<div id="div_nivelbusqpers" align="left"><input class="ui-text" type="text" id="txtcidper" name="txtcidper" value="" maxlength="10" size="30"></div>
				</td>
				<td align="right" valign="middle">
					<input type="button" id="Buscar" name="Buscar" value="Buscar">
					<input type="button" id="Nuevo" name="Nuevo" value="Nuevo">
				</td>
			</tr>
			<tr>
				<td colspan="4" align="center" valign="top">
					<div id="div_rsbusqpers" align="center"></div>
				</td>
			</tr>
		</table>
	</div>
</div>