<div align="center">				
    	<table width="539" height="268" border="0" cellpadding="0" cellspacing="0">
          <tr>
            <td height="54" colspan="9">&nbsp;</td>
            </tr>
          <tr>
            <td width="41" height="40">&nbsp;</td>
            <td colspan="7" align="center" valign="middle"><strong>Reporte Tesoreria</strong></td>
            <td width="16">&nbsp;</td>
          </tr>
           <tr>
            <td height="30" colspan="9">&nbsp;</td>
          </tr>
           <tr>
            <td height="30" colspan="9" align="center">
            	Tipo de Reporte: &nbsp;&nbsp;
            	<select id="tiporpt" style="width:350px">
            		<option value="0">Seleccionar...</option>
            		<option value="1">Reporte de Parte Diario</option>
            		<option value="2">Reporte de Tipo de Ingreso</option>
            	</select>
            </td>
          </tr>
          <tr>
            <td height="30" colspan="9">&nbsp;</td>
          </tr>
          <tr>
            <td height="19">&nbsp;</td>
            <td colspan="7">Seleccionar fecha de Inicio:</td>
            <td>&nbsp;</td>
          </tr>
          <tr>
            <td height="19">&nbsp;</td>
            <td width="112">&nbsp;</td>
            <td width="31">D&iacute;a: </td>
            <td width="65">
            	<select id="rptdia">
						            
  				</select>
   			</td>
            <td width="31">Mes:</td>
            <td width="65">
            	<select id="rptmes">
						            
  				 </select>
            </td>
            <td width="39">A&ntilde;o:</td>
            <td width="116">
            	<select id="rptanio">
							            
   				</select>
            </td>
            <td>&nbsp;</td>
          </tr>
          <tr>
            <td height="19" colspan="9">&nbsp;</td>
            </tr>
            
            <!--  -->
            
            <tr>
            <td height="19">&nbsp;</td>
            <td colspan="7">Seleccionar Fecha de Fin:</td>
            <td>&nbsp;</td>
          </tr>
          <tr>
            <td height="19">&nbsp;</td>
            <td width="112">&nbsp;</td>
            <td width="31">D&iacute;a: </td>
            <td width="65">
            	<select id="rptdiaf">
						            
  				</select>
   			</td>
            <td width="31">Mes:</td>
            <td width="65">
            	<select id="rptmesf">
						            
  				 </select>
            </td>
            <td width="39">A&ntilde;o:</td>
            <td width="116">
            	<select id="rptaniof">
							            
   				</select>
            </td>
            <td>&nbsp;</td>
          </tr>
          <tr>
            <td height="19" colspan="9">&nbsp;</td>
            </tr>
            
            
            <!--  -->
            
            <tr>
            <td height="19">&nbsp;</td>
            <td colspan="7">		                
                        C&oacute;digo cajero:
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <input type="text" id="txtcodcajero" name="txtcodcajero" value="" size="5" maxlength="4"/>
                        </td>
            <td>&nbsp;</td>
          </tr>
          <tr>
            <td height="19" colspan="9">&nbsp;</td>
          </tr>
          
          <tr>
            <td height="19">&nbsp;</td>
            <td colspan="7">		                
                        Forma de Pago:
                		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		                <select id="cbtipopago">
									            
		   				</select>
                        </td>
            <td>&nbsp;</td>
          </tr>
          <tr>
            <td height="19" colspan="9">&nbsp;</td>
          </tr>
            
          <tr>
            <td height="41">&nbsp;</td>
            <td colspan="7" align="center" valign="middle">
				<div id="div_rptapartediario"></div>
            	<input type="button" id="genrecibo" name="genrecibo" value="&nbsp;&nbsp;&nbsp;&nbsp;Generar reporte&nbsp;&nbsp;&nbsp;&nbsp;"/>
            </td>
            <td>&nbsp;</td>
          </tr>
          <tr>
            <td colspan="9">&nbsp;</td>
    	  </tr>
		</table>
    </div>