<div align="center" id="showsmppi">
<table width="690" border="0" cellspacing="0" cellpadding="0">
	<tr>
		<td colspan="10">&nbsp;</td>
	</tr>
	<tr>
		<td width="50">&nbsp;</td>
		<td colspan="8" align="center">
		<h2>Pagos diversos - SubModulo de Piscinas</h2>
		</td>
		<td width="57">&nbsp;</td>
	</tr>
	<tr>
		<td colspan="10" align="center">
		<div id="div_piscinarpta" align="center">&nbsp;</div>
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td colspan="2" align="right" valign="top">&nbsp;</td>
		<td colspan="5"><strong>Piscinas:</strong><br />
		<select size="3" id="cbconceptos" style="width: 340px">
		</select></td>
		<td width="65">&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td colspan="10">&nbsp;</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td width="62">&nbsp;</td>
		<td width="82">&nbsp;</td>
		<td colspan="4" align="center">
		<table width="336" border="1" cellspacing="0" cellpadding="0">
			<tr>
				<td width="332" align="center">
				<table width="301" border="0" cellspacing="0" cellpadding="0">
					<tr>
						<td colspan="4" height="10"></td>
					</tr>
					<tr>
						<td width="67">&nbsp;</td>
						<td width="69" align="center">Cantidad:</td>
						<td width="8">&nbsp;</td>
						<td width="146" align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tarifa:</td>
					</tr>
					<tr>
						<td width="67" align="right"><strong>Adultos:&nbsp;</strong></td>
						<td width="69" align="center"><input type="text" id="txtadulto"
							name="txtadulto" value="0" size="8"
							onkeypress="return validarnumeros(event)" /></td>
						<td width="8">&nbsp;</td>
						<td width="146" align="center"><input type="text"
							id="txtadultocosto" name="txtadultocosto" value="5" size="2"
							disabled="disabled" /> <strong>Nuevos Soles</strong></td>
					</tr>
					<tr>
						<td width="67">&nbsp;</td>
						<td width="69">&nbsp;</td>
						<td width="8">&nbsp;</td>
						<td width="146">&nbsp;</td>
					</tr>
					<tr>
						<td width="67" align="right"><strong>Ni&ntilde;os:&nbsp;</strong></td>
						<td width="69" align="center"><input type="text" id="txtninio"
							name="txtninio" value="0" size="8"
							onkeypress="return validarnumeros(event)" /></td>
						<td width="8">&nbsp;</td>
						<td width="146" align="center"><input type="text"
							id="txtniniocosto" name="txtniniocosto" value="2" size="2"
							disabled="disabled" /> <strong>Nuevos Soles</strong></td>
					</tr>
					<tr>
						<td colspan="4" height="10"></td>
					</tr>
				</table>
				</td>
			</tr>
		</table>
		</td>
		<td width="77">&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td colspan="10">&nbsp;</td>
	</tr>
	<tr>
		<td colspan="10">
		<div id="div_piscinaimpresion" align="center"></div>
		</td>
	</tr>
	<tr>
		<td colspan="10">&nbsp;</td>
	</tr>
	<tr>
		<td colspan="10" align="center"><input type="button" id="btncobrar"
			name="btncobrar"
			value="&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cobrar&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" />
		<input type="button" id="btnnuevo" name="btnnuevo"
			value="&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nuevo&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" />
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td width="67" align="right">&nbsp;</td>
		<td width="70" align="center">&nbsp;</td>
		<td width="8">&nbsp;</td>
		<td width="152" align="center">&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
</table>
</div>


