<div class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
	<div class="ui-widget ui-state-default ui-corner-top ui-title">
		<label>ARANCEL</label>
	</div>
	<br/>
	<table class="ui-tablecontent">
	<tr>
	<td>
	<br/><button id="btningresar" name="btningresar">Ingresar</button>
	</td>
	</tr>
	</table>
</div>


	<br/>
	<div id="busqresult">
	<div id="panelResult">
	
	</div>
	</div>
	

	<div id="manttarancel" class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
	<br/>
	<table class="ui-tablecontent"  border="0">
	<tr>	
		<td>A&ntilde;os:</td><td style="width: 250px"><select id="cboanios"></select></td>		
	</tr>
	<tr> 
	   <td>Via: </td> <td><input type="hidden" />   <input />&nbsp;<button id="btnbuscarvia">Buscar</button></td>	
	</tr>	
	<tr>
	  <td>Lado: </td><td><input /></td>
	</tr>
	<tr>
	  <td>Arancel: </td><td><input /></td>
	</tr>
	<tr>
	  <td>Cuadra: </td><td><input /></td>
	</tr>
	<tr>
	  <td>Cuadra Fin: </td><td><input /></td>
	</tr>
	<tr>
	  <td>Factor Barrido: </td><td><input /></td>
	</tr>
	<tr>	
	  <td>Centro Poblado.:</td><td><input type="hidden" />  <input /> &nbsp;<button id="btnbuscarcentrpoblado">Buscar</button></td>
	</tr>	
	</table>
</div>
