<div id="manttarancel" class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
	<br/>
	<table class="ui-tablecontent"  border="0">
	<tr>
	  <td><input id="idsigma" type="hidden"/> </td>
	</tr>
	
	<tr>	
		<td>A&ntilde;os:</td><td style="width: 250px"><select id="cboanios"></select></td>		
	</tr>
	<tr>	
	  <td>Centro Poblado.:</td><td><select id="cbocentrpob"> </select> </td>
	</tr>
	<tr> 
	   <td>Via: </td> <td><select id="cbovia"> </select> </td>	
	</tr>	
	<tr>
	  <td>Lado: </td><td><input id="txtnlado" /></td>
	</tr>
	<tr>
	  <td>Arancel: </td><td><input id="txtarancel" /></td>
	</tr>
	<tr>
	  <td>Cuadra: </td><td><input id="txtcuadraini"/></td>
	</tr>
	<tr>
	  <td>Cuadra Fin: </td><td><input id="txtcuadrafin" /></td>
	</tr>
	<tr>
	  <td>Factor Barrido: </td><td><input id="txtfacbarr"/></td>
	</tr>
	<tr>
	  <td>Estado: </td><td><select id= "cboestado"></select> </td>
	</tr>
	
		
	<tr>
			<td  colspan="2" align="center">
				<button id="btnguardar" >Guardar</button> &nbsp;
				<button id="btnregresar">Regresar</button> &nbsp;
			</td>
		</tr>
	</table>
</div>


<div id="busqvias">


</div>

