<div class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
	<div class="ui-widget ui-state-default ui-corner-top ui-title">
		<label>Arancel</label>
	</div>
	<br/>
	<table class="ui-tablecontent">
	<tr>
	 <td>	Buscar: <input id="txtbuscar"></input>	</td>
	<td><button id="btnbuscar" name="btnbuscar">Buscar</button> </td>
	</tr>
	<tr>
	<td>
	<br/><button id="btningresar" name="btningresar">Ingresar</button>
	</td>
	</tr>
	</table>
</div>


	<br/>
	<div style="width: 782px; padding: 1px;" class="ui-widget-content ui-widget ui-corner-all">
	<table align='center' style="width: 782px" id="tbl_capert" cellpadding='0' cellspacing='0'>
		<thead class="ui-widget ui-widget-header ui-title2">
		<tr>
			<th style="width: 100px">A&ntilde;o</th>
			<th  style="width: 100px">Via</th>	
			<th  style="width: 100px">Via Desde</th>
			<th  style="width: 100px">Via Hasta</th>
			<th style="width: 100px">Lado</th>
			<th style="width: 100px">Valor</th>	
			<th style="width: 100px">Cuadra</th>
			<th style="width: 100px">Cuadra Fin</th>
			<th style="width: 100px">Manzana</th>
			<th style="width: 100px">Manzana Fin</th>
			<th style="width: 100px">Centro Poblado</th>
			<th style="width: 100px">Sector</th>
			<th style="width: 16px">&nbsp;</th>
		</tr>
		</thead>
	</table>
	</div>
	

	<div id="manttarancel" class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
	<br/>
	<table class="ui-tablecontent" border="0">
	<tr>	
		<td>A&ntilde;os:</td><td style="width: 190px"><select id="cboanios"></select></td>		
	</tr>
	<tr> 
	   <td>Via: </td> <td><input type="hidden" />   <input />&nbsp;<button id="btnbuscarvia">Buscar</button></td>	
	</tr>	
	<tr>
	  <td>Via Desde:</td><td><input/></td>	
	</tr>
	<tr>
	  <td>Via Hasta:</td><td><input/></td>	
	</tr>		
	<tr>
	  <td>Lado: </td><td><input /></td>
	</tr>
	<tr>
	  <td>Valor: </td><td><input /></td>
	</tr>
	<tr>
	  <td>Cuadra: </td><td><input /></td>
	</tr>
	<tr>
	  <td>Cuadra Fin: </td><td><input /></td>
	</tr>
	<tr>
	  <td>Manzana: </td><td><input /></td>
	</tr>	
	<tr>
	  <td>Manzana Fin: </td><td><input /></td>
	</tr>		
	<tr>
	  <td>Centro Poblado.:</td><td><input type="hidden" />  <input /> &nbsp;<button id="btnbuscarcentrpoblado">Buscar</button></td>
	</tr>	
	<tr>
	 <td>Sector:</td><td><input /></td>
	</tr>	
	</table>
</div>

<div id="busqvias" class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
<div class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
   	<br/>
	<table class="ui-tablecontent" >
	<tr>
	<td colspan="2" align="center"> Vias </td>
	</tr>
	<tr>
	 <td>Buscar: <input id="txtbuscar"></input>	</td>
	<td><button id="btnbuscar" name="btnbuscar">Buscar</button> </td>
	</tr>	
	</table>	
</div>

<br/>
	<div style="width: 782px; padding: 1px;" class="ui-widget-content ui-widget ui-corner-all">
	<table align='center' style="width: 100%" id="tbl_capert" cellpadding='0' cellspacing='0'>
		<thead class="ui-widget ui-widget-header ui-title2">
		<tr>
			<th style="width: 50px">Codigo</th>
			<th  style="width: 400px">Via</th>		
			<th style="width: 16px">&nbsp;</th>
		</tr>
		</thead>
	</table>
</div>
</div>


<div id="busqcentrpobl" class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
<div class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
   	<br/>
	<table class="ui-tablecontent" >
	<tr>
	<td colspan="2" align="center"> Centro Poblado </td>
	</tr>
	<tr>
	 <td>Buscar: <input id="txtbuscar"></input>	</td>
	<td><button id="btnbuscar" name="btnbuscar">Buscar</button> </td>
	</tr>	
	</table>	
</div>
<br/>
	<div style="width: 782px; padding: 1px;" class="ui-widget-content ui-widget ui-corner-all">
	<table align='center' style="width: 100%" id="tbl_capert" cellpadding='0' cellspacing='0'>
		<thead class="ui-widget ui-widget-header ui-title2">
		<tr>
			<th style="width: 50px">Codigo</th>
			<th  style="width: 400px">Centro Poblado</th>		
			<th style="width: 16px">&nbsp;</th>
		</tr>
		</thead>
	</table>
</div>
</div>


	