<div class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
	<div class="ui-widget ui-state-default ui-corner-top ui-title">
		<label>CENTRO POBLADO</label>
	</div>
	<br/>
	<table class="ui-tablecontent" width="50%" border="0">
	<tr id="panelbusqueda">
	<td>Centro Poblado: &nbsp; <input class="ui-text" id="txtbusq" /> </td>
	</tr>
	<tr align="center">
	 	<td colspan="2"><button id="btnbuscar" name="btnbuscar">Buscar</button> 
	 	<button id="btnnuevo" name="btnnuevo">Nuevo</button>
	 	<button id="btnactualizar" name="btnactualizar">Actualizar</button>
	 	<button id="btneliminar" name="btneliminar">Eliminar</button></td>
	</tr>
	
	</table>


<div id="manttcentropoblad" class="ui-widget ui-widget-content ui-corner-all" style="width: 50%;margin: 3px;">
	<br/>
	<table class="ui-tablecontent" border="0" width="100%">
	<tr> 
	   <td>Codigo : </td> <td ><input id="txtcodcentropobl" ReadOnly></td>	
	</tr>
	
	<tr>	
		<td>Tipo:</td><td style="width: 190px"><select id="cbotipo"></select></td>		
	</tr>
	
	<tr> 
	   <td>Centro Poblado: </td> <td><input id="txtcentropobl" /></td>	
	</tr>
	
	<tr>
	  <td>Distrito:</td><td><input id="cboPostal"></td>
	
	</tr>		
	
	<tr>
	  <td>Desde: </td><td><input id="txtdesde" ReadOnly></td>
	</tr>	
	
	<tr>
	  <td>Hasta: </td><td><input id="txthasta" ReadOnly ></td>
	</tr>	
	
	<tr>
    <td align="center" colspan="2"><button id="btngrabar">Grabar</button><button id="btncancelar">Cancelar</button></td>
    </tr>
		
	</table>
</div>
	<br/>		
	<div id="busqresult">
	<div id="panelResult">
	
	</div>
	</div>
</div>
	
