<div class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
	<div class="ui-widget ui-state-default ui-corner-top ui-title">
		<label>Contenedor</label>
	</div>
	<br/>
	<table class="ui-tablecontent">
	<tr>
	 <td>	Buscar: <input id="txtbuscar"></input>	</td>
	<td><button id="btnbuscar" name="btnbuscar">Buscar</button> </td>
	</tr>
	<tr>
	<td>
	<br/><button id="btningresar" name="btningresar">Ingresar</button>
	</td>
	</tr>
	</table>
</div>
	<br/>
	<div  style="width: 782px; padding: 1px;" class="ui-widget-content ui-widget ui-corner-all">
	<table align='center' style="width: 782px" id="tbl_capert" cellpadding='0' cellspacing='0'>
		<thead class="ui-widget ui-widget-header ui-title2">
		<tr>
			<th style="width: 190px">Cod.Grupo</th>
			<th style="width: 190px">Grupo</th>
			<th style="width: 100px">Cod.Tipo</th>
			<th style="width: 100px">Descripcion</th>
			<th style="width: 130px">Estado</th>
			<th style="width: 16px">&nbsp;</th>
		</tr>
		</thead>
	</table>
	</div>
	
	
	
	<div id="divmantcontenedor" class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
	<br/>
	<table class="ui-tablecontent" border="0">
	<tr>
	
		<td>Grupo:</td><td style="width: 190px"><select id="cbogrupo"></select></td>
		
	</tr>
	<tr> 
	   <td>Descripcion: </td> <td><input id="txtdescripcion"></td>
	
	</tr>	
	<tr>
	 <td>Estado:</td><td><select id="cboestado"><option>ACTIVO</option><option>DESACTIVADO</option> </select> </td>
	</tr>			

	
	</table>
</div>
	