<div class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
	<div class="ui-widget ui-state-default ui-corner-top ui-title">
		<label>DEPRECIACION</label>
	</div>
	<br/>
	<table class="ui-tablecontent">
	<tr>
	 <td>	Buscar: <input id="txtbuscar"></input>	</td>
	<td><button id="btnbuscar" name="btnbuscar">Buscar</button> </td>
	</tr>
	<tr>
	<td>
	<br/><button id="btningresar" name="btningresar">Ingresar</button>
	</td>
	</tr>
	</table>
</div>


	<br/>
	<div style="width: 782px; padding: 1px;" class="ui-widget-content ui-widget ui-corner-all">
	<table align='center' style="width: 782px" id="tbl_capert" cellpadding='0' cellspacing='0'>
		<thead class="ui-widget ui-widget-header ui-title2">
		<tr>
			<th rowspan="2" style="width: 100px">A&ntilde;o</th>
			<th rowspan="2" style="width: 100px">Clasificacion</th>	
			<th rowspan="2" style="width: 100px">Material</th>
			<th rowspan="2" style="width: 100px">Antiguedad</th>
			<th colspan="4" style="width: 100px">Estado Conservacion</th>	
			<th style="width: 16px">&nbsp;</th>
		</tr>
		<tr>	
			<th style="width: 100px">Muy Bueno%</th>
			<th style="width: 100px">Bueno%</th>
			<th style="width: 100px">Malo %</th>
			<th style="width: 100px">Muy Malo %</th>			
			<th style="width: 16px">&nbsp;</th>
		
		</tr>
		</thead>
	</table>
	</div>
	

	<div id="manttdepreciacion" class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
	<br/>
	<table class="ui-tablecontent" border="0">
	<tr>
	
		<td>A&ntilde;os:</td><td style="width: 190px"><select id="cboanios"></select></td>
		
	</tr>
	<tr> 
	   <td>Clasificacion : </td> <td><select id="cboclasificacion"></select></td>
	
	</tr>
	
	<tr>
	  <td>Material:</td><td><select id="cbomaterial"> </select></td>
	
	</tr>		
	
	<tr>
	  <td>Antiguedad: </td><td><select id="cboantiguedad"> </select></td>
	</tr>
	<tr>
	 <td colspan="2">Estado de Conservacion(%)</td>
	</tr>
	<tr>
	 <td>Muy Bueno:</td><td><select id="cbomuybueno"> </select></td>
	</tr>
	<tr>
	 <td>Bueno:</td><td><select id="cbobueno"></select> </td>
	</tr>
		<tr>
	 <td>Malo:</td><td><select id="cbomalo"></select> </td>
	</tr>
		<tr>
	 <td>Muy Malo:</td><td><select id="cbomuymalo"></select> </td>
	</tr>

	
	</table>
</div>
	