<br/>
<table class="ui-tablecontent" border="0" width="100%">
    <tr> 
        <td>Codigo : </td> <td ><input id="txtcodcentropobl" ReadOnly  value="<?php echo $this->ccodcen; ?>"></td>	
    </tr>

    <tr>

        <td>Tipo:</td><td style="width: 190px"><select id="cbotipo"><option value="<?php echo $this->ctipcen; ?>"></option></select></td>

    </tr>
    <tr> 
        <td>Centro Poblado: </td> <td><input id="txtcentropobl" value="<?php echo $this->vnombre; ?>"/></td>	
    </tr>

    <tr>
        <td>Distrito:</td><td><input id="cboPostal" value="<?php echo $this->cdistri; ?>"></td>

    </tr>		

    <tr>
        <td>Cod. Zona : </td><td><input id="nrozona" value="<?php echo $this->cidzona; ?>"></td>
    </tr>

    <tr>
        <td>Desde: </td><td><input id="txtdesde" value="<?php echo $this->dfecdes; ?>"></td>
    </tr>	

    <tr>
        <td>Hasta: </td><td><input id="txthasta" value="<?php echo $this->dfechas; ?>"></td>
    </tr>	
</table>