<div id="panelbusqueda" align="center" class="ui-widget ui-widget-content ui-corner-all "  style="width: 1000px;margin: 3px;">
    <div class="ui-widget ui-state-default ui-corner-top ui-title">
        <label>Cajas</label>
    </div>
    <table border="0" width="800px">
		<tr>
            <td width="50px">Nro Caja</td>
            <td colspan="3">
           		 <input type="text" id="txtnrocaja" class="ui-text" style="text-align: right;width: 100px;	"/>
            </td>
            <td rowspan="2" align="center">
            	<button id="btnbuscar">Buscar</button>
            </td>
        </tr>
        <tr>
            <td width="50px">Local</td>
            <td>
           		 <select id="cbolocal" style="width: 200px;"></select>
            </td>
            <td width="50px">Estado</td>
            <td>
           		 <select id="cboestado" style="width: 150px;"></select>
            </td>
        </tr>
    </table>
</div>
<div id="panelResultmcaja">
	<table id="tblResultmcaja"></table>
	<div id="ptblResultmcaja"></div>
</div>
<div id="dvjson"></div>
<!-- --------------------------------------------------------------------------------------------------------------------	 -->