<div align="center" class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
	<div class="ui-widget ui-state-default ui-corner-top ui-title">
		<label>Mantenimiento de Tablas Generales</label>
	</div>
	<table style="width: 100%; height: 492px; padding-bottom: 2px;" border="0" cellpadding="0" cellspacing="0">
		<tr>
			<td rowspan='2' style="width: 300px">
				<div id="tree-mconten" align="left" style="overflow:scroll; height: 492px; width:300px; border:1px solid #c3daf9;"></div>
			</td>
			<td style="vertical-align: top;"><div id="cont_form"></div></td>
		</tr>
		<tr>
			<td style="height: 35px;text-align: right;">
				<button id="btnnuevonodo">Nuevo Nodo</button>
				<button id="btnaniadirnodo">A&ntilde;adir Nodo Hijo</button>
				<button id="btnguardarmcontennodo">Guardar</button>
			</td>
		</tr>
	</table>
</div>