	<div class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
	<div class="ui-widget ui-state-default ui-corner-top ui-title">
		<label>Parametros de Recaudaci&oacute;n</label>
	</div>
	<br/>
	<table class="ui-tablecontent">
	
	</table>

	
	
		<table border="0">
		  
		<tr>
		<td><b>Seleccion el monto minimo de la Cuota Inicial:</b></td>
		</tr>
		
		<tr> 
			<td> <input name="option" type="radio" id="opcion1">Sin monto minimo de cuota inicial</td>
		</tr>
		
		<tr> 
		<td> <input name="option" type="radio" id="opcion2">Con monto minimo de cuota inicial para todos los Contribuyentes</td>
		</tr>
		<tr>
			<td>  Porcentaje del Importe Fraccionado(%):</td>
			<td> <input id="txtporimpofracct"  >	</td>
		</tr>
		
		<tr>
			<td>	  Monto Determinado(S/.):	</td>
			<td>	 <input id="txtmontdetert" >	</td>
		</tr>
		
		<tr> 
		<td> <input name="option" type="radio" id="opcion3" >Con monto minimo de cuota inicial de acuerdo al tipo de Contribuyente</td>
		</tr>
		<tr>
		<td><b>-Personas Jur&iacute;dica: </b></td>
		</tr>
		<tr>
			<td>  Porcentaje del Importe Fraccionado(%):</td>
			<td>  <input id="txtporimpofracctipjur"  ></td>
		</tr>
		<tr>
			<td>	  Monto Determinado(S/.):	</td>
			<td>	 <input id="txtmontdeterttipjur" >	</td>
		</tr>
		<tr>
		<td><b>-Resto de Contribuyentes: </b></td>
		</tr>
		<tr>
			<td>  Porcentaje del Importe Fraccionado(%):</td>
			<td>  <input id="txtporimpofracctipnorm"  ></td>
		</tr>
		<tr>
			<td>	  Monto Determinado(S/.):	</td>
			<td>	 <input id="txtmontdeterttipnorm" >	</td>
		</tr>
		</table>
	
	 
<br/>
<b>Ingrese la Ordenanza que aprueba los Montos Minimos de Cuota Inicial.</b>
<br/>


		<table border="0">		  
		<tr>
		<td>Codigo Documento:</td>
		<td>Numero Documento:</td>
		<td>Fecha:</td>
		</tr>	
		<tr>
		<td><select id="cbocoddoc"> </select></td>
		<td><input id="txtnrodoc" /></td>
		<td><input id="txtfechdoc"></td>
		</tr>	
		<tr>
		<td colspan="3">Datos acerca de la &uacute;ltima modificacion de los parametros. </td>		
		</tr>
		<tr>
		<td>Usuario:&nbsp;<input id="txtusuario" ReadOnly/> </td><td>Fecha:<input id="txtfechmod"></td>		
		</tr>
		
		</table>


</div>








