
<input type="hidden" id="txtidsigma4"/>
	<div class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">

	<br/>
	<table class="ui-tablecontent">
	
	</table>

	
	
		<table border="0">
		<tr>
			<td colspan="2"><b><u>Ingrese el N&uacute;mero de cuotas atrasadas necesarias para considerar un Convenio <br/> de Fraccionamiento con Casualidad de Perdida:</u></b>
			</td>
		</tr>			
		
		<tr>
			<td colspan="2"><br/>
			</td>
		</tr>
			
		<tr>
			<td>	  Cuotas Atrasadas:	</td>
			<td>	 <input id="txtmontdetert4" >	</td>
		</tr>
		
		<tr>
			<td colspan="2"><br/>
			</td>
		</tr>
		
		<tr>
			<td colspan="2"><b>NOTA: El n&uacute;mero de cuotas atrasadas para considerar un convenio con causal </br>
			                   de perdida, no tomar&acute; en cuenta los casos de Convenios de Fraccionamiento </br>
			                   donde solo se tiene atrasada la ultima cuota.      
			                </b>                                    
			</td>
		</tr>
		
		
		
		</table>
	
	 
<br/>
<b>Ingrese la Ordenanza que aprueba los Montos Minimos de Cuota.</b>
<br/>


		<table border="0">		  
		<tr>
		<td>Codigo Documento:</td>
		<td>Numero Documento:</td>
		<td>Fecha:</td>
		</tr>	
		<tr>
		<td><select id="cbocoddoc4"> </select></td>
		<td><input id="txtnrodoc4" /></td>
		<td><input id="txtfechdoc4"></td>
		</tr>	

		<tr>
			<td colspan="4" align="center">
			<button id="btngrabar4">Grabar</button>
			</td>
		</tr>
		
		</table>


</div>


<span id="locategrid4" class="visibility:false;"></span>







