
<input type="hidden" id="txtidsigma3"/>
	<div class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">

	<br/>
	<table class="ui-tablecontent">
	
	</table>
		
		<table border="0">
		  
		<tr>
		<td><b>Seleccion la Cantidad Maxima de Cuotas :</b></td>
		</tr>
		
		<tr> 
			<td> <input name="option3" type="radio" id="opcion31">Sin Cantidad Maxima de Cuotas </td>
		</tr>
		
		<tr> 
		<td> <input name="option3" type="radio" id="opcion32">Con Cantidad Maxima de Cuotas  para todos los Contribuyentes</td>
		</tr>
	
		
		<tr>
			<td>	  Cantidad Maxima de Cuotas:	</td>
			<td>	 <input id="txtmontdetert3" >	</td>
		</tr>
		
		</table>
	
	 
<br/>
<b>Ingrese la Ordenanza que aprueba la Cantidad Maxima de Cuotas.</b>
<br/>


		<table border="0">		  
		<tr>
		<td>Codigo Documento:</td>
		<td>Numero Documento:</td>
		<td>Fecha:</td>
		</tr>	
		<tr>
		<td><select id="cbocoddoc3"> </select></td>
		<td><input id="txtnrodoc3" /></td>
		<td><input id="txtfechdoc3"></td>
		</tr>	

		<tr>
			<td colspan="4" align="center">
			<button id="btngrabar3">Grabar</button>
			</td>
		</tr>
		
		</table>


</div>


<span id="locategrid3" class="visibility:false;"></span>



