
<input type="hidden" id="txtidsigma2"/>
	<div class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">

	<br/>
	<table class="ui-tablecontent">
	
	</table>

	
	
		<table border="0">
		  
		<tr>
		<td><b>Seleccion el monto minimo de la Cuota :</b></td>
		</tr>
		
		<tr> 
			<td> <input name="option2" type="radio" id="opcion21">Sin monto minimo de cuota </td>
		</tr>
		
		<tr> 
		<td> <input name="option2" type="radio" id="opcion22">Con monto minimo  para todos los Contribuyentes</td>
		</tr>
	
		
		<tr>
			<td>	  Monto Determinado(S/.):	</td>
			<td>	 <input id="txtmontdetert2" >	</td>
		</tr>
		
		</table>
	
	 
<br/>
<b>Ingrese la Ordenanza que aprueba los Montos Minimos de Cuota.</b>
<br/>


		<table border="0">		  
		<tr>
		<td>Codigo Documento:</td>
		<td>Numero Documento:</td>
		<td>Fecha:</td>
		</tr>	
		<tr>
		<td><select id="cbocoddoc2"> </select></td>
		<td><input id="txtnrodoc2" /></td>
		<td><input id="txtfechdoc2"></td>
		</tr>	

		<tr>
			<td colspan="4" align="center">
			<button id="btngrabar2">Grabar</button>
			</td>
		</tr>
		
		</table>


</div>


<span id="locategrid2" class="visibility:false;"></span>







