<div id="tabs">
    <ul>
        <li><a href="paramfracc"> Monto minimo de la Cuota Inicial:</a></li>
       <li><a href="paramfracmontomin">Monto Minimo Cuota</a></li>
        <li><a href="paramfracuotas">Numero Maximo Cuotas</a></li>
        <li><a href="paramfracuotasatrasadas">Numero Cuotas Atrasadas</a></li>
    </ul>
    <div id="tabs-1">
  
    </div>
    <div id="tabs-2">
    </div>
    <div id="tabs-3">
    </div>
     <div id="tabs-4">
    </div>
</div>