<!-- 

<div class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
	<div class="ui-widget ui-state-default ui-corner-top ui-title">
		<label>PERSONAS</label>
	</div>
	<br/>
	<table border="0" class="ui-tablecontent">
	<tr>
	<td >Tipo Ingreso&nbsp;<select id="cbotipingreso"><option>Administrado</option><option>Contribuyente</option></select></td>
	<td>Codigo&nbsp;<input ReadOnly id="txtcodigo"/></td>
	</tr>
	<tr>
	<td colspan="2" >
	<fieldset> <legend>Identificacion del Contribuyente</legend> 
	<table>
	<tr><td>Tipo Documento</td><td>Nro. Documento</td><td>Tipo de Persona</td>
	</tr>
	<tr>
	<td><select id="cbotipdoc" ><option>DNI</option></select></td><td><input/></td><td><select id="cbotipper"><option>PERSONA NATURAL</option></select></td>
	</tr>
	<tr>
	<td colspan="2">Apellido Paterno</td><td>Apellido Materno</td>
	</tr>
	<tr>
	<td colspan="2"><input style="width:250"/></td><td><input style="width:250"/></td>
	</tr>
	<tr>
	<td colspan="2" >Nombres</td><td>F.Nacimiento</td>
	</tr>
	<tr>
	<td  colspan="2"><input style="width:250" /></td><td><input></td>
	</tr>
	<tr>
	<td>Nro.Telefono</td><td>Nro.Fax</td><td>Correo Electronico</td>
	</tr>
	<tr>
	<td><input></td><td><input></td><td><input></td>
	</tr>
	</table>	
	</fieldset>	
	</td>
	</tr>
	<tr>
	<td colspan="2">
		<fieldset> <legend>Direcci&oacute;n Fiscal</legend> 
	<table border="0">
	<tr>
	<td>Codigo Postal </td><td>Cod.Via</td><td colspan="2">Av., Jr. , Psje., Calle, etc.</td>
	</tr>
	<tr>
	<td><select id="cbocodpostal" ><option>Puente Piedra</option></select></td><td><input style="width:50;"/></td><td colspan="2"><input style="width:50;"/>&nbsp;<input></td>
	</tr>
	<tr>
	<td colspan="5"><div>
	    <table>
	       <tr>	
	        <td >Urbanizacion, Asentamiento Humano, etc.</td><td>Nro.</td><td>Dpto.</td><td >Interior</td>
	       </tr>
			<tr>
			<td><input style="width:50;">&nbsp;<input></td><td><input style="width:50;"></td><td><input style="width:50;"></td><td><input style="width:50;">&nbsp;<input style="width:50;" ></td>
			</tr>
		 </table></div>
		 </td>
	</tr>

	<tr>
	<td colspan="5">
	<div>
	    <table>
	       <tr>	<td>Block.</td><td>Mz.</td><td>Lote</td><td>Referencia</td>
			</tr>
			<tr>
			<td><input style="width:50;"></td><td><input style="width:50;"></td><td><input style="width:50;"></td><td><input style="width:250;"></td>
			</tr>
	</table>
	</div>
	</td>
	</tr>
	
	</table>
	</fieldset>
	</td>
	</tr>
	<tr>
	 <td  align="center"">
	    <button id="btnbuscar" name="btnbuscar">Buscar</button> &nbsp;	
        <button id="btnnuevo" name="btnnuevo">Nuevo</button> &nbsp;
        <button id="btneditar" name="btneditar">Editar</button>
      </td>
        
	</tr>
	</table>
</div>
 -->
<div id="panelPersons">
	<div align="center" class="ui-widget ui-widget-content ui-corner-all"
		style="width: 99%; margin: 3px;">
		<div class="ui-widget ui-state-default ui-corner-top ui-title">
			<label>Personas</label>
		</div>
		<table class="ui-panelLayout-main" border="0" cellpadding="0"
			cellspacing="0">
			<tr>
				<td style="vertical-align: top;">
					<table style="width: 100%;" class="ui-table-body" border="0">
						<tr>
							<td width="20">&nbsp;</td>
							<td width="100">C&oacute;digo:</td>
							<td width="10">&nbsp;</td>
							<td width="100">Nro DNI</td>
							<td width="10">&nbsp;</td>
							<td width="180"></td>
							<td width="10"></td>
							<td rowspan="3" valign="middle" align="center">
								<button id="btnbuscar" name="btnbuscar">Buscar</button>
							</td>
						</tr>
						<tr id="only">
							<td width="20">&nbsp;</td>
							<td width="100"><input class="ui-text" id="id_person"
								maxlength="10" style="width: 50%" /></td>
							<td width="10">&nbsp;</td>
							<td width="100"><input class="ui-text" id="nrodni"
								maxlength="8" style="width: 50%" /></td>
							<td width="10">&nbsp;</td>
							<td width="180"></td>
							<td width="10"></td>
						</tr>
						<tr>
							<td width="20">&nbsp;</td>
							<td width="180">Nombre:</td>
							<td width="10">&nbsp;</td>
							<td width="180">Apellido Paterno:</td>
							<td width="10">&nbsp;</td>
							<td width="180">Apellido Materno:</td>
							<td width="20">&nbsp;</td>
						</tr>
						<tr id="common">
							<td width="20">&nbsp;</td>
							<td width="180"><input class="ui-text" id="ds_nombre"
								style="width: 80%" /></td>
							<td width="10">&nbsp;</td>
							<td width="180"><input class="ui-text" id="ds_apepat"
								style="width: 80%" /></td>
							<td width="10">&nbsp;</td>
							<td width="180"><input class="ui-text" id="ds_apemat"
								style="width: 80%" /></td>
							<td width="20">&nbsp;</td>
							<td rowspan="2" valign="middle" align="center">
								<button id="btninsert" name="btninsert">Nuevo</button>
							</td>
						</tr>
						<tr>
							<td colspan="7" height="8px"></td>
						</tr>
						<tr>
							<td colspan="8" align="center"><br />
								<div id="panelResultpersons">
									<table id="tblResultpersons"></table>
									<div id="ptblResultpersons"></div>
								</div>
							</td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
	</div>
</div>
