<div id="panelbusqueda" align="center" class="ui-widget ui-widget-content ui-corner-all "  style="width: 1000px;margin: 3px;">
    <div class="ui-widget ui-state-default ui-corner-top ui-title">
        <label>Registro de Reajuste</label>
    </div>
    <table border="0" class="ui-table-panelLayout">
			<tr>
            <td align="right">periodo</td>
            <td style="width: 90px;" align="right"><div class="ui-widget"><?php echo $this->util()->getPeriodos(); ?></div></td>
        </tr>
    </table>
</div>
<div id="panelResultreajust">
	<table id="tblResultreajust"></table>
	<div id="ptbreajustsultuit"></div>
</div>
<!-- --------------------------------------------------------------------------------------------------------------------	 -->