<div class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
	<div class="ui-widget ui-state-default ui-corner-top ui-title">
		<label>UIT</label>
	</div>
	<br/>
	<table class="ui-tablecontent">
	<tr>
	 <td>	Buscar: <input id="txtbuscar"></input>	</td>
	<td><button id="btnbuscar" name="btnbuscar">Buscar</button> </td>
	</tr>
	<tr>
	<td>
	<br/><button id="btningresar" name="btningresar">Ingresar</button>
	</td>
	</tr>
	</table>
</div>


	<br/>
	<div style="width: 782px; padding: 1px;" class="ui-widget-content ui-widget ui-corner-all">
	<table align='center' style="width: 782px" id="tbl_capert" cellpadding='0' cellspacing='0'>
		<thead class="ui-widget ui-widget-header ui-title2">
		<tr>
			<th style="width: 190px">A&ntilde;o</th>
			<th style="width: 100px">Valor</th>	
			<th style="width: 16px">&nbsp;</th>
		</tr>
		</thead>
	</table>
	</div>

<div id="divmanttuit" >	
	<br/>
	<table class="ui-tablecontent" border="0">
	<tr>
	
		<td>A&ntilde;os:</td><td style="width: 190px"><select id="cboanios"></select></td>
		
	</tr>
	<tr> 
	   <td>Valor : </td> <td><input id="txtvalor"/></td>
	
	</tr>	
	
	</table>
</div>