<div class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
	<div class="ui-widget ui-state-default ui-corner-top ui-title">
		<label>VALORES UNITARIOS</label>
	</div>
	<br/>
	<table class="ui-tablecontent">
	<tr>
	 <td>	Buscar: <input id="txtbuscar"></input>	</td>
	<td><button id="btnbuscar" name="btnbuscar">Buscar</button> </td>
	</tr>
	<tr>
	<td>
	<br/><button id="btningresar" name="btningresar">Ingresar</button>
	</td>
	</tr>
	</table>
</div>


	<br/>
	<div style="width: 782px; padding: 1px;" class="ui-widget-content ui-widget ui-corner-all">
	<table align='center' style="width: 782px" id="tbl_capert" cellpadding='0' cellspacing='0'>
		<thead class="ui-widget ui-widget-header ui-title2">
		<tr>
			<th rowspan="2" style="width: 100px">A&ntilde;o</th>
			<th rowspan="2" style="width: 100px">Indice</th>
			<th colspan="2" style="width: 100px">Estructuras</th>	
			<th colspan="4" style="width: 100px">Acabados</th>
			<th rowspan="2" style="width: 100px">Instalaciones Electricas y Sanitarias</th>
			<th rowspan="2" style="width: 16px">&nbsp;</th>
		</tr>
		<tr>	
			<th style="width: 100px">Muros y Columnas</th>
			<th style="width: 100px">Techos </th>
			<th style="width: 100px">Pisos</th>
			<th style="width: 100px">Puertas y Ventanas</th>	
			<th style="width: 100px">Revestimientos</th>	
			<th style="width: 100px">Ba&ntilde;os</th>				
		</tr>
		</thead>
	</table>
	</div>
	

	<div id="manttvaloresunitarios" class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
	<br/>
	<table class="ui-tablecontent" border="0">
	<tr>
	
		<td>A&ntilde;os:</td><td style="width: 190px"><select id="cboanios"></select></td>
		
	</tr>
	<tr> 
	   <td>Indice : </td> <td><select id="cboindice"></select></td>
	
	</tr>
	
	<tr>
	  <td>Muros y Columnas:</td><td><input  id="txtmurcol" /> </td>
	
	</tr>		
	
	<tr>
	  <td>Techos: </td><td><input id="txttechos"></td>
	</tr>
	<tr>
	 <td>Pisos</td><td><input id="txtpisos" ></td>
	</tr>
	<tr>
	 <td>Puertas y Ventanas:</td><td><input id="txtpuertasventanas" > </td>
	</tr>
	<tr>
	 <td>Revestimientos:</td><td><input id="txtrevestimiento" />  </td>
	</tr>
	<tr>
	 <td>Ba&ntilde;os:</td><td><input id="txtbanios"/> </td>
	</tr>
    <tr>
	 <td>Instalaciones Electricas y Sanitarias:</td><td><input id="txtinstelecsan"/> </td>
	</tr>
	
	</table>
</div>
	