<div class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
	<div class="ui-widget ui-state-default ui-corner-top ui-title">
		<label>VIAS</label>
	</div>
	<br/>
	<table class="ui-tablecontent">
	<tr>
	 <td>	Buscar: <input id="txtbuscar"></input>	</td>
	<td><button id="btnbuscar" name="btnbuscar">Buscar</button> </td>
	</tr>
	<tr>
	<td>
	<br/><button id="btningresar" name="btningresar">Ingresar</button>
	</td>
	</tr>
	</table>
</div>


	<br/>
	<div style="width: 782px; padding: 1px;" class="ui-widget-content ui-widget ui-corner-all">
	<table align='center' style="width: 782px" id="tbl_capert" cellpadding='0' cellspacing='0'>
		<thead class="ui-widget ui-widget-header ui-title2">
		<tr>
			<th style="width: 100px">Tipo</th>
			<th  style="width: 100px">Via</th>	
			<th  style="width: 100px">Cod.Postal</th>
			<th style="width: 100px">Zona</th>
			<th style="width: 100px">Centro Poblado</th>
			<th style="width: 100px">Codigo Nro. Zona</th>
			<th style="width: 100px">Centro Nro. Zona Catastral</th>	
			<th style="width: 16px">&nbsp;</th>
		</tr>
		</thead>
	</table>
	</div>
	

	<div id="manttvias" class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
	<br/>
	<table class="ui-tablecontent" border="0">
	<tr>
	
		<td>Tipo:</td><td style="width: 190px"><select id="cbotipo"></select></td>
		
	</tr>
	<tr> 
	   <td>Via: </td> <td><input />&nbsp;<button id="btnbuscarvia">Buscar</button></td>	
	</tr>
	
	<tr>
	  <td>Postal:</td><td><input id="cboPostal"></td>
	
	</tr>		
	
	<tr>
	  <td>Zona: </td><td><input id="cbozona"></td>
	</tr>
	
	<tr>
	  <td>Centro Poblado: </td><td><input id="cbocentrpobl">&nbsp;<button id="btnbuscarcentpobl">Buscar</button></td>
	</tr>
	
	<tr>
	  <td>Nro. Zona: </td><td><input id="nrozona"></td>
	</tr>
	
	<tr>
	  <td>Nro. Zona Catastral: </td><td><input id="nrozonacatastral"></td>
	</tr>	

	</table>
</div>

<div id="busqvias" class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
<div class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
   	<br/>
	<table class="ui-tablecontent" >
	<tr>
	<td colspan="2" align="center"> Vias </td>
	</tr>
	<tr>
	 <td>Buscar: <input id="txtbuscar"></input>	</td>
	<td><button id="btnbuscar" name="btnbuscar">Buscar</button> </td>
	</tr>	
	</table>	
</div>

<br/>
	<div style="width: 782px; padding: 1px;" class="ui-widget-content ui-widget ui-corner-all">
	<table align='center' style="width: 100%" id="tbl_capert" cellpadding='0' cellspacing='0'>
		<thead class="ui-widget ui-widget-header ui-title2">
		<tr>
			<th style="width: 50px">Codigo</th>
			<th  style="width: 400px">Via</th>		
			<th style="width: 16px">&nbsp;</th>
		</tr>
		</thead>
	</table>
</div>
</div>


<div id="busqcentrpobl" class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
<div class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
   	<br/>
	<table class="ui-tablecontent" >
	<tr>
	<td colspan="2" align="center"> Centro Poblado </td>
	</tr>
	<tr>
	 <td>Buscar: <input id="txtbuscar"></input>	</td>
	<td><button id="btnbuscar" name="btnbuscar">Buscar</button> </td>
	</tr>	
	</table>	
</div>
<br/>
	<div style="width: 782px; padding: 1px;" class="ui-widget-content ui-widget ui-corner-all">
	<table align='center' style="width: 100%" id="tbl_capert" cellpadding='0' cellspacing='0'>
		<thead class="ui-widget ui-widget-header ui-title2">
		<tr>
			<th style="width: 50px">Codigo</th>
			<th  style="width: 400px">Centro Poblado</th>		
			<th style="width: 16px">&nbsp;</th>
		</tr>
		</thead>
	</table>
</div>
</div>