<div class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
	<div class="ui-widget ui-state-default ui-corner-top ui-title">
		<label>VIAS</label>
	</div>
	<br/>
	<table class="ui-tablecontent" width="50%" border="0">
	<tr id="panelbusqueda">
	<td>Via: &nbsp;<input class="ui-text"  id="txtbusq" /> 
	&nbsp; <button id="btnbuscar" name="btnbuscar">Buscar</button> 	</td> 
	</tr>
	
	</table>
	</div>

<div id="manttvias" class="ui-widget ui-widget-content ui-corner-all" style="width: 50%;margin: 3px;">
	<br/>
	<table class="ui-tablecontent" border="0" width="100%">
	<tr> 
	   <td>Codigo : </td> <td ><input id="txtcodvia" ReadOnly></td>	
	</tr>	
	<tr>	
		<td>Tipo:</td><td style="width: 190px"><select id="cbotipo"></select></td>		
	</tr>
	<tr>
		<td>Via:</td><td style="width: 190px"><input id="txtvia" /></td>		
	</tr>
	<tr>
	  <td>Desde: </td><td><input id="txtdesde" ReadOnly></td>
	</tr>		
	<tr>
	  <td>Hasta: </td><td><input id="txthasta" ReadOnly ></td>
	</tr>	
	
	<tr>	
    <td  colspan="2" align="center"><button id="btngrabar">Grabar</button><button id="btncancelar">Cancelar</button></td>
    </tr>
	
	</table>
</div>


	<br/>
	
	    
   
	<div id="busqresult">
	<div id="panelResult">
	
	</div>
	</div>


	
	
	
