<div class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
	<div class="ui-widget ui-state-default ui-corner-top ui-title">
		<label>VIAS</label>
	</div>
	<br/>
	<table class="ui-tablecontent">
	<tr>
	 	<td><button id="btnbuscar" name="btnbuscar" title="Buscar" >Buscar</button> </td>
	 	<td><button id="btnnuevo" name="btnnuevo">Nuevo</button></td>
	 	<td><button id="btnactualizar" name="btnactualizar">Actualizar</button></td>
	 	<td><button id="btneliminar" name="btneliminar">Eliminar</button></td>
	</tr>
	
	</table>
</div>

<div id="manttvias" class="ui-widget ui-widget-content ui-corner-all" style="width: 50%;margin: 3px;">
	<br/>
	<table class="ui-tablecontent" border="0" width="100%">
	<tr> 
	   <td>Codigo : </td> <td ><input id="txtcodvia" ReadOnly></td>	
	</tr>	
	<tr>	
		<td>Tipo:</td><td style="width: 190px"><select id="cbotipo"></select></td>		
	</tr>
	<tr>
		<td>Via:</td><td style="width: 190px"><input id="txtvia" /></td>		
	</tr>
	<tr>
	  <td>Desde: </td><td><input id="txtdesde" ReadOnly></td>
	</tr>		
	<tr>
	  <td>Hasta: </td><td><input id="txthasta" ReadOnly ></td>
	</tr>	
	</table>
</div>


	<br/>
	
	    
    <table id="acciones" width="50%">
    <tr>
    <td align="center"><button id="btngrabar">Grabar</button><button id="btncancelar">Cancelar</button></td>
    </tr>
	</table>
	
	<div id="busqresult">
	<table id="tblResult"></table>
	<div id="panelResult">
	
	</div>
	</div>
	
	
	
