<center>

	<table border="0" class="ui-widget ui-widget-content ui-corner-top" >
	<tr>
	<td width=250px>Descripci&oacute;n</td>
	<td width=50px>Predio</td>
	<td width=50px>Periodo</td>
	<td width=50px>A&ntilde;o</td>
	<td width=50px>Insoluto</td>
	<td width=50px>Gastos</td>
	<td width=100px>Nro.Valor</td>
	<td width=100px>Exp.Coactivo</td>
	<td width=50px>Estado</td>
	<td width=50px><input type='checkbox' /></td>
	</tr>
	
		<tr>
	<td width=250px>Impuesto Predial</td>
	<td width=50px>&nbsp; </td>
	<td width=50px>01</td>
	<td width=50px>2013</td>
	<td width=50px>1000</td>
	<td width=50px>0</td>
	<td width=100px></td>
	<td width=100px>0</td>
	<td width=50px>Deuda</td>
	<td width=50px><input type='checkbox' /></td>
	</tr>
	
	</table>
	

<br/>

<table align="left">
<tr><td>Nro.Cuotas</td><td><input id="txtnrocuotas" value="10"/></td> </tr>
<tr><td>%Cuota Inicial</td><td><input id="txtporcuotas" value=0 /></td> </tr>
<tr><td>Cuota Inicial</td><td><input id="txtcuotainicial" value=0 /></td> </tr>
</table>

<br/>

<div id="locategridresultestctacte"></div>

</center>




