<table width="100%" border="0" >
<tr>
	<td>Persona: </td>
	<td><input id="txt_persona"  /> </td>
	<td align="center"><button>Buscar </button> </td>
</tr>
<tr>
	<td>Tipo:</td>
	<td><select id="tipopers" style="width:250" <?php echo $this->util()->getComboContenedor('1000000450', $this->mpredio["cusoesp"]); ?> >  </select>  </td> 
</tr>
<tr>
	<td colspan="3" align="center" ><button id="btnguardar">Guardar</button>
	 &nbsp; <button id="btnregresar">Regresar</button></td>
</tr>


</table>

<script type="text/javascript">
   /* $(function(){

    	openDialogData2("registro/busqprediocontr", {}, "300", "150", "Persona", function() {
   
    	});

	});*/

</script>