<input type="hidden"  id="txtMperson"> 
<div id="panelbusqueda" align="center" class="ui-widget ui-widget-content ui-corner-all "  style="width: 100%;margin: 3px;">
    <div class="ui-widget ui-state-default ui-corner-top ui-title">
        <label>Predios</label>
    </div>
    <div id="dvbusqueda">
    <table border="0" width="100%">
          <tr>
              <td colspan="15" align="center">

          </tr>
          <tr>
                            <td>&nbsp;</td>
                            <td>C&oacute;digo Predial:</td>
                            <td></td>
                            <td>Centro Poblado:</td>
                            <td>&nbsp;</td>
                            <td>Via:</td>
                            <td>&nbsp;</td>
                            <td width="50">Nro:</td>
                            <td width="10">&nbsp;</td>
                            <td width="50">Mza:</td>
                            <td width="10">&nbsp;</td>
                            <td width="50">Lote:</td>
                            <td>&nbsp;</td>
                              <td rowspan="2" align="center">
                            <button id="btnbuscar">Buscar</button>              
                            </td>
            </tr>
            <tr id="panelBusqPredio">
                            <td>&nbsp;</td>
                            <td><input class="ui-text" id="c_predial" maxlength="10" style="width:90px" /></td>
                            <td></td>
                            <td colspan="3"><input class="ui-text pnl" id="c_viacontrib" style="width:100%" /></td>
                            <td>&nbsp;</td>
                            <td width="50"><input class="ui-text pnl" id="c_nroviacontrib" style="width:100%" /></td>
                            <td width="10">&nbsp;</td>
                            <td width="50"><input class="ui-text pnl" id="c_mzacontrib" style="width:100%" /></td>
                            <td width="10">&nbsp;</td>
                            <td width="50"><input class="ui-text pnl" id="c_lotecontrib" style="width:100%" /></td>
                            <td>&nbsp;</td>
                            
             </tr>
		
    </table>
    </div>
    <div id="dvaccion"></div>
</div>
<div id="panelResultmBusqPredio">
	<table id="tblResultmBusqPredio"></table>
	<div id="ptblResultmBusqPredio"></div>
</div>

<script type="text/javascript">
    $(function(){
        
verPredio = function(rowid, iRow, iCol, e) {
	if(rowid != undefined && rowid != null && rowid !== false ) {
		row = $("#tblResultmBusqPredio").jqGrid('getRowData', rowid);
	} else {
		row = undefined;
	}
	  	if(row != undefined) {

    		row2 = {
    				idsigma: row.idsigma,
    				vdirpre: row.vdirpre
    		};


    		parameters = {
                	mperson: $("#txtMperson").val(),
                	mhresum: "-1",
                	idsigma: row.idsigma,
                	vdirpre: row.vdirpre	
                };

    		closeDialog("jqDialog2");
    		//closeDialog("jqDialog1");

    		openDialogData1("registro/declaracion", parameters, "850", "600", "Declaraci&oacute;n Jurada");

    		
    		
    		/*_post = $.post(path + "registro/pintarpredio", row2);
    	    _post.success(function(data){
    	    	
				$("#panelResultmBusqPredio").html(data);
				
        	 });*/
    		    
   }  else {
	   $("#txt_idsigma").val('-1');  
	   
   		} 
	  	
	  	//closeDialog("jqDialog1");
	  	
//});

};

bindkeysmpredio = {"onEnter": verPredio};

buscarmpredio = function() {
	/*if(_periodo == undefined || _periodo == null) {
		 $("#txtPeriodo").val('');
		 _periodo ='%'
    }else{
    	
    }*/
    parameters = {
        "name": "tblResultmBusqPredio",
        "procedure": "registro.mostrarpredios",
        "parameters": '{' +
        '"p_cperiod":"01"' +
        '}'
    };
    
    proceso = function(requestData){
        $("#panelResultmBusqPredio").html(requestData);
        records = $("#ctblResultmBusqpredio").val();

       // alert(records);
       //if(records > 1) {
            actualizarGrid("tblResultmBusqPredio", optionmpredio, bindkeysmpredio,navPanelPredio);
       //}
    };
    
    procesarConsultaSubProceso('registrar', parameters, proceso);        
 
};
 
optionmpredio= {
    height: 250,
    width: 550,
    editurl: "mcajerosave",
    colNames: [              
			   "C\u00F3digo",
			   "C\u00F3digo de la via",
			   "Numero",
			   "Interior",
			   "Letra",
			   "Departamento", 
			   "Estacionamiento", 
			   "Deposito",
			   "Referencia",
			   "Manzana",
			   "Lote",
			   "C\u00F3digo Catastral",
			   "Ubicacion en el plano",
			   "Tipo de Mercado",
			   "Nro de puesto dentro del mercado",
			   "Distrito Catastral",
			   "Zona Catastral",
			   "Manzana Catastral",
			   "Sector Catastral",
			   "Lote Catastral",
			   "Unidad Catastral",
			   "Bloque",
			   "Seccion",
			   "Unidad",
			   "C\u00F3digo Centro Poblado",
			   "Direccion del Predio",
			   "Estado",
			   "Codigo de Predio Mostrar",
			   "Tipo de Predio",
			   "Anexo",
			   "C\u00F3digounico castastral new",
			   "Estacion",
			   "Usuario",
			   "Fecha de Registro",
			   "Latitud del predio",
			   "Longitud del predio",
			   "Zoom del mapa"
               ],
    colModel: [
        {name:'idsigma', index:'idsigma', width:80,editable: true, align: 'center', frozen: true,editoptions:{readonly:true,size:10}},
        {name:'mviadis', index:'mviadis', width:90,editable: true, align: 'center',hidden:true},
        {name:'dnumero', index:'dnumero', width:90,editable: true },
        {name:'dinteri', index:'dinteri', width:90,editable: true },
        {name:'dletras', index:'dletras', width:90,editable: true, align: 'left'},
        
        {name:'ddepart', index:'ddepart', width:90,editable: true },
        {name:'destaci', index:'destaci', width:90,editable: true, align: 'center'},
        {name:'ddeposi', index:'ddeposi', width:80,editable: true, align: 'center'},
        {name:'drefere', index:'drefere', width:90,editable: true, align: 'left'},
        
        {name:'dmanzan', index:'dmanzan', width:90,editable: true, align: 'center'},
        {name:'dnlotes', index:'dnlotes', width:90,editable: true, align: 'center'},
        {name:'ccatast', index:'ccatast', width:90,editable: true, align: 'center'},
        
        
        {name:'cplanos', index:'cplanos', width:90,editable: true,align:"center",hidden:true},
        {name:'ctipmer', index:'ctipmer', width:90,editable: true,align:"right",hidden:true},
        {name:'dnummer', index:'dnummer', width:90 },
        {name:'cdiscat', index:'cdiscat', width:90 },
        {name:'czoncat', index:'czoncat', width:90 },
         {name:'cmzacat', index:'cmzacat', width:90 },
          {name:'cseccat', index:'cseccat', width:90 },  
          {name:'cltecat', index:'cltecat', width:90 },
         {name:'cundcat', index:'cundcat', width:90 }, 
         {name:'dbloque', index:'dbloque', width:90 },  
         {name:'dseccio', index:'dseccio', width:90 },  
         {name:'dunidad', index:'dunidad', width:90 },  
		 {name:'mpoblad', index:'mpoblad', width:90,hidden:true},  
		 {name:'vdirpre', index:'vdirpre', width:90 },  
		 {name:'nestado', index:'nestado', width:90,hidden:true ,edittype:"checkbox",editoptions:{value:"1:0",defaultValue:"1"},formatter:'checkbox' },  
		 {name:'ccodpre', index:'ccodpre', width:90,hidden:true},  
		 {name:'ctippre', index:'ctippre', width:90,hidden:true},  
		 {name:'idanexo', index:'idanexo', width:90,hidden:true},  
		 {name:'ccodcuc', index:'ccodcuc', width:90,hidden:true},  
		 {name:'vhostnm', index:'vhostnm', width:90,hidden:true},  
		 {name:'vusernm', index:'vusernm', width:90,hidden:true},  
		 {name:'ddatetm', index:'ddatetm', width:90,hidden:true ,formatter:'date',formatoptions: { newformat: 'd-m-Y'}},  
		 {name:'nlatitu', index:'nlatitu', width:90,hidden:true},  
		 {name:'nlongit', index:'nlongit', width:90,hidden:true},  
		 {name:'nzoom', index:'nzoom', width:90,hidden:true}         
        ],
    caption: "&nbsp;&nbsp;&nbsp;Resultados de la busqueda",
    ondblClickRow: verPredio
    	

};

	


 navPanelPredio = function() {
        $("#tblResultmBusqPredio").jqGrid('navGrid', '#ptblResultmBusqPredio', {edit:false, add:false, del:false, search:false, refresh:false});

    };

    inicializarGrid("tblResultmBusqPredio", optionmpredio,null,navPanelPredio);


$(function(){


    buscarmpredio();

    themeTextBox();
    themeComboBox();
    
});
    });
   
</script>

<!-- --------------------------------------------------------------------------------------------------------------------	 -->