<input type="hidden"  id="txtMperson"> 
<div id="panelbusqueda" align="center" class="ui-widget ui-widget-content ui-corner-all "  style="width: 100%;margin: 3px;">
    <div class="ui-widget ui-state-default ui-corner-top ui-title">
        <label>Predios</label>
    </div>
    <div id="dvbusqueda">
    <table border="0" width="100%">
          <tr>
              <td colspan="15" align="center">

          </tr>
          <tr>
                            <td>&nbsp;</td>
                            <td>C&oacute;digo Predial:</td>
                            <td></td>
                            <td>Centro Poblado:</td>
                            <td>&nbsp;</td>
                            <td>Via:</td>
                            <td>&nbsp;</td>
                            <td width="50">Nro:</td>
                            <td width="10">&nbsp;</td>
                            <td width="50">Mza:</td>
                            <td width="10">&nbsp;</td>
                            <td width="50">Lote:</td>
                            <td>&nbsp;</td>
                              <td rowspan="2" align="center">
                            <button id="btnbuscar">Buscar</button>              
                            </td>
            </tr>
            <tr id="panelBusqPredio">
                            <td>&nbsp;</td>
                            <td><input class="ui-text" id="c_predial" maxlength="10" style="width:90px" /></td>
                            <td></td>
                            <td colspan="3"><input class="ui-text pnl" id="c_viacontrib" style="width:100%" /></td>
                            <td>&nbsp;</td>
                            <td width="50"><input class="ui-text pnl" id="c_nroviacontrib" style="width:100%" /></td>
                            <td width="10">&nbsp;</td>
                            <td width="50"><input class="ui-text pnl" id="c_mzacontrib" style="width:100%" /></td>
                            <td width="10">&nbsp;</td>
                            <td width="50"><input class="ui-text pnl" id="c_lotecontrib" style="width:100%" /></td>
                            <td>&nbsp;</td>
                            
             </tr>
		
    </table>
    </div>
    <div id="dvaccion"></div>
</div>
<div id="panelResultmBusqPredio">
	<table id="tblResultmBusqPredio"></table>
	<div id="ptblResultmBusqPredio"></div>
</div>

<script type="text/javascript">
    $(function(){
        
verPredio = function(rowid, iRow, iCol, e) {
	if(rowid != undefined && rowid != null && rowid !== false ) {
		row = $("#tblResultmBusqPredio").jqGrid('getRowData', rowid);
	} else {
		row = undefined;
	}
	  	if(row != undefined) {

    	/*	row2 = {
    				idsigma: row.idsigma,
    				vdirpre: row.tnumero
    		};
		*/

    		parameters = {
                	mperson: $("#txtMperson").val(),
                	mhresum: "-1",
                	idsigma: row.idsigma,
                	vdirpre: row.tnumero,
                	fechvig: $("#dtpFechaVigencia").val(),
                	nrodecla: $("#txtNroDeclaracion").val(),
                	fechdecl: $("#dtpFechaDeclaracion").val(),
                	motivo:	  $("#cboMotivo").val(),
                	observa:  $("#txtObservacion").text()		
                };

    		closeDialog("jqDialog2");

        	openDialogData1("registro/declaracion", parameters, "850", "600", "Declaraci&oacute;n Jurada");
    	    		    
   }  else {
	   $("#txt_idsigma").val('-1');  
	   
   		} 
   		
};

bindkeysmpredio = {"onEnter": verPredio};


optionmpredio = {
    height: 250,
    width: 550,
    editurl: "mcajerosave",
    colNames: [              
			   "C\u00F3digo",
			   "Codigo de Predio Mostrar",
			   "Direccion del Predio",
			   "C\u00F3digo Centro Poblado",
			   "Centro Poblado",
			   "C\u00F3digo de la via",
			   "Via",
			   "Numero",
			   "Departamento", 
			   "Manzana",
			   "Lote"
               ],
    colModel: [
        {name:'idsigma', index:'idsigma', width:80,editable: true, align: 'center',editoptions:{readonly:true,size:10}},
        {name:'ccodpre', index:'ccodpre', width:90,hidden:true},  
      	 {name:'tnumero', index:'tnumero', width:200 },  
		 {name:'mpoblad', index:'mpoblad', width:90,hidden:true},
		 {name:'tnompoblad', index:'tnompoblad', width:90,hidden:true},  
		 {name:'mviadis', index:'mviadis', width:90,hidden:true},  
		 {name:'tnomvia', index:'tnomvia', width:90,hidden:true},  
		 {name:'dnumero', index:'dnumero', width:90,hidden:true},
		 {name:'ddepart', index:'ddepart', width:90,editable: true },
	     {name:'dmanzan', index:'dmanzan', width:90,editable: true, align: 'center'},
	     {name:'dnlotes', index:'dnlotes', width:90,editable: true, align: 'center'}        
        ],
    caption: "&nbsp;&nbsp;&nbsp;Resultados de la busqueda",
    ondblClickRow: verPredio
    	

};

	
 navPanelPredio = function() {
        $("#tblResultmBusqPredio").jqGrid('navGrid', '#ptblResultmBusqPredio', {edit:false, add:false, del:false, search:false, refresh:false});
    };




    buscarmpredio2 = function() {
    	/*if(_periodo == undefined || _periodo == null) {
    		 $("#txtPeriodo").val('');
    		 _periodo ='%'
        }else{
        	
        }*/

    	c_predial= $("#c_predial");
    	
    	viacontrib=$("#c_viacontrib");
    	
    	nroviacontrib=$("#c_nroviacontrib");
    	
    	mzacontrib=$("#c_mzacontrib");
    	
    	lotecontrib=$("#c_lotecontrib");
    	

    	  if(trim(c_predial.val()).length > 0){
    		  c_predial.val(LPad(c_predial.val(), 10, '0'));
    	    }
        
        parameters = {
            "name": "tblResultmBusqPredio",
            "procedure": "pl_function.buscar_mpredio",
            "print": "true",
            "parameters": '{' +
            '"p_ccodpre":"'+ c_predial.val().toUpperCase() +'",' +
            //'"p_ccodpre":"'+ "0000000327" +'",' +
            '"p_ccodvia":"'+ viacontrib.val().toUpperCase() + '",' +
            '"p_cnrovia":"'+ nroviacontrib.val().toUpperCase() + '",' +
            '"p_cmanzan":"'+ mzacontrib.val().toUpperCase() + '",' +
            '"p_cnrlote":"'+ lotecontrib.val().toUpperCase() + '"' +
            '}' 
        };

        console.log(parameters);
        
        proceso = function(requestData){
            $("#panelResultmBusqPredio").html(requestData);

            console.log(requestData);
            
            records = $("#ctblResultmBusqpredio").val();

           // alert(records);
           //if(records > 1) {
           //actualizarGrid("tblResultmBusqPredio", optionmpredio, bindkeysmpredio);
           // inicializarGrid("tblResultmBusqPredio", optionmpredio);
           //}
	    	procesarJSON("panelResultmBusqPredio", "tblResultmBusqPredio", optionmpredio, null, navPanelPredio);
              
          
        };

    	 //procesarConsultaSubProceso('registrar', parameters, proceso);
    };    
  

buscarmpredio = function() {
	/*if(_periodo == undefined || _periodo == null) {
		 $("#txtPeriodo").val('');
		 _periodo ='%'
    }else{
    	
    }*/

	c_predial= $("#c_predial");
	
	viacontrib=$("#c_viacontrib");
	
	nroviacontrib=$("#c_nroviacontrib");
	
	mzacontrib=$("#c_mzacontrib");
	
	lotecontrib=$("#c_lotecontrib");
	

	  if(trim(c_predial.val()).length > 0){
		  c_predial.val(LPad(c_predial.val(), 10, '0'));
	    }
    
   /* parameters = {
        "name": "tblResultmBusqPredio",
        "procedure": "pl_function.buscar_mpredio",
        "print": "true",
        "parameters": '{' +
        //'"p_ccodpre":"'+ c_predial.val().toUpperCase() +'",' +
        '"p_ccodpre":"'+ "0000000327" +'",' +
        '"p_ccodvia":"'+ viacontrib.val().toUpperCase() + '",' +
        '"p_cnrovia":"'+ nroviacontrib.val().toUpperCase() + '",' +
        '"p_cmanzan":"'+ mzacontrib.val().toUpperCase() + '",' +
        '"p_cnrlote":"'+ lotecontrib.val().toUpperCase() + '"' +
        '}' 
    };

    console.log(parameters);
    
    proceso = function(requestData){
        $("#panelResultmBusqPredio").html(requestData);

        console.log(requestData);
        
        records = $("#ctblResultmBusqpredio").val();

       // alert(records);
       //if(records > 1) {
       actualizarGrid("tblResultmBusqPredio", optionmpredio, bindkeysmpredio);
       // inicializarGrid("tblResultmBusqPredio", optionmpredio);
       //}

      
    };
	    procesarConsultaSubProceso('registrar', parameters, proceso);        
	  
	    */ 

	    parameters = {
	            "name": "tblResultmBusqPredio",
	            "procedure": "registro.mostrarpredios",
	            "parameters": '{' +
	            '"p_cperiod":"01"' +
	            '}'
	        };
	        
	        proceso = function(requestData){
	            $("#panelResultmBusqPredio").html(requestData);
	            records = $("#ctblResultmBusqpredio").val();

	           // alert(records);
	           //if(records > 1) {
	                actualizarGrid("tblResultmBusqPredio", optionmpredio, bindkeysmpredio,navPanelPredio);

	                //optionmpredio = $.extend(optionmpredio, {data: data.data});
        	    	//procesarJSON("panelResultmBusqPredio", "tblResultmBusqPredio", optionmpredio, null, navPanelPredio);
	                
	           //}
	        };
	        
	        procesarConsultaSubProceso('registrar', parameters, proceso);   
    

};
 


$(function(){


    buscarmpredio();

	$("#btnbuscar").click(function(){
		buscarmpredio2();
	});

	//inicializarGrid("tblResultmBusqPredio", optionmpredio);

    themeTextBox();
    themeComboBox();
    
});
    });
   
</script>

<!-- --------------------------------------------------------------------------------------------------------------------	 -->