<script type="text/javascript" src="<?php echo $this->util()->getPath(); ?>js/registro/declaracion.js"></script>
<input type="hidden" id="hdnIdDeclaracion" value="<?php echo $this->mhresum; ?>"/>
<input type="hidden" id="hdnIdPersona" value="<?php echo $this->mperson; ?>"/>
<input type="hidden" id="hdnAnioTermino" value="<?php echo $this->cperiod; ?>"/>

<table class="ui-table-panelLayout" style="width: 100%">
    <tr>
		<td style="width: 130px;">
			<table>
				<tr>
					<td>Nro. :</td>
					<td><div style="font-size: 14px;font-weight: bold;" id="txtNroDeclaracion"></div></td>
				</tr>
			</table>
		</td>
        <td>
        	La modificaci&oacute;n de esta declaraci&oacute;n entra en vigencia a partir del a&ntilde;o:
        	<input class="ui-text" style="width: 80px; text-align: left;" id="dtpFechaVigencia"/>
        </td>
    </tr>
    <tr>
        <td colspan="2">
        	<hr/>
        </td>
    </tr>
    <tr>
	    <td>
	    	<table style="width: 100%;">
				<tr>
					<td style="text-align: right">Fecha:</td>
					<td>
						<input class="ui-text" style="width: 80px; text-align: center;" id="dtpFechaDeclaracion"/>
					</td>
				</tr>
				<tr>
					<td style="text-align: right">Motivo:</td>
					<td id="cellMotivo">
						<select style="width: 240px;" id="cboMotivo">
							<?php echo $this->util()->getComboContenedorOtro('1000000004', null,'public.obtener_tabla_otro'); ?>
						</select>
					</td>
				</tr>
				<tr>
					<td style="text-align: right;vertical-align: top;">Observaci&oacute;n:</td>
				</tr>
				<tr>
					<td colspan="2">
						<textarea class="ui-text" class="jquery_ckeditor" cols="80" id="txtObservacion" name="txtObservacion" rows="10">
						</textarea>
					</td>
				</tr>
			</table>
		</td>
		<td style="width: 100%; vertical-align: top;">
			<table style="width: 100%;">
				<tr>
					<td>				    
						<div id="panelResultmPredio">
							<!-- 
							<button id="btnAgreParti">Agregar</button>						
							<table id="tblResultmPredio" border="1">
							<tr>
								<td>Codigo</td>
								<td>Nombre</td>
								<td>Tipo Propietario</td>  
							</tr>
							<tr>
							<tr>
								<td><?php echo $this->mperson; ?></td>
<td><?php echo $this->dperson; ?></td>
<td ><input type="hidden" id="txt_tipprop1" /> </td>
							</tr>
							</table>
							<div id="ptblResultmPredio"></div>
							 -->
						</div>
			   		</td>	
				</tr>
			</table>      
		</td>
    </tr>
	<tr>
		<td colspan="2" style="text-align: right;">
			<button id="btnAceptarDeclaracion">Aceptar</button>
			<button id="btnCancelarDeclaracion">Cancelar</button>
		</td>
	</tr>
</table>
<script type="text/javascript">
    $(function(){

     $("#txtNroDeclaracion").html("0000000000");
        
        var config = {
            skin:'v2'
            , toolbar: [
                ['Bold','Italic','Underline','-','NumberedList','BulletedList','-','Outdent','Indent','-','Undo','Redo','-','HorizontalRule','-','Blockquote','CreateDiv','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock','-','TextColor','BGColor'],
                ['UIColor']
            ]
        };
        
        var hEd = CKEDITOR.instances['txtObservacion'];
        if (hEd) {
            CKEDITOR.remove(hEd);
        }
        // CKEDITOR.replace('txtObservacion', config);
        
        $("#dtpFechaDeclaracion, #dtpFechaVigencia").datepicker({
            dateFormat: "dd/mm/yy",
            showOn: "button",
            buttonImage: pathImage + "calendar.gif",
            buttonImageOnly: true
        });
        
        themeComboBox("#cellMotivo select");

		$("#btnAgreParti").click(function(){
			openDialog2("registro/busqprediocontr",  "300", "150", "Persona");     
		}); 
    

        
        
        $("#btnAceptarDeclaracion").button({
            icons: {primary:'ui-icon-check'}
        }).bind("click", function(){
            mhresum = {
	        	idsigma: $("#hdnIdDeclaracion").val(),
	        	ctipdat: "1000000002", /* Registro Tributario */
	        	vnrodoc: 0,  //$("#hdnId").val(),
	        	dfecdoc: $("#dtpFechaDeclaracion").val(),
	        	cmotivo: $("#cboMotivo").val(), 
	        	dataidsigma: $("#cboMotivo option:selected").attr("data-idsigma"),  
	        	ctipdoc: "1000000021", /* Declaracion Jurada */ 
	        	vnrodjj: $("#txtNroDeclaracion").text(),
	        	vobserv: $("#txtObservacion").val(),
	        	nestado: "1",
	        	cperini: $("#dtpFechaVigencia").val(),
	        	cperfin: $("#hdnAnioTermino").val(),
	        	mperson: $("#hdnIdPersona").val(),
	        	mpredio: $("#txtMpredio").val() 
        	};
        	console.log(mhresum);

			if ($("#dtpFechaDeclaracion").val()==''){
				alert("Ingrese la fecha de declaracion ");
				return false;
			} 

			if ($("#cboMotivo").val()=='9999999999'){
				alert("Seleccione el motivo.");
				$("#cboMotivo").focus();
				return false; 
			}

					
        	
        	_post = $.post(path + "registro/guardardeclaracion", mhresum);
            _post.success(function(data){
            	
        		openDialogWarning("Los datos han sido guardados.", 380, 150);
        		  
        		closeDialog('jqDialog1');
        	});
            
        });
        $("#btnCancelarDeclaracion").button({
            icons: {primary:'ui-icon-arrowreturnthick-1-w'}
        }).bind("click", function(){
            closeDialog("jqDialog1");
        });

	  function verificar(){    		
    		//alert(""+$("#txtMotivo").val());
    		//1000000008 --Compra
    		//1000000009 --Venta
	  		 
		  /*if ( $("#cboMotivo").val()=='2' ||  $("#cboMotivo").val()=='3' ){
				$("#dvBajalt").show();			  		
			}else{
				$("#dvBajalt").hide();		
		 	}*/
	  }	  	 

        $("#txtMotivo").bind("autocompleteselect", verificar);
        $("#txtMotivo").bind("autocompletechange", verificar);

    	//$("#dvBajalt").hide();	


        $("#btnVerPredios").button({
            icons: {primary:'ui-icon-search'}
        }).bind("click", function(){

        	row2={
					mperson: $("#hdnIdPersona").val()                	
        		}; 
        	
        	openDialogData2("registro/busqpredio", row2 , "600", "500", "Predios", function() {
            	
    	    	if(row != undefined) {
    	    		$("#txt_idsigma").val(row.idsigma);
    		        $("#txtnombre").val(row.nombre);
    		  //	$("#txt_instcnitems").val(row.cnitems);
    		        $("#txtdni").val(row.dni);
    		  //	$("#txt_instctipdat").val(row.ctipdat);       
    		  //	$("#txt_instvnrodoc").val(row.vnrodoc);
    		   		
    		 //		$("#txt_instdafecta").val(row.dafecta);     
    	   }  else {
    		   $("#txt_idsigma").val('-1');  
    		   
    	   		}
    		});
            
        }); 

        
        
    });
</script>