<table class="ui-table-panelLayout">
    <tr>
        <td colspan="2" style="text-align: right;font-weight: bold;">La modificaci&oacute;n de esta declaraci&oacute;n entra en vigencia a partir del a&ntilde;o:</td>
        <td><input class="ui-text" style="width: 80px; text-align: center;" id="dtpFechaVigencia"/></td>
    </tr>
    <tr>
        <td colspan="3" style="padding: 2px;"><hr/></td>
    </tr>
    <tr>
        <td style="text-align: right;width: 130px">Declaraci&oacute;n Jurada:</td>
        <td><input class="ui-text" style="width: 100px"></td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td style="text-align: right">Fecha:</td>
        <td><input class="ui-text" style="width: 80px; text-align: center;" id="dtpFechaDeclaracion"/></td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td style="text-align: right">Motivo:</td>
        <td id="cellMotivo"><select style="width: 240px;" id="cboMotivo"><?php echo $this->util()->getComboContenedor('1000000004', null); ?></select></td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td style="text-align: right;vertical-align: top;">Observaci&oacute;n:</td>
        <td colspan="2"><textarea class="ui-text" class="jquery_ckeditor" cols="80" id="txtObservacion" name="txtObservacion" rows="10"></textarea></td>
    </tr>
    <tr>
        <td colspan="3" style="text-align: right;">
            <button id="btnAceptarDeclaracion">Aceptar</button>
            <button id="btnCancelarDeclaracion">Cancelar</button>
        </td>
    </tr>
</table>
<script type="text/javascript">
    $(function(){
        var config = {
            skin:'v2'
            , toolbar: [
                ['Bold','Italic','Underline','-','NumberedList','BulletedList','-','Outdent','Indent','-','Undo','Redo','-','HorizontalRule','-','Blockquote','CreateDiv','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock','-','TextColor','BGColor'],
                ['UIColor']
            ]
        };
        
        var hEd = CKEDITOR.instances['txtObservacion'];
        if (hEd) {
            CKEDITOR.remove(hEd);
        }
        CKEDITOR.replace('txtObservacion', config);
        
        $("#dtpFechaDeclaracion, #dtpFechaVigencia").datepicker({
            dateFormat: "dd/mm/yy",
            showOn: "button",
            buttonImage: pathImage + "calendar.gif",
            buttonImageOnly: true
        });
        
        themeComboBox("#cellMotivo select");
        
        $("#btnAceptarDeclaracion").button({
            icons: {primary:'ui-icon-check'}
        }).bind("click", function(){
            closeDialog("jqDialog1");
        });
        $("#btnCancelarDeclaracion").button({
            icons: {primary:'ui-icon-arrowreturnthick-1-w'}
        }).bind("click", function(){
            closeDialog("jqDialog1");
        });
    });
</script>