<script type="text/javascript" src="<?php echo $this->util()->getPath(); ?>js/registro/declaracion.js"></script>
<input type="hidden" id="hdnIdDeclaracion" value="<?php echo $this->mhresum; ?>"/>
<input type="hidden" id="hdnIdPersona" value="<?php echo $this->mperson; ?>"/>
<input type="hidden" id="hdnAnioTermino" value="<?php echo $this->cperiod; ?>"/>

<table class="ui-table-panelLayout" style="width: 100%">
    <tr>
		<td style="width: 350px;">
			<table>
				<tr>
					<td>Nro. :</td>
					<td><div style="font-size: 14px;font-weight: bold;" id="txtNroDeclaracion"></div></td>
				</tr>
			</table>
		</td>
        <td style="text-align: right;">
        	La modificaci&oacute;n de esta declaraci&oacute;n entra en vigencia a partir del a&ntilde;o:
        	<input class="ui-text" style="width: 80px; text-align: left;" id="dtpFechaVigencia"/>
        </td>
    </tr>
    <tr>
        <td colspan="2">
        	<hr/>
        </td>
    </tr>
    <tr>
	    <td>
	    	<table style="width: 100%;">
				<tr>
					<td style="text-align: right">Fecha:</td>
					<td>
						<input class="ui-text" style="width: 80px; text-align: center;" id="dtpFechaDeclaracion"/>
					</td>
				</tr>
				<tr>
					<td style="text-align: right">Motivo:</td>
					<td id="cellMotivo">
						<select style="width: 240px;" id="cboMotivo">
							<?php echo $this->util()->getComboContenedorOtro('1000000004', null,'public.obtener_tabla_otro'); ?>
						</select>
					</td>
				</tr>
				<tr>
					<td style="text-align: right;vertical-align: top;">Observaci&oacute;n:</td>
				</tr>
				<tr>
					<td colspan="2">
						<textarea style="width: 340px; height: 350px;" class="ui-text jquery_ckeditor" cols="80" id="txtObservacion" name="txtObservacion" rows="10">
						</textarea>
					</td>
				</tr>
			</table>
		</td>
		<td style="width: 100%; vertical-align: top;">
			<table style="width: 100%;">
				<tr>
					<td>				    
						<div id="panelResultmPredio">
							<!-- 
							<button id="btnAgreParti">Agregar</button>						
							<table id="tblResultmPredio" border="1">
							<tr>
								<td>Codigo</td>
								<td>Nombre</td>
								<td>Tipo Propietario</td>  
							</tr>
							<tr>
							<tr>
								<td><?php echo $this->mperson; ?></td>
<td><?php echo $this->dperson; ?></td>
<td ><input type="hidden" id="txt_tipprop1" /> </td>
							</tr>
							</table>
							<div id="ptblResultmPredio"></div>
							 -->
						</div>
			   		</td>	
				</tr>
			</table>      
		</td>
    </tr>
	<tr>
		<td colspan="2" style="text-align: right;">
			<button id="btnAceptarDeclaracion">Aceptar</button>
			<button id="btnCancelarDeclaracion">Cancelar</button>
		</td>
	</tr>
</table>