<table>
    <tr>
        <td>Centro Poblado</td>
    </tr>
    <tr>
        <td>Via</td>
    </tr>
    <tr>
        <td>Nro.</td>
        <td style="font-weight: bold;width: 90px;"><input class="ui-text" style="width: 100%" id="txtNro" /></td>
        <td>Dpto.</td>
        <td style="font-weight: bold;width: 90px;"><input class="ui-text" style="width: 100%" id="txtNro" /></td>
        <td>Mza.</td>
        <td style="font-weight: bold;width: 90px;"><input class="ui-text" style="width: 100%" id="txtNro" /></td>
        <td>lte.</td>
        <td style="font-weight: bold;width: 90px;"><input class="ui-text" style="width: 100%" id="txtNro" /></td>
    </tr>
</table>
    