<div align="center" class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
	<div class="ui-widget ui-state-default ui-corner-top ui-title">
		<label>Registro de Declaraci&oacute;n Jurada</label>
	</div>
	<table style="width: 100%; height: 480px; padding-top: 10px; padding-bottom: 2px;" border="0" cellpadding="0" cellspacing="0">
	<tr><td style="vertical-align: top;">
		<table style="width: 100%;" border="0" >
		<tr>
			<td width="20">&nbsp;</td>
			<td width="100">C&oacute;digo:</td>
			<td width="10">&nbsp;</td>
			<td width="180">Nombre:</td>
			<td width="10">&nbsp;</td>
			<td width="180">Apellido Paterno:</td>
			<td width="10">&nbsp;</td>
			<td width="180" colspan="5">Apellido Materno:</td>
			<td width="20">&nbsp;</td>
			<td rowspan="5">
				<button id="btnbuscar" name="btnbuscar">Buscar</button>
				<button id="btncontri" name="btncontri">Contribuyente</button>
				<button id="btnestcta" name="btnestcta">Estado de Cuenta</button>
			</td>
		</tr>
		<tr id="panelContribuyente">
			<td width="20">&nbsp;</td>
			<td width="100"><input id="c_codigocontrib" maxlength="7" style="width:100%" /></td>
			<td width="10">&nbsp;</td>
			<td width="180"><input id="c_nombrecontrib" style="width:100%" /></td>
			<td width="10">&nbsp;</td>
			<td width="180"><input id="c_apepatcontrib" style="width:100%" /></td>
			<td width="10">&nbsp;</td>
			<td width="180" colspan="5"><input id="c_apematcontrib" style="width:100%" /></td>
			<td width="20">&nbsp;</td>
		</tr>
		<tr>
			<td colspan="13" height="8px"></td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>C&oacute;digo Predial:</td>
			<td></td>
			<td>Centro Poblado:</td>
			<td>&nbsp;</td>
			<td>Via:</td>
			<td>&nbsp;</td>
			<td width="50">Nro:</td>
			<td width="10">&nbsp;</td>
			<td width="50">Mza:</td>
			<td width="10">&nbsp;</td>
			<td width="50">Lote:</td>
			<td>&nbsp;</td>
		</tr>
		<tr id="panelPredio">
			<td>&nbsp;</td>
			<td><input id="c_predial" style="width:100%" /></td>
			<td></td>
			<td><input id="c_centropobladcontri" style="width:100%" /></td>
			<td>&nbsp;</td>
			<td><input id="c_viacontrib" style="width:100%" /></td>
			<td>&nbsp;</td>
			<td width="50"><input id="c_nroviacontrib" style="width:100%" /></td>
			<td width="10">&nbsp;</td>
			<td width="50"><input id="c_mzacontrib" style="width:100%" /></td>
			<td width="10">&nbsp;</td>
			<td width="50"><input id="c_lotecontrib" style="width:100%" /></td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td colspan="14" align="center">
				<br/>
				<!--
				<div style="width: 96%; padding: 1px;" class="ui-widget-content ui-widget ui-corner-all">
				<table align='center' style="width: 100%" id="tbl_result" cellpadding='0' cellspacing='0'>
					<thead class="ui-widget ui-widget-header ui-title2">
					<tr>
						<th style="width: 190px">Nro. Caja</th>
						<th style="width: 100px">Nro.Inicial</th>
						<th style="width: 100px">Nro.Final</th>
						<th style="width: 130px">Monto Canc.</th>
						<th style="width: 130px">Monto Anul.</th>
						<th style="width: 100px">Estado</th>
						<th style="width: 16px">&nbsp;</th>
					</tr>
					</thead>
				</table>
				</div>
				-->
				<div id="panelResult">
					<table id="tblResult"></table>
					<div id="ptblResult"></div>
				</div>
			</td>
		</tr>
		</table>
	</td></tr>
	</table>
</div>
<!--
	<div id="div_result_princ" style="overflow-y:scroll;height:200px;border:1px solid">
	</div>
-->

<!-- ---------------------------------------------------------------------------------------------------------------------------------  -->
<!-- form buscar persona -->
<div id="ventanabuscarpersonanombre">
	<table width="700" border="0" cellspacing="0" cellpadding="0">
	  <tr>
	    <td width="20">&nbsp;</td>
	    <td>&nbsp;</td>
	    <td width="20">&nbsp;</td>
	  </tr>
	  <tr>
	    <td>&nbsp;</td>
	    <td>
	    <table width="660" border="1" cellspacing="0" cellpadding="0">
	    <thead class="ui-widget ui-widget-header ui-title1">
	      <tr>
	        <th width="80">Cod. Contrib.</th>
	        <th width="240">Nombre</th>
	        <th width="323">Direcci&oacute;n Fiscal</th>
	        <th width="17">-</th>
	        </tr>
	    </thead>
	    </table>
	    
	    </td>
	    <td>&nbsp;</td>
	  </tr>
	  <tr>
	    <td>&nbsp;</td>
	    <td>
	    	<div id="div_rptabuscarpersonanombre" style="overflow-y: scroll; height: 150px; border: 1px solid;">
	        	<table id="tbl_buscarpersonanombre" width="640" border="1" cellspacing="0" cellpadding="0"><tbody class="ui-table-body">
	                  <tr>
	                    <td width="79">Cod. Contrib.</td>
	                    <td width="239">Nombre</td>
	                    <td width="320">Direcci&oacute;n Fiscal</td>                    
	                    </tr>
	                    <tr>
	                    <td width="79">Cod. Contrib.</td>
	                    <td width="239">Nombre</td>
	                    <td width="320">Direcci&oacute;n Fiscal</td>                    
	                    </tr>
	                </tbody></table>
	        </div>
	    </td>
	    <td>&nbsp;</td>
	  </tr>
	  <tr>
	    <td>&nbsp;</td>
	    <td>&nbsp;</td>
	    <td>&nbsp;</td>
	  </tr>
	</table>
</div>
<!-- ---------------------------------------------------------------------------------------------------------------------------------  -->
<!-- form buscar por direccion -->
<div id="ventanabuscarpersonadireccion">
	<table width="850" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="12">&nbsp;</td>
    <td width="822">&nbsp;</td>
    <td width="16">&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>
    <table width="822" border="1" cellspacing="0" cellpadding="0">
    <thead class="ui-widget ui-widget-header ui-title1">
      <tr>
        <th width="54" >Cod.Pred.</th>
        <th width="237" >Nombre Via</th>
        <th width="24" >Nro.</th>
        <th width="41" >Depart.</th>
        <th width="24" >Int.</th>
        <th width="29" >Letra</th>
        <th width="34" >Estac.</th>
        <th width="39" >Depos.</th>
        <th width="24" >Mz.</th>
        <th width="25" >Lote</th>
        <th width="248" >Contribuyente</th>
        <th width="17" >-</th>
      </tr>
      </thead>
    </table>

    </td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>
    	<div id="div_rptabuscarpersonadir" style="overflow-y: scroll; height: 150px; border: 1px solid;">
        	<table width="805" border="1" cellspacing="0" cellpadding="0">
                <tbody class="ui-table-body">
                 	<tr>
                    	<td width="54" >Cod.Pred.</td>
                        <td width="237" >Nombre Via</td>
                        <td width="24" >Nro.</td>
                        <td width="41" >Depart.</td>
                        <td width="24" >Int.</td>
                        <td width="29" >Letra</td>
                        <td width="34" >Estac.</td>
                        <td width="39" >Depos.</td>
                        <td width="24" >Mz.</td>
                        <td width="25" >Lote</td>
                        <td width="248" >Contribuyente</td>
                    </tr>
                </tbody>
                </table>
        </div>
    </td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
</table>
</div>

<!-- ---------------------------------------------------------------------------------------------------------------------------------  -->
<!-- form predio rustico -->
<div id="ventanadatosprediorustico">
<table width="660" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="30">&nbsp;</td>
    <td width="600">&nbsp;</td>
    <td width="30">&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td  style="border:1px solid">
   	  <fieldset>
        	<legend><h2>Predios Colindantes</h2>
            <table width="600" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="6" align="right" height="8px"></td>
  </tr>
  <thead class="ui-widget ui-widget-header ui-title1">          
  <tr>
    <th width="40">&nbsp;</th>
    <th width="10">&nbsp;</th>
    <th width="300" align="center">Ubicaci&oacute;n</th>
    <th width="10">&nbsp;</th>
    <th width="220" align="center">Propietario</th>
    <th width="20" align="center">(*)</th>
  </tr>
  </thead>
  <tr>
    <td align="right"><b>Norte:</b></td>
    <td>&nbsp;</td>
    <td><input type="text" style="width:100%" id="txtrust_predcolinnorte" value="" /></td>
    <td>&nbsp;</td>
    <td><input type="text" style="width:100%" id="txtrust_propietarionorte" value="" /></td>
    <td align="center"><input type="checkbox" id="txtrust_checknorte" /></td>
  </tr>
  <tr>
    <td colspan="6" align="right" height="5px"></td>
    </tr>
  <tr>
    <td align="right"><b>Sur:</b></td>
    <td>&nbsp;</td>
    <td><input type="text" style="width:100%" id="txtrust_predcolinsur" value="" /></td>
    <td>&nbsp;</td>
    <td><input type="text" style="width:100%" id="txtrust_propietariosur" value="" /></td>
    <td align="center"><input type="checkbox" id="txtrust_checksur" /></td>
  </tr>
  <tr>
    <td colspan="6" align="right" height="5px"></td>
  </tr>
  <tr>
    <td align="right"><b>Este:</b></td>
    <td>&nbsp;</td>
    <td><input type="text" style="width:100%" id="txtrust_predcolineste" value="" /></td>
    <td>&nbsp;</td>
    <td><input type="text" style="width:100%" id="txtrust_propietarioeste" value="" /></td>
    <td align="center"><input type="checkbox" id="txtrust_checkeste" /></td>
  </tr>
  <tr>
    <td colspan="6" align="right" height="5px"></td>
  </tr>
  <tr>
    <td align="right"><b>Oeste:</b></td>
    <td>&nbsp;</td>
    <td><input type="text" style="width:100%" id="txtrust_predcolinoeste" value="" /></td>
    <td>&nbsp;</td>
    <td><input type="text" style="width:100%" id="txtrust_propietariooeste" value="" /></td>
    <td align="center"><input type="checkbox" id="txtrust_checkoeste" /></td>
  </tr>
  <tr>
    <td colspan="6" align="right" height="8px"></td>
  </tr>
</table>

        </fieldset>
    </td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td  style="border:1px solid">
    	<fieldset>
        	<legend><h2>Datos Relativos al Terreno</h2><br>
            <table width="600" border="0" cellspacing="0" cellpadding="0">
            
    <tr>
    <td width="105"><b>Plan de Cultivo:</b></td>
    <td width="15">&nbsp;</td>
    <td width="130"><input type="text" style="width:130px" id="txtrust_plancultivo" value="" /></td>
    <td width="15">&nbsp;</td>
    <td width="115"><b>Canon de Agua:</b></td>
    <td width="10">&nbsp;</td>
    <td width="210"><input type="text" style="width:130px" id="txtrust_canonagua" value="" /></td>
  </tr>
  <tr>
    <td colspan="7" align="right" height="8px"></td>
  </tr>
</table>

    	</fieldset>
    </td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td style="border:1px solid">
    <fieldset>
        	<legend><h2>Determinaci&oacute;n del valuo del Predio</h2>
        	<ul><li class="ui-state-default ui-corner-all" style="width:16px" id="anadirdatosprediorustico" ><span class="ui-icon ui-icon-plusthick"></span></li></ul>
            <table width="600" border="0" cellspacing="0" cellpadding="0">
 <thead class="ui-widget ui-widget-header ui-title1">
  <tr>  	
    <th width="241">Clasificaci&oacute;n:</th>
    <th width="10">&nbsp;</th>
    <th width="55">Categoria:</th>
    <th width="10">&nbsp;</th>
    <th width="72">Arancel:</th>
    <th width="10">&nbsp;</th>
    <th width="72">Hectarias:</th>
    <th width="10">&nbsp;</th>
    <th width="72">Valor Total:</th>
    <th width="10">&nbsp;</th>
    <th width="18"></th>
    <th width="20"></th>
  </tr>
  </thead>
    <tr>
    <td colspan="12" height="5px"></td>
    </tr>
    <tr><td colspan="12" height="5px">
    <input type="hidden" value="0" id="correlprediorustico">
    
    <div id="div_modelo_datoscalculoprediorustico" style="display: none; ">    
      <table id="tbl_datoscalculoprediorustico_x" width="580" border="0" cellspacing="0" cellpadding="0">
	  <tr>
	    <td width="241"><select id="cbrustico_clasif_x" style="width:100%"></select></td>
	    <td width="10">&nbsp;</td>
	    <td width="55"><select id="cbrustico_categ_x" style="width:100%"></select></td>
	    <td width="10">&nbsp;</td>
	    <td width="72"><input type="text" id="cbrustico_arancel_x" readonly="readonly" style="width:100%" value="0.00" /></td>
	    <td width="10">&nbsp;</td>
	    <td width="72"><input type="text" id="cbrustico_hectaria_x" style="width:100%" value="0.00" /></td>
	    <td width="10">&nbsp;</td>
	    <td width="72"><input type="text" id="cbrustico_valor_x" readonly="readonly" style="width:100%" value="0.00" /></td>
	    <td width="10">&nbsp;</td>
	    <td width="18"><ul><li class="ui-state-default ui-corner-all" id="borrardatosprediorustico_x" onclick="$('#tbl_datoscalculoprediorustico_x').remove();" style="width:16px"><span class="ui-icon ui-icon-closethick"></span></li></ul></td>
	  </tr>
	  <tr>
	    <td colspan="11" height="5px"></td>
	  </tr>
  	  </table> 	  
    </div>
    
    <div id="div_datoscalculoprediorustico" style="overflow-y:scroll;height:100px;border:1px solid">
    </div>
        
    </td></tr>
    <tr>
     <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td><b>Valor Total</b></td>
    <td>&nbsp;</td>
    <td><input type="text" id="cbrustico_valortotal" readonly="readonly" style="width:80px" value="" /></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
<tr>
    <td colspan="12" height="8px"></td>
  </tr>
</table>

    </fieldset>
    </td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><b>(*) El mismo Propietario</b></td>
    <td>&nbsp;</td>
  </tr>
</table>
</div>

<!-- ---------------------------------------------------------------------------------------------------------------------------------  -->
<div id="ventanadetallepredio">

<div align="center">
    <table  border="1" cellspacing="0" cellpadding="0"><tr valign="middle"><td align="center">
    <table width="662" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="7" height="8px"></td>
    </tr>
  <tr>
    <td width="40">&nbsp;</td>
    <td width="50">C&oacute;digo:</td>
    <td width="79" id="c_codigocontrib_x">&nbsp;</td>
    <td width="22">&nbsp;</td>
    <td width="56">Nombre:</td>
    <td width="399" id="c_nombrecontrib_x">&nbsp;</td>
    <td width="16">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="7" height="8px"></td>
    </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Direcci&oacute;n:</td>
    <td colspan="4" id="c_dirfiscal_x">&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td colspan="7" height="8px"></td>
    </tr>
</table>
</td></tr></table>
</div> 
<br>
	<div id="tabs_detallepredio">
		<ul>
			<li><a href="#predio_descripcion">Descripci&oacute;n</a></li>
			<li><a href="#predio_pisos">Pisos</a></li>
			<li><a href="#predio_instalacion">Instalaci&oacute;n</a></li>
		</ul>
		<div id="predio_descripcion">
			
			<div align="center" style="overflow-y:scroll;height:350px;border:1px solid"> 
				<table width="799" border="0" cellspacing="0" cellpadding="0">
				  <tr>
				    <td width="28">&nbsp;</td>
				    <td width="70">&nbsp;</td>
				    <td width="113">&nbsp;</td>
				    <td width="15">&nbsp;</td>
				    <td width="100">&nbsp;</td>
				    <td width="401">&nbsp;</td>
				    <td width="39">&nbsp;</td>
				    <td width="33">&nbsp;</td>
				  </tr>
				  <tr>
				    <td>&nbsp;</td>
				    <td>Cod. Predio:</td>
				    <td id="c_codpred">&nbsp;</td>
				    <td>&nbsp;</td>
				    <td>Direcci&oacute;n Predial:</td>
				    <td id="c_dirpred">&nbsp;</td>
				    <td>
				    	<button id="btndireccion" name="btndireccion"><span class="ui-button-text">...</span></button>    </td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td>&nbsp;</td>
				    <td colspan="6"><table width="736" border="0" cellspacing="0" cellpadding="0">
				      <tr>
				        <td>Fecha de Adquisici&oacute;n<input id="txt_fechaadquisicion" style="width:100%" value="" /></fieldset></td>
				        <td>&nbsp;</td>
				        <td>Fecha de Baja<input id="txt_fechabaja" style="width:100%" value="" /></fieldset></td>
				        <td>&nbsp;</td>
				        <td>Ultimo Recalculo<input id="txt_ultimorecalculo" style="width:100%" value="" /></fieldset></td>
				      </tr>
				      <tr>
				        <td>&nbsp;</td>
				        <td>&nbsp;</td>
				        <td>&nbsp;</td>
				        <td>&nbsp;</td>
				        <td>&nbsp;</td>
				      </tr>
				      <tr>
				        <td width="238">
				        	Condici&oacute;n de Propiedad<select id="cb_condicionpropiedad" style="width:100%;padding:2px"></select></fieldset>        </td>
				        <td width="10">&nbsp;</td>
				        <td width="238">Estado de Predio<select id="cb_estadopredio" style="width:100%;padding:2px"></select></fieldset></td>
				        <td width="10">&nbsp;</td>
				        <td width="240">Tipo Predio<select id="cb_tipopredio" style="width:100%;padding:2px"></select></fieldset></td>
				      </tr>
				      <tr>
				        <td colspan="5" height="8px"></td>
				        </tr>
				      <tr>
				        <td>Clasificaci&oacute;n del Predio<select id="cb_clasificacionpredio" style="width:100%;padding:2px"></select></fieldset></td>
				        <td>&nbsp;</td>
				        <td>Uso General de Predio<select id="cb_usogeneralpredio" style="width:100%;padding:2px"></select></fieldset></td>
				        <td>&nbsp;</td>
				        <td>Uso Espec&iacute;fico del Predio<select id="cb_usoespecificopredio" style="width:100%;padding:2px"></select></fieldset></td>
				      </tr>
				      <tr>
				        <td colspan="5" height="8px"></td>
				        </tr>
				        <tr>
				        <td colspan="5" align="left"><button id="btnprediorustico">Datos de Predio R&uacute;stico</button></td>
				        </tr>
				    </table></td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td>&nbsp;</td>
				    <td colspan="6">&nbsp;</td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td>&nbsp;</td>
				    <td colspan="6">
				    	<fieldset  style="padding:5px"><legend>Datos del Terreno        
				        	<table width="737" border="0" cellspacing="0" cellpadding="0">
				              <tr>
				                <td width="114">&Aacute;rea Terreno:<input id="txt_areaterreno" style="width:100%" value="" /></fieldset></td>
				                <td width="10">&nbsp;</td>
				                <td width="114">Porcentaje Terreno:<input id="txt_procentajeterreno" style="width:100%" value="" /></fieldset></td>
				                <td width="10">&nbsp;</td>
				                <td width="114">Total &Aacute;rea:<input id="txt_totalarea" style="width:100%" value="" /></fieldset></td>
				                <td width="10">&nbsp;</td>
				                <td width="114">&Aacute;rea Com&uacute;n:<input id="txt_areacomun" style="width:100%" value="" /></fieldset></td>
				                <td width="10">&nbsp;</td>
				                <td width="114">Porcentaje Com&uacute;n:<input id="txt_porcentajecomun" style="width:100%" value="" />
				                </fieldset></td>
				                <td width="10">&nbsp;</td>
				                <td width="114">Total Com&uacute;n:<input id="txt_totalcomun" style="width:100%" value="" /></fieldset></td>
				              </tr>
				              <tr>
				                <td colspan="11" height="8px"></td>
				                </tr>
				              <tr>
				                <td>Frente:<input id="txt_frente" style="width:100%" value="" /></fieldset></td>
				                <td>&nbsp;</td>
				                <td>Arancel:<input id="txt_arancel" style="width:100%" value="" /></fieldset></td>
				                <td>&nbsp;</td>
				                <td>Porcentaje Cond:<input id="txt_porcentajecond" style="width:100%" value="" /></fieldset></td>
				                <td>&nbsp;</td>
				                <td colspan="5">Ubicaci&oacute;n del Parque:<select id="cb_ubicacionparque" style="width:100%;padding:2px"></select></fieldset></td>
				              </tr>
				            </table>
				        </fieldset>        </td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td>&nbsp;</td>
				    <td colspan="6">&nbsp;</td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td>&nbsp;</td>
				    <td colspan="6">
				    	<fieldset style="padding:5px"><legend>Inafecto        
				        	<table width="737" border="0" cellspacing="0" cellpadding="0">
				              <tr>
				                <td colspan="5">Tipo de Inafectaci&oacute;n:<select id="cb_tipoinafecto" style="width:100%;padding:2px"></select></fieldset></td>
				                <td>&nbsp;</td>
				                <td>Expediente:<input id="txt_expedienteinafecto" style="width:100%" value="" /></fieldset></td>
				                <td>&nbsp;</td>
				                <td>Resoluci&oacute;n:<input id="txt_resolucioninafecto" style="width:100%" value="" /></fieldset></td>
				                <td>&nbsp;</td>
				                <td>Fecha Resoluci&oacute;n:<input id="txt_fecharesolucioninafecto" style="width:100%" value="" /></fieldset></td>
				              </tr>
				              <tr>
				                <td colspan="11">&nbsp;</td>
				              </tr>
				              <tr>
				                <td colspan="3">Base Legal:<input id="txt_baselegalinafecto" style="width:100%" value="" /></fieldset></td>
				                <td>&nbsp;</td>
				                <td colspan="3">Observaci&oacute;n:<input id="txt_observacioninafecto" style="width:100%" value="" /></fieldset></td>
				                <td>&nbsp;</td>
				                <td>Fecha Inicio:<input id="txt_inicioinafecto" style="width:100%" value="" /></fieldset></td>
				                <td>&nbsp;</td>
				                <td>Fecha Fin:<input id="txt_fininafecto" style="width:100%" value="" /></fieldset></td>
				              </tr>
				              <tr>
				                <td colspan="11">&nbsp;</td>
				              </tr>
				              <tr>
				                <td width="114">% IP:<input id="txt_inafectoip" style="width:100%" value="" /></fieldset></td>
				                <td width="10">&nbsp;</td>
				                <td width="114">% LC:<input id="txt_inafectolc" style="width:100%" value="" /></fieldset></td>
				                <td width="10">&nbsp;</td>
				                <td width="114">% RB:<input id="txt_inafectorb" style="width:100%" value="" /></fieldset></td>
				                <td width="10">&nbsp;</td>
				                <td width="114">% LP:<input id="txt_inafectolp" style="width:100%" value="" /></fieldset></td>
				                <td width="10">&nbsp;</td>
				                <td width="114">% PJ:<input id="txt_inafectopj" style="width:100%" value="" /></fieldset></td>
				                <td width="10">&nbsp;</td>
				                <td width="114">% SG:<input id="txt_inafectosg" style="width:100%" value="" /></fieldset></td>
				              </tr>
				              <tr>
				                <td colspan="11" height="8px"></td>
				                </tr>
				            </table>
				        </fieldset>    </td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				    <td>&nbsp;</td>
				  </tr>
				</table>
				
				</div>
			
		</div>
		<div id="predio_pisos">
			
			<div align="center" style="overflow-y:scroll;height:350px;border:1px solid">
					<table width="800" border="0" cellspacing="0" cellpadding="0">
				  <tr>
				    <td colspan="8" height="8px"></td>
				    </tr>
				  <tr>
				    <td width="20">&nbsp;</td>
				    <td colspan="6">
				    
				    	<div style="border:1px solid;overflow-x:scroll;width:760px">
				                <table width="1150" border="1" cellspacing="0" cellpadding="0">
				                <thead class="ui-widget ui-widget-header ui-title1">
				                      <tr>
				                        <th width="30" >Nivel</th>
				                        <th width="41" >Antig.</th>
				                        <th width="80" >Material</th>
				                        <th width="60" >Estado</th>
				                        <th width="20" >Mu</th>
				                        <th width="20" >Te</th>
				                        <th width="20" >Pi</th>
				                        <th width="20" >Pv</th>
				                        <th width="20" >Rv</th>
				                        <th width="20" >Ba</th>
				                        <th width="20" >In</th>
				                        <th width="70" >Area. Contr.</th>
				                        <th width="85" >Val. Unit. m2</th>
				                        <th width="50" >Inc. 5%</th>
				                        <th width="50" >% depr</th>
				                        <th width="50" >depr.</th>
				                        <th width="100" >Val. Unit. Deprec.</th>
				                        <th width="90" >Val. Area Const.</th>
				                        <th width="90" >% Area Com&uacute;n</th>
				                        <th width="95" >Val. Area Comun</th>
				                        <th width="80" >valor final</th>
				                  	  </tr>
				                 </thead> 	  
				                      <tr>
				                        <td colspan="21" height="100px" valign="top" id="c_tablapisos">
				                            
				                                <table border="1" cellspacing="0" cellpadding="0">
				                                    <tr>
				                                      <td width="27" align="center">x</td>
				                                      <td width="40" align="center">x</td>
				                                      <td width="78">x</td>
				                                      <td width="59">x</td>
				                                      <td width="20" align="center">x</td>
				                                      <td width="20" align="center">x</td>
				                                      <td width="20" align="center">x</td>
				                                      <td width="20" align="center">x</td>
				                                      <td width="20" align="center">x</td>
				                                      <td width="20" align="center">x</td>
				                                      <td width="20" align="center">x</td>
				                                      <td width="70" align="right">x</td>
				                                      <td width="85" align="right">x</td>
				                                      <td width="50" align="right">x</td>
				                                      <td width="50" align="right">x</td>
				                                      <td width="50" align="right">x</td>
				                                      <td width="100" align="right">x</td>
				                                      <td width="90" align="right">x</td>
				                                      <td width="90" align="right">x</td>
				                                      <td width="95" align="right">x</td>
				                                      <td width="78" align="right">x</td>
				                                  </tr>
				                                  <tr>
				                                      <td width="27" align="center">x</td>
				                                      <td width="40" align="center">x</td>
				                                      <td width="78">x</td>
				                                      <td width="59">x</td>
				                                      <td width="20" align="center">x</td>
				                                      <td width="20" align="center">x</td>
				                                      <td width="20" align="center">x</td>
				                                      <td width="20" align="center">x</td>
				                                      <td width="20" align="center">x</td>
				                                      <td width="20" align="center">x</td>
				                                      <td width="20" align="center">x</td>
				                                      <td width="70" align="right">x</td>
				                                      <td width="85" align="right">x</td>
				                                      <td width="50" align="right">x</td>
				                                      <td width="50" align="right">x</td>
				                                      <td width="50" align="right">x</td>
				                                      <td width="100" align="right">x</td>
				                                      <td width="90" align="right">x</td>
				                                      <td width="90" align="right">x</td>
				                                      <td width="95" align="right">x</td>
				                                      <td width="78" align="right">x</td>
				                                  </tr>
				                                </table>
				                        </td>
				                      </tr>
				                      <tr>
				                        <td colspan="11">&nbsp;</td>
				                        <td align="right" id="c_total_area_cons">total</td>
				                        <td colspan="5">&nbsp;</td>
				                        <td align="right" id="c_valor_area_cons">total</td>
				                        <td colspan="3">&nbsp;</td>
				                      </tr>
				                    </table>
				    
				    </div>
				       
				    </td>
				    <td width="20">&nbsp;</td>
				  </tr>
				  <tr>
				    <td colspan="8" height="8px"></td>
				    </tr>
				  <tr>
				    <td>&nbsp;</td>
				    <td colspan="6">
				    	<fieldset  style="padding:5px"><legend>Datos del Piso
				        	<table width="748" border="0" cellspacing="0" cellpadding="0">
				              <tr>
				                <td width="59">Nro Piso<input id="txt_nropiso" style="width:100%" value="" /></fieldset></td>
				                <td width="14">&nbsp;</td>
				                <td width="90">Area Const.<input id="txt_pisoareaconst" style="width:100%" value="" /></fieldset></td>
				                <td width="15">&nbsp;</td>
				                <td width="70">A&ntilde;o Const.<input id="txt_pisoanioconst" style="width:100%" value="" /></fieldset></td>
				                <td width="15">&nbsp;</td>
				                <td width="70">Antig&uuml;edad<input id="txt_pisoantig" style="width:100%" value="" /></fieldset></td>
				                <td width="15">&nbsp;</td>
				                <td width="95">% Area Com&uacute;n<input id="txt_pisoporcareacomun" style="width:100%" value="" /></fieldset></td>
				                <td width="15">&nbsp;</td>
				                <td width="141">Material<select id="cb_pisomaterial" style="width:100%;padding:2px"></select></fieldset></td>
				                <td width="15">&nbsp;</td>
				                <td width="134">Estado<select id="cb_pisoestado" style="width:100%;padding:2px"></select></fieldset></td>
				              </tr>
				            </table>
				        </fieldset>    </td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td colspan="8" height="8px"></td>
				    </tr>
				  <tr>
				    <td>&nbsp;</td>
				    <td colspan="6">
				    	<fieldset  style="padding:5px"><legend>Carecter&iacute;sticas del Piso
				        	<table width="740" border="0" cellspacing="0" cellpadding="0">
				              <tr>
				                <td width="197">
				               	  <fieldset  style="padding:5px"><legend>Estructura
				                    	<table width="180" border="0" cellspacing="0" cellpadding="0">
				                          <tr>
				                            <td width="100">Muro y Columas<select id="cb_pisomuro" style="width:100%;padding:2px"></select></fieldset></td>
				                            <td width="10">&nbsp;</td>
				                            <td width="70">Techo<select id="cb_pisotecho" style="width:100%;padding:2px"></select></fieldset></td>
				                          </tr>
				                        </table>
				                  </fieldset>                </td>
				              <td width="400">
				               	<fieldset  style="padding:5px"><legend>Acabado
				                	<table width="380" border="0" cellspacing="0" cellpadding="0">
				                      <tr>
				                        <td width="70">Pisos<select id="cb_pisopisos" style="width:100%;padding:2px"></select></fieldset></td>
				                        <td width="10">&nbsp;</td>
				                        <td width="125">Puertas y Ventanas<select id="cb_pisopuertavetana" style="width:100%;padding:2px"></select></fieldset></td>
				                        <td width="10">&nbsp;</td>
				                        <td width="85">Revestimiento<select id="cb_pisorevestimiento" style="width:100%;padding:2px"></select></fieldset></td>
				                        <td width="10">&nbsp;</td>
				                        <td width="70">Ba&ntilde;os<select id="cb_pisobanio" style="width:100%;padding:2px"></select></fieldset></td>
				                      </tr>
				                    </table>
				                </fieldset>                </td>
				              <td width="158">
				               	<fieldset  style="padding:5px"><legend>Instalaciones
				                    Electricas y Sanitarias<select id="cb_pisoinstalaciones" style="width:100%;padding:2px"></select></fieldset>
				               	</fieldset>                </td>
				              </tr>
				            </table>
				        </fieldset>    </td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td colspan="8" height="8px"></td>
				    </tr>
				   <tr>
				    <td>&nbsp;</td>
				    <td colspan="6">
				    	<fieldset  style="padding:5px"><legend>Calculo
				        	<table width="748" border="0" cellspacing="0" cellpadding="0">
				              <tr>
				                <td width="200">Valor de Construcci&oacute;n<input id="txt_pisovalorconstruccion" style="width:100%" value="" /></fieldset></td>
				                <td width="548">&nbsp;</td>			                
				              </tr>
				            </table>
				        </fieldset>    </td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td colspan="8" height="8px"></td>
				    </tr>  
				  <tr>
				    <td>&nbsp;</td>
				    <td colspan="6">
				    	<fieldset  style="padding:5px"><legend>Datos de Igreso
				        <table width="740" border="0" cellspacing="0" cellpadding="0">
				  <tr>
				    <td width="100">Ultimo Recalculo<input id="txt_pisoultimorecalculo" style="width:100%" value="" /></fieldset></td>
				    <td width="15">&nbsp;</td>
				    <td width="140">Tipo Documento<select id="cb_pisotipodoc" style="width:100%;padding:2px"></select></fieldset></td>
				    <td width="10">&nbsp;</td>
				    <td width="180">Nro Documento<input id="txt_pisonrodoc" style="width:100%" value="" /></fieldset></td>
				    <td width="10">&nbsp;</td>
				    <td width="175">Motivo<select id="cb_pisomotivo" style="width:100%;padding:2px"></select></fieldset></td>
				    <td width="10">&nbsp;</td>
				    <td width="100">Fecha de Doc.<input id="txt_pisofechadoc" style="width:100%" value="" /></fieldset></td>
				  </tr>
				</table>
				        </fieldset>    </td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td>&nbsp;</td>
				    <td width="160">&nbsp;</td>
				    <td width="120">&nbsp;</td>
				    <td width="100">&nbsp;</td>
				    <td width="100">&nbsp;</td>
				    <td width="100">&nbsp;</td>
				    <td width="180">&nbsp;</td>
				    <td>&nbsp;</td>
				  </tr>
				</table>
				
				</div>			
		</div>
		<div id="predio_instalacion">
			
			<div align="center" style="overflow-y:scroll;height:350px;border:1px solid">
					<table width="800" border="0" cellspacing="0" cellpadding="0">
				  <tr>
				    <td colspan="8" height="8px"></td>
				    </tr>
				  <tr>
				    <td width="20">&nbsp;</td>
				    <td colspan="6">
				    
				    	<div style="border:1px solid;overflow-x:scroll;width:760px">
				                <table width="1310" border="1" cellspacing="0" cellpadding="0">
				                <thead class="ui-widget ui-widget-header ui-title1">
				                      <tr>				                        
				                        <th width="41" >Antig.</th>
				                        <th width="80" >Material</th>
				                        <th width="60" >Estado</th>
				                        <th width="150" >Descripcion</th>
				                        <th width="50" >Altura</th>
				                        <th width="50" >Ancho</th>
				                        <th width="50" >Largo</th>
				                        <th width="80" >Unid. Medida.</th>
				                        <th width="70" >Area. Contr.</th>
				                        <th width="85" >Val. Unit. m2</th>
				                        <th width="50" >% depr</th>
				                        <th width="50" >depr.</th>
				                        <th width="100" >Val. Unit. Deprec.</th>
				                        <th width="90" >Val. Area Const.</th>
				                        <th width="90" >% Area Com&uacute;n</th>
				                        <th width="95" >Val. Area Comun</th>
				                        <th width="80" >valor final</th>
				                  </tr>
				                  </thead>
				                      <tr>
				                        <td colspan="17" height="100px" valign="top" id="c_tablainstalacion">
				                            
				                                <table border="1" cellspacing="0" cellpadding="0">
				                                    <tr>
				                                      <td width="40" align="center">x</td>
				                                      <td width="79">x</td>
				                                      <td width="60">x</td>
				                                      <td width="150">x</td>
				                                      <td width="50" align="center">x</td>
				                                      <td width="50" align="center">x</td>
				                                      <td width="50" align="center">x</td>
				                                      <td width="80" align="center">x</td>
				                                      <td width="70" align="right">x</td>
				                                      <td width="85" align="right">x</td>
				                                      <td width="50" align="right">x</td>
				                                      <td width="50" align="right">x</td>
				                                      <td width="100" align="right">x</td>
				                                      <td width="90" align="right">x</td>
				                                      <td width="90" align="right">x</td>
				                                      <td width="95" align="right">x</td>
				                                      <td width="78" align="right">x</td>
				                                  </tr>
				                                  <tr>
				                                      <td width="40" align="center">x</td>
				                                      <td width="79">x</td>
				                                      <td width="60">x</td>
				                                      <td width="150">x</td>
				                                      <td width="50" align="center">x</td>
				                                      <td width="50" align="center">x</td>
				                                      <td width="50" align="center">x</td>
				                                      <td width="80" align="center">x</td>
				                                      <td width="70" align="right">x</td>
				                                      <td width="85" align="right">x</td>
				                                      <td width="50" align="right">x</td>
				                                      <td width="50" align="right">x</td>
				                                      <td width="100" align="right">x</td>
				                                      <td width="90" align="right">x</td>
				                                      <td width="90" align="right">x</td>
				                                      <td width="95" align="right">x</td>
				                                      <td width="78" align="right">x</td>
				                                  </tr>
				                                </table>
				                        </td>
				                      </tr>
				                      <tr>
				                        <td colspan="8">&nbsp;</td>
				                        <td align="right" id="c_total_area_cons_inst">total</td>
				                        <td colspan="4">&nbsp;</td>
				                        <td align="right" id="c_valor_area_cons_inst">total</td>
				                        <td colspan="3">&nbsp;</td>
				                      </tr>
				                    </table>
				    
				    </div>
				       
				    </td>
				    <td width="20">&nbsp;</td>
				  </tr>
				  <tr>
				    <td colspan="8" height="8px"></td>
				    </tr>
				  <tr>
				    <td>&nbsp;</td>
				    <td colspan="6">
				    	<fieldset  style="padding:5px"><legend>Datos de Instalaci&oacute;n
				        	<table width="748" border="0" cellspacing="0" cellpadding="0">
				              <tr>
				                <td width="59">Valor<input id="txt_nrovalorinstalacion" style="width:100%" value="" /></fieldset></td>
				                <td width="14">&nbsp;</td>
				                <td width="90">Area Const.<input id="txt_instalacionareaconst" style="width:100%" value="" /></fieldset></td>
				                <td width="15">&nbsp;</td>
				                <td width="70">A&ntilde;o Const.<input id="txt_instalacionanioconst" style="width:100%" value="" /></fieldset></td>
				                <td width="15">&nbsp;</td>
				                <td width="70">Antig&uuml;edad<input id="txt_instalacionantig" style="width:100%" value="" /></fieldset></td>
				                <td width="15">&nbsp;</td>
				                <td width="95">% Area Com&uacute;n<input id="txt_instalacionporcareacomun" style="width:100%" value="" /></fieldset></td>
				                <td width="15">&nbsp;</td>
				                <td width="141">Material<select id="cb_instalacionmaterial" style="width:100%;padding:2px"></select></fieldset></td>
				                <td width="15">&nbsp;</td>
				                <td width="134">Estado<select id="cb_instalacionestado" style="width:100%;padding:2px"></select></fieldset></td>
				              </tr>
				            </table>
				        </fieldset>    </td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td colspan="8" height="8px"></td>
				    </tr>
				    
				    <tr>
					    <td>&nbsp;</td>
					    <td colspan="6">
					    	<fieldset  style="padding:5px"><legend>Datos Dimensionales
					        <table width="740" border="0" cellspacing="0" cellpadding="0">
								  <tr>
								    <td width="100">Alto<input id="txt_instalacionalto" style="width:100%" value="" /></fieldset></td>
								    <td width="10">&nbsp;</td>
								    <td width="100">Ancho<input id="txt_instalacionancho" style="width:100%" value="" /></fieldset></td>
								    <td width="10">&nbsp;</td>
								    <td width="100">Largo<input id="txt_instalacionlargo" style="width:100%" value="" /></fieldset></td>
								    <td width="10">&nbsp;</td>
								    <td width="150">Unid. Medida<select id="cb_instalacionunidmedida" style="width:100%;padding:2px"></select></fieldset></td>
								    <td width="10">&nbsp;</td>
								    <td width="250"></td>
								  </tr>
								</table>
					        </fieldset>    </td>
					    <td>&nbsp;</td>
					  </tr>
				    
				     <tr>
				    <td colspan="8" height="8px"></td>
				    </tr>
				   <tr>
				    <td>&nbsp;</td>
				    <td colspan="6">
				    	<fieldset  style="padding:5px"><legend>Calculo
				        	<table width="748" border="0" cellspacing="0" cellpadding="0">
				              <tr>
				                <td width="200">Valor de Instalaci&oacute;n<input id="txt_instalacionvalor" style="width:100%" value="" /></fieldset></td>
				                <td width="548">&nbsp;</td>			                
				              </tr>
				            </table>
				        </fieldset>    </td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td colspan="8" height="8px"></td>
				    </tr>  
				  <tr>
				    <td>&nbsp;</td>
				    <td colspan="6">
				    	<fieldset  style="padding:5px"><legend>Datos de Igreso
				        <table width="740" border="0" cellspacing="0" cellpadding="0">
							  <tr>
							    <td width="100">Ultimo Recalculo<input id="txt_instalacionultimorecalculo" style="width:100%" value="" /></fieldset></td>
							    <td width="15">&nbsp;</td>
							    <td width="140">Tipo Documento<select id="cb_instalaciontipodoc" style="width:100%;padding:2px"></select></fieldset></td>
							    <td width="10">&nbsp;</td>
							    <td width="180">Nro Documento<input id="txt_instalacionnrodoc" style="width:100%" value="" /></fieldset></td>
							    <td width="10">&nbsp;</td>
							    <td width="175">Motivo<select id="cb_instalacionmotivo" style="width:100%;padding:2px"></select></fieldset></td>
							    <td width="10">&nbsp;</td>
							    <td width="100">Fecha de Doc.<input id="txt_instalacionfechadoc" style="width:100%" value="" /></fieldset></td>
							  </tr>
							</table>
				        </fieldset>    </td>
				    <td>&nbsp;</td>
				  </tr>
				  <tr>
				    <td>&nbsp;</td>
				    <td width="160">&nbsp;</td>
				    <td width="120">&nbsp;</td>
				    <td width="100">&nbsp;</td>
				    <td width="100">&nbsp;</td>
				    <td width="100">&nbsp;</td>
				    <td width="180">&nbsp;</td>
				    <td>&nbsp;</td>
				  </tr>
				</table>
				
				</div>
		</div>
				
		</div>
	</div>
</div>

<!-- ---------------------------------------------------------------------------------------------------------------------------------  -->
