<table width="850" border="0" cellspacing="0" cellpadding="0">
    <tr>
        <td width="12">&nbsp;</td>
        <td width="822">&nbsp;</td>
        <td width="16">&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>
            <table width="822" border="1" cellspacing="0" cellpadding="0">
                <thead class="ui-widget ui-widget-header ui-title1">
                    <tr>
                        <th width="54" >Cod.Pred.</th>
                        <th width="237" >Nombre Via</th>
                        <th width="24" >Nro.</th>
                        <th width="41" >Depart.</th>
                        <th width="24" >Int.</th>
                        <th width="29" >Letra</th>
                        <th width="34" >Estac.</th>
                        <th width="39" >Depos.</th>
                        <th width="24" >Mz.</th>
                        <th width="25" >Lote</th>
                        <th width="248" >Contribuyente</th>
                        <th width="17" >-</th>
                    </tr>
                </thead>
            </table>

        </td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>
            <div id="panelListaPredio">
                <div id="ptblListaPredio"></div>
                <table id="tblListaPredio"></table>
            </div>
<!--            <div id="div_rptabuscarpersonadir" style="overflow-y: scroll; height: 150px; border: 1px solid;">
                <table width="805" border="1" cellspacing="0" cellpadding="0">
                    <tbody class="ui-table-body">
                        <tr>
                            <td width="54" >Cod.Pred.</td>
                            <td width="237" >Nombre Via</td>
                            <td width="24" >Nro.</td>
                            <td width="41" >Depart.</td>
                            <td width="24" >Int.</td>
                            <td width="29" >Letra</td>
                            <td width="34" >Estac.</td>
                            <td width="39" >Depos.</td>
                            <td width="24" >Mz.</td>
                            <td width="25" >Lote</td>
                            <td width="248" >Contribuyente</td>
                        </tr>
                    </tbody>
                </table>
            </div>-->
        </td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
</table>