<table style="width: 95%" align="center">
<tr>
	<td valign="top" style="width: 425px"><div id="Panellistadeclaraciones"></div></td>
	<td valign="top">
		<div class="ui-widget ui-widget-content ui-corner-all" style="width: 272px; height: 220px;">
			<div align="center" class="ui-widget ui-state-default ui-corner-top ui-title">
		    	<label>Observaciones</label>
			</div>
			<div id="PanellistaObservaciones"></div>
		</div>
	</td>
</tr>
<tr>
	<td colspan=2><div id="PanelDetalleDeclaracion"></div></td>
</tr>
</table>

<script type="text/javascript">

	buscarDetalle = function(id) {
		row = $(this).getRowData(id);
	
		$("#PanellistaObservaciones").html(row.vobserv);
			
	    parameters = {
	        "name": "tblDetalleDeclaracion",
	        "procedure": "pl_function.listar_predios",
	        "print": "true",
	        "parameters": '{' +
	        '"p_mhresum":"' + row.mhresum + '",' +
	        '"p_cidpers":"' + row.cidpers + '"' +
	        '}'
	    };

	    optionPredio.caption = "&nbsp;&nbsp;&nbsp;Predios Registrados en la Declaraci\u00F3n Nro. " + row.vnrodoc;
	    ajaxDialog = false;
	    procesarProcedimientoJSON("PanelDetalleDeclaracion", "tblDetalleDeclaracion", optionPredio, parameters, bindkeysPredio);
	};

	optionPredio = {
        height: 140,
        width: 715,
        rowNum: 5,
        colNames: ['Predio', 'Direcci\u00F3n', 'Uso', 'mhresum', 'mpredio'],
        colModel: [
			{name: 'ccodpre', index:'ccodpre', width: 75, align: 'center'},
			{name: 'tnumero', index:'tnumero', width: 415},
			{name: 'vusogen', index:'vusogen', width: 180},
			{name: 'mhresum', index:'mhresum', width: 180},
			{name: 'mpredio', index:'mpredio', width: 180}
		],
		caption: "&nbsp;&nbsp;&nbsp;Predios Registrados en la Declaraci\u00F3n Nro. ",
        onSelectRow: function(id) {
	       row = $(this).getRowData(id);
        },
		ondblClickRow: function(rowid, iRow, iCol, e) {
            row = $(this).getRowData(rowid);
			
			parameters = {
	            "mperson": $("#lblCodigo").text(),
	            "vnombre": $("#lblNombre").text(),
	            "vdirecf": $("#lblDireccion").text(),
	            "mpredio": row.mpredio,
	            "mhresum": row.mhresum,
	            "cperiod": 'max'
	        };
			
			closeDialog('jqDialog1');
			
	        _post = $.post(path + "registro/verpredio", parameters);
	        _post.error(postError);
	        _post.success(function(request){
	            $("#panelRegistro").html(request);
	        });
		}
    };

	optionDeclaraciones = {
        height: 140,
        width: 438,
        rowNum: 5,
        colNames: [
            'Nro. Doc.',
            'F. Doc.',
            'Motivo',
            'Fec. Registro',
            'Observaci\u00F3n',
            'Cod. Persona'
        ],
        colModel: [
                   {name: 'vnrodoc', index:'vnrodoc', width: 75, align: 'center'},
                   {name: 'dfecdoc', index:'dfecdoc', width: 80, align: 'center'},
                   {name: 'vmotivo', index:'vmotivo', width: 238},
                   {name: 'mhresum', index:'mhresum', width: 100, hidden: true},
                   {name: 'vobserv', index:'vobserv', width: 100, hidden: true},
                   {name: 'cidpers', index:'cidpers', width: 100, hidden: true}
               ],
		caption: "&nbsp;&nbsp;&nbsp;Declaraciones Registradas",
       	onSelectRow: buscarDetalle
    };
    
	listarDeclaracion = function() {
		parameters = {
			"name": "tblListarDeclaracion",
			"print": "true",
			"procedure": "pl_function.listar_declaraciones",
			"parameters": '{' +
			'"p_cidpers":"<?php echo $this->cidpers; ?>"' +
			'}'
		};	
		
		procesar = function(requestData){
			options = $.extend(optionDeclaraciones, {
				data: requestData,
				datatype: "local"
			});
			procesarJSON("Panellistadeclaraciones", "tblListaDeclaracion", optionDeclaraciones, null, null);
			row = $("#tblListaDeclaracion").jqGrid('getRowData', 1);
			$("#tblListaDeclaracion").jqGrid('setSelection', row.vnrodoc);
		};
	
		procesarConsultaSubProceso("registrar", parameters, procesar, 'json');

	};

	listarobservacion = function() {
		parameters = {
		"name": "tblListarDobservacion",
		"print": "true",
		"procedure": "pl_function.listar_declaraciones",
		"parameters": '{' +
		'"p_cidpers":"<?php echo $this->cidpers; ?>"' +
		'}'
		};	
		
		processobv = function(requestData){
			options = $.extend(optionDeclaraciones, {
				data: requestData,
				datatype: "local"
			});
			procesarJSON("Panellistadeclaraciones", "tblListaDeclaracion", optionDeclaraciones, null, null);
		};
	
		procesarConsultaSubProceso("registrar", parameters, procesar, 'json');
	};

	$(document).ready(function(){
		listarDeclaracion();
	});
</script>