<div id="panelContribuyente" align="center" class="ui-widget ui-widget-content ui-corner-top" style="width: 1000px;margin: 3px;">
    <div class="ui-widget ui-state-default ui-corner-top ui-title">
        <label>Registro de Declaraci&oacute;n Jurada</label>
    </div>
    <table border="0" class="ui-table-panelLayout">
        <tr>
            <td style="width: 55px;">C&oacute;digo:</td>
            <td style="width: 75px;font-weight: bold;"><div id="lblCodigo"><?php echo $this->cidpers; ?></div></td>
            <td style="width: 75px; text-align: right; padding-right: 9px;">Nombre:</td>
            <td style="font-weight: bold;"><?php echo $this->vnombre; ?></td>
            <td style="width: 90px;" align="right" rowspan="2"><div class="ui-widget"><?php echo $this->util()->getPeriodos(); ?></div></td>
        </tr><tr>
            <td>Direcci&oacute;n:</td>
            <td colspan="3" style="font-weight: bold;"><?php echo $this->vdirecc; ?></td>
        </tr>
    </table>
</div>
<div id="panelControl" align="right" class="ui-widget ui-widget-content ui-corner-bottom" style="width: 1000px;margin: 3px;">
    <button id="btnRegistrarPredio">Registrar</button>
    <button id="btnCancelarPredio">Cancelar</button>
</div>
<div id="panelListaPredio" align="center" style="width: 99%;margin: 3px;">
    <table id="tblListaPredio"></table>
    <div id="tblListaPredio"></div>
</div>