<table style="width: 95%" align="center">
<tr>
	<td valign="top" style="width: 425px"><div id="Panellistadeclaraciones"></div></td>
	<td valign="top">
		<div class="ui-widget ui-widget-content ui-corner-all" style="width: 272px; height: 220px;">
			<div align="center" class="ui-widget ui-state-default ui-corner-top ui-title">
		    	<label>Observaciones</label>
			</div>
			<div id="PanellistaObservaciones"></div>
		</div>
	</td>
</tr>
<tr>
	<td colspan=2><div id="PanelDetalleDeclaracion"></div></td>
</tr>
</table>

<script type="text/javascript">

	isGridComplete = false;
	buscarDetalle = function(id) {
		row = $(this).getRowData(id);
	
		$("#PanellistaObservaciones").html(row.vobserv);
			
	    parameters = {
	        "name": "tblDetalleDeclaracion",
	        "procedure": "pl_function.listar_predios",
	        "print": "true",
	        "parameters": '{' +
	        '"p_mhresum":"' + row.mhresum + '",' +
	        '"p_cidpers":"' + row.cidpers + '"' +
	        '}'
	    };

	    optionPredio.caption = "&nbsp;&nbsp;&nbsp;Predios Registrados en la Declaraci\u00F3n Nro. " + row.vnrodoc;
	    ajaxDialog = isGridComplete;
	    procesarProcedimientoJSON("PanelDetalleDeclaracion", "tblDetalleDeclaracion", optionPredio, parameters, bindkeysPredio);
	    isGridComplete = false;
	};

	verPredioDeclaracion = function(rowid, iRow, iCol, e) {
        row = $(this).getRowData(rowid);
		
		parameters = {
            "mperson": $("#lblCodigo").text(),
            "vnombre": $("#lblNombre").text(),
            "vdirecf": $("#lblDireccion").text(),
            "mpredio": row.mpredio,
            "mhresum": row.mhresum,
            "cperiod": 'max'
        };
		
		closeDialog('jqDialog1');
		
        _post = $.post(path + "registro/verpredio", parameters);
        _post.error(postError);
        _post.success(function(request){
            $("#panelRegistro").html(request);
        });
	};
	
	optionPredio = {
        height: 140,
        width: 715,
        rowNum: 5,
        colNames: ['Predio', 'Direcci\u00F3n', 'Uso', 'Uso', 'mhresum', 'mpredio'],
        colModel: [
			{name: 'ccodpre', index:'ccodpre', width: 75, align: 'center'},
			{name: 'tnumero', index:'tnumero', width: 550},
			{name: 'vusogen', index:'vusogen', width: 30, hidden: true},
			{name: 'viconos', index:'viconos', width: 55, formatter:imageFormat, unformat:imageUnFormat, align:'center'},
			{name: 'mhresum', index:'mhresum', width: 180, hidden: true},
			{name: 'mpredio', index:'mpredio', width: 180, hidden: true}
		],
		caption: "&nbsp;&nbsp;&nbsp;Predios Registrados en la Declaraci\u00F3n Nro. ",
		ondblClickRow: verPredioDeclaracion
    };

	optionDeclaraciones = {
        height: 140,
        width: 438,
        rowNum: 5,
        colNames: [
            'Nro. Doc.',
            'F. Doc.',
            'Motivo',
            'Fec. Registro',
            'Observaci\u00F3n',
            'Cod. Persona'
        ],
        colModel: [
                   {name: 'vnrodoc', index:'vnrodoc', width: 75, align: 'center'},
                   {name: 'dfecdoc', index:'dfecdoc', width: 80, align: 'center'},
                   {name: 'vmotivo', index:'vmotivo', width: 238},
                   {name: 'mhresum', index:'mhresum', width: 100, hidden: true},
                   {name: 'vobserv', index:'vobserv', width: 100, hidden: true},
                   {name: 'cidpers', index:'cidpers', width: 100, hidden: true}
               ],
		caption: "&nbsp;&nbsp;&nbsp;Declaraciones Registradas",
       	onSelectRow: buscarDetalle
    };
    
	listarDeclaracion = function() {
		parameters = {
			"name": "tblListarDeclaracion",
			"print": "true",
			"procedure": "pl_function.listar_declaraciones",
			"parameters": '{' +
			'"p_cidpers":"<?php echo $this->cidpers; ?>"' +
			'}'
		};	
		
		procesar = function(requestData){
			options = $.extend(optionDeclaraciones, {
				data: requestData,
				datatype: "local",
				gridComplete: function(){
					isGridComplete = true;
					$("#tblListaDeclaracion").jqGrid('setSelection', 1, true);
				}
			});
			procesarJSON("Panellistadeclaraciones", "tblListaDeclaracion", optionDeclaraciones, null, null);
		};
	
		procesarConsultaSubProceso("registrar", parameters, procesar, 'json');

	};

	$(document).ready(function(){
		listarDeclaracion();
	});
</script>