
<div id="panelbusqueda" align="center" class="ui-widget ui-widget-content ui-corner-all "  style="width: 1000px;margin: 3px;">
    <div class="ui-widget ui-state-default ui-corner-top ui-title">
        <label>Predios</label>
    </div>
    <div id="dvbusqueda">
    <table border="0" width="650px">
          <tr>
              <td colspan="15" align="center">

          </tr>
          <tr>
                            <td>&nbsp;</td>
                            <td>C&oacute;digo Predial:</td>
                            <td></td>
                            <td>Centro Poblado:</td>
                            <td>&nbsp;</td>
                            <td>Via:</td>
                            <td>&nbsp;</td>
                            <td width="50">Nro:</td>
                            <td width="10">&nbsp;</td>
                            <td width="50">Mza:</td>
                            <td width="10">&nbsp;</td>
                            <td width="50">Lote:</td>
                            <td>&nbsp;</td>
                              <td rowspan="2" align="center">
                            <button id="btnbuscar">Buscar</button>              
                            </td>
            </tr>
            <tr id="panelPredio">
                            <td>&nbsp;</td>
                            <td><input class="ui-text" id="c_predial" maxlength="10" style="width:90px" /></td>
                            <td></td>
                            <td colspan="3"><input class="ui-text pnl" id="c_viacontrib" style="width:100%" /></td>
                            <td>&nbsp;</td>
                            <td width="50"><input class="ui-text pnl" id="c_nroviacontrib" style="width:100%" /></td>
                            <td width="10">&nbsp;</td>
                            <td width="50"><input class="ui-text pnl" id="c_mzacontrib" style="width:100%" /></td>
                            <td width="10">&nbsp;</td>
                            <td width="50"><input class="ui-text pnl" id="c_lotecontrib" style="width:100%" /></td>
                            <td>&nbsp;</td>
                            
             </tr>
		
    </table>
    </div>
    <div id="dvaccion"></div>
</div>
<div id="panelResultmPredio">
	<table id="tblResultmPredio"></table>
	<div id="ptblResultmPredio"></div>
</div>


<!-- --------------------------------------------------------------------------------------------------------------------	 -->