<script type="text/javascript" src="<?php echo $this->util()->getPath(); ?>js/app/ui/01_jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="<?php echo $this->util()->getPath(); ?>js/app/plupload/plupload.js"></script>
<script type="text/javascript" src="<?php echo $this->util()->getPath(); ?>js/app/plupload/plupload.gears.js"></script>
<script type="text/javascript" src="<?php echo $this->util()->getPath(); ?>js/app/plupload/plupload.silverlight.js"></script>
<script type="text/javascript" src="<?php echo $this->util()->getPath(); ?>js/app/plupload/plupload.flash.js"></script>
<script type="text/javascript" src="<?php echo $this->util()->getPath(); ?>js/app/plupload/plupload.browserplus.js"></script>
<script type="text/javascript" src="<?php echo $this->util()->getPath(); ?>js/app/plupload/plupload.html4.js"></script>
<script type="text/javascript" src="<?php echo $this->util()->getPath(); ?>js/app/plupload/plupload.html5.js"></script>

<input type="hidden"  id="dpredio"/>
<input type="hidden"  id="textfotos"/>
<div id="ajaxaca"></div>

<center>
<h1 style="font-size:16px;color:navy;" >Subir Fotos</h1>

<div id="container">
    <div id="filelist" ></div>
    <br />
    <a id="pickfiles" href="javascript:;">[Selecc. Fotos]</a>
    <br/> 
    <a id="uploadfiles" href="javascript:;">[Subir Fotos]</a>
</div>

</center>


<script type="text/javascript">

function $(id) {
	return document.getElementById(id);	
}


var uploader = new plupload.Uploader({
	runtimes : 'gears,html5,flash,silverlight,browserplus',
	browse_button : 'pickfiles',
	container: 'container',
	max_file_size : '10mb',
	url : 'upload',
	resize : {width : 320, height : 240, quality : 90},
	flash_swf_url : "<?php echo $this->util()->getPath(); ?>js/app/plupload.flash.swf",
	silverlight_xap_url : "<?php echo $this->util()->getPath(); ?>js/app/plupload.silverlight.xap",
	filters : [
		{title : "Image files", extensions : "jpg,gif,png"},
		{title : "Zip files", extensions : "zip"}
	]
});

uploader.bind('Init', function(up, params) {
	//$('filelist').innerHTML = "<div>Current runtime: " + params.runtime + "</div>";
});

uploader.init();

uploader.bind('FilesAdded', function(up, files) {
	var foto="";
	for (var i in files) {
		$('filelist').innerHTML += '<div id="' + files[i].id + '">' + files[i].name + ' (' + plupload.formatSize(files[i].size) + ') <b></b></div>';

		//foto= document.getElementById('textfotos').getAttribute('value');
		//$("#textfotos").val(foto+"*"+files[i].name);
		//alert(foto);
	}
});

uploader.bind('UploadProgress', function(up, file) {
	$(file.id).getElementsByTagName('b')[0].innerHTML = '<span>' + file.percent + "%</span>";
});

$('uploadfiles').onclick = function() {
	uploader.start();

	

	return false;
};



</script>
