<div id="forminstalacion" align="center">
	<table>
		 <tr>
			<td width="450"  align="center" valign='top'>
				<div class="ui-widget ui-state-default ui-corner-top ui-title">
					<label>Descripci&oacute;n de la Instalaci&oacute;n</label>
				</div>
				<div class="ui-widget-content ui-corner-bottom">
					<table align="left" cellspacing="5" style="margin: 3px;">
						<!--  <tr>
							<td width="140">&nbsp;Cod. Predio&nbsp;</td>
							<td width="35" ><input id="txt_instdpredio" class="ui-text" style="width: 100px; padding:2px;text-align:center; " value="" /></td>
							<td width="35" ><select style="width: 150px;" id="cboinstctipint"><?php echo $this->util()->getComboContenedor('1000000439', null); ?></select></td>
						<tr>
							<td width="140">&nbsp;Orden de Construcci&oacute;n&nbsp;</td>
							<td width="35"><input id="txt_instcnitems"  class="ui-text" style="width:100px; padding:2px;text-align:center; " value="" /></td>
						<tr>
							<td width="140">&nbsp;Decl. Jurada&nbsp;</td>
							<td width="35"><input id="txt_instcperiod"  class="ui-text" style="width:100px; padding:2px;text-align:center; " value="" /></td>
						<tr>
							<td width="140">&nbsp;Tipo de Ficha&nbsp;</td>
							<td width="35"><input id="txt_instctipdat"  class="ui-text" style="width:100px;padding:2px;text-align:center; "/></td>
						<tr>
							<td width="140">&nbsp;Nro. Decl. Jurada</td>
							<td width="35"><input id="txt_instvnrodoc"  class="ui-text" style="width:100px;padding:2px;text-align:center; "/></td>
						<tr>
							<td width="140">&nbsp;Fecha Decl. Jurada</td>
							<td width="35"><input id="txt_instdfecdoc"  class="ui-text" style="width:100px;padding:2px;text-align:center; "/></td>
						<tr>
							<td width="140">&nbsp;Motivo</td>
							<td width="35"><input id="txt_instcmotivo"  class="ui-text" style="width:100px;padding:2px;text-align:center; "/></td>
						</tr>
						<tr> 
							<td width="140">&nbsp;Tip. Documento</td>
							<td width="35"><input id="txt_instctipdoc"  class="ui-text" style="width:100px;padding:2px;text-align:center; "/></td>
						</tr>-->
						<tr>
							<td width="140">&nbsp;Nro. Pisos</td>
							<td width="35"><input id="txt_instcnumpis"  maxlength="2" class="ui-text ui-text-numeric" style="width:50px;padding:2px;text-align:center;" onkeypress="return validarnumeros(event);"/>&nbsp;&nbsp;<select id="cb_tipoinstalacion" style="width:190px;padding:2px"><?php echo $this->util()->getComboContenedor('1000000443', null); ?></select></td>
						</tr>
						<tr>
							<td width="140">&nbsp;Antiguedad</td>
							<td width="35"><input id="txt_instnantigu"  maxlength="3" class="ui-text ui-text-numeric"  style="width:50px;padding:2px;text-align:center;" onkeypress="return validarnumeros(event);"/></td>
						</tr>
						<tr>
							<td width="140">&nbsp;A&ntilde;o Construcci&oacute;n</td>
							<td width="35"><input id="txt_instcanocon"  class="ui-text"  maxlength="4" style="width:50px;padding:2px;text-align:center;" onkeypress="return validarnumeros(event);"/></td>
						</tr>
					<!-- </table>
				</div>
			</td>
			<td width="365" align="center" valign='top'>
				<div class="ui-widget ui-state-default ui-corner-top ui-title">
					<label>Descripci&oacute;n</label>
				</div>
				<div class="ui-widget-content ui-corner-bottom">
					<table align="left" cellspacing="5" style="margin: 3px;"> -->
						<tr>
							<td width="140">&nbsp;&nbsp;Unidad de Medida</td>
							<td width="35" ><select style="width: 150px;" id="cboinstctipint"><?php echo $this->util()->getComboContenedor('1000000439', null); ?></select></td>
						</tr>
						<tr>
							<td width="140">&nbsp;&nbsp;Ancho Instalaci&oacute;n</td>
							<td width="35"><input id="txt_instnvalanc" class="ui-text ui-text-numeric" style="width:50px;padding:2px; "/></td>
						</tr>
						<tr>
							<td width="140">&nbsp;&nbsp;Altura Instalaci&oacute;n</td>
							<td width="35"><input id="txt_instnvalalt" class="ui-text ui-text-numeric"   style="width:50px; padding:2px" value="" /></td>
						</tr>
						<tr>
							<td width="140">&nbsp;&nbsp;Largo Instalaci&oacute;n</td>
							<td width="35"><input id="txt_instnvallar" class="ui-text ui-text-numeric"  style="width:50px; padding:2px" value="" /></td>
						</tr>
						<tr>
							<td width="140">&nbsp;&nbsp;Descripci&oacute;n inst.</td>
							<td width="35"><input id="txt_instvdesint" class="ui-text"  style="width:300px" value="" /></td>
						</tr>
						<tr>
							<td width="140">&nbsp;&nbsp;Val. Instalaci&oacute;n</td>
							<td width="35"><input id="txt_instnvalins" class="ui-text ui-text-numeric"  style="width:50px" value="" /></td>
						</tr>
						<tr>
							<td width="450" colspan="2" align="right"><input  type="button" id="btnguardar" name="guardar" value="Aceptar"/>&nbsp;&nbsp;<input type="button" id="btncancelar" name="cancelar" value="Cancelar"/></td>
						</tr>
					</table>
				</div>
				
			</td>
		</tr>
	</table>
</div>


<script>


	 $("#btnguardar").button({
         icons: {primary:'ui-icon-disk'}
     }).bind('click', function(){
    	 isValid = true;
    	 $("#forminstalacion").find("input").each(function(){
 			if($(this).val().length ==0){
 				isValid = false;
 	            return;
 	        }
 		});
 		if(!isValid){
 		   openDialogWarning("Los campos deben estar llenos.", 380, 150);	
 		}else{
 			GuardaInstalacion();
 			//openDialogWarning("Los datos han sido guardados.", 380, 150);
 			 closeDialog('jqDialog1');
 			}
     });

	 $("#btncancelar").button({
         icons: {primary:'ui-icon-pencil'}
     }).bind('click', function(){
    	 closeDialog('jqDialog1');
    	 //  habilitarComponenteDetalle(false);
     });

	 GuardaInstalacion= function() {
		 indexRow = $("#ctblInstalacion").val();
			row = {
					idsigma:'01',
					dpredio:$("#txt_instdpredio").val(),
		    		cnitems:$("#txt_instcnitems").val(),
		            cperiod:$("#txt_instcperiod").val(),
		    		ctipdat:$("#txt_instctipdat").val(),      
		    		vnrodoc:$("#txt_instvnrodoc").val(),
		    		dfecdoc:$("#txt_instdfecdoc").val(),      
		    		cmotivo:$("#txt_instcmotivo").val(),
		    		ctipdoc:$("#txt_instctipdoc").val(),    
		    		cnumpis:$("#txt_instcnumpis").val(),
		    		nantigu:$("#txt_instnantigu").val(),      
		    		canocon:$("#txt_instcanocon").val(),
		    		nvalanc:$("#txt_instnvalanc").val(),  
		    		nvalalt:$("#txt_instnvalalt").val(),   
		    		nvallar:$("#txt_instnvallar").val(),  
		    		//ctipint:$("#txt_instctipint").val(), 
		    		vdesint:$("#txt_instvdesint").val(),
		    		nvalins:$("#txt_instnvalins").val(),    
		    		dafecta:''
			};
			if($("#tblInstalacion").jqGrid('addRowData', indexRow,row)) {
				$("#ctblInstalacion").val(indexRow + 1);
			} else {
				alert('Error no se pudo agregar');
			}
		};
	</script>