	<div id="forminstalacion" align="center">
	<table>
		 <tr>
			<td width="450"  align="center" valign='top'>
				<div class="ui-widget ui-state-default ui-corner-top ui-title">
					<label>Descripci&oacute;n de la Instalaci&oacute;n</label>
				</div>
				<div class="ui-widget-content ui-corner-bottom">
					<input id="txt_idsigma" type="hidden" value="" />
					<table style="margin: 3px;">
						<tr>
							<td width="140">Nro. Pisos</td>
							<td width="35">
								<input id="txt_instcnumpis"  maxlength="2" class="ui-text ui-text-numeric" style="width:50px;padding:2px;text-align:center;" onkeypress="return validarnumeros(event);"/>
							</td>
						</tr>
						<tr>
							<td width="140">Antiguedad</td>
							<td width="35"><input id="txt_instnantigu"  maxlength="3" class="ui-text ui-text-numeric"  style="width:50px;padding:2px;text-align:center;" onkeypress="return validarnumeros(event);"/></td>
						</tr>
						<tr>
							<td width="140">A&ntilde;o Construcci&oacute;n</td>
							<td width="35"><input id="txt_instcanocon"  class="ui-text"  maxlength="4" style="width:50px;padding:2px;text-align:center;" onkeypress="return validarnumeros(event);"/></td>
						</tr>
						<tr>
							<td width="140">Unidad de Medida</td>
							<td width="35" ><select style="width: 150px;" id="cboinstctipint"><?php echo $this->util()->getComboContenedor('1000000439', null); ?></select></td>
						</tr>
						<tr>
							<td width="140">Ancho</td>
							<td width="35"><input id="txt_instnvalanc" class="ui-text ui-text-numeric" style="width:50px;padding:2px; "/></td>
						</tr>
						<tr>
							<td width="140">Altura</td>
							<td width="35"><input id="txt_instnvalalt" class="ui-text ui-text-numeric"   style="width:50px; padding:2px" value="" /></td>
						</tr>
						<tr>
							<td width="140">Largo</td>
							<td width="35"><input id="txt_instnvallar" class="ui-text ui-text-numeric"  style="width:50px; padding:2px" value="" /></td>
						</tr>
						<tr>
							<td width="140">Descripci&oacute;n</td>
							<td width="35"><input id="txt_instvdesint" class="ui-text"  style="width:300px" value="" /></td>
						</tr>
						<tr>
							<td width="140">Val. Instalaci&oacute;n</td>
							<td width="35"><input id="txt_instnvalins" class="ui-text ui-text-numeric"  style="width:50px" value="" /></td>
						</tr>
						<tr>
							<td width="450" colspan="2" align="right">
								<button id="btnguardar">Aceptar</button>&nbsp;&nbsp;<button id="btncancelar">Cancelar</button>
							</td>
						</tr>
					</table>
				</div>
				
			</td>
		</tr>
	</table>
</div>

<!-- 
<select id="cb_tipoinstalacion" style="width:190px;padding:2px"><?php echo $this->util()->getComboContenedor('1000000443', null); ?></select>
 -->
 
<script>


	 $("#btnguardar").button({
         icons: {primary:'ui-icon-disk'}
     }).bind('click', function(){
    	 isValid = true;
    	 $("#forminstalacion").find("input").each(function(){
 			if($(this).val().length ==0){
 				isValid = false;
 	            return;
 	        }
 		});
 		if(!isValid){
 		   openDialogWarning("Los campos deben estar llenos.", 380, 150);	
 		}else{
 			GuardaInstalacion();
 			//openDialogWarning("Los datos han sido guardados.", 380, 150);
 			 closeDialog('jqDialog1');
 			}
     });

	 $("#btncancelar").button({
         icons: {primary:'ui-icon-pencil'}
     }).bind('click', function(){
    	 closeDialog('jqDialog1');
    	 //  habilitarComponenteDetalle(false);
     });
	    
	 GuardaInstalacion= function() {

		 indexRow = $("#ctblInstalacion").val();
			row = {};
			ids = $("#tblInstalacion").jqGrid('getDataIDs');
			gsr = $("#tblInstalacion").jqGrid('getGridParam', 'selrow');
			
			if(gsr){
				row = $("#tblInstalacion").jqGrid('getRowData', gsr);
			}
		// var actual= new Date();
	   //  var anyo= actual.getUTCFullYear();

	    row = $.extend(row, {
					idsigma:$("#txt_idsigma").val(),
					dpredio:$("#_dpredio").val(),
		    	//	cnitems:$("#txt_instcnitems").val(),
		            cperiod:$("#txtPeriodo").val(),
		    	//	ctipdat:$("#txt_instctipdat").val(),      
		    	//	vnrodoc:$("#txt_instvnrodoc").val(),
		    		dfecdoc:$("#txt_instdfecdoc").val(),      
		    	//	cmotivo:$("#txt_instcmotivo").val(),
		    	//	ctipdoc:$("#txt_instctipdoc").val(),    
		    		cnumpis:$("#txt_instcnumpis").val(),
		    		nantigu:$("#txt_instnantigu").val(),      
		    		canocon:$("#txt_instcanocon").val(),
		    		nvalanc:$("#txt_instnvalanc").val(),  
		    		nvalalt:$("#txt_instnvalalt").val(),   
		    		nvallar:$("#txt_instnvallar").val(),  
		    		ctipint:$("#cb_tipoinstalacion option:selected").val(), 
		    		vdesint:$("#txt_instvdesint").val(),
		    		nvalins:$("#txt_instnvalins").val(),    
		    	//	dafecta:''
			});
		console.log(row);
		_post = $.post(path + "registro/guardarinstalacion", row);
	    _post.success(function(data){
	    	optionInstalacion = $.extend(optionInstalacion, {data: data.data});
	    	procesarJSON("panelInstalacion", "tblInstalacion", optionInstalacion, null, function(){
	            $("#tblInstalacion").jqGrid('navGrid', '#ptblInstalacion', {edit:false, add:false, del:false, search:false, refresh:false});
	            $("#tblInstalacion").jqGrid('navButtonAdd', '#ptblInstalacion', btnInsertarInstalacion);
	            $("#tblInstalacion").jqGrid('navSeparatorAdd','#ptblInstalaciontblInstalacion');
	            $("#tblInstalacion").jqGrid('navButtonAdd','#ptblInstalacion', btnEditarInstalacion);
	            $("#tblInstalacion").jqGrid('navSeparatorAdd','#ptblInstalacion');
	            $("#tblInstalacion").jqGrid('navButtonAdd','#ptblInstalacion', btnEliminarInstalacion);
	        });
		});
	    _post.error(postError);
		};
	</script>