<div id="formLindero">
	<table >
		<tr>
		  <td><input id="idsigma" type="hidden" value="-1"/> </td>
		</tr>
		 <tr align="center">
			<td width="310">
				<div class="ui-widget ui-state-default ui-corner-top ui-title">
					<label>Linderos</label>
				</div>
				<div class="ui-widget-content ui-corner-bottom">
					<table cellspacing="5" style="margin: 3px;" class="ui-table-panelLayout">
					<tr>
							<td width="150">Tipo de Lindero</td>
							<td width="35" ><select style="width: 150px;" id="cboTipLindero"><?php echo $this->util()->getComboContenedor('1000000411', null); ?></select></td>
						</tr>
						<tr>
							<td width="150">Punto Cardinal</td>
							<td width="35" ><select style="width: 150px;" id="cboCardinal"><?php echo $this->util()->getComboContenedor('1000000415', null); ?></select></td>
						</tr>
						<tr>
							<td>Cod. Propiedad</td>
							<td><input id="txtcodpropie" class="ui-text" maxlength="10" style="width:70px; padding:2px;text-align:right;" value="" onkeypress="return validarnumeros(event);" /></td>
						</tr>
						<tr>
							<td>Ubicacion</td>
							<td><input id="txt_ubicacion" class="ui-text" style="width:350px;padding:2px;text-align:left;"/></td>
						</tr>
						<tr>
							<td>Contribuyente</td>
							<td><input id="txt_dpropie" class="ui-text" maxlength="10" style="width:70px; padding:2px;text-align:right;" value="" onkeypress="return validarnumeros(event);"/></td>
							<td>&nbsp;</td>
						</tr>
						<tr>
					 	<td>Nombre Propietario</td>
							<td><input id="txt_mpropie" class="ui-text" style="width:250px;padding:2px;"/></td>
						</tr>
						<tr>
						<td>idsigma</td>
							<td><input id="txt_idsigma" class="ui-text" style="width:250px;padding:2px;"/></td>
						</tr> 
						<tr>
							<td colspan="2" align="right"><button id="btnguardar">Aceptar</button>&nbsp;&nbsp;<button id="btncancelar">Cancelar</button></td>
						</tr>
					</table>
				</div>
			</td>
		</tr>
	</table>
</div>
<script type="text/javascript">


var Contrib = [
	{
		value: "1",
		label: "0000000189",
		desc: "PALOMINO MOLINA, TEOBALDO",
		icon: "jquery_32x32.png"
	},
	{
		value: "2",
		label: "0000000248",
		desc: "MALCA VERA, UBALDO",
		icon: "jqueryui_32x32.png"
	},
	{
		value: "3",
		label: "0000000354",
		desc: "BUENO ARIZA, NESTOR",
		icon: "sizzlejs_32x32.png"
	},
	{
		value: "4",
		label: "0000000158",
		desc: "GOMEZ OSORIO, IGNACIO",
		icon: "sizzlejs_32x32.png"
	}
];

var Pred = [
	{
		value: "1",
		label: "0000000148",
		desc: "AA.HH. CERRO LAS ANIMAS MZ.V1 LOTE 01",
		icon: "jquery_32x32.png"
	},
	{
		value: "2",
		label: "0000000176",
		desc: "ZONA TARAPACA MZ.F LOTE 05",
		icon: "jqueryui_32x32.png"
	},
	{
		value: "3",
		label: "0000000253",
		desc: "AA.HH. LA ENSENADA DE CHILLON MZ.J LOTE 15",
		icon: "sizzlejs_32x32.png"
	},
	{
		value: "4",
		label: "0000000179",
		desc: "ASOC.VIV. ROSA LUZ II ETAPA MZ.B LOTE 16",
		icon: "sizzlejs_32x32.png"
	}
];


	autocompletarporcod = function(id, data,llenar) {
		$(id).autocomplete({
			minLength: 0,
			source: data,
			select: function( event, ui ) {
				$(this).val(ui.item.label);
				$(llenar).val(ui.item.desc);

				return false;
			}
		}).data("autocomplete")._renderItem = function(ul, item) {
			return $("<li></li>")
				.data("item.autocomplete", item)
				.append("<a><b>" + item.label + "</b><br>" + item.desc + "</a>")
				.appendTo(ul);
		};
	};

	autocompletarpordesc = function(id, data,llenar) {
		$(id).autocomplete({
			minLength: 0,
			source: data,
			select: function( event, ui ) {
				$(this).val(ui.item.desc);
				$(llenar).val(ui.item.label);

				return false;
			}
		}).data("autocomplete")._renderItem = function(ul, item) {
			return $("<li></li>")
				.data("item.autocomplete", item)
				.append("<a><b>" + item.desc + "</b><br>" + item.label + "</a>")
				.appendTo(ul);
		};
	};
	

	$(function() {
		autocompletarporcod("#txt_dpropie", Contrib ,"#txt_mpropie");
		autocompletarporcod("#txtcodpropie", Pred ,"#txt_ubicacion");

		autocompletarpordesc("#txt_mpropie", Contrib ,"#txt_dpropie");
		autocompletarpordesc("#txt_ubicacion", Pred ,"#txtcodpropie");
	/*	autocompletar("#txt_pisomuro", projects);
		autocompletar("#txt_pisotecho", projects);
		autocompletar("#txt_pisopisos", projects);
		autocompletar("#txt_pisopuertaventana", projects);
		autocompletar("#txt_pisorevestimiento", projects);
		autocompletar("#txt_pisobanio", projects);
		autocompletar("#txt_pisoinstalaciones", projects);*/
	});

//........................................................................................

	$("#btnguardar").button({
		icons: {primary:'ui-icon-disk'}
	}).bind('click', function(){
		isValid = true;
		$("#formLindero").find("input").each(function(){
			if($(this).val().length ==0){
				isValid = false;
	            return;
	        }
		});
	//	if(!isValid){
	//	   openDialogWarning("Los campos deben estar llenos.", 380, 150);	
	//	}else{
			GuardaLindero();
			// openDialogWarning("Los datos han sido guardados.", 380, 150);
			closeDialog('jqDialog1');
	//		}
		
	});

	$("#btncancelar").button({
		icons: {primary:'ui-icon-pencil'}
	}).bind('click', function(){
		closeDialog('jqDialog1');
	});



	
	GuardaLindero= function() {
	
		indexRow = $("#ctblLindero").val();
			
		row = {};

		ids = $("#tblLindero").jqGrid('getDataIDs');
		
		for(var i=0; i < ids.length; i++) {
			console.log(ids[i]); 
		}

		
		gsr = $("#tblLindero").jqGrid('getGridParam','selrow');
		if(gsr){
			row = $("#tblLindero").jqGrid('getRowData', gsr);
		}

		console.log('EE->'+gsr);
				
		row = $.extend(row, {
				vptocar: $('#cboCardinal option:selected').text(), // $('#cboTipLindero").text();
				vtiplin: $('#cboTipLindero option:selected').text(),
				ccodpre: $("#txtcodpropie").val(),
				vdirecc: $("#txt_ubicacion").val(),
				mperson: $("#txt_dpropie").val(),
				vnombre: $("#txt_mpropie").val(),
				cptocar: $("#cboCardinal").val(),
				ctiplin: $("#cboTipLindero").val(),
				idsigma: $("#txt_idsigma").val(),
				dpredio: '0000000001', // Falta setear
				ddatetm: '2013-05-14 20:00:00'
		});
		
		console.log(row);
		
		
		if(parseInt(row.idsigma) > -1) {
			// debugger
			if(!$("#tblLindero").jqGrid('setRowData', indexRow, row)) {
				alert('Error no se pudo editar');
			}
		} else {
			if($("#tblLindero").jqGrid('addRowData', indexRow, row)) {
				$("#ctblLindero").val(indexRow + 1);
			} else {
				alert('Error no se pudo agregar');
			}
		}


	


		//	echo json_encode(row, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP);


	
	//		executeSelect(pl_function.guardar_mlindero, $parameters = null);
	};




</script>