<table border="0" cellpadding="0"  cellspacing="0" style="width: 1000px;margin: 3px;">
    <tr>
        <td colspan="2">
            <div id="panelContribuyente" align="center" class="ui-widget ui-widget-content ui-corner-top" style="width: 100%;">
                <div class="ui-widget ui-state-default ui-corner-top ui-title">
                    <label>Registro de Declaraci&oacute;n Jurada</label>
                </div>
                <table border="0" class="ui-table-panelLayout">
                    <tr>
                        <td style="width: 40px;">C&oacute;digo:</td>
                        <td style="width: 75px;font-weight: bold;"><div id="lblCodigo">codigo</div></td>
                        <td style="width: 60px; text-align: right; padding-right: 4px;">Nombre:</td>
                        <td style="font-weight: bold;" colspan="2">nombre</td>
                        <td style="width: 90px;" align="right" rowspan="3"><div class="ui-widget"><?php echo $this->util()->getPeriodos(); ?></div></td>
                    </tr><tr>
                        <td style="text-align: right; padding-right: 4px;" colspan="3">Direcci&oacute;n Fiscal:</td>
                        <td style="font-weight: bold;" colspan="2">direccion</td>
                    </tr><tr>
                        <td>Predio:</td>
                        <td style="font-weight: bold;"><div id="lblPredio">predio</div></td>
                        <td style="text-align: right; padding-right: 4px;">Direcci&oacute;n:</td>
                        <td style="font-weight: bold;">direccion</td>
                        <td style="width: 30px;"><button id="btnBuscarDireccion" style="line-height: 25px;height: 25px;" title="Buscar predio" /></td>
                    </tr>
                </table>
            </div>
        </td>
    </tr>
    <tr>
        <td style="padding-top: 3px;padding-right: 3px;">
            <div id="panelValor" align="center" class="ui-widget ui-widget-content" style="width: 100%;">
                <table border="0" align="center" class="ui-table-panelLayout" style="width: 470px;">
                    <tr>
                        <td style="width: 55px; text-align: center;">Arancel</td>
                        <td style="width: 100px; text-align: center;">V. Terreno</td>
                        <td style="width: 100px; text-align: center;">V. Construcci&oacute;n</td>
                        <td style="width: 100px; text-align: center;">V. Instalaci&oacute;n</td>
                        <td style="width: 100px; text-align: center;">Autovaluo</td>
                    </tr>
                    <tr>
                        <td style="font-weight: bold; text-align: center;">Valor</td>
                        <td style="font-weight: bold; text-align: center;">Valor</td>
                        <td style="font-weight: bold; text-align: center;">Valor</td>
                        <td style="font-weight: bold; text-align: center;">Valor</td>
                        <td style="font-weight: bold; text-align: center;">Valor</td>
                    </tr>
                </table>
            </div>
        </td>
        <td style="padding-top: 3px;padding-left: 2px;">
            <div id="panelUsuario" align="center" class="ui-widget ui-widget-content" style="width: 100%;">
                <table border="0" align="center" class="ui-table-panelLayout" style="width: 470px;">
                    <tr>
                        <td>Modificado por <b>quispe</b> el <b>27/03/2012</b></td>
                    </tr>
                    <tr>
                        <td>Ultimo recalculo el <b>27/03/2012</b></td>
                    </tr>
                </table>
            </div>
        </td>
    </tr>
    <tr>
        <td colspan="2" style="padding-top: 3px;">
            <div id="panelControl" align="right" class="ui-widget ui-widget-content ui-corner-bottom" style="width: 100%;">
                <button id="btnEditarPredio">Editar</button>
                <button id="btnGrabarPredio">Grabar</button>
                <button id="btnCancelarPredio">Cancelar</button>
            </div>
        </td>
    </tr>
</table>
<div id="panelDetallePredio">
    <div id="tabsDetallePredio" style="width: 995px; margin: 3px;">
        <ul>
            <li><a href="#predioDescripcion">Descripci&oacute;n</a></li>
            <li><a href="#predioPiso">Pisos</a></li>
            <li><a href="#predioInstalacion">Instalaci&oacute;n</a></li>
            <li><a href="#predioInafectacion">Inafectaci&oacute;n</a></li>
        </ul>
        <div style="overflow-y: auto; overflow-x: hidden; height:300px; padding: 2px;" id="predioDescripcion">
            <?php echo $this->render("registro/verpredio/descripcion.php"); ?>
        </div>
        <div style="overflow-y: auto; overflow-x: hidden; height:300px; padding: 2px;" id="predioPiso">
            <?php echo $this->render("registro/verpredio/piso.php"); ?>
        </div>
        <div style="overflow-y: auto; overflow-x: hidden; height:300px; padding: 2px;" id="predioInstalacion">
            <?php echo $this->render("registro/verpredio/instalacion.php"); ?>
        </div>
        <div style="overflow-y: auto; overflow-x: hidden; height:300px; padding: 2px;" id="predioInafectacion">
            <?php echo $this->render("registro/verpredio/inafectacion.php"); ?>
        </div>
    </div>
</div>