<?php
                          
                          $doc=new DOMDocument();						
                        $direccion="Puente Piedra, Lima, Peru";
                        //$direccion=$datos[0]["direccion"]." "."puente piedra";
							$xml="http://maps.googleapis.com/maps/api/geocode/xml?address=".$direccion."&sensor=true";
     //echo $xml;
                            $doc->load($xml);

							$persona=$doc->getElementsByTagName("result");

							foreach ($persona as $p)
							{
									$latitud=$p->getElementsByTagName("lat");
									$latitud=$latitud->item(0)->nodeValue;
									
									$longitud=$p->getElementsByTagName("lng");
									$longitud=$longitud->item(0)->nodeValue;
									
									
									
									//echo "latitud=".$latitud." - longitud=".$longitud."<br>";
							}
							
                          ?>
<script type="text/javascript"
    src="https://maps.google.com/maps/api/js?sensor=true">
</script>
<script type="text/javascript">

	var geocoder = new google.maps.Geocoder();

	function geocodePosition(pos) {
	  geocoder.geocode({
		latLng: pos
	  }, function(responses) {
		if (responses && responses.length > 0) {
		  updateMarkerAddress(responses[0].formatted_address);
		} else {
		  updateMarkerAddress('Cannot determine address at this location.');
		}
	  });
	}

	function updateMarkerStatus(str) {
	  document.getElementById('markerStatus').innerHTML = str;
	}

	function updateMarkerPosition(latLng) {
	  document.getElementById('info').innerHTML = [
		latLng.lat(),
		latLng.lng()
	  ].join(', ');
	}

	function updateMarkerAddress(str) {
	  document.getElementById('address').innerHTML = str;
	}

   function cargar_mapa()
    {
		$("#txt_nlatitu").val(<?php echo $latitud;?>);
		$("#txt_nlongit").val(<?php echo $longitud;?>);
		
		
		 var latLng = new google.maps.LatLng(<?php echo $latitud;?>, <?php echo $longitud;?>);
		 
        var myOptions = {
          scaleControl: true,
          center: new google.maps.LatLng(<?php echo $latitud;?>, <?php echo $longitud;?>),
          zoom: 15,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };

        var map = new google.maps.Map(document.getElementById('map_canvas'),
            myOptions);

        var marker = new google.maps.Marker({
          map: map,
		  title: "<?php echo $direccion;?>",
		  draggable: true,
          position: map.getCenter()
        });
        var infowindow = new google.maps.InfoWindow();
        infowindow.setContent('<b>Mapa</b>');
        google.maps.event.addListener(marker, 'click', function() {
            infowindow.open(map, marker);
        });
		
		  // Update current position info.
		  updateMarkerPosition(latLng);
		  geocodePosition(latLng);
		  
		  // Add dragging event listeners.
		  google.maps.event.addListener(marker, 'dragstart', function() {
			updateMarkerAddress('Dragging...');
		  });
		  
		  google.maps.event.addListener(marker, 'drag', function() {
			updateMarkerStatus('Dragging...');
			updateMarkerPosition(marker.getPosition());
		  });
		  
		  google.maps.event.addListener(marker, 'dragend', function() {
			updateMarkerStatus('Drag ended');
			geocodePosition(marker.getPosition());
		  });
   
		   

		  google.maps.event.addListener(map, 'zoom_changed', function() {
			    var zoomLevel = map.getZoom();
			    
			    //infowindow.setContent('Zoom: ' + zoomLevel);

			    $("#txt_nzoom").val(zoomLevel);

			    //alert(zoomLevel);
			    
		  });
      }

      google.maps.event.addDomListener(window, 'load', cargar_mapa);

</script>



<div id="formPredioMantt">
	<table border="0">
		 <tr align="center">
			<td width="310">
				<div class="ui-widget ui-state-default ui-corner-top ui-title">
					<label>Predio</label>
				</div>
				<div class="ui-widget-content ui-corner-bottom">
					<table cellspacing="5" style="margin: 3px;" class="ui-table-panelLayout" border="0">
						<tr> 
						   <td colspan="4">Datos de la Via y Centro Poblado: </td> 	
						</tr>
						
						<tr>	
						    <td colspan="4"><select id="cbocentrpob"> </select> </td>
						</tr>
						
						<tr>	
						  <td>Codigo:</td><td><input id="txtnumero" class="ui-text"  ReadOnly />  </td>
						   <td>Cod.Catastral:</td><td><input id="txtczoncat" class="ui-text" style="width:50px;" />  <input id="txtcmzacat" class="ui-text" style="width:50px;"  />  <input id="txtcseccat" class="ui-text" style="width:50px;"  />  <input id="txtcltecat" class="ui-text" style="width:50px;"  /> <input id="txtcundcat" class="ui-text" style="width:50px;"  />  </td>
						</tr>
					
						<tr>	
						  <td>N&uacute;mero:</td><td><input id="txtnumero" class="ui-text" />  </td>
						   <td>Departamento:</td><td><input id="txtnumero" class="ui-text" />  </td>
						</tr>
						
						<tr>	
						  <td>Interior:</td><td><input id="txtnumero" class="ui-text" />  </td>
						  <td>Letra:</td><td><input id="txtnumero" class="ui-text" />  </td>
						</tr>
						
						<tr>	
						  <td>Estacionamiento:</td><td><input id="txtnumero" class="ui-text" />  </td>
						  <td>Deposito:</td><td><input id="txtnumero" class="ui-text" />  </td>
						</tr>
						
						<tr>	
						  <td>Manzana:</td><td><input id="txtnumero" class="ui-text" />  </td>
						  <td>Lote:</td><td><input id="txtnumero" class="ui-text" />  </td>
						</tr>
						
						<tr>	
						  <td>Block:</td><td><input id="txtnumero" class="ui-text" />  </td>
						  <td>Seccion:</td><td><input id="txtnumero" class="ui-text" />  </td>
						</tr>
						
						<tr>	
						  <td >Unid. Inmobilaria:</td><td><input id="txtnumero" class="ui-text" />  </td>
						
						</tr>
						
						<tr>
							<td></td>
							<td> <input id="txt_idsigma" type="hidden" class="ui-text" style="width:250px;padding:2px;"/>
								 <input id="txt_nlatitu" type="hidden" class="ui-text" style="width:250px;padding:2px;"/>
								 <input id="txt_nlongit" type="hidden" class="ui-text" style="width:250px;padding:2px;"/>
								 <input id="txt_nzoom" type="hidden" class="ui-text" style="width:250px;padding:2px;"/>							
							</td>
						</tr> 
						<tr>
							<td colspan="4" align="right"><button id="btnguardar">Aceptar</button>&nbsp;&nbsp;<button id="btncancelar">Cancelar</button></td>
						</tr>
						<tr>
						<td colspan="4"><div id="map_canvas" style="width:800px; height:500px;"></div>
						  <div id="infoPanel">
						    <b>Marker status:</b>
						    <div id="markerStatus"><i>Click and drag the marker.</i></div>
						    <b>Current position:</b>
						    <div id="info"></div>
						    <b>Closest matching address:</b>
						    <div id="address"></div>
						  </div></td>
						</tr>
					</table>
				</div>
			</td>
		</tr>
	</table>
</div>
<br/>
