<style>
    .ui-autocomplete {
        max-height: 218px;
        overflow-y: auto;
        /* prevent horizontal scrollbar */
        overflow-x: hidden;
        /* add padding to account for vertical scrollbar */
        padding-right: 8px;
    }

    /* IE 6 doesn't support max-height
    * we use height instead, but this forces the menu to always be this tall
    */
    * html .ui-autocomplete {
        height: 218px;
    }
</style>
<script type="text/javascript">

guardar = function() {
	row = { 
			idsigma: $("#txt_idsigma").val(),
			mviadis: $("#txt_mviadis").val(),
			dnumero: $("#txtnumero").val(),
			dinteri: $("#txtinterior").val(),
			dletras: $("#txtletra").val(),        			
			ddepart: $("#txtdepart").val(),
			destaci: $("#txtestacio").val(),  
			ddeposi: $("#txtdeposito").val(),     
			drefere: $("#txtreferencia").val(),
			dmanzan: $("#txtmanzana").val(),     
			dnlotes: $("#txtlote").val(),
			ccatast: 0,    
			cplanos: 0,
			ctipmer: "0",      
			dnummer: "0",
			cdiscat: "0",		
			czoncat: $("#txtczoncat").val(),      
			cmzacat: $("#txtcmzacat").val(),
			cseccat: $("#txtcseccat").val(),
			cltecat: $("#txtcltecat").val(), 
			cundcat: $("#txtcundcat").val(),
			dbloque: $("#txtbloque").val() ,
			dseccio: $("#txtseccion").val(),
			dunidad: $("#txtunidinmob").val(),
			mpoblad: $("#txt_mpoblad").val(),
			vdirpre: $("#txtviacentrpob").val()+' '+ $("#txtnumero").val()+' ' + $("#txtinterior").val()+' ' + $("#txtletra").val()+' '+ $("#txtdepart").val() +' '+  $("#txtestacio").val() +' '+  $("#txtdeposito").val() +' '+  $("#txtreferencia").val() +' '+  $("#txtmanzana").val() +' '+ $("#txtlote").val() , 
			nestado: "1" ,
			ccodpre: 0 ,
			//ctippre: '1000000090' ,
			ctippre: $("#cbotipopredio").val(),
			idanexo: 0 , 
			ccodcuc: 0,
			nlatitu: $("#txt_nlatitu").val() ,
			nlongit: $("#txt_nlongit").val() ,
			nzoom: $("#txt_nzoom").val()
			 
	};

	_post = $.post(path + "registro/guardarmpredio", row);
    _post.success(function(data){
    	
		openDialogWarning("Los datos han sido guardados.", 380, 150);
		  
		closeDialog('jqDialog1');
		
		location.reload();
	});
    //_post.error(postError);	
};


    var jsonVias = <?php echo json_encode($this->mviascp); ?>,
        ccodvia = '';
        cpoblad = '';

    $("#txtviacentrpob").autocompleteCategory({
        delay: 0,
        source: jsonVias,
        minLength: 4,
        select: function(event, ui) {
            ccodvia = ui.item.ccodvia;
            cpoblad = ui.item.mpoblad;

            $("#txt_mviadis").val(ccodvia);
            $("#txt_mpoblad").val(cpoblad);
        },
        change: function(event, ui) {
            if(ui.item) {
                ccodvia = ui.item.ccodvia;
            } else {
                if($(this).val().length > 0) {
                    openDialogWarning("El valor ingresado no esta en la lista de elementos.", 380, 150);
                }
            }
        }
    });

      $("#btnguardar").button({
        icons: {primary:'ui-icon-disk'}
        
    }).bind('click', function(){
    	isValid = true;

    	if ($("#cbotipopredio").val()=='9999999999'){
    		openDialogWarning("Seleccione el tipo de Predio.", 380, 150);	
			isValid = false;
       		return;
    	}
    	
    	if(($("#txt_mviadis").val().length ==0) && ($("#txt_mpoblad").val().length ==0)  ) {
			openDialogWarning("Busque una Via y Centro Poblado.", 380, 150);	
			isValid = false;
       		return;
   		}

		if(($("#txtnumero").val().length ==0) && ($("#txtmanzana").val().length ==0) && ($("#txtlote").val().length ==0)  ) {
			openDialogWarning("Ingrese el numero o la manzana y el lote.", 380, 150);	
			isValid = false; 
       		return;
   		} 
   
	
	if(!isValid) {
			openDialogWarning("Los campos deben estar llenos.", 380, 150);	
			return false;
	} else {
	         guardar();  
	} 
		
    });

      $("#btncancelar").button({
        icons: {primary:'ui-icon-arrowreturnthick-1-w'}
    }).bind('click', function(){
    	closeDialog('jqDialog1');
    });

</script>

<div id="formPredioMantt">
	<table border="0">
		 <tr align="center">
			<td width="310">
				<div class="ui-widget ui-state-default ui-corner-top ui-title">
					<label>Predio</label>
				</div>
				<div class="ui-widget-content ui-corner-bottom">
					<table cellspacing="5" style="margin: 3px;" class="ui-table-panelLayout" border="0">
					    <tr>
					      <td colspan="1">Tipo Predio:</td><td colspan="3"><select id="cbotipopredio"><?php echo $this->util()->getComboContenedor('1000000089', null); ?></select> </td>
					    </tr>
						<tr> 
						   <td colspan="4">Centro Poblado          y            Via: </td> 	
						</tr>
						
						<tr>	
						    <td colspan="4"><input id="txtviacentrpob" class="ui-text pnl" style="width:100%"/> </td>
						</tr>
						
						<tr>	
						  <td>Codigo:</td><td><input id="txtcodpre" class="ui-text ui-text-disable"  ReadOnly />  </td>
						   <td>Cod.Catastral:</td><td><input id="txtczoncat" class="ui-text" style="width:50px;" />  <input id="txtcmzacat" class="ui-text" style="width:50px;"  />  <input id="txtcseccat" class="ui-text" style="width:50px;"  />  <input id="txtcltecat" class="ui-text" style="width:50px;"  /> <input id="txtcundcat" class="ui-text" style="width:50px;"  />  </td>
						</tr>
					
						<tr>	
						  <td>N&uacute;mero:</td><td><input id="txtnumero" class="ui-text"  />   </td>
						   <td>Departamento:</td><td><input id="txtdepart" class="ui-text" />  </td>
						</tr>
						
						<tr>	
						  <td>Interior:</td><td><input id="txtinterior" class="ui-text" />  </td>
						  <td>Letra:</td><td><input id="txtletra" class="ui-text" />  </td>
						</tr>
						
						<tr>	
						  <td>Estacionamiento:</td><td><input id="txtestacio" class="ui-text" />  </td>
						  <td>Deposito:</td><td><input id="txtdeposito" class="ui-text" />  </td>
						</tr>
						
						<tr>	
						  <td>Manzana:</td><td><input id="txtmanzana" class="ui-text" />  </td>
						  <td>Lote:</td><td><input id="txtlote" class="ui-text" />  </td>
						</tr>
						
						<tr>	
						  <td>Block:</td><td><input id="txtbloque" class="ui-text" />  </td>
						  <td>Seccion:</td><td><input id="txtseccion" class="ui-text" />  </td>
						</tr>
						
						<tr>	
						  <td >Unid. Inmobilaria:</td><td><input id="txtunidinmob" class="ui-text" />  </td>
						
						</tr>

						<tr>	
						  <td >Referencia :</td><td colspan="3"><input id="txtreferencia" class="ui-text" style="width:100%" />  </td>
						
						</tr>

						
						
						<tr>
							<td></td>
							<td> <input id="txt_idsigma" type="hidden" class="ui-text" style="width:250px;padding:2px;"/>
								<input id="txt_mviadis" type="hidden" class="ui-text" style="width:250px;padding:2px;"/>
								<input id="txt_mpoblad" type="hidden" class="ui-text" style="width:250px;padding:2px;"/>
								 <input id="txt_nlatitu" type="hidden" class="ui-text" style="width:250px;padding:2px;" value='-11.875965758844075'/>
								 <input id="txt_nlongit" type="hidden" class="ui-text" style="width:250px;padding:2px;" value='-77.08266639709473'/>
								 <input id="txt_nzoom" type="hidden" class="ui-text" style="width:250px;padding:2px;" value=15 />							
							</td>
						</tr> 
						<tr>
							<td colspan="4" align="right"><button id="btnguardar" name="btnguardar">Aceptar</button>&nbsp;&nbsp;<button id="btncancelar">Cancelar</button></td>
						</tr>
						<tr>
						<td colspan="4"><div id="map_canvas" style="width:800px; height: 280px;"></div>
						  <div id="infoPanel">
<!--						    <b>Marker status:</b>-->
						    <div id="markerStatus" style="visibility:hidden;"><i>Click and drag the marker.</i></div>
<!--						    <b>Current position:</b>-->
						    <div id="info" style="visibility:hidden;"></div>
						    <b>Direcci&oacute;n Actual:</b>
						    <div id="address"></div>
						  </div></td>
						</tr>
					</table>
				</div>
			</td>
		</tr>
	</table>
</div>
<br/>
 



<script type="text/javascript">



      $(document).ready(function() {
 
		$("#txtnumero").numeric(
				{ decimal : "," }
		);
		 
      });

</script>
