<input type="hidden" id="_mhresum" value="<?php echo $this->p_mhresum; ?>" />
<input type="hidden" id="_mpredio" value="<?php echo $this->p_mpredio; ?>" />
<input type="hidden" id="_dpredio" value="<?php echo $this->mpredio["dpredio"]; ?>" />
<input type="hidden" id="ccodpre" />
<div  id="ajaxaca" style="visibility:hidden;" ></div>
<div  id="ajaxaca2" style="visibility:hidden;" ></div>
<table style="width: 1000px; margin: 3px;">
    <tr>
        <td colspan="2">
            <div id="panelContribuyente" align="center" class="ui-widget ui-widget-content ui-corner-top" style="width: 100%;">
                <div class="ui-widget ui-state-default ui-corner-top ui-title">
                    <label>Registro de Declaraci&oacute;n Jurada</label>
                </div>
                <table class="ui-table-panelLayout">
                    <tr>
                        <td style="width: 40px;">C&oacute;digo:</td>
                        <td style="width: 75px;font-weight: bold;"><div id="lblCodigo"><?php echo $this->mperson; ?></div></td>
                        <td style="width: 60px; text-align: right; padding-right: 4px;">Nombre:</td>
                        <td style="font-weight: bold;" colspan="2"><div id="lblNombre"><?php echo $this->vnombre; ?></div></td>
                        <td style="width: 110px;" align="right" rowspan="3">
                        	<div class="ui-widget" style="text-align: center;">
                        		Declaraci&oacute;n Nro.
                        		<br/>
                        		<div style="font-weight: bold;"><?php echo $this->mpredio["vnrodoc"]; ?></div>
                        		<br/>
                        		<?php echo $this->util()->getPeriodosDeclarado($this->p_mhresum, $this->p_cperiod); ?>
                        	</div>
                        </td>
                    </tr><tr>
                        <td style="text-align: right; padding-right: 4px;" colspan="3">Direcci&oacute;n Fiscal:</td>
                        <td style="font-weight: bold;" colspan="2"><div id="lblDireccionFiscal"><?php echo $this->vdirecf; ?></div></td>
                    </tr><tr>
                        <td>Predio:</td>
                        <td style="font-weight: bold;"><div id="lblPredio"><div id="lblPredio"><?php echo $this->mpredio["ccodpre"]; ?></div></div></td>
                        <td style="text-align: right; padding-right: 4px;">Direcci&oacute;n:</td>
                        <td style="font-weight: bold;"><div id="lblDireccion"><?php echo $this->mpredio["vdirpre"]; ?></div></td>
                        <td style="width: 30px;"> 
                        		<button id="btnBuscarDireccion" style="line-height: 25px;height: 25px;" title="Buscar predio" ></button>
                        </td>
                    </tr>
                </table>
            </div>
        </td>
    </tr>
    <tr>
        <td style="padding-top: 3px;padding-right: 3px;">
            <div id="panelValor" align="center" class="ui-widget ui-widget-content" style="width: 100%;height: 100%;">
                <table align="center" class="ui-table-panelLayout" style="width: 470px;">
                    <tr>
                        <td style="width: 55px; text-align: center;">Arancel</td>
                        <td style="width: 100px; text-align: center;">V. Terreno</td>
                        <td style="width: 100px; text-align: center;">V. Construcci&oacute;n</td>
                        <td style="width: 100px; text-align: center;">V. Instalaci&oacute;n</td>
                        <td style="width: 100px; text-align: center;">Autovaluo</td>
                    </tr>
                    <tr>
                        <td style="font-weight: bold; text-align: center;"><div id="lblArancel"><?php echo $this->mpredio["narance"]; ?></div></td>
                        <td style="font-weight: bold; text-align: center;"><div id="lblValorTerreno"><?php echo $this->mpredio["nvalter"]; ?></div></td>
                        <td style="font-weight: bold; text-align: center;"><div id="lblValorConstruccion"><?php echo $this->mpredio["nvalpis"]; ?></div></td>
                        <td style="font-weight: bold; text-align: center;"><div id="lblValorInstalacion"><?php echo $this->mpredio["nvalins"]; ?></div></td>
                        <td style="font-weight: bold; text-align: center;"><div id="lblAutovaluo"><?php echo $this->mpredio["nvalafe"]; ?></div></td>
                    </tr>
                </table>
            </div>
        </td>
        <td style="padding-top: 3px;padding-left: 2px;">
            <div id="panelUsuario" align="center" class="ui-widget ui-widget-content" style="width: 100%;height: 100%;">
                <table align="center"  class="ui-table-panelLayout" style="width: 470px;">
                    <tr>
                        <td>Modificado por <b><span id="lblUsuario"><?php echo $this->mpredio["vusernm"]; ?></span></b> el <b><span id="lblFechaModificacion"><?php echo $this->mpredio["ddatetm"]; ?></span></b></td>
                    </tr>
                    <tr>
                        <td>Ultimo recalculo el <b><span id="lblFechaProceso"><?php echo $this->mpredio["dafecta"]; ?></span></b></td>
                    </tr>
                </table>
            </div>
        </td>
    </tr>
    <tr>
        <td colspan="2" style="padding-top: 3px;">
            <div id="panelControl" align="right" class="ui-widget ui-widget-content ui-corner-bottom" style="width: 100%;">
            	<button id="btnValorPredio" style="display: none">Valores del predio</button>
            	<button id="btnImprimir">Imprimir</button>
            	<!-- http://127.0.0.1:8080/titania_report/index.jsp?reporte=Report_Completo&opt=p_mhresum^-1|p_cperiod^-1|p_ccodpre^-1|p_mperson^0000000158 -->
            	<button id="btnFinalizar">Finalizar</button>
                <button id="btnCancelarPredio">Cancelar</button>
            </div>
        </td>
    </tr>
</table>
<div id="panelDetallePredio">
    <div id="tabsDetallePredio" style="width: 995px; margin: 3px;">
        <ul>
            
            <li id="tabPredioDescripcion"><a href="#predioDescripcion">Descripci&oacute;n</a></li>
            <li id="tabPredioLindero"><a href="#predioLindero">Lindero</a></li>
<!--            <li id="tabPredioRustico"<?php echo ($this->mpredio["ctippre"]!='1000000091'? ' style="display:none;"': '')?>><a href="#predioRustico">Rustico</a></li>-->
            <li id="tabPredioPiso"><a href="#predioPiso">Pisos</a></li>
            <li id="tabPredioInstalacion"><a href="#predioInstalacion">Instalaci&oacute;n</a></li>    
<!--            <li id="tabPredioInafectacion"><a href="#predioInafectacion">Inafectaci&oacute;n y Exoneraci&oacute;n</a></li>-->
            <li id="tabPredioUbicacion"><a href="#predioUbicacion">Ubicaci&oacute;n</a></li>
        </ul>
        <div style="overflow-y: auto; overflow-x: hidden; height:310px; padding: 2px;" id="predioUbicacion">
            <table style="width: 100%;">
            	<tr>
            		<td valign="top">
            			<table style="width: 100%;">
            				<!--
            				<tr>
            					<td>Direcci&oacute;n: </td>
            					<td style="width: 85%;"><input class="ui-text" style="width: 100%;" id="direccionXY" type="text" value="" title="Ingrese la direcci&oacute;n para buscar" /></td>
            				</tr>
            				 -->
            				<tr>
            					<td colspan="2">
            						<img src=""/>
            						<input type="button" id="btnGaleria" value="Ver Galeria">
            					<td>
            				</tr>
            			</table>
            		</td>
            		<td style="width: 420px;">
            			<!-- Longitud --><input type="hidden" id="longitud" value="-11.866663">
            			<!-- Latitud --><input type="hidden" id="latitud" value="-77.077125">
            			<!-- Zoom --><input type="hidden" id="zoom" value="17" >
						<div id="map" style="width:400px; height: 280px; margin-top: 10px; border: 1px solid #000;"></div>
            		</td>
            	</tr>
            </table>
        </div>
        <div style="overflow-y: auto; overflow-x: hidden; height:310px; padding: 2px;" id="predioDescripcion">
            <?php echo $this->render("registro/verpredio/descripcion.php"); ?>
        </div>
        <div style="overflow-y: auto; overflow-x: hidden; height:300px; padding: 2px;" id="predioLindero">
            <?php echo $this->render("registro/verpredio/lindero.php"); ?>
        </div>
         <!--   <div style="overflow-y: hidden; overflow-x: hidden; height:300px; padding: 2px;" id="predioRustico">
            <?php echo $this->render("registro/verpredio/rustico.php"); ?>
        </div> -->       
        <div style="overflow-y: auto; overflow-x: hidden; height:300px; padding: 2px;" id="predioPiso">
            <?php echo $this->render("registro/verpredio/piso.php"); ?>
        </div>
        <div style="overflow-y: auto; overflow-x: hidden; height:300px; padding: 2px;" id="predioInstalacion">
            <?php echo $this->render("registro/verpredio/instalacion.php"); ?>
        </div>
        <!--   <div style="overflow-y: hidden; overflow-x: hidden; height:300px; padding: 2px;" id="predioInafectacion">
            <?php echo $this->render("registro/verpredio/inafectacion.php"); ?>
        </div>-->
    </div>
</div>

<script type="text/javascript" src="<?php echo $this->util()->getPath(); ?>js/registro/js_registro_verpredio_verinstalacion.js"></script>
<script type="text/javascript" src="<?php echo $this->util()->getPath(); ?>js/registro/js_registro_verpredio_verpiso.js"></script>
<script type="text/javascript" src="<?php echo $this->util()->getPath(); ?>js/registro/js_registro_verpredio.js"></script>
<script type="text/javascript" src="<?php echo $this->util()->getPath(); ?>js/registro/js_registro_verpredio_vermapa.js"></script>
<script type="text/javascript">
    tabs = null;
    jsonPredio = <?php echo json_encode($this->mpredio); ?>;
    
    $(function() {
        loadVerDetalle();
    });

    /*
    $(document).ready(function() {
        
    	$("#direccionXY").autocomplete({          
    		source: function(request, response) {
    			if (geocoder == null){
    				geocoder = new google.maps.Geocoder();
    			} 
    			geocoder.geocode( {'address': request.term }, function(results, status) {
    				if (status == google.maps.GeocoderStatus.OK) {
    					// var searchLoc = results[0].geometry.location;
    					// var bounds = results[0].geometry.bounds;
    					var lat = results[0].geometry.location.lat();
    					var lng = results[0].geometry.location.lng();
    					var latlng = new google.maps.LatLng(lat, lng);

    					geocoder.geocode({'latLng': latlng}, function(results1, status1) {
    						if (status1 == google.maps.GeocoderStatus.OK) {
    							if (results1[1]) {
    								response($.map(results1, function(loc) {
    									return {
    										label  : loc.formatted_address,
    										value  : loc.formatted_address,
    										bounds   : loc.geometry.bounds
    									};
    								}));
    							}
    						}
    					});
    				}
    			});
    		},
    		select: function(event,ui){
    			// var pos = ui.item.position;
    			// var lct = ui.item.locType;
    			var bounds = ui.item.bounds;

    			if (bounds){
    				map.fitBounds(bounds);
    			}
    		}
    	});
    	
    	mapOptions = {
        	zoom: parseInt($('#zoom').val(), 10),
        	mapTypeId: google.maps.MapTypeId.ROADMAP,
    		center: new google.maps.LatLng($('#longitud').val(), $('#latitud').val())
    	};

        initMap();
    });
    */
</script>
<!-- 
    /*
jQuery("#custbut").jqGrid('navButtonAdd','#pcustbut',{caption:"Edit", onClickButton:function(){ var gsr = jQuery("#custbut").jqGrid('getGridParam','selrow'); if(gsr){ jQuery("#custbut").jqGrid('GridToForm',gsr,"#order"); } else { alert("Please select Row") } } });
jQuery("#savedata").click(function(){ var invid = jQuery("#invid").val(); if(invid) { jQuery("#custbut").jqGrid('FormToGrid',invid,"#order"); } });
     */
-->