<style>
    .ui-autocomplete {
        max-height: 218px;
        overflow-y: auto;
        /* prevent horizontal scrollbar */
        overflow-x: hidden;
        /* add padding to account for vertical scrollbar */
        padding-right: 8px;
    }

    /* IE 6 doesn't support max-height
    * we use height instead, but this forces the menu to always be this tall
    */
    * html .ui-autocomplete {
        height: 218px;
    }
</style>
<script type="text/javascript">

    var jsonVias = <?php echo json_encode($this->mviascp); ?>,
        ccodvia = '';
        cpoblad = '';

    $("#txtviacentrpob").autocompleteCategory({
        delay: 0,
        source: jsonVias,
        minLength: 4,
        select: function(event, ui) {
            ccodvia = ui.item.ccodvia;
            cpoblad = ui.item.mpoblad;

            $("#txt_mviadis").val(ccodvia);
            $("#txt_mpoblad").val(cpoblad);
        },
        change: function(event, ui) {
            if(ui.item) {
                ccodvia = ui.item.ccodvia;
            } else {
                if($(this).val().length > 0) {
                    openDialogWarning("El valor ingresado no esta en la lista de elementos.", 380, 150);
                }
            }
        }
    });

      $("#btnguardar").button({
        icons: {primary:'ui-icon-disk'}
        
    }).bind('click', function(){
    	isValid = true;
    	
    	
		if(($("#txt_mviadis").val().length ==0) && ($("#txt_mpoblad").val().length ==0)  ) {
			isValid = false;
       		//return;
   		}

	
	if(!isValid) {
			openDialogWarning("Los campos deben estar llenos.", 380, 150);	
			return false;
	} else {
		//GuardarPiso();

	     guardar = function() {
	        	row = { 
	        			idsigma: $("#txt_idsigma").val(),
	        			mviadis: $("#txt_mviadis").val(),
	        			dnumero: $("#txtnumero").val(),
	        			dinteri: $("#txtinterior").val(),
	        			dletras: $("#txtletra").val(),        			
	        			ddepart: $("#txtdepart").val(),
	        			destaci: $("#txtestacio").val(),  
	        			ddeposi: $("#txtdeposito").val(),     
	        			drefere: $("#txtreferencia").val(),
	        			dmanzan: $("#txtmanzana").val(),     
	        			dnlotes: $("#txtlote").val(),
	        			ccatast: 0,    
	        			cplanos: 0,
	        			ctipmer: "0",      
	        			dnummer: "0",
	        			cdiscat: "0",		
	        			czoncat: $("#txtczoncat").val(),      
	        			cmzacat: $("#txtcmzacat").val(),
	        			cseccat: $("#txtcseccat").val(),
	        			cltecat: $("#txtcltecat").val(), 
	        			cundcat: $("#txtcundcat").val(),
	        			dbloque: $("#txtbloque").val() ,
	        			dseccio: $("#txtseccion").val(),
	        			dunidad: $("#txtunidinmob").val(),
	        			mpoblad: $("#txt_mpoblad").val(),
	        			vdirpre: $("#txtviacentrpob").val()+' '+ $("#txtnumero").val()+' ' + $("#txtinterior").val()+' ' + $("#txtletra").val()+' '+ $("#txtdepart").val() +' '+  $("#txtestacio").val() +' '+  $("#txtdeposito").val() +' '+  $("#txtreferencia").val() +' '+  $("#txtmanzana").val() +' '+ $("#txtlote").val() , 
	        			nestado: "1" ,
	        			ccodpre: 0 ,
	        			ctippre: 0 ,
	        			idanexo: 0 ,
	        			ccodcuc: 0,
	        			nlatitu: $("#txt_nlatitu").val() ,
	        			nlongit: $("#txt_nlongit").val() ,
	        			nzoom: $("#txt_nzoom").val()
	        			 
	        	};

	        	_post = $.post(path + "registro/guardarmpredio", row);
	            _post.success(function(data){
	            	
	        		openDialogWarning("Los datos han sido guardados.", 380, 150);
	        		  
	        		closeDialog('jqDialog1');
	        		
	        		location.reload();
	        	});
	            _post.error(postError);	
	        };
	        
	         guardar();  
	
		
	} 
		
    });

      $("#btncancelar").button({
        icons: {primary:'ui-icon-arrowreturnthick-1-w'}
    }).bind('click', function(){
        location.href = path + "registro/prediomanten";
    });

</script>

<!-- <script type="text/javascript">-->
<!--   src="https://maps.google.com/maps/api/js?libraries=geometry&sensor=true";-->
<!---->
<!--</script>-->






<div id="formPredioMantt">
	<table border="0">
		 <tr align="center">
			<td width="310">
				<div class="ui-widget ui-state-default ui-corner-top ui-title">
					<label>Predio</label>
				</div>
				<div class="ui-widget-content ui-corner-bottom">
					<table cellspacing="5" style="margin: 3px;" class="ui-table-panelLayout" border="0">
						<tr> 
						   <td colspan="4">Centro Poblado          y            Via: </td> 	
						</tr>
						
						<tr>	
						    <td colspan="4"><input id="txtviacentrpob" class="ui-text pnl" style="width:100%"/> </td>
						</tr>
						
						<tr>	
						  <td>Codigo:</td><td><input id="txtcodpre" class="ui-text ui-text-disable"  ReadOnly />  </td>
						   <td>Cod.Catastral:</td><td><input id="txtczoncat" class="ui-text" style="width:50px;" />  <input id="txtcmzacat" class="ui-text" style="width:50px;"  />  <input id="txtcseccat" class="ui-text" style="width:50px;"  />  <input id="txtcltecat" class="ui-text" style="width:50px;"  /> <input id="txtcundcat" class="ui-text" style="width:50px;"  />  </td>
						</tr>
					
						<tr>	
						  <td>N&uacute;mero:</td><td><input id="txtnumero" class="ui-text"  />   </td>
						   <td>Departamento:</td><td><input id="txtdepart" class="ui-text" />  </td>
						</tr>
						
						<tr>	
						  <td>Interior:</td><td><input id="txtinterior" class="ui-text" />  </td>
						  <td>Letra:</td><td><input id="txtletra" class="ui-text" />  </td>
						</tr>
						
						<tr>	
						  <td>Estacionamiento:</td><td><input id="txtestacio" class="ui-text" />  </td>
						  <td>Deposito:</td><td><input id="txtdeposito" class="ui-text" />  </td>
						</tr>
						
						<tr>	
						  <td>Manzana:</td><td><input id="txtmanzana" class="ui-text" />  </td>
						  <td>Lote:</td><td><input id="txtlote" class="ui-text" />  </td>
						</tr>
						
						<tr>	
						  <td>Block:</td><td><input id="txtbloque" class="ui-text" />  </td>
						  <td>Seccion:</td><td><input id="txtseccion" class="ui-text" />  </td>
						</tr>
						
						<tr>	
						  <td >Unid. Inmobilaria:</td><td><input id="txtunidinmob" class="ui-text" />  </td>
						
						</tr>

						<tr>	
						  <td >Referencia :</td><td colspan="3"><input id="txtreferencia" class="ui-text" style="width:100%" />  </td>
						
						</tr>

						
						
						<tr>
							<td></td>
							<td> <input id="txt_idsigma" type="hidden" class="ui-text" style="width:250px;padding:2px;"/>
								<input id="txt_mviadis" type="hidden" class="ui-text" style="width:250px;padding:2px;"/>
								<input id="txt_mpoblad" type="hidden" class="ui-text" style="width:250px;padding:2px;"/>
								 <input id="txt_nlatitu" type="hidden" class="ui-text" style="width:250px;padding:2px;" value='1'/>
								 <input id="txt_nlongit" type="hidden" class="ui-text" style="width:250px;padding:2px;" value='1'/>
								 <input id="txt_nzoom" type="hidden" class="ui-text" style="width:250px;padding:2px;" value=15 />							
							</td>
						</tr> 
						<tr>
							<td colspan="4" align="right"><button id="btnguardar" name="btnguardar">Aceptar</button>&nbsp;&nbsp;<button id="btncancelar">Cancelar</button></td>
						</tr>
						<tr>
						<td colspan="4"><div id="map_canvas" style="width:800px; height: 280px;"></div>
						  <div id="infoPanel">
<!--						    <b>Marker status:</b>-->
						    <div id="markerStatus" style="visibility:hidden;"><i>Click and drag the marker.</i></div>
<!--						    <b>Current position:</b>-->
						    <div id="info" style="visibility:hidden;"></div>
						    <b>Direcci&oacute;n Actual:</b>
						    <div id="address"></div>
						  </div></td>
						</tr>
					</table>
				</div>
			</td>
		</tr>
	</table>
</div>
<br/>


<?php
                          
                          $doc=new DOMDocument();						
                        $direccion="Puente Piedra, Lima, Peru";
                        //$direccion=$datos[0]["direccion"]." "."puente piedra";
							$xml="http://maps.googleapis.com/maps/api/geocode/xml?address=".$direccion."&sensor=true";
    // echo $xml;
                            $doc->load($xml);

							$persona=$doc->getElementsByTagName("result");

							foreach ($persona as $p)
							{
									$latitud=$p->getElementsByTagName("lat");
									$latitud=$latitud->item(0)->nodeValue;
									
									$longitud=$p->getElementsByTagName("lng");
									$longitud=$longitud->item(0)->nodeValue;
									
									//echo "latitud=".$latitud." - longitud=".$longitud."<br>";
							}
							
?>

<script type="text/javascript">

 
	
	  var map = null,
		  image = pathImage + '../img/casa.png',
		  markersArray = [],
		  mapOptions = null,
		  geocoder = null, latitud, longitud ;
	      latitud=null;
	      longitud=null;

     	//alert($("#txt_nlongit").val());		    
	     	
		if ($("#txt_nlatitu").val()=='1' && $("#txt_nlongit").val()=='1') {
			latitud  = <?php echo $latitud;?>; 
			longitud = <?php echo $longitud;?>;
		}
		else {
			latitud = $("#txt_nlatitu").val();
			longitud= $("#txt_nlongit").val(); 
		}

		 		
	  var latLng = new google.maps.LatLng(latitud, longitud);
 
		var geocoder = new google.maps.Geocoder();
	  
	  	function geocodePosition(pos) {
	  	  geocoder.geocode({
	  		latLng: pos
	  	  }, function(responses) {
	  		if (responses && responses.length > 0) {
	  		  updateMarkerAddress(responses[0].formatted_address);
	  		} else {
	  		  updateMarkerAddress('Cannot determine address at this location.');
	  		}
	  	  });
	  	}
	
	  
		function updateMarkerStatus(str) {
	  document.getElementById('markerStatus').innerHTML = str;
	}

	function updateMarkerPosition(latLng) {
	  document.getElementById('info').innerHTML = [
		latLng.lat(),
		latLng.lng()
	  ].join(', ');

	 $("#txt_nlatitu").val(latLng.lat());
	 $("#txt_nlongit").val(latLng.lng());
	
	}

	
	function updateMarkerAddress(str) {
	  document.getElementById('address').innerHTML = str;
	}

	var zoom = parseInt($("#txt_nzoom").val());
	  
	mapOptions = {
				scaleControl: true,
	        	zoom: zoom ,
	        	mapTypeId: google.maps.MapTypeId.ROADMAP,
	    		center: latLng
	    	};

    	
	  		initMap = function(){
			//clearOverlays();
			map = new google.maps.Map(document.getElementById("map_canvas"),mapOptions);

//			var marker = new google.maps.Marker({
//				map: map,
//				draggable: true,
//				animation: google.maps.Animation.DROP,
//				icon: image,			
//				title: "Municipalidad de Puente Piedra",
//				position: latLng
//				
//			});
 
			var marker = new google.maps.Marker({
		          map: map,
				  title: "<?php echo $direccion;?>",
				  draggable: true,
		          position: latLng
		        }); 

		        var infowindow = new google.maps.InfoWindow();
		        infowindow.setContent('<b>Mapa</b>');
		        google.maps.event.addListener(marker, 'click', function() {
		            infowindow.open(map, marker);
		        });


				  // Update current position info.
				  updateMarkerPosition(latLng);
				  geocodePosition(latLng);
				  
				  // Add dragging event listeners.
				  google.maps.event.addListener(marker, 'dragstart', function() {
					updateMarkerAddress('Dragging...');
				  });
				  
				  google.maps.event.addListener(marker, 'drag', function() {
					updateMarkerStatus('Dragging...');
					updateMarkerPosition(marker.getPosition());
				  });
				  
				  google.maps.event.addListener(marker, 'dragend', function() {
					updateMarkerStatus('Drag ended');
					geocodePosition(marker.getPosition());
				  });
  
				   
//
				  google.maps.event.addListener(map, 'zoom_changed', function() {
					    var zoomLevel = map.getZoom();
					    
					    //infowindow.setContent('Zoom: ' + zoomLevel);
//
					    $("#txt_nzoom").val(zoomLevel);
//
					    //alert(zoomLevel);
					    
				  });
				
		};

      $(document).ready(function() {
		initMap(); 
		 
      });

</script>
