<script type="text/javascript" src="<?php echo $this->util()->getPath(); ?>js/registro/js_registro_verpredio_verpiso_detalle.js"></script>
<style>
	.panel-detalle-construccion td,
	.panel-valor-construccion td {
		padding: 3px;
	}
	.panel-valor-construccion input {
		width: 90px;
	}
	.panel-detalle-construccion div.detalle {
		font-size: 9px;
	}
	.panel-detalle-construccion input.ui-text {
		width: 30px;
		text-align: center;
	}
	.panel-detalle-construccion tr.caracteristica {
		height: 42px;
	}
</style>
<div id="formPiso">
	<table>
		<tr>
			<td width="650px" align="center" valign='top'>
				<div class="ui-widget ui-state-default ui-corner-top ui-title">
					<label>Caracter&iacute;sticas</label>
				</div>
				<div class="ui-widget-content ui-corner-bottom">
					<table class="panel-detalle-construccion" style="margin: 3px; padding: 5px;">
						<tr>
							<td width="90">Nivel</td>
							<td width="35"><input id="txt_pisonivel" maxlength="2" class="ui-text ui-text-numeric" /></td>
							<td width="510">&nbsp;</td>
						</tr>
						<tr>
							<td>A&ntilde;os de Construcci&oacute;n</td>
							<td><input id="txt_pisoanocon" maxlength="4" class="ui-text ui-text-numeric" /></td>
							<td><div id="dtxt_pisoano" class="detalle"></div></td>
						</tr>
						<tr>
							<td>Mes</td>
							<td><input id="txt_pisomescon" maxlength="2" class="ui-text ui-text-numeric" /></td>
							<td>&nbsp;</td>
						</tr>
						<tr>
							<td>Materiales</td>
							<td><input id="txt_cmateri" maxlength="1" class="ui-text ui-text-numeric" /></td>
							<td><div id="dtxt_cmateri" class="detalle"></div></td>
						</tr>
						<tr>
							<td>Estado</td>
							<td><input id="txt_cconser" maxlength="1" class="ui-text ui-text-numeric" /></td>
							<td><div id="dtxt_cconser" class="detalle"></div></td>
						</tr>
						<tr class="caracteristica">
							<td>Muro y Columas</td>
							<td><input id="txt_cmurcol" maxlength="1" class="ui-text" /></td>
							<td><div id="dtxt_cmurcol" class="detalle"></div></td>
						</tr>
						<tr class="caracteristica">
							<td>Techo</td>
							<td><input id="txt_ctechos" maxlength="1" class="ui-text" /></td>
							<td><div id="dtxt_ctechos" class="detalle"></div></td>
						</tr>
						<tr class="caracteristica">
							<td>Pisos</td>
							<td><input id="txt_cmpisos" maxlength="1" class="ui-text" /></td>
							<td><div id="dtxt_cmpisos" class="detalle"></div></td>
						</tr>
						<tr class="caracteristica">
							<td>Puertas y Ventanas</td>
							<td><input id="txt_cpueven" maxlength="1" class="ui-text" /></td>
							<td><div id="dtxt_cpueven" class="detalle"></div></td>
						</tr>
						<tr class="caracteristica">
							<td>Revestimiento</td>
							<td><input id="txt_crevest" maxlength="1" class="ui-text" /></td>
							<td><div id="dtxt_crevest" class="detalle"></div></td>
						</tr>
						<tr class="caracteristica">
							<td>Ba&ntilde;os</td>
							<td><input id="txt_cbanios" maxlength="1" class="ui-text" /></td>
							<td><div id="dtxt_cbanios" class="detalle"></div></td>
						</tr>
						<tr class="caracteristica">
							<td>Instalaciones Electricas y Sanitarias</td>
							<td><input id="txt_celectr" maxlength="1" class="ui-text" /></td>
							<td><div id="dtxt_celectr" class="detalle"></div></td>
						</tr>
					</table>
				</div>
			</td>
			<td width="210px" align="center" valign='top'>
				<div class="ui-widget ui-state-default ui-corner-top ui-title">
					<label>&Aacute;reas</label>
				</div>
				<div class="ui-widget-content ui-corner-bottom">
					<table class="panel-valor-construccion" style="margin: 3px; padding: 5px;">
						<tr>
							<td style="width: 120px">Area Construida</td>
							<td style="width: 95px"><input id="txt_pisoarecon" class="ui-text ui-text-numeric" /></td>
						</tr>
						<tr>
							<td>Val. Unit. x m2</td>
							<td><input id="txt_pisovaluni" class="ui-text-disable ui-text-numeric" readonly="readonly" /></td>
						</tr>
						<tr>
							<td>% Incremento</td>
							<td><input id="txt_pisoincrem" class="ui-text-disable ui-text-numeric" readonly="readonly" /></td>
						</tr>
						<tr>
							<td>% Depreciacion</td>
							<td><input id="txt_pisopordep" class="ui-text-disable ui-text-numeric" readonly="readonly" /></td>
						</tr>
						<tr>
							<td>Val. Depreciado</td>
							<td><input id="txt_pisodepred" class="ui-text-disable ui-text-numeric" readonly="readonly" /></td>
						</tr>
						<tr>
							<td>Val. Unit. Depreciado</td>
							<td><input id="txt_pisovalare" class="ui-text-disable ui-text-numeric" readonly="readonly" /></td>
						</tr>
						<tr>
							<td>Area Com&uacute;n</td>
							<td><input id="txt_pisoarecom" class="ui-text ui-text-numeric" /></td>
						</tr>
						<tr>
							<td>% Area Com&uacute;n</td>
							<td><input id="txt_pisoporcom" class="ui-text-disable ui-text-numeric" readonly="readonly" /></td>
						</tr>
						<tr>
							<td>Val. Area Com.</td>
							<td><input id="txt_pisovalcom" class="ui-text-disable ui-text-numeric" readonly="readonly" /></td>
						</tr>
						<tr>
							<td>Val. del Predio</td>
							<td><input id="txt_valpre" class="ui-text-disable ui-text-numeric" readonly="readonly" />
						</tr>
					</table>
				</div> 				
			<td>			
		</tr>
	</table>
	<hr/>
	<div style="direction: rtl;">
	<button id="btnguardar">Aceptar</button>&nbsp;&nbsp;<button id="btncancelar">Cancelar</button>
	</div>
	<input type="hidden" id="txt_idsigma" />
	<input type="hidden" id="ctxt_cmateri" />
	<input type="hidden" id="ctxt_cconser" />
	<input type="hidden" id="ctxt_cmurcol" />
	<input type="hidden" id="ctxt_ctechos" />
	<input type="hidden" id="ctxt_cmpisos" />
	<input type="hidden" id="ctxt_cpueven" />
	<input type="hidden" id="ctxt_crevest" />
	<input type="hidden" id="ctxt_cbanios" />
	<input type="hidden" id="ctxt_celectr" />
</div>