<div id="formRustico">

	<table >
		 <tr align="center">
			<td width="310">
				<div class="ui-widget ui-state-default ui-corner-top ui-title">
					<label></label>
				</div>
				<div class="ui-widget-content ui-corner-bottom">
					<table cellspacing="5" style="margin: 3px;" class="ui-table-panelLayout">
						<tr>
						  <td><input type="hidden" name="txtidsigma" id="txtidsigma" value="" /></td>
						</tr>
						<tr>
							<td width="100px">Clasificacion</td>
							<td width="35" ><select style="width: 150px;" id="cboClasificacionRustico"><?php echo $this->util()->getComboContenedor('1000000326', null); ?></select></td>
						</tr>
						<tr>
					
							<td>Categoria</td>
							<td width="35" ><select style="width: 150px;" id="cboCategoria"><?php echo $this->util()->getComboContenedor('1000000319', null); ?></select></td>
						</tr>
						<tr>
							<td>Arancel</td>
							<td><input id="txtArancel" class="ui-text ui-text-numeric" style="width:70px;" value="0" /></td>
						</tr>
						<tr>
							<td>Hectareas</td>
							<td><input id="txt_Hectareas" class="ui-text ui-text-numeric" style="width:70px;" value="0"/></td>
						</tr>
						<tr>
							<td>Total</td>
							<td><input id="txt_Total" class="ui-text-disable ui-text-numeric"  style="width:70px;" value="0"  ReadOnly /></td>
							<td>&nbsp;</td>
						</tr>	
						<tr>
							<td colspan="2" align="right">
								<button id="btnguardar">Aceptar</button>&nbsp;&nbsp;<button id="btncancelar">Cancelar</button>
							</td>
						</tr>
						<tr>
						  <td><input type="hidden" name="_mrustic" id="_mrustic" value="" /></td>
						</tr>
					</table>
				</div>
			</td>
		</tr>
	</table>
</div>
<script type="text/javascript">

	$("#txtArancel").autoNumeric();
	$("#txt_Hectareas").autoNumeric();
	$("#txt_Total").autoNumeric();

	$("#txtArancel").keyup(function(){
 
		$("#txt_Total").val( ($("#txtArancel").val()) * ($("#txt_Hectareas").val()) );
	});

	$("#txt_Hectareas").keyup(function(){
		 
		$("#txt_Total").val( ($("#txtArancel").val()) * ($("#txt_Hectareas").val()) );
	});        
  
	
	$("#btnguardar").button({
		icons: {primary:'ui-icon-disk'}
	}).bind('click', function(){
		isValid = true;
		$("#formRustico").find("input").each(function(){
			if($(this).val().length ==0){
				isValid = false;
	            return;
	        }
		});
		if(!isValid){
		   openDialogWarning("Los campos deben estar llenos.", 380, 150);	
		}else{
			GuardaRustico();
			//openDialogWarning("Los datos han sido guardados.", 380, 150);
			closeDialog('jqDialog1');
			}
	});

	$("#btncancelar").button({
		icons: {primary:'ui-icon-pencil'}
	}).bind('click', function(){
		closeDialog('jqDialog1');
	});

	/*GuardaRustico= function() {
		indexRow = $("#ctblRustico").val();
	//	debugger
		row = {
			vclasif: $('#cboClasificacionRustico option:selected').text(),
			vcatego: $('#cboCategoria option:selected').text(),
			narance: $("#txtArancel").val(),
			nhectar: $("#txt_Hectareas").val(),
      		nvalrus: $("#txt_Total").val(),
      		idsigma: $("#txtidsigma").val(),//"0000000009"
      		mrustic: '01',
      		cclasif: $("#cboClasificacionRustico").val(),
      		ccatego: $("#cboCategoria").val(),
      		dpredio: $("#_dpredio").val(),
      		nestado: '1',
      		cperiod: $("#txtPeriodo").val()
		};
		console.log(row);

		if($("#tblRustico").jqGrid('addRowData', indexRow,row)) {
			$("#ctblRustico").val(indexRow + 1);
		} else {
			alert('Error no se pudo agregar');
		}
	};*/

	GuardaRustico= function() {
		indexRow = $("#ctblRustico").val();
		row = {};
		ids = $("#tblRustico").jqGrid('getDataIDs');
		gsr = $("#tblRustico").jqGrid('getGridParam', 'selrow');
		
		if(gsr){
			row = $("#tblRustico").jqGrid('getRowData', gsr);
		}
				
		row = $.extend(row, {
			
			vclasif: $('#cboClasificacionRustico option:selected').text(),
			vcatego: $('#cboCategoria option:selected').text(),
			narance: $("#txtArancel").val(),
			nhectar: $("#txt_Hectareas").val(),
      		nvalrus: $("#txt_Total").val(),
      		idsigma: $("#txtidsigma").val(),//"0000000009"
      		mrustic: '22',
      		cclasif: $("#cboClasificacionRustico").val(),
      		ccatego: $("#cboCategoria").val(),
      		dpredio: $("#_dpredio").val(),
      		nestado: '1',
      		cperiod: $("#txtPeriodo").val()
		});
		console.log(row);
		
		_post = $.post(path + "registro/guardarrustico", row);
	    _post.success(function(data){
	    	optionRustico = $.extend(optionRustico, {data: data.data});
	    	procesarJSON("panelRustico", "tblRustico", optionRustico, null, function(){
	            $("#tblRustico").jqGrid('navGrid', '#ptblRustico', {edit:false, add:false, del:false, search:false, refresh:false});
	            $("#tblRustico").jqGrid('navButtonAdd', '#ptblRustico', btnInsertarRustico);
	            $("#tblRustico").jqGrid('navSeparatorAdd','#ptblRustico');
	            $("#tblRustico").jqGrid('navButtonAdd','#ptblRustico', btnEditarRustico);
	            $("#tblRustico").jqGrid('navSeparatorAdd','#ptblRustico');
	            $("#tblRustico").jqGrid('navButtonAdd','#ptblRustico', btnEliminarRustico);
	        });
		});
	    _post.error(postError);
	};


	
</script>



