CREATE OR REPLACE PACKAGE IIDO.PKG_INGRESO IS
  PROCEDURE PROC_INSERTAR_INGRESO(P_COD_USUARIO IN VARCHAR2, P_CARGO IN VARCHAR2, P_TERRITORIO IN VARCHAR2, P_OFICINA IN VARCHAR2, P_USUARIO IN VARCHAR2, P_ID OUT NUMBER);
  PROCEDURE PROC_INSERTAR_INGRESO_DETALLE(P_ID IN NUMBER, P_TIPO IN NUMBER, P_MES IN VARCHAR2, P_ANIO IN VARCHAR2);
  PROCEDURE PROC_INSERTAR_INGRESO_FORM(P_TIPO IN VARCHAR2, P_MES IN VARCHAR2, P_ANIO IN VARCHAR2, P_COD_USUARIO IN VARCHAR2, P_MODO IN VARCHAR2, P_COD_GESTOR IN VARCHAR2, P_COD_OFICINA IN VARCHAR2);
  PROCEDURE PROC_EXISTE_INGRESO_FORM(P_TIPO IN VARCHAR2, P_MES IN VARCHAR2, P_ANIO IN VARCHAR2, P_COD_USUARIO IN VARCHAR2, P_COD_GESTOR IN VARCHAR2, P_COD_OFICINA IN VARCHAR2, P_ID OUT NUMBER);
  PROCEDURE PROC_ACTUALIZAR_INGRESO_FORM(P_ID IN NUMBER);
END PKG_INGRESO;
/