package com.grupobbva.bc.per.tel.iilc.entity.websphere_deploy.ORACLE_V10_1;

/**
 * Tiilc_clienteBeanInjectorImpl_f5b4eb46
 */
public class Tiilc_clienteBeanInjectorImpl_f5b4eb46 implements com.grupobbva.bc.per.tel.iilc.entity.websphere_deploy.Tiilc_clienteBeanInjector_f5b4eb46 {
	/**
	 * ejbCreate
	 */
	public void ejbCreate(com.ibm.ws.ejbpersistence.beanextensions.ConcreteBean cb, javax.resource.cci.IndexedRecord record) {
		com.grupobbva.bc.per.tel.iilc.entity.ConcreteTiilc_cliente_f5b4eb46 concreteBean=(com.grupobbva.bc.per.tel.iilc.entity.ConcreteTiilc_cliente_f5b4eb46)cb;
		record.set(0,concreteBean.getCod_cliente());
		record.set(1,concreteBean.getCodigo());
		record.set(2,concreteBean.getCod_oficina());
		record.set(3,concreteBean.getCod_gestor());
		record.set(4,concreteBean.getNombre());
		record.set(5,concreteBean.getCod_territorio());
		record.set(6,concreteBean.getSegment1());
		record.set(7,concreteBean.getEdad());
		record.set(8,concreteBean.getEstcivil());
		record.set(9,concreteBean.getCalle());
		record.set(10,concreteBean.getNro());
		record.set(11,concreteBean.getPerfil());
		record.set(12,concreteBean.getDirec1());
		record.set(13,concreteBean.getDistrito());
		record.set(14,concreteBean.getProvincia());
		record.set(15,concreteBean.getDepartamento());
		record.set(16,concreteBean.getTipo_persona());
		record.set(17,concreteBean.getClasificacion());
		record.set(18,concreteBean.getTelefono());
		record.set(19,concreteBean.getVinculacion());
		record.set(20,concreteBean.getPper());
		record.set(21,concreteBean.getPcom());
		record.set(22,concreteBean.getVnac());
		record.set(23,concreteBean.getCcte());
		record.set(24,concreteBean.getColb());
		record.set(25,concreteBean.getCnet());
		record.set(26,concreteBean.getPaut());
		record.set(27,concreteBean.getDsct());
		record.set(28,concreteBean.getVarc());
		record.set(29,concreteBean.getCemp());
		record.set(30,concreteBean.getSdep());
		record.set(31,concreteBean.getCext());
		record.set(32,concreteBean.getPhip());
		record.set(33,concreteBean.getLeas());
		record.set(34,concreteBean.getVcla());
		record.set(35,concreteBean.getCvip());
		record.set(36,concreteBean.getSvid());
		record.set(37,concreteBean.getLinco());
		record.set(38,concreteBean.getPmiv());
		record.set(39,concreteBean.getCloc());
		record.set(40,concreteBean.getVrep());
		record.set(41,concreteBean.getAhsd());
		record.set(42,concreteBean.getSonc());
		record.set(43,concreteBean.getTco());
		record.set(44,concreteBean.getB24());
		record.set(45,concreteBean.getCpte());
		record.set(46,concreteBean.getPref());
		record.set(47,concreteBean.getVoro());
		record.set(48,concreteBean.getAhor());
		record.set(49,concreteBean.getSpro());
		record.set(50,concreteBean.getPos());
		record.set(51,concreteBean.getT_act2());
		record.set(52,concreteBean.getPmas());
		record.set(53,concreteBean.getT_act3());
		record.set(54,concreteBean.getLcta());
		record.set(55,concreteBean.getT_act4());
		record.set(56,concreteBean.getVpla());
		record.set(57,concreteBean.getT_act5());
		record.set(58,concreteBean.getPlzo());
		record.set(59,concreteBean.getT_act6());
		record.set(60,concreteBean.getPserv());
		record.set(61,concreteBean.getTpr());
		record.set(62,concreteBean.getProm());
		record.set(63,concreteBean.getT_act_ct2());
		record.set(64,concreteBean.getVemp());
		record.set(65,concreteBean.getT_act_ct3());
		record.set(66,concreteBean.getPh());
		record.set(67,concreteBean.getT_act_ct4());
		record.set(68,concreteBean.getFcex());
		record.set(69,concreteBean.getT_act_ct5());
		record.set(70,concreteBean.getVctr());
		record.set(71,concreteBean.getT_act_ct6());
		record.set(72,concreteBean.getFmut());
		record.set(73,concreteBean.getMargeno());
		record.set(74,concreteBean.getNro_documento());
		record.set(75,concreteBean.getBcorie());
		record.set(76,concreteBean.getEmph());
		record.set(77,concreteBean.getBcorid());
		record.set(78,concreteBean.getAval());
		record.set(79,concreteBean.getBcorii());
		record.set(80,concreteBean.getMcla());
		record.set(81,concreteBean.getBcopas());
		record.set(82,concreteBean.getCts());
		record.set(83,concreteBean.getBcovol());
		record.set(84,concreteBean.getTdeb());
		record.set(85,concreteBean.getPorcrie());
		record.set(86,concreteBean.getMoro());
		record.set(87,concreteBean.getPorcrid());
		record.set(88,concreteBean.getCtsd());
		record.set(89,concreteBean.getPorcrii());
		record.set(90,concreteBean.getTvip());
		record.set(91,concreteBean.getSbsrie());
		record.set(92,concreteBean.getSbsrid());
		record.set(93,concreteBean.getSbsrii());
		record.set(94,concreteBean.getSbsjud());
		record.set(95,concreteBean.getCod_empresa());
		record.set(96,concreteBean.getDes_empresa());
		record.set(97,concreteBean.getIntervpas());
		record.set(98,concreteBean.getMofactv());
		record.set(99,concreteBean.getCs000lineamaxtc());
		record.set(100,concreteBean.getMofpasv());
		record.set(101,concreteBean.getMofserv());
		record.set(102,concreteBean.getMofcanal());
		record.set(103,concreteBean.getMphpasv());
		record.set(104,concreteBean.getCs000mtoprestamo());
		record.set(105,concreteBean.getMontovehicular());
		record.set(106,concreteBean.getCtacteoferta());
		record.set(107,concreteBean.getCtaahoferta());
		record.set(108,concreteBean.getCtapoferta());
		record.set(109,concreteBean.getFmutuoofert());
		record.set(110,concreteBean.getCtactsofert());
		record.set(111,concreteBean.getTconsactv());
		record.set(112,concreteBean.getMontosubrogados());
		record.set(113,concreteBean.getTsubactv());
		record.set(114,concreteBean.getThipotactv());
		record.set(115,concreteBean.getTvehicactv());
		record.set(116,concreteBean.getTcuot36act());
		record.set(117,concreteBean.getTcuot48act());
		record.set(118,concreteBean.getCs000montocta60());
		record.set(119,concreteBean.getTcuot60act());
		record.set(120,concreteBean.getCss000presmena5000());
		record.set(121,concreteBean.getCs000comisdesemen5000());
		record.set(122,concreteBean.getCs000pres5000a15000());
		record.set(123,concreteBean.getC5000comdes15000act());
		record.set(124,concreteBean.getCs000presmaya15000());
		record.set(125,concreteBean.getComdes15000ac());
		record.set(126,concreteBean.getCs000linminadqtc());
		record.set(127,concreteBean.getCs000tipodecredito());
		record.set(128,concreteBean.getCs000mixmonprest());
		record.set(129,concreteBean.getCs000mixlinasistc());
		record.set(130,concreteBean.getCs000mixtipotc());
		record.set(131,concreteBean.getCs000prestcmena5000());
		record.set(132,concreteBean.getCs000prestc500015000());
		record.set(133,concreteBean.getCs000prestcmaya15000());
		record.set(134,concreteBean.getAtribctactepasv());
		record.set(135,concreteBean.getAtribctaahpasv());
		record.set(136,concreteBean.getAtribctaplazpasv());
		record.set(137,concreteBean.getAtribctspasv());
		record.set(138,concreteBean.getAtribfmutuopasv());
		record.set(139,concreteBean.getCobofserv());
		record.set(140,concreteBean.getSvidofserv());
		record.set(141,concreteBean.getSoncofserv());
		record.set(142,concreteBean.getSvincofserv());
		record.set(143,concreteBean.getPhofserv());
		record.set(144,concreteBean.getDebofserv());
		record.set(145,concreteBean.getVipofserv());
		record.set(146,concreteBean.getOfcnetcan());
		record.set(147,concreteBean.getOfcempcan());
		record.set(148,concreteBean.getOflincocan());
		record.set(149,concreteBean.getOfb24can());
		record.set(150,concreteBean.getOfposcan());
		record.set(151,concreteBean.getPrefijo());
		record.set(152,concreteBean.getMontohipotecario());
		record.set(153,concreteBean.getCs000montocta36());
		record.set(154,concreteBean.getCs000montocta48());
	}
	/**
	 * ejbStore
	 */
	public void ejbStore(com.ibm.ws.ejbpersistence.beanextensions.ConcreteBean cb, javax.resource.cci.IndexedRecord record) {
		com.grupobbva.bc.per.tel.iilc.entity.ConcreteTiilc_cliente_f5b4eb46 concreteBean=(com.grupobbva.bc.per.tel.iilc.entity.ConcreteTiilc_cliente_f5b4eb46)cb;
		record.set(0,concreteBean.getCod_cliente());
		record.set(1,concreteBean.getCodigo());
		record.set(2,concreteBean.getCod_oficina());
		record.set(3,concreteBean.getCod_gestor());
		record.set(4,concreteBean.getNombre());
		record.set(5,concreteBean.getCod_territorio());
		record.set(6,concreteBean.getSegment1());
		record.set(7,concreteBean.getEdad());
		record.set(8,concreteBean.getEstcivil());
		record.set(9,concreteBean.getCalle());
		record.set(10,concreteBean.getNro());
		record.set(11,concreteBean.getPerfil());
		record.set(12,concreteBean.getDirec1());
		record.set(13,concreteBean.getDistrito());
		record.set(14,concreteBean.getProvincia());
		record.set(15,concreteBean.getDepartamento());
		record.set(16,concreteBean.getTipo_persona());
		record.set(17,concreteBean.getClasificacion());
		record.set(18,concreteBean.getTelefono());
		record.set(19,concreteBean.getVinculacion());
		record.set(20,concreteBean.getPper());
		record.set(21,concreteBean.getPcom());
		record.set(22,concreteBean.getVnac());
		record.set(23,concreteBean.getCcte());
		record.set(24,concreteBean.getColb());
		record.set(25,concreteBean.getCnet());
		record.set(26,concreteBean.getPaut());
		record.set(27,concreteBean.getDsct());
		record.set(28,concreteBean.getVarc());
		record.set(29,concreteBean.getCemp());
		record.set(30,concreteBean.getSdep());
		record.set(31,concreteBean.getCext());
		record.set(32,concreteBean.getPhip());
		record.set(33,concreteBean.getLeas());
		record.set(34,concreteBean.getVcla());
		record.set(35,concreteBean.getCvip());
		record.set(36,concreteBean.getSvid());
		record.set(37,concreteBean.getLinco());
		record.set(38,concreteBean.getPmiv());
		record.set(39,concreteBean.getCloc());
		record.set(40,concreteBean.getVrep());
		record.set(41,concreteBean.getAhsd());
		record.set(42,concreteBean.getSonc());
		record.set(43,concreteBean.getTco());
		record.set(44,concreteBean.getB24());
		record.set(45,concreteBean.getCpte());
		record.set(46,concreteBean.getPref());
		record.set(47,concreteBean.getVoro());
		record.set(48,concreteBean.getAhor());
		record.set(49,concreteBean.getSpro());
		record.set(50,concreteBean.getPos());
		record.set(51,concreteBean.getT_act2());
		record.set(52,concreteBean.getPmas());
		record.set(53,concreteBean.getT_act3());
		record.set(54,concreteBean.getLcta());
		record.set(55,concreteBean.getT_act4());
		record.set(56,concreteBean.getVpla());
		record.set(57,concreteBean.getT_act5());
		record.set(58,concreteBean.getPlzo());
		record.set(59,concreteBean.getT_act6());
		record.set(60,concreteBean.getPserv());
		record.set(61,concreteBean.getTpr());
		record.set(62,concreteBean.getProm());
		record.set(63,concreteBean.getT_act_ct2());
		record.set(64,concreteBean.getVemp());
		record.set(65,concreteBean.getT_act_ct3());
		record.set(66,concreteBean.getPh());
		record.set(67,concreteBean.getT_act_ct4());
		record.set(68,concreteBean.getFcex());
		record.set(69,concreteBean.getT_act_ct5());
		record.set(70,concreteBean.getVctr());
		record.set(71,concreteBean.getT_act_ct6());
		record.set(72,concreteBean.getFmut());
		record.set(73,concreteBean.getMargeno());
		record.set(74,concreteBean.getNro_documento());
		record.set(75,concreteBean.getBcorie());
		record.set(76,concreteBean.getEmph());
		record.set(77,concreteBean.getBcorid());
		record.set(78,concreteBean.getAval());
		record.set(79,concreteBean.getBcorii());
		record.set(80,concreteBean.getMcla());
		record.set(81,concreteBean.getBcopas());
		record.set(82,concreteBean.getCts());
		record.set(83,concreteBean.getBcovol());
		record.set(84,concreteBean.getTdeb());
		record.set(85,concreteBean.getPorcrie());
		record.set(86,concreteBean.getMoro());
		record.set(87,concreteBean.getPorcrid());
		record.set(88,concreteBean.getCtsd());
		record.set(89,concreteBean.getPorcrii());
		record.set(90,concreteBean.getTvip());
		record.set(91,concreteBean.getSbsrie());
		record.set(92,concreteBean.getSbsrid());
		record.set(93,concreteBean.getSbsrii());
		record.set(94,concreteBean.getSbsjud());
		record.set(95,concreteBean.getCod_empresa());
		record.set(96,concreteBean.getDes_empresa());
		record.set(97,concreteBean.getIntervpas());
		record.set(98,concreteBean.getMofactv());
		record.set(99,concreteBean.getCs000lineamaxtc());
		record.set(100,concreteBean.getMofpasv());
		record.set(101,concreteBean.getMofserv());
		record.set(102,concreteBean.getMofcanal());
		record.set(103,concreteBean.getMphpasv());
		record.set(104,concreteBean.getCs000mtoprestamo());
		record.set(105,concreteBean.getMontovehicular());
		record.set(106,concreteBean.getCtacteoferta());
		record.set(107,concreteBean.getCtaahoferta());
		record.set(108,concreteBean.getCtapoferta());
		record.set(109,concreteBean.getFmutuoofert());
		record.set(110,concreteBean.getCtactsofert());
		record.set(111,concreteBean.getTconsactv());
		record.set(112,concreteBean.getMontosubrogados());
		record.set(113,concreteBean.getTsubactv());
		record.set(114,concreteBean.getThipotactv());
		record.set(115,concreteBean.getTvehicactv());
		record.set(116,concreteBean.getTcuot36act());
		record.set(117,concreteBean.getTcuot48act());
		record.set(118,concreteBean.getCs000montocta60());
		record.set(119,concreteBean.getTcuot60act());
		record.set(120,concreteBean.getCss000presmena5000());
		record.set(121,concreteBean.getCs000comisdesemen5000());
		record.set(122,concreteBean.getCs000pres5000a15000());
		record.set(123,concreteBean.getC5000comdes15000act());
		record.set(124,concreteBean.getCs000presmaya15000());
		record.set(125,concreteBean.getComdes15000ac());
		record.set(126,concreteBean.getCs000linminadqtc());
		record.set(127,concreteBean.getCs000tipodecredito());
		record.set(128,concreteBean.getCs000mixmonprest());
		record.set(129,concreteBean.getCs000mixlinasistc());
		record.set(130,concreteBean.getCs000mixtipotc());
		record.set(131,concreteBean.getCs000prestcmena5000());
		record.set(132,concreteBean.getCs000prestc500015000());
		record.set(133,concreteBean.getCs000prestcmaya15000());
		record.set(134,concreteBean.getAtribctactepasv());
		record.set(135,concreteBean.getAtribctaahpasv());
		record.set(136,concreteBean.getAtribctaplazpasv());
		record.set(137,concreteBean.getAtribctspasv());
		record.set(138,concreteBean.getAtribfmutuopasv());
		record.set(139,concreteBean.getCobofserv());
		record.set(140,concreteBean.getSvidofserv());
		record.set(141,concreteBean.getSoncofserv());
		record.set(142,concreteBean.getSvincofserv());
		record.set(143,concreteBean.getPhofserv());
		record.set(144,concreteBean.getDebofserv());
		record.set(145,concreteBean.getVipofserv());
		record.set(146,concreteBean.getOfcnetcan());
		record.set(147,concreteBean.getOfcempcan());
		record.set(148,concreteBean.getOflincocan());
		record.set(149,concreteBean.getOfb24can());
		record.set(150,concreteBean.getOfposcan());
		record.set(151,concreteBean.getPrefijo());
		record.set(152,concreteBean.getMontohipotecario());
		record.set(153,concreteBean.getCs000montocta36());
		record.set(154,concreteBean.getCs000montocta48());
	}
	/**
	 * ejbRemove
	 */
	public void ejbRemove(com.ibm.ws.ejbpersistence.beanextensions.ConcreteBean cb, javax.resource.cci.IndexedRecord record) {
		com.grupobbva.bc.per.tel.iilc.entity.ConcreteTiilc_cliente_f5b4eb46 concreteBean=(com.grupobbva.bc.per.tel.iilc.entity.ConcreteTiilc_cliente_f5b4eb46)cb;
		record.set(0,concreteBean.getCod_cliente());
	}
	/**
	 * ejbFindByPrimaryKey
	 */
	public void ejbFindByPrimaryKey(Object pkeyObject, javax.resource.cci.IndexedRecord record) {
		com.grupobbva.bc.per.tel.iilc.entity.Tiilc_clienteKey pkey=(com.grupobbva.bc.per.tel.iilc.entity.Tiilc_clienteKey)pkeyObject;
		record.set(0,pkey.cod_cliente);
	}
	/**
	 * readReadChecking
	 */
	public void readReadChecking(com.ibm.ws.ejbpersistence.beanextensions.ConcreteBean cb, javax.resource.cci.IndexedRecord record) {
		com.grupobbva.bc.per.tel.iilc.entity.ConcreteTiilc_cliente_f5b4eb46 concreteBean=(com.grupobbva.bc.per.tel.iilc.entity.ConcreteTiilc_cliente_f5b4eb46)cb;
		record.set(0,concreteBean.getCod_cliente());
	}
	/**
	 * ejbPartialStore
	 */
	public void ejbPartialStore(com.ibm.ws.ejbpersistence.beanextensions.ConcreteBean cb, javax.resource.cci.IndexedRecord record) {
		com.grupobbva.bc.per.tel.iilc.entity.ConcreteTiilc_cliente_f5b4eb46 concreteBean=(com.grupobbva.bc.per.tel.iilc.entity.ConcreteTiilc_cliente_f5b4eb46)cb;
		com.ibm.ws.ejbpersistence.beanextensions.ConcreteBeanInstanceExtension  instanceExtension = (com.ibm.ws.ejbpersistence.beanextensions.ConcreteBeanInstanceExtension)concreteBean._WSCB_getInstanceInfo();
		 
		record.set(0,concreteBean.getCod_cliente());
		if(instanceExtension.isDirty(1))
		{
			record.set(1,concreteBean.getCodigo());
		}
		if(instanceExtension.isDirty(2))
		{
			record.set(2,concreteBean.getCod_oficina());
		}
		if(instanceExtension.isDirty(3))
		{
			record.set(3,concreteBean.getCod_gestor());
		}
		if(instanceExtension.isDirty(4))
		{
			record.set(4,concreteBean.getNombre());
		}
		if(instanceExtension.isDirty(5))
		{
			record.set(5,concreteBean.getCod_territorio());
		}
		if(instanceExtension.isDirty(6))
		{
			record.set(6,concreteBean.getSegment1());
		}
		if(instanceExtension.isDirty(7))
		{
			record.set(7,concreteBean.getEdad());
		}
		if(instanceExtension.isDirty(8))
		{
			record.set(8,concreteBean.getEstcivil());
		}
		if(instanceExtension.isDirty(9))
		{
			record.set(9,concreteBean.getCalle());
		}
		if(instanceExtension.isDirty(10))
		{
			record.set(10,concreteBean.getNro());
		}
		if(instanceExtension.isDirty(11))
		{
			record.set(11,concreteBean.getPerfil());
		}
		if(instanceExtension.isDirty(12))
		{
			record.set(12,concreteBean.getDirec1());
		}
		if(instanceExtension.isDirty(13))
		{
			record.set(13,concreteBean.getDistrito());
		}
		if(instanceExtension.isDirty(14))
		{
			record.set(14,concreteBean.getProvincia());
		}
		if(instanceExtension.isDirty(15))
		{
			record.set(15,concreteBean.getDepartamento());
		}
		if(instanceExtension.isDirty(16))
		{
			record.set(16,concreteBean.getTipo_persona());
		}
		if(instanceExtension.isDirty(17))
		{
			record.set(17,concreteBean.getClasificacion());
		}
		if(instanceExtension.isDirty(18))
		{
			record.set(18,concreteBean.getTelefono());
		}
		if(instanceExtension.isDirty(19))
		{
			record.set(19,concreteBean.getVinculacion());
		}
		if(instanceExtension.isDirty(20))
		{
			record.set(20,concreteBean.getPper());
		}
		if(instanceExtension.isDirty(21))
		{
			record.set(21,concreteBean.getPcom());
		}
		if(instanceExtension.isDirty(22))
		{
			record.set(22,concreteBean.getVnac());
		}
		if(instanceExtension.isDirty(23))
		{
			record.set(23,concreteBean.getCcte());
		}
		if(instanceExtension.isDirty(24))
		{
			record.set(24,concreteBean.getColb());
		}
		if(instanceExtension.isDirty(25))
		{
			record.set(25,concreteBean.getCnet());
		}
		if(instanceExtension.isDirty(26))
		{
			record.set(26,concreteBean.getPaut());
		}
		if(instanceExtension.isDirty(27))
		{
			record.set(27,concreteBean.getDsct());
		}
		if(instanceExtension.isDirty(28))
		{
			record.set(28,concreteBean.getVarc());
		}
		if(instanceExtension.isDirty(29))
		{
			record.set(29,concreteBean.getCemp());
		}
		if(instanceExtension.isDirty(30))
		{
			record.set(30,concreteBean.getSdep());
		}
		if(instanceExtension.isDirty(31))
		{
			record.set(31,concreteBean.getCext());
		}
		if(instanceExtension.isDirty(32))
		{
			record.set(32,concreteBean.getPhip());
		}
		if(instanceExtension.isDirty(33))
		{
			record.set(33,concreteBean.getLeas());
		}
		if(instanceExtension.isDirty(34))
		{
			record.set(34,concreteBean.getVcla());
		}
		if(instanceExtension.isDirty(35))
		{
			record.set(35,concreteBean.getCvip());
		}
		if(instanceExtension.isDirty(36))
		{
			record.set(36,concreteBean.getSvid());
		}
		if(instanceExtension.isDirty(37))
		{
			record.set(37,concreteBean.getLinco());
		}
		if(instanceExtension.isDirty(38))
		{
			record.set(38,concreteBean.getPmiv());
		}
		if(instanceExtension.isDirty(39))
		{
			record.set(39,concreteBean.getCloc());
		}
		if(instanceExtension.isDirty(40))
		{
			record.set(40,concreteBean.getVrep());
		}
		if(instanceExtension.isDirty(41))
		{
			record.set(41,concreteBean.getAhsd());
		}
		if(instanceExtension.isDirty(42))
		{
			record.set(42,concreteBean.getSonc());
		}
		if(instanceExtension.isDirty(43))
		{
			record.set(43,concreteBean.getTco());
		}
		if(instanceExtension.isDirty(44))
		{
			record.set(44,concreteBean.getB24());
		}
		if(instanceExtension.isDirty(45))
		{
			record.set(45,concreteBean.getCpte());
		}
		if(instanceExtension.isDirty(46))
		{
			record.set(46,concreteBean.getPref());
		}
		if(instanceExtension.isDirty(47))
		{
			record.set(47,concreteBean.getVoro());
		}
		if(instanceExtension.isDirty(48))
		{
			record.set(48,concreteBean.getAhor());
		}
		if(instanceExtension.isDirty(49))
		{
			record.set(49,concreteBean.getSpro());
		}
		if(instanceExtension.isDirty(50))
		{
			record.set(50,concreteBean.getPos());
		}
		if(instanceExtension.isDirty(51))
		{
			record.set(51,concreteBean.getT_act2());
		}
		if(instanceExtension.isDirty(52))
		{
			record.set(52,concreteBean.getPmas());
		}
		if(instanceExtension.isDirty(53))
		{
			record.set(53,concreteBean.getT_act3());
		}
		if(instanceExtension.isDirty(54))
		{
			record.set(54,concreteBean.getLcta());
		}
		if(instanceExtension.isDirty(55))
		{
			record.set(55,concreteBean.getT_act4());
		}
		if(instanceExtension.isDirty(56))
		{
			record.set(56,concreteBean.getVpla());
		}
		if(instanceExtension.isDirty(57))
		{
			record.set(57,concreteBean.getT_act5());
		}
		if(instanceExtension.isDirty(58))
		{
			record.set(58,concreteBean.getPlzo());
		}
		if(instanceExtension.isDirty(59))
		{
			record.set(59,concreteBean.getT_act6());
		}
		if(instanceExtension.isDirty(60))
		{
			record.set(60,concreteBean.getPserv());
		}
		if(instanceExtension.isDirty(61))
		{
			record.set(61,concreteBean.getTpr());
		}
		if(instanceExtension.isDirty(62))
		{
			record.set(62,concreteBean.getProm());
		}
		if(instanceExtension.isDirty(63))
		{
			record.set(63,concreteBean.getT_act_ct2());
		}
		if(instanceExtension.isDirty(64))
		{
			record.set(64,concreteBean.getVemp());
		}
		if(instanceExtension.isDirty(65))
		{
			record.set(65,concreteBean.getT_act_ct3());
		}
		if(instanceExtension.isDirty(66))
		{
			record.set(66,concreteBean.getPh());
		}
		if(instanceExtension.isDirty(67))
		{
			record.set(67,concreteBean.getT_act_ct4());
		}
		if(instanceExtension.isDirty(68))
		{
			record.set(68,concreteBean.getFcex());
		}
		if(instanceExtension.isDirty(69))
		{
			record.set(69,concreteBean.getT_act_ct5());
		}
		if(instanceExtension.isDirty(70))
		{
			record.set(70,concreteBean.getVctr());
		}
		if(instanceExtension.isDirty(71))
		{
			record.set(71,concreteBean.getT_act_ct6());
		}
		if(instanceExtension.isDirty(72))
		{
			record.set(72,concreteBean.getFmut());
		}
		if(instanceExtension.isDirty(73))
		{
			record.set(73,concreteBean.getMargeno());
		}
		if(instanceExtension.isDirty(74))
		{
			record.set(74,concreteBean.getNro_documento());
		}
		if(instanceExtension.isDirty(75))
		{
			record.set(75,concreteBean.getBcorie());
		}
		if(instanceExtension.isDirty(76))
		{
			record.set(76,concreteBean.getEmph());
		}
		if(instanceExtension.isDirty(77))
		{
			record.set(77,concreteBean.getBcorid());
		}
		if(instanceExtension.isDirty(78))
		{
			record.set(78,concreteBean.getAval());
		}
		if(instanceExtension.isDirty(79))
		{
			record.set(79,concreteBean.getBcorii());
		}
		if(instanceExtension.isDirty(80))
		{
			record.set(80,concreteBean.getMcla());
		}
		if(instanceExtension.isDirty(81))
		{
			record.set(81,concreteBean.getBcopas());
		}
		if(instanceExtension.isDirty(82))
		{
			record.set(82,concreteBean.getCts());
		}
		if(instanceExtension.isDirty(83))
		{
			record.set(83,concreteBean.getBcovol());
		}
		if(instanceExtension.isDirty(84))
		{
			record.set(84,concreteBean.getTdeb());
		}
		if(instanceExtension.isDirty(85))
		{
			record.set(85,concreteBean.getPorcrie());
		}
		if(instanceExtension.isDirty(86))
		{
			record.set(86,concreteBean.getMoro());
		}
		if(instanceExtension.isDirty(87))
		{
			record.set(87,concreteBean.getPorcrid());
		}
		if(instanceExtension.isDirty(88))
		{
			record.set(88,concreteBean.getCtsd());
		}
		if(instanceExtension.isDirty(89))
		{
			record.set(89,concreteBean.getPorcrii());
		}
		if(instanceExtension.isDirty(90))
		{
			record.set(90,concreteBean.getTvip());
		}
		if(instanceExtension.isDirty(91))
		{
			record.set(91,concreteBean.getSbsrie());
		}
		if(instanceExtension.isDirty(92))
		{
			record.set(92,concreteBean.getSbsrid());
		}
		if(instanceExtension.isDirty(93))
		{
			record.set(93,concreteBean.getSbsrii());
		}
		if(instanceExtension.isDirty(94))
		{
			record.set(94,concreteBean.getSbsjud());
		}
		if(instanceExtension.isDirty(95))
		{
			record.set(95,concreteBean.getCod_empresa());
		}
		if(instanceExtension.isDirty(96))
		{
			record.set(96,concreteBean.getDes_empresa());
		}
		if(instanceExtension.isDirty(97))
		{
			record.set(97,concreteBean.getIntervpas());
		}
		if(instanceExtension.isDirty(98))
		{
			record.set(98,concreteBean.getMofactv());
		}
		if(instanceExtension.isDirty(99))
		{
			record.set(99,concreteBean.getCs000lineamaxtc());
		}
		if(instanceExtension.isDirty(100))
		{
			record.set(100,concreteBean.getMofpasv());
		}
		if(instanceExtension.isDirty(101))
		{
			record.set(101,concreteBean.getMofserv());
		}
		if(instanceExtension.isDirty(102))
		{
			record.set(102,concreteBean.getMofcanal());
		}
		if(instanceExtension.isDirty(103))
		{
			record.set(103,concreteBean.getMphpasv());
		}
		if(instanceExtension.isDirty(104))
		{
			record.set(104,concreteBean.getCs000mtoprestamo());
		}
		if(instanceExtension.isDirty(105))
		{
			record.set(105,concreteBean.getMontovehicular());
		}
		if(instanceExtension.isDirty(107))
		{
			record.set(106,concreteBean.getCtacteoferta());
		}
		if(instanceExtension.isDirty(108))
		{
			record.set(107,concreteBean.getCtaahoferta());
		}
		if(instanceExtension.isDirty(109))
		{
			record.set(108,concreteBean.getCtapoferta());
		}
		if(instanceExtension.isDirty(110))
		{
			record.set(109,concreteBean.getFmutuoofert());
		}
		if(instanceExtension.isDirty(111))
		{
			record.set(110,concreteBean.getCtactsofert());
		}
		if(instanceExtension.isDirty(112))
		{
			record.set(111,concreteBean.getTconsactv());
		}
		if(instanceExtension.isDirty(113))
		{
			record.set(112,concreteBean.getMontosubrogados());
		}
		if(instanceExtension.isDirty(114))
		{
			record.set(113,concreteBean.getTsubactv());
		}
		if(instanceExtension.isDirty(115))
		{
			record.set(114,concreteBean.getThipotactv());
		}
		if(instanceExtension.isDirty(116))
		{
			record.set(115,concreteBean.getTvehicactv());
		}
		if(instanceExtension.isDirty(118))
		{
			record.set(116,concreteBean.getTcuot36act());
		}
		if(instanceExtension.isDirty(120))
		{
			record.set(117,concreteBean.getTcuot48act());
		}
		if(instanceExtension.isDirty(121))
		{
			record.set(118,concreteBean.getCs000montocta60());
		}
		if(instanceExtension.isDirty(122))
		{
			record.set(119,concreteBean.getTcuot60act());
		}
		if(instanceExtension.isDirty(123))
		{
			record.set(120,concreteBean.getCss000presmena5000());
		}
		if(instanceExtension.isDirty(124))
		{
			record.set(121,concreteBean.getCs000comisdesemen5000());
		}
		if(instanceExtension.isDirty(125))
		{
			record.set(122,concreteBean.getCs000pres5000a15000());
		}
		if(instanceExtension.isDirty(126))
		{
			record.set(123,concreteBean.getC5000comdes15000act());
		}
		if(instanceExtension.isDirty(127))
		{
			record.set(124,concreteBean.getCs000presmaya15000());
		}
		if(instanceExtension.isDirty(128))
		{
			record.set(125,concreteBean.getComdes15000ac());
		}
		if(instanceExtension.isDirty(129))
		{
			record.set(126,concreteBean.getCs000linminadqtc());
		}
		if(instanceExtension.isDirty(130))
		{
			record.set(127,concreteBean.getCs000tipodecredito());
		}
		if(instanceExtension.isDirty(131))
		{
			record.set(128,concreteBean.getCs000mixmonprest());
		}
		if(instanceExtension.isDirty(132))
		{
			record.set(129,concreteBean.getCs000mixlinasistc());
		}
		if(instanceExtension.isDirty(133))
		{
			record.set(130,concreteBean.getCs000mixtipotc());
		}
		if(instanceExtension.isDirty(134))
		{
			record.set(131,concreteBean.getCs000prestcmena5000());
		}
		if(instanceExtension.isDirty(135))
		{
			record.set(132,concreteBean.getCs000prestc500015000());
		}
		if(instanceExtension.isDirty(136))
		{
			record.set(133,concreteBean.getCs000prestcmaya15000());
		}
		if(instanceExtension.isDirty(137))
		{
			record.set(134,concreteBean.getAtribctactepasv());
		}
		if(instanceExtension.isDirty(138))
		{
			record.set(135,concreteBean.getAtribctaahpasv());
		}
		if(instanceExtension.isDirty(139))
		{
			record.set(136,concreteBean.getAtribctaplazpasv());
		}
		if(instanceExtension.isDirty(140))
		{
			record.set(137,concreteBean.getAtribctspasv());
		}
		if(instanceExtension.isDirty(141))
		{
			record.set(138,concreteBean.getAtribfmutuopasv());
		}
		if(instanceExtension.isDirty(142))
		{
			record.set(139,concreteBean.getCobofserv());
		}
		if(instanceExtension.isDirty(143))
		{
			record.set(140,concreteBean.getSvidofserv());
		}
		if(instanceExtension.isDirty(144))
		{
			record.set(141,concreteBean.getSoncofserv());
		}
		if(instanceExtension.isDirty(145))
		{
			record.set(142,concreteBean.getSvincofserv());
		}
		if(instanceExtension.isDirty(146))
		{
			record.set(143,concreteBean.getPhofserv());
		}
		if(instanceExtension.isDirty(147))
		{
			record.set(144,concreteBean.getDebofserv());
		}
		if(instanceExtension.isDirty(148))
		{
			record.set(145,concreteBean.getVipofserv());
		}
		if(instanceExtension.isDirty(149))
		{
			record.set(146,concreteBean.getOfcnetcan());
		}
		if(instanceExtension.isDirty(150))
		{
			record.set(147,concreteBean.getOfcempcan());
		}
		if(instanceExtension.isDirty(151))
		{
			record.set(148,concreteBean.getOflincocan());
		}
		if(instanceExtension.isDirty(152))
		{
			record.set(149,concreteBean.getOfb24can());
		}
		if(instanceExtension.isDirty(153))
		{
			record.set(150,concreteBean.getOfposcan());
		}
		if(instanceExtension.isDirty(154))
		{
			record.set(151,concreteBean.getPrefijo());
		}
		if(instanceExtension.isDirty(106))
		{
			record.set(152,concreteBean.getMontohipotecario());
		}
		if(instanceExtension.isDirty(117))
		{
			record.set(153,concreteBean.getCs000montocta36());
		}
		if(instanceExtension.isDirty(119))
		{
			record.set(154,concreteBean.getCs000montocta48());
		}
	}
	/**
	 * ejbStoreGetDirtyColumnFields
	 */
	public void ejbStoreGetDirtyColumnFields(com.ibm.ws.ejbpersistence.beanextensions.ConcreteBean cb, boolean[] dirtyBitmap) {
		
	}
}
