package com.grupobbva.bc.per.tel.iilc.entity.websphere_deploy.ORACLE_V10_1;

/**
 * Tiilc_totalBeanInjectorImpl_40ed895e
 */
public class Tiilc_totalBeanInjectorImpl_40ed895e implements com.grupobbva.bc.per.tel.iilc.entity.websphere_deploy.Tiilc_totalBeanInjector_40ed895e {
	/**
	 * ejbCreate
	 */
	public void ejbCreate(com.ibm.ws.ejbpersistence.beanextensions.ConcreteBean cb, javax.resource.cci.IndexedRecord record) {
		com.grupobbva.bc.per.tel.iilc.entity.ConcreteTiilc_total_40ed895e concreteBean=(com.grupobbva.bc.per.tel.iilc.entity.ConcreteTiilc_total_40ed895e)cb;
		record.set(0,concreteBean.getCod_total());
		record.set(1,concreteBean.getCod_territorio());
		record.set(2,concreteBean.getInd_registro());
		record.set(3,concreteBean.getCod_oficina());
		record.set(4,concreteBean.getCod_gestor());
		record.set(5,concreteBean.getClixgest());
		record.set(6,concreteBean.getSeg_10100());
		record.set(7,concreteBean.getSeg_10200());
		record.set(8,concreteBean.getSeg_20100());
		record.set(9,concreteBean.getSeg_20200());
		record.set(10,concreteBean.getSeg_20300());
		record.set(11,concreteBean.getSeg_20400());
		record.set(12,concreteBean.getSeg_20500());
		record.set(13,concreteBean.getSeg_20600());
		record.set(14,concreteBean.getSeg_30100());
		record.set(15,concreteBean.getSeg_30200());
		record.set(16,concreteBean.getSeg_30300());
		record.set(17,concreteBean.getSeg_30400());
		record.set(18,concreteBean.getSeg_40100());
		record.set(19,concreteBean.getSeg_40200());
		record.set(20,concreteBean.getSeg_40300());
		record.set(21,concreteBean.getSeg_40400());
		record.set(22,concreteBean.getSeg_50100());
		record.set(23,concreteBean.getSeg_50200());
		record.set(24,concreteBean.getSeg_50300());
		record.set(25,concreteBean.getSeg_50400());
		record.set(26,concreteBean.getSeg_60100());
		record.set(27,concreteBean.getSeg_60200());
		record.set(28,concreteBean.getSeg_60300());
		record.set(29,concreteBean.getSeg_60400());
		record.set(30,concreteBean.getSeg_80100());
		record.set(31,concreteBean.getSeg_80200());
		record.set(32,concreteBean.getSeg_80300());
		record.set(33,concreteBean.getSeg_80400());
		record.set(34,concreteBean.getSeg_80500());
		record.set(35,concreteBean.getSeg_80600());
		record.set(36,concreteBean.getSeg_80700());
		record.set(37,concreteBean.getSeg_90200());
		record.set(38,concreteBean.getSeg_99900());
		record.set(39,concreteBean.getDesvin());
		record.set(40,concreteBean.getPocovin());
		record.set(41,concreteBean.getVin());
		record.set(42,concreteBean.getMuyvin());
		record.set(43,concreteBean.getNatdesvin());
		record.set(44,concreteBean.getNatvin());
		record.set(45,concreteBean.getJurvin());
		record.set(46,concreteBean.getAhor_t());
		record.set(47,concreteBean.getAhsd_t());
		record.set(48,concreteBean.getAval_t());
		record.set(49,concreteBean.getB24_t());
		record.set(50,concreteBean.getCcte_t());
		record.set(51,concreteBean.getCext_t());
		record.set(52,concreteBean.getCloc_t());
		record.set(53,concreteBean.getColb_t());
		record.set(54,concreteBean.getCpte_t());
		record.set(55,concreteBean.getCts_t());
		record.set(56,concreteBean.getCtsd_t());
		record.set(57,concreteBean.getVip_t());
		record.set(58,concreteBean.getDsct_t());
		record.set(59,concreteBean.getFcex_t());
		record.set(60,concreteBean.getFmut_t());
		record.set(61,concreteBean.getLcta_t());
		record.set(62,concreteBean.getLeas_t());
		record.set(63,concreteBean.getMcla_t());
		record.set(64,concreteBean.getMoro_t());
		record.set(65,concreteBean.getMp_t());
		record.set(66,concreteBean.getPaut_t());
		record.set(67,concreteBean.getPcom_t());
		record.set(68,concreteBean.getPer_t());
		record.set(69,concreteBean.getPh_t());
		record.set(70,concreteBean.getPhip_t());
		record.set(71,concreteBean.getPlzo_t());
		record.set(72,concreteBean.getPmas_t());
		record.set(73,concreteBean.getPmiv_t());
		record.set(74,concreteBean.getPper_t());
		record.set(75,concreteBean.getPpper_t());
		record.set(76,concreteBean.getPref_t());
		record.set(77,concreteBean.getProm_t());
		record.set(78,concreteBean.getPser_t());
		record.set(79,concreteBean.getPserv_t());
		record.set(80,concreteBean.getDep_t());
		record.set(81,concreteBean.getSdep_t());
		record.set(82,concreteBean.getSext_t());
		record.set(83,concreteBean.getSonc_t());
		record.set(84,concreteBean.getSpro_t());
		record.set(85,concreteBean.getVid_t());
		record.set(86,concreteBean.getSvid_t());
		record.set(87,concreteBean.getTde_t());
		record.set(88,concreteBean.getSvip_t());
		record.set(89,concreteBean.getTvip_t());
		record.set(90,concreteBean.getVarc_t());
		record.set(91,concreteBean.getVcla_t());
		record.set(92,concreteBean.getVctr_t());
		record.set(93,concreteBean.getVemp_t());
		record.set(94,concreteBean.getVnac_t());
		record.set(95,concreteBean.getVoro_t());
		record.set(96,concreteBean.getVpla_t());
		record.set(97,concreteBean.getVpola_t());
		record.set(98,concreteBean.getVrep_t());
		record.set(99,concreteBean.getTdeb_t());
		record.set(100,concreteBean.getCnet_t());
		record.set(101,concreteBean.getLinco_t());
		record.set(102,concreteBean.getPos_t());
		record.set(103,concreteBean.getEmph_t());
		record.set(104,concreteBean.getRiesgo_d_t());
		record.set(105,concreteBean.getRiesgo_i_t());
		record.set(106,concreteBean.getRiesgo_t());
		record.set(107,concreteBean.getPasivo_t());
		record.set(108,concreteBean.getVolumen_t());
		record.set(109,concreteBean.getSum_t_act());
		record.set(110,concreteBean.getSum_t_act1());
		record.set(111,concreteBean.getSum_t_act2());
		record.set(112,concreteBean.getSum_t_act3());
		record.set(113,concreteBean.getSum_t_act4());
		record.set(114,concreteBean.getSum_t_act5());
		record.set(115,concreteBean.getSum_t_act6());
		record.set(116,concreteBean.getSum_act_cto());
		record.set(117,concreteBean.getSum_act_ct1());
		record.set(118,concreteBean.getSum_act_ct2());
		record.set(119,concreteBean.getSum_act_ct3());
		record.set(120,concreteBean.getSum_act_ct4());
		record.set(121,concreteBean.getSum_act_ct5());
		record.set(122,concreteBean.getSum_act_ct6());
		record.set(123,concreteBean.getCemp_t());
		record.set(124,concreteBean.getCvip_t());
		record.set(125,concreteBean.getIcalicte00());
		record.set(126,concreteBean.getIcalicte10());
		record.set(127,concreteBean.getIcalicte20());
		record.set(128,concreteBean.getIcalicte30());
		record.set(129,concreteBean.getIcalicte40());
		record.set(130,concreteBean.getMofactv_t());
		record.set(131,concreteBean.getCs000lineamaxtc_t());
		record.set(132,concreteBean.getCs000mtoprestamo_t());
		record.set(133,concreteBean.getMontovehicular_t());
		record.set(134,concreteBean.getMontohipotecario_t());
		record.set(135,concreteBean.getMontosubrogados_t());
	}
	/**
	 * ejbStore
	 */
	public void ejbStore(com.ibm.ws.ejbpersistence.beanextensions.ConcreteBean cb, javax.resource.cci.IndexedRecord record) {
		com.grupobbva.bc.per.tel.iilc.entity.ConcreteTiilc_total_40ed895e concreteBean=(com.grupobbva.bc.per.tel.iilc.entity.ConcreteTiilc_total_40ed895e)cb;
		record.set(0,concreteBean.getCod_total());
		record.set(1,concreteBean.getCod_territorio());
		record.set(2,concreteBean.getInd_registro());
		record.set(3,concreteBean.getCod_oficina());
		record.set(4,concreteBean.getCod_gestor());
		record.set(5,concreteBean.getClixgest());
		record.set(6,concreteBean.getSeg_10100());
		record.set(7,concreteBean.getSeg_10200());
		record.set(8,concreteBean.getSeg_20100());
		record.set(9,concreteBean.getSeg_20200());
		record.set(10,concreteBean.getSeg_20300());
		record.set(11,concreteBean.getSeg_20400());
		record.set(12,concreteBean.getSeg_20500());
		record.set(13,concreteBean.getSeg_20600());
		record.set(14,concreteBean.getSeg_30100());
		record.set(15,concreteBean.getSeg_30200());
		record.set(16,concreteBean.getSeg_30300());
		record.set(17,concreteBean.getSeg_30400());
		record.set(18,concreteBean.getSeg_40100());
		record.set(19,concreteBean.getSeg_40200());
		record.set(20,concreteBean.getSeg_40300());
		record.set(21,concreteBean.getSeg_40400());
		record.set(22,concreteBean.getSeg_50100());
		record.set(23,concreteBean.getSeg_50200());
		record.set(24,concreteBean.getSeg_50300());
		record.set(25,concreteBean.getSeg_50400());
		record.set(26,concreteBean.getSeg_60100());
		record.set(27,concreteBean.getSeg_60200());
		record.set(28,concreteBean.getSeg_60300());
		record.set(29,concreteBean.getSeg_60400());
		record.set(30,concreteBean.getSeg_80100());
		record.set(31,concreteBean.getSeg_80200());
		record.set(32,concreteBean.getSeg_80300());
		record.set(33,concreteBean.getSeg_80400());
		record.set(34,concreteBean.getSeg_80500());
		record.set(35,concreteBean.getSeg_80600());
		record.set(36,concreteBean.getSeg_80700());
		record.set(37,concreteBean.getSeg_90200());
		record.set(38,concreteBean.getSeg_99900());
		record.set(39,concreteBean.getDesvin());
		record.set(40,concreteBean.getPocovin());
		record.set(41,concreteBean.getVin());
		record.set(42,concreteBean.getMuyvin());
		record.set(43,concreteBean.getNatdesvin());
		record.set(44,concreteBean.getNatvin());
		record.set(45,concreteBean.getJurvin());
		record.set(46,concreteBean.getAhor_t());
		record.set(47,concreteBean.getAhsd_t());
		record.set(48,concreteBean.getAval_t());
		record.set(49,concreteBean.getB24_t());
		record.set(50,concreteBean.getCcte_t());
		record.set(51,concreteBean.getCext_t());
		record.set(52,concreteBean.getCloc_t());
		record.set(53,concreteBean.getColb_t());
		record.set(54,concreteBean.getCpte_t());
		record.set(55,concreteBean.getCts_t());
		record.set(56,concreteBean.getCtsd_t());
		record.set(57,concreteBean.getVip_t());
		record.set(58,concreteBean.getDsct_t());
		record.set(59,concreteBean.getFcex_t());
		record.set(60,concreteBean.getFmut_t());
		record.set(61,concreteBean.getLcta_t());
		record.set(62,concreteBean.getLeas_t());
		record.set(63,concreteBean.getMcla_t());
		record.set(64,concreteBean.getMoro_t());
		record.set(65,concreteBean.getMp_t());
		record.set(66,concreteBean.getPaut_t());
		record.set(67,concreteBean.getPcom_t());
		record.set(68,concreteBean.getPer_t());
		record.set(69,concreteBean.getPh_t());
		record.set(70,concreteBean.getPhip_t());
		record.set(71,concreteBean.getPlzo_t());
		record.set(72,concreteBean.getPmas_t());
		record.set(73,concreteBean.getPmiv_t());
		record.set(74,concreteBean.getPper_t());
		record.set(75,concreteBean.getPpper_t());
		record.set(76,concreteBean.getPref_t());
		record.set(77,concreteBean.getProm_t());
		record.set(78,concreteBean.getPser_t());
		record.set(79,concreteBean.getPserv_t());
		record.set(80,concreteBean.getDep_t());
		record.set(81,concreteBean.getSdep_t());
		record.set(82,concreteBean.getSext_t());
		record.set(83,concreteBean.getSonc_t());
		record.set(84,concreteBean.getSpro_t());
		record.set(85,concreteBean.getVid_t());
		record.set(86,concreteBean.getSvid_t());
		record.set(87,concreteBean.getTde_t());
		record.set(88,concreteBean.getSvip_t());
		record.set(89,concreteBean.getTvip_t());
		record.set(90,concreteBean.getVarc_t());
		record.set(91,concreteBean.getVcla_t());
		record.set(92,concreteBean.getVctr_t());
		record.set(93,concreteBean.getVemp_t());
		record.set(94,concreteBean.getVnac_t());
		record.set(95,concreteBean.getVoro_t());
		record.set(96,concreteBean.getVpla_t());
		record.set(97,concreteBean.getVpola_t());
		record.set(98,concreteBean.getVrep_t());
		record.set(99,concreteBean.getTdeb_t());
		record.set(100,concreteBean.getCnet_t());
		record.set(101,concreteBean.getLinco_t());
		record.set(102,concreteBean.getPos_t());
		record.set(103,concreteBean.getEmph_t());
		record.set(104,concreteBean.getRiesgo_d_t());
		record.set(105,concreteBean.getRiesgo_i_t());
		record.set(106,concreteBean.getRiesgo_t());
		record.set(107,concreteBean.getPasivo_t());
		record.set(108,concreteBean.getVolumen_t());
		record.set(109,concreteBean.getSum_t_act());
		record.set(110,concreteBean.getSum_t_act1());
		record.set(111,concreteBean.getSum_t_act2());
		record.set(112,concreteBean.getSum_t_act3());
		record.set(113,concreteBean.getSum_t_act4());
		record.set(114,concreteBean.getSum_t_act5());
		record.set(115,concreteBean.getSum_t_act6());
		record.set(116,concreteBean.getSum_act_cto());
		record.set(117,concreteBean.getSum_act_ct1());
		record.set(118,concreteBean.getSum_act_ct2());
		record.set(119,concreteBean.getSum_act_ct3());
		record.set(120,concreteBean.getSum_act_ct4());
		record.set(121,concreteBean.getSum_act_ct5());
		record.set(122,concreteBean.getSum_act_ct6());
		record.set(123,concreteBean.getCemp_t());
		record.set(124,concreteBean.getCvip_t());
		record.set(125,concreteBean.getIcalicte00());
		record.set(126,concreteBean.getIcalicte10());
		record.set(127,concreteBean.getIcalicte20());
		record.set(128,concreteBean.getIcalicte30());
		record.set(129,concreteBean.getIcalicte40());
		record.set(130,concreteBean.getMofactv_t());
		record.set(131,concreteBean.getCs000lineamaxtc_t());
		record.set(132,concreteBean.getCs000mtoprestamo_t());
		record.set(133,concreteBean.getMontovehicular_t());
		record.set(134,concreteBean.getMontohipotecario_t());
		record.set(135,concreteBean.getMontosubrogados_t());
	}
	/**
	 * ejbRemove
	 */
	public void ejbRemove(com.ibm.ws.ejbpersistence.beanextensions.ConcreteBean cb, javax.resource.cci.IndexedRecord record) {
		com.grupobbva.bc.per.tel.iilc.entity.ConcreteTiilc_total_40ed895e concreteBean=(com.grupobbva.bc.per.tel.iilc.entity.ConcreteTiilc_total_40ed895e)cb;
		record.set(0,concreteBean.getCod_total());
	}
	/**
	 * ejbFindTotalxGexOfxTe
	 */
	public void ejbFindTotalxGexOfxTe(java.lang.String ind_registro, java.lang.String cod_territorio, java.lang.String cod_oficina, java.lang.String cod_gestor, javax.resource.cci.IndexedRecord record) {
		record.set(0,ind_registro);
		record.set(1,cod_territorio);
		record.set(2,cod_oficina);
		record.set(3,cod_gestor);
	}
	/**
	 * ejbFindByPrimaryKey
	 */
	public void ejbFindByPrimaryKey(Object pkeyObject, javax.resource.cci.IndexedRecord record) {
		com.grupobbva.bc.per.tel.iilc.entity.Tiilc_totalKey pkey=(com.grupobbva.bc.per.tel.iilc.entity.Tiilc_totalKey)pkeyObject;
		record.set(0,pkey.cod_total);
	}
	/**
	 * readReadChecking
	 */
	public void readReadChecking(com.ibm.ws.ejbpersistence.beanextensions.ConcreteBean cb, javax.resource.cci.IndexedRecord record) {
		com.grupobbva.bc.per.tel.iilc.entity.ConcreteTiilc_total_40ed895e concreteBean=(com.grupobbva.bc.per.tel.iilc.entity.ConcreteTiilc_total_40ed895e)cb;
		record.set(0,concreteBean.getCod_total());
	}
	/**
	 * ejbPartialStore
	 */
	public void ejbPartialStore(com.ibm.ws.ejbpersistence.beanextensions.ConcreteBean cb, javax.resource.cci.IndexedRecord record) {
		com.grupobbva.bc.per.tel.iilc.entity.ConcreteTiilc_total_40ed895e concreteBean=(com.grupobbva.bc.per.tel.iilc.entity.ConcreteTiilc_total_40ed895e)cb;
		com.ibm.ws.ejbpersistence.beanextensions.ConcreteBeanInstanceExtension  instanceExtension = (com.ibm.ws.ejbpersistence.beanextensions.ConcreteBeanInstanceExtension)concreteBean._WSCB_getInstanceInfo();
		 
		record.set(0,concreteBean.getCod_total());
		if(instanceExtension.isDirty(1))
		{
			record.set(1,concreteBean.getCod_territorio());
		}
		if(instanceExtension.isDirty(2))
		{
			record.set(2,concreteBean.getInd_registro());
		}
		if(instanceExtension.isDirty(3))
		{
			record.set(3,concreteBean.getCod_oficina());
		}
		if(instanceExtension.isDirty(4))
		{
			record.set(4,concreteBean.getCod_gestor());
		}
		if(instanceExtension.isDirty(5))
		{
			record.set(5,concreteBean.getClixgest());
		}
		if(instanceExtension.isDirty(6))
		{
			record.set(6,concreteBean.getSeg_10100());
		}
		if(instanceExtension.isDirty(7))
		{
			record.set(7,concreteBean.getSeg_10200());
		}
		if(instanceExtension.isDirty(8))
		{
			record.set(8,concreteBean.getSeg_20100());
		}
		if(instanceExtension.isDirty(9))
		{
			record.set(9,concreteBean.getSeg_20200());
		}
		if(instanceExtension.isDirty(10))
		{
			record.set(10,concreteBean.getSeg_20300());
		}
		if(instanceExtension.isDirty(11))
		{
			record.set(11,concreteBean.getSeg_20400());
		}
		if(instanceExtension.isDirty(12))
		{
			record.set(12,concreteBean.getSeg_20500());
		}
		if(instanceExtension.isDirty(13))
		{
			record.set(13,concreteBean.getSeg_20600());
		}
		if(instanceExtension.isDirty(14))
		{
			record.set(14,concreteBean.getSeg_30100());
		}
		if(instanceExtension.isDirty(15))
		{
			record.set(15,concreteBean.getSeg_30200());
		}
		if(instanceExtension.isDirty(16))
		{
			record.set(16,concreteBean.getSeg_30300());
		}
		if(instanceExtension.isDirty(17))
		{
			record.set(17,concreteBean.getSeg_30400());
		}
		if(instanceExtension.isDirty(18))
		{
			record.set(18,concreteBean.getSeg_40100());
		}
		if(instanceExtension.isDirty(19))
		{
			record.set(19,concreteBean.getSeg_40200());
		}
		if(instanceExtension.isDirty(20))
		{
			record.set(20,concreteBean.getSeg_40300());
		}
		if(instanceExtension.isDirty(21))
		{
			record.set(21,concreteBean.getSeg_40400());
		}
		if(instanceExtension.isDirty(22))
		{
			record.set(22,concreteBean.getSeg_50100());
		}
		if(instanceExtension.isDirty(23))
		{
			record.set(23,concreteBean.getSeg_50200());
		}
		if(instanceExtension.isDirty(24))
		{
			record.set(24,concreteBean.getSeg_50300());
		}
		if(instanceExtension.isDirty(25))
		{
			record.set(25,concreteBean.getSeg_50400());
		}
		if(instanceExtension.isDirty(26))
		{
			record.set(26,concreteBean.getSeg_60100());
		}
		if(instanceExtension.isDirty(27))
		{
			record.set(27,concreteBean.getSeg_60200());
		}
		if(instanceExtension.isDirty(28))
		{
			record.set(28,concreteBean.getSeg_60300());
		}
		if(instanceExtension.isDirty(29))
		{
			record.set(29,concreteBean.getSeg_60400());
		}
		if(instanceExtension.isDirty(30))
		{
			record.set(30,concreteBean.getSeg_80100());
		}
		if(instanceExtension.isDirty(31))
		{
			record.set(31,concreteBean.getSeg_80200());
		}
		if(instanceExtension.isDirty(32))
		{
			record.set(32,concreteBean.getSeg_80300());
		}
		if(instanceExtension.isDirty(33))
		{
			record.set(33,concreteBean.getSeg_80400());
		}
		if(instanceExtension.isDirty(34))
		{
			record.set(34,concreteBean.getSeg_80500());
		}
		if(instanceExtension.isDirty(35))
		{
			record.set(35,concreteBean.getSeg_80600());
		}
		if(instanceExtension.isDirty(36))
		{
			record.set(36,concreteBean.getSeg_80700());
		}
		if(instanceExtension.isDirty(37))
		{
			record.set(37,concreteBean.getSeg_90200());
		}
		if(instanceExtension.isDirty(38))
		{
			record.set(38,concreteBean.getSeg_99900());
		}
		if(instanceExtension.isDirty(39))
		{
			record.set(39,concreteBean.getDesvin());
		}
		if(instanceExtension.isDirty(40))
		{
			record.set(40,concreteBean.getPocovin());
		}
		if(instanceExtension.isDirty(41))
		{
			record.set(41,concreteBean.getVin());
		}
		if(instanceExtension.isDirty(42))
		{
			record.set(42,concreteBean.getMuyvin());
		}
		if(instanceExtension.isDirty(43))
		{
			record.set(43,concreteBean.getNatdesvin());
		}
		if(instanceExtension.isDirty(44))
		{
			record.set(44,concreteBean.getNatvin());
		}
		if(instanceExtension.isDirty(45))
		{
			record.set(45,concreteBean.getJurvin());
		}
		if(instanceExtension.isDirty(46))
		{
			record.set(46,concreteBean.getAhor_t());
		}
		if(instanceExtension.isDirty(47))
		{
			record.set(47,concreteBean.getAhsd_t());
		}
		if(instanceExtension.isDirty(48))
		{
			record.set(48,concreteBean.getAval_t());
		}
		if(instanceExtension.isDirty(49))
		{
			record.set(49,concreteBean.getB24_t());
		}
		if(instanceExtension.isDirty(50))
		{
			record.set(50,concreteBean.getCcte_t());
		}
		if(instanceExtension.isDirty(51))
		{
			record.set(51,concreteBean.getCext_t());
		}
		if(instanceExtension.isDirty(52))
		{
			record.set(52,concreteBean.getCloc_t());
		}
		if(instanceExtension.isDirty(53))
		{
			record.set(53,concreteBean.getColb_t());
		}
		if(instanceExtension.isDirty(54))
		{
			record.set(54,concreteBean.getCpte_t());
		}
		if(instanceExtension.isDirty(55))
		{
			record.set(55,concreteBean.getCts_t());
		}
		if(instanceExtension.isDirty(56))
		{
			record.set(56,concreteBean.getCtsd_t());
		}
		if(instanceExtension.isDirty(57))
		{
			record.set(57,concreteBean.getVip_t());
		}
		if(instanceExtension.isDirty(58))
		{
			record.set(58,concreteBean.getDsct_t());
		}
		if(instanceExtension.isDirty(59))
		{
			record.set(59,concreteBean.getFcex_t());
		}
		if(instanceExtension.isDirty(60))
		{
			record.set(60,concreteBean.getFmut_t());
		}
		if(instanceExtension.isDirty(61))
		{
			record.set(61,concreteBean.getLcta_t());
		}
		if(instanceExtension.isDirty(62))
		{
			record.set(62,concreteBean.getLeas_t());
		}
		if(instanceExtension.isDirty(63))
		{
			record.set(63,concreteBean.getMcla_t());
		}
		if(instanceExtension.isDirty(64))
		{
			record.set(64,concreteBean.getMoro_t());
		}
		if(instanceExtension.isDirty(65))
		{
			record.set(65,concreteBean.getMp_t());
		}
		if(instanceExtension.isDirty(66))
		{
			record.set(66,concreteBean.getPaut_t());
		}
		if(instanceExtension.isDirty(67))
		{
			record.set(67,concreteBean.getPcom_t());
		}
		if(instanceExtension.isDirty(68))
		{
			record.set(68,concreteBean.getPer_t());
		}
		if(instanceExtension.isDirty(69))
		{
			record.set(69,concreteBean.getPh_t());
		}
		if(instanceExtension.isDirty(70))
		{
			record.set(70,concreteBean.getPhip_t());
		}
		if(instanceExtension.isDirty(71))
		{
			record.set(71,concreteBean.getPlzo_t());
		}
		if(instanceExtension.isDirty(72))
		{
			record.set(72,concreteBean.getPmas_t());
		}
		if(instanceExtension.isDirty(73))
		{
			record.set(73,concreteBean.getPmiv_t());
		}
		if(instanceExtension.isDirty(74))
		{
			record.set(74,concreteBean.getPper_t());
		}
		if(instanceExtension.isDirty(75))
		{
			record.set(75,concreteBean.getPpper_t());
		}
		if(instanceExtension.isDirty(76))
		{
			record.set(76,concreteBean.getPref_t());
		}
		if(instanceExtension.isDirty(77))
		{
			record.set(77,concreteBean.getProm_t());
		}
		if(instanceExtension.isDirty(78))
		{
			record.set(78,concreteBean.getPser_t());
		}
		if(instanceExtension.isDirty(79))
		{
			record.set(79,concreteBean.getPserv_t());
		}
		if(instanceExtension.isDirty(80))
		{
			record.set(80,concreteBean.getDep_t());
		}
		if(instanceExtension.isDirty(81))
		{
			record.set(81,concreteBean.getSdep_t());
		}
		if(instanceExtension.isDirty(82))
		{
			record.set(82,concreteBean.getSext_t());
		}
		if(instanceExtension.isDirty(83))
		{
			record.set(83,concreteBean.getSonc_t());
		}
		if(instanceExtension.isDirty(84))
		{
			record.set(84,concreteBean.getSpro_t());
		}
		if(instanceExtension.isDirty(85))
		{
			record.set(85,concreteBean.getVid_t());
		}
		if(instanceExtension.isDirty(86))
		{
			record.set(86,concreteBean.getSvid_t());
		}
		if(instanceExtension.isDirty(87))
		{
			record.set(87,concreteBean.getTde_t());
		}
		if(instanceExtension.isDirty(88))
		{
			record.set(88,concreteBean.getSvip_t());
		}
		if(instanceExtension.isDirty(89))
		{
			record.set(89,concreteBean.getTvip_t());
		}
		if(instanceExtension.isDirty(90))
		{
			record.set(90,concreteBean.getVarc_t());
		}
		if(instanceExtension.isDirty(91))
		{
			record.set(91,concreteBean.getVcla_t());
		}
		if(instanceExtension.isDirty(92))
		{
			record.set(92,concreteBean.getVctr_t());
		}
		if(instanceExtension.isDirty(93))
		{
			record.set(93,concreteBean.getVemp_t());
		}
		if(instanceExtension.isDirty(94))
		{
			record.set(94,concreteBean.getVnac_t());
		}
		if(instanceExtension.isDirty(95))
		{
			record.set(95,concreteBean.getVoro_t());
		}
		if(instanceExtension.isDirty(96))
		{
			record.set(96,concreteBean.getVpla_t());
		}
		if(instanceExtension.isDirty(97))
		{
			record.set(97,concreteBean.getVpola_t());
		}
		if(instanceExtension.isDirty(98))
		{
			record.set(98,concreteBean.getVrep_t());
		}
		if(instanceExtension.isDirty(99))
		{
			record.set(99,concreteBean.getTdeb_t());
		}
		if(instanceExtension.isDirty(100))
		{
			record.set(100,concreteBean.getCnet_t());
		}
		if(instanceExtension.isDirty(101))
		{
			record.set(101,concreteBean.getLinco_t());
		}
		if(instanceExtension.isDirty(102))
		{
			record.set(102,concreteBean.getPos_t());
		}
		if(instanceExtension.isDirty(103))
		{
			record.set(103,concreteBean.getEmph_t());
		}
		if(instanceExtension.isDirty(104))
		{
			record.set(104,concreteBean.getRiesgo_d_t());
		}
		if(instanceExtension.isDirty(105))
		{
			record.set(105,concreteBean.getRiesgo_i_t());
		}
		if(instanceExtension.isDirty(106))
		{
			record.set(106,concreteBean.getRiesgo_t());
		}
		if(instanceExtension.isDirty(107))
		{
			record.set(107,concreteBean.getPasivo_t());
		}
		if(instanceExtension.isDirty(108))
		{
			record.set(108,concreteBean.getVolumen_t());
		}
		if(instanceExtension.isDirty(109))
		{
			record.set(109,concreteBean.getSum_t_act());
		}
		if(instanceExtension.isDirty(110))
		{
			record.set(110,concreteBean.getSum_t_act1());
		}
		if(instanceExtension.isDirty(111))
		{
			record.set(111,concreteBean.getSum_t_act2());
		}
		if(instanceExtension.isDirty(112))
		{
			record.set(112,concreteBean.getSum_t_act3());
		}
		if(instanceExtension.isDirty(113))
		{
			record.set(113,concreteBean.getSum_t_act4());
		}
		if(instanceExtension.isDirty(114))
		{
			record.set(114,concreteBean.getSum_t_act5());
		}
		if(instanceExtension.isDirty(115))
		{
			record.set(115,concreteBean.getSum_t_act6());
		}
		if(instanceExtension.isDirty(116))
		{
			record.set(116,concreteBean.getSum_act_cto());
		}
		if(instanceExtension.isDirty(117))
		{
			record.set(117,concreteBean.getSum_act_ct1());
		}
		if(instanceExtension.isDirty(118))
		{
			record.set(118,concreteBean.getSum_act_ct2());
		}
		if(instanceExtension.isDirty(119))
		{
			record.set(119,concreteBean.getSum_act_ct3());
		}
		if(instanceExtension.isDirty(120))
		{
			record.set(120,concreteBean.getSum_act_ct4());
		}
		if(instanceExtension.isDirty(121))
		{
			record.set(121,concreteBean.getSum_act_ct5());
		}
		if(instanceExtension.isDirty(122))
		{
			record.set(122,concreteBean.getSum_act_ct6());
		}
		if(instanceExtension.isDirty(123))
		{
			record.set(123,concreteBean.getCemp_t());
		}
		if(instanceExtension.isDirty(124))
		{
			record.set(124,concreteBean.getCvip_t());
		}
		if(instanceExtension.isDirty(125))
		{
			record.set(125,concreteBean.getIcalicte00());
		}
		if(instanceExtension.isDirty(126))
		{
			record.set(126,concreteBean.getIcalicte10());
		}
		if(instanceExtension.isDirty(127))
		{
			record.set(127,concreteBean.getIcalicte20());
		}
		if(instanceExtension.isDirty(128))
		{
			record.set(128,concreteBean.getIcalicte30());
		}
		if(instanceExtension.isDirty(129))
		{
			record.set(129,concreteBean.getIcalicte40());
		}
		if(instanceExtension.isDirty(130))
		{
			record.set(130,concreteBean.getMofactv_t());
		}
		if(instanceExtension.isDirty(131))
		{
			record.set(131,concreteBean.getCs000lineamaxtc_t());
		}
		if(instanceExtension.isDirty(132))
		{
			record.set(132,concreteBean.getCs000mtoprestamo_t());
		}
		if(instanceExtension.isDirty(133))
		{
			record.set(133,concreteBean.getMontovehicular_t());
		}
		if(instanceExtension.isDirty(134))
		{
			record.set(134,concreteBean.getMontohipotecario_t());
		}
		if(instanceExtension.isDirty(135))
		{
			record.set(135,concreteBean.getMontosubrogados_t());
		}
	}
	/**
	 * ejbStoreGetDirtyColumnFields
	 */
	public void ejbStoreGetDirtyColumnFields(com.ibm.ws.ejbpersistence.beanextensions.ConcreteBean cb, boolean[] dirtyBitmap) {
		
	}
}
